In [1]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive/ KrishiTrust_AI")
DATA_DIR = BASE_DIR / "datasets"

TRAIN_FILE = DATA_DIR / "fertilizer_train.csv"
TEST_FILE = DATA_DIR / "fertilizer_test.csv"

PREPROCESSOR_FILE = DATA_DIR / "fertilizer_preprocessor.joblib"
LABEL_ENCODER_FILE = DATA_DIR / "fertilizer_label_encoder.joblib"

print("Base directory:", BASE_DIR)
print("Train file:", TRAIN_FILE)
print("Test file:", TEST_FILE)
print("Preprocessor:", PREPROCESSOR_FILE)
print("Label encoder:", LABEL_ENCODER_FILE)

Base directory: /content/drive/MyDrive/ KrishiTrust_AI
Train file: /content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_train.csv
Test file: /content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_test.csv
Preprocessor: /content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_preprocessor.joblib
Label encoder: /content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_label_encoder.joblib

In [ ]:
required_files = {
    "Training dataset": TRAIN_FILE,
    "Testing dataset": TEST_FILE,
    "Preprocessor": PREPROCESSOR_FILE,
    "Label encoder": LABEL_ENCODER_FILE,
}

for name, path in required_files.items():
    print(f"{name}: {'FOUND' if path.exists() else 'NOT FOUND'}")

Training dataset: FOUND
Testing dataset: FOUND
Preprocessor: FOUND
Label encoder: FOUND

In [ ]:
from pathlib import Path

MY_DRIVE = Path("/content/drive/MyDrive")

target_names = {
    "fertilizer_train.csv",
    "fertilizer_test.csv",
    "fertilizer_preprocessor.joblib",
    "fertilizer_label_encoder.joblib",
}

print("Searching Google Drive...")
print("=" * 70)

found = []

for path in MY_DRIVE.rglob("*"):
    if path.is_file() and path.name in target_names:
        found.append(path)

if found:
    print("\nFOUND FILES:\n")
    for path in found:
        print(path)
else:
    print("\n❌ None of the four files were found.")

Searching Google Drive...
======================================================================

FOUND FILES:

/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_train.csv
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_test.csv
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_preprocessor.joblib
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_label_encoder.joblib

In [ ]:
from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive/ KrishiTrust_AI")
DATA_DIR = BASE_DIR / "datasets"

TRAIN_FILE = DATA_DIR / "fertilizer_train.csv"
TEST_FILE = DATA_DIR / "fertilizer_test.csv"

PREPROCESSOR_FILE = DATA_DIR / "fertilizer_preprocessor.joblib"
LABEL_ENCODER_FILE = DATA_DIR / "fertilizer_label_encoder.joblib"

print("Train:", TRAIN_FILE.exists())
print("Test:", TEST_FILE.exists())
print("Preprocessor:", PREPROCESSOR_FILE.exists())
print("Label encoder:", LABEL_ENCODER_FILE.exists())

Train: True
Test: True
Preprocessor: True
Label encoder: True

In [ ]:
import pandas as pd

train_df = pd.read_csv(TRAIN_FILE)
test_df = pd.read_csv(TEST_FILE)

print("Training shape:", train_df.shape)
print("Testing shape:", test_df.shape)

print("\nTraining columns:")
print(train_df.columns.tolist())

print("\nTesting columns:")
print(test_df.columns.tolist())

Training shape: (2238, 12)
Testing shape: (560, 12)

Training columns:
['Temperature', 'Moisture', 'Rainfall', 'PH', 'Nitrogen', 'Phosphorous', 'Potassium', 'Carbon', 'Soil', 'Crop', 'Fertilizer', 'Remark']

Testing columns:
['Temperature', 'Moisture', 'Rainfall', 'PH', 'Nitrogen', 'Phosphorous', 'Potassium', 'Carbon', 'Soil', 'Crop', 'Fertilizer', 'Remark']

In [ ]:
print("\nTraining preview:")
display(train_df.head())

print("\nTesting preview:")
display(test_df.head())

Training preview:

,Temperature,Moisture,Rainfall,PH,Nitrogen,Phosphorous,Potassium,Carbon,Soil,Crop,Fertilizer,Remark
0,26.081299,0.733012,163.892415,6.991204,69.793361,145.658820,138.906278,2.237692,Loamy Soil,Jute,Balanced NPK Fertilizer,"Provides a balanced mix of nitrogen, phosphoru..."
1,29.014380,0.419976,82.525854,6.373472,58.600270,177.314481,50.821261,1.352830,Acidic Soil,maize,Water Retaining Fertilizer,Improves water retention in dry soils. Prefer ...
2,22.088064,0.715145,233.745073,5.526186,70.968236,51.202258,62.019792,2.585261,Peaty Soil,Rubber,Lime,Neutralizes acidic soil and improves pH balanc...
3,27.174129,0.972361,195.768822,5.618820,71.850492,58.060762,47.755439,1.919368,Acidic Soil,Coconut,Muriate of Potash,"High potassium content, improves fruit and flo..."
4,21.177156,0.302811,115.608112,6.594669,60.705961,54.067099,51.810752,0.524974,Acidic Soil,wheat,Compost,Enhances organic matter and improves soil stru...

Testing preview:

,Temperature,Moisture,Rainfall,PH,Nitrogen,Phosphorous,Potassium,Carbon,Soil,Crop,Fertilizer,Remark
0,26.383120,0.667123,127.389076,6.268580,66.159887,52.449476,55.982669,1.883618,Acidic Soil,banana,Water Retaining Fertilizer,Improves water retention in dry soils. Prefer ...
1,24.009493,0.541478,35.331447,6.836684,53.551623,151.111533,95.852445,1.889592,Neutral Soil,Lentil,Water Retaining Fertilizer,Improves water retention in dry soils. Prefer ...
2,19.728164,0.652371,35.696447,6.126073,53.562067,50.379147,57.224947,0.895771,Acidic Soil,Lentil,Compost,Enhances organic matter and improves soil stru...
3,28.558521,0.666531,156.186975,6.546242,73.243459,71.972243,74.219512,0.456110,Acidic Soil,Coconut,Compost,Enhances organic matter and improves soil stru...
4,50.179845,0.227436,76.750568,5.977129,86.969711,43.674594,55.155546,1.588997,Acidic Soil,Adzuki Beans,DAP,"Rich in phosphorus, essential for root develop..."

In [ ]:
# ============================================================
# STEP 5.5 — DATA STRUCTURE VALIDATION
# ============================================================

TARGET = "Fertilizer"

NUMERICAL_FEATURES = [
    "Temperature",
    "Moisture",
    "Rainfall",
    "PH",
    "Nitrogen",
    "Phosphorous",
    "Potassium",
    "Carbon",
]

CATEGORICAL_FEATURES = [
    "Soil",
    "Crop",
]

EXPECTED_FEATURES = (
    NUMERICAL_FEATURES
    + CATEGORICAL_FEATURES
)

print("=" * 70)
print("STEP 5.5 — DATA STRUCTURE VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# Check columns
# ------------------------------------------------------------

print("\nTraining columns:")
print(train_df.columns.tolist())

print("\nTesting columns:")
print(test_df.columns.tolist())

# ------------------------------------------------------------
# Check required features
# ------------------------------------------------------------

missing_train = [
    col for col in EXPECTED_FEATURES + [TARGET]
    if col not in train_df.columns
]

missing_test = [
    col for col in EXPECTED_FEATURES + [TARGET]
    if col not in test_df.columns
]

print("\nMissing required training columns:", missing_train)
print("Missing required testing columns:", missing_test)

assert not missing_train
assert not missing_test

# ------------------------------------------------------------
# Check target
# ------------------------------------------------------------

print("\nTarget column:", TARGET)

print("\nTraining target distribution:")
print(train_df[TARGET].value_counts().sort_index())

print("\nTesting target distribution:")
print(test_df[TARGET].value_counts().sort_index())

# ------------------------------------------------------------
# Check missing values
# ------------------------------------------------------------

print("\nMissing values:")
print("Training:", train_df.isna().sum().sum())
print("Testing: ", test_df.isna().sum().sum())

assert train_df.isna().sum().sum() == 0
assert test_df.isna().sum().sum() == 0

# ------------------------------------------------------------
# Check Remark exclusion
# ------------------------------------------------------------

ML_FEATURES = EXPECTED_FEATURES

assert "Remark" not in ML_FEATURES

print("\nRemark included as feature:", "Remark" in ML_FEATURES)

# ------------------------------------------------------------
# Final
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STRUCTURE VALIDATION: PASS")
print("=" * 70)

print("\nFeatures used:")
for feature in ML_FEATURES:
    print(" -", feature)

print("\nTarget:")
print(" -", TARGET)

print("\nExcluded:")
print(" - Remark")

======================================================================
STEP 5.5 — DATA STRUCTURE VALIDATION
======================================================================

Training columns:
['Temperature', 'Moisture', 'Rainfall', 'PH', 'Nitrogen', 'Phosphorous', 'Potassium', 'Carbon', 'Soil', 'Crop', 'Fertilizer', 'Remark']

Testing columns:
['Temperature', 'Moisture', 'Rainfall', 'PH', 'Nitrogen', 'Phosphorous', 'Potassium', 'Carbon', 'Soil', 'Crop', 'Fertilizer', 'Remark']

Missing required training columns: []
Missing required testing columns: []

Target column: Fertilizer

Training target distribution:
Fertilizer
Balanced NPK Fertilizer       122
Compost                       265
DAP                           725
General Purpose Fertilizer     23
Gypsum                         38
Lime                          136
Muriate of Potash             213
Organic Fertilizer             76
Urea                          113
Water Retaining Fertilizer    527
Name: count, dtype: int64

Testing target distribution:
Fertilizer
Balanced NPK Fertilizer        31
Compost                        66
DAP                           181
General Purpose Fertilizer      6
Gypsum                         10
Lime                           34
Muriate of Potash              53
Organic Fertilizer             19
Urea                           28
Water Retaining Fertilizer    132
Name: count, dtype: int64

Missing values:
Training: 0
Testing:  0

Remark included as feature: False

======================================================================
STRUCTURE VALIDATION: PASS
======================================================================

Features used:
 - Temperature
 - Moisture
 - Rainfall
 - PH
 - Nitrogen
 - Phosphorous
 - Potassium
 - Carbon
 - Soil
 - Crop

Target:
 - Fertilizer

Excluded:
 - Remark

In [ ]:
# ============================================================
# STEP 5.6 — LEAKAGE-SAFE PREPROCESSING PIPELINE
# ============================================================

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

print("=" * 70)
print("STEP 5.6 — LEAKAGE-SAFE PREPROCESSING PIPELINE")
print("=" * 70)

# ------------------------------------------------------------
# Feature definitions
# ------------------------------------------------------------

NUMERICAL_FEATURES = [
    "Temperature",
    "Moisture",
    "Rainfall",
    "PH",
    "Nitrogen",
    "Phosphorous",
    "Potassium",
    "Carbon",
]

CATEGORICAL_FEATURES = [
    "Soil",
    "Crop",
]

TARGET = "Fertilizer"

# ------------------------------------------------------------
# Separate X and y
# ------------------------------------------------------------

X = train_df[
    NUMERICAL_FEATURES + CATEGORICAL_FEATURES
].copy()

y = train_df[TARGET].copy()

print("\nTraining feature shape:", X.shape)
print("Training target shape:", y.shape)

# ------------------------------------------------------------
# Create preprocessing transformer
# ------------------------------------------------------------

preprocessor_cv = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            CATEGORICAL_FEATURES,
        ),
    ],
    remainder="drop",
)

print("\nNumerical preprocessing:")
print("  StandardScaler")

print("\nCategorical preprocessing:")
print("  OneHotEncoder")
print("  handle_unknown='ignore'")

# ------------------------------------------------------------
# Test pipeline construction
# ------------------------------------------------------------

test_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor_cv),
    ]
)

print("\nPipeline created successfully.")

print("\nPipeline steps:")
print(test_pipeline.named_steps)

print("\n" + "=" * 70)
print("LEAKAGE-SAFE PIPELINE SETUP: PASS")
print("=" * 70)

======================================================================
STEP 5.6 — LEAKAGE-SAFE PREPROCESSING PIPELINE
======================================================================

Training feature shape: (2238, 10)
Training target shape: (2238,)

Numerical preprocessing:
  StandardScaler

Categorical preprocessing:
  OneHotEncoder
  handle_unknown='ignore'

Pipeline created successfully.

Pipeline steps:
{'preprocessor': ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                 ['Temperature', 'Moisture', 'Rainfall', 'PH',
                                  'Nitrogen', 'Phosphorous', 'Potassium',
                                  'Carbon']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Soil', 'Crop'])])}

======================================================================
LEAKAGE-SAFE PIPELINE SETUP: PASS
======================================================================

In [ ]:
# ============================================================
# STEP 5.7 — 5-FOLD STRATIFIED CROSS-VALIDATION
# ============================================================

from sklearn.model_selection import StratifiedKFold

print("=" * 70)
print("STEP 5.7 — 5-FOLD STRATIFIED CROSS-VALIDATION")
print("=" * 70)

N_SPLITS = 5
RANDOM_STATE = 42

cv = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE,
)

print("\nConfiguration:")
print(f"  Number of folds: {N_SPLITS}")
print(f"  Shuffle: True")
print(f"  Random state: {RANDOM_STATE}")
print(f"  Stratification target: {TARGET}")

print("\nFold sizes:")

for fold_number, (train_idx, val_idx) in enumerate(
    cv.split(X, y),
    start=1
):
    X_fold_train = X.iloc[train_idx]
    X_fold_val = X.iloc[val_idx]

    y_fold_train = y.iloc[train_idx]
    y_fold_val = y.iloc[val_idx]

    print(
        f"  Fold {fold_number}: "
        f"train={len(train_idx)}, "
        f"validation={len(val_idx)}"
    )

    # Verify every fertilizer class exists in both partitions
    train_classes = set(y_fold_train.unique())
    val_classes = set(y_fold_val.unique())
    all_classes = set(y.unique())

    assert train_classes == all_classes
    assert val_classes == all_classes

print("\nAll folds contain all fertilizer classes.")

print("\n" + "=" * 70)
print("STRATIFIED CROSS-VALIDATION SETUP: PASS")
print("=" * 70)

======================================================================
STEP 5.7 — 5-FOLD STRATIFIED CROSS-VALIDATION
======================================================================

Configuration:
  Number of folds: 5
  Shuffle: True
  Random state: 42
  Stratification target: Fertilizer

Fold sizes:
  Fold 1: train=1790, validation=448
  Fold 2: train=1790, validation=448
  Fold 3: train=1790, validation=448
  Fold 4: train=1791, validation=447
  Fold 5: train=1791, validation=447

All folds contain all fertilizer classes.

======================================================================
STRATIFIED CROSS-VALIDATION SETUP: PASS
======================================================================

In [ ]:
# ============================================================
# STEP 5.8 — LOGISTIC REGRESSION BASELINE
# ============================================================

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline

print("=" * 70)
print("STEP 5.8 — LOGISTIC REGRESSION BASELINE")
print("=" * 70)

# ------------------------------------------------------------
# Model
# ------------------------------------------------------------

logistic_model = LogisticRegression(
    max_iter=2000,
    random_state=42,
)

# ------------------------------------------------------------
# Complete leakage-safe pipeline
# ------------------------------------------------------------

logistic_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            ColumnTransformer(
                transformers=[
                    (
                        "numerical",
                        StandardScaler(),
                        NUMERICAL_FEATURES,
                    ),
                    (
                        "categorical",
                        OneHotEncoder(
                            handle_unknown="ignore",
                            sparse_output=False,
                        ),
                        CATEGORICAL_FEATURES,
                    ),
                ],
                remainder="drop",
            ),
        ),
        (
            "model",
            logistic_model,
        ),
    ]
)

print("\nModel:")
print("  Logistic Regression")

print("\nConfiguration:")
print("  max_iter = 2000")
print("  random_state = 42")

# ------------------------------------------------------------
# Cross-validation scoring
# ------------------------------------------------------------

scoring = {
    "accuracy": "accuracy",
    "precision_macro": "precision_macro",
    "recall_macro": "recall_macro",
    "f1_macro": "f1_macro",
    "f1_weighted": "f1_weighted",
}

print("\nRunning 5-fold stratified cross-validation...")

cv_results_logistic = cross_validate(
    logistic_pipeline,
    X,
    y,
    cv=cv,
    scoring=scoring,
    n_jobs=-1,
    return_train_score=True,
)

# ------------------------------------------------------------
# Calculate summary
# ------------------------------------------------------------

logistic_summary = {
    "model": "Logistic Regression",

    "accuracy_mean":
        cv_results_logistic[
            "test_accuracy"
        ].mean(),

    "accuracy_std":
        cv_results_logistic[
            "test_accuracy"
        ].std(),

    "precision_macro_mean":
        cv_results_logistic[
            "test_precision_macro"
        ].mean(),

    "precision_macro_std":
        cv_results_logistic[
            "test_precision_macro"
        ].std(),

    "recall_macro_mean":
        cv_results_logistic[
            "test_recall_macro"
        ].mean(),

    "recall_macro_std":
        cv_results_logistic[
            "test_recall_macro"
        ].std(),

    "f1_macro_mean":
        cv_results_logistic[
            "test_f1_macro"
        ].mean(),

    "f1_macro_std":
        cv_results_logistic[
            "test_f1_macro"
        ].std(),

    "f1_weighted_mean":
        cv_results_logistic[
            "test_f1_weighted"
        ].mean(),

    "f1_weighted_std":
        cv_results_logistic[
            "test_f1_weighted"
        ].std(),
}

# ------------------------------------------------------------
# Display results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LOGISTIC REGRESSION — CROSS-VALIDATION RESULTS")
print("=" * 70)

print(
    f"\nAccuracy:       "
    f"{logistic_summary['accuracy_mean']:.4f} "
    f"± {logistic_summary['accuracy_std']:.4f}"
)

print(
    f"Macro Precision:"
    f" {logistic_summary['precision_macro_mean']:.4f} "
    f"± {logistic_summary['precision_macro_std']:.4f}"
)

print(
    f"Macro Recall:   "
    f"{logistic_summary['recall_macro_mean']:.4f} "
    f"± {logistic_summary['recall_macro_std']:.4f}"
)

print(
    f"Macro F1:       "
    f"{logistic_summary['f1_macro_mean']:.4f} "
    f"± {logistic_summary['f1_macro_std']:.4f}"
)

print(
    f"Weighted F1:    "
    f"{logistic_summary['f1_weighted_mean']:.4f} "
    f"± {logistic_summary['f1_weighted_std']:.4f}"
)

print("\nPer-fold Macro F1:")

for fold_number, score in enumerate(
    cv_results_logistic["test_f1_macro"],
    start=1,
):
    print(
        f"  Fold {fold_number}: "
        f"{score:.4f}"
    )

print("\n" + "=" * 70)
print("LOGISTIC REGRESSION BASELINE: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.8 — LOGISTIC REGRESSION BASELINE
======================================================================

Model:
  Logistic Regression

Configuration:
  max_iter = 2000
  random_state = 42

Running 5-fold stratified cross-validation...

======================================================================
LOGISTIC REGRESSION — CROSS-VALIDATION RESULTS
======================================================================

Accuracy:       0.8298 ± 0.0008
Macro Precision: 0.7774 ± 0.0225
Macro Recall:   0.7381 ± 0.0142
Macro F1:       0.7488 ± 0.0160
Weighted F1:    0.8243 ± 0.0015

Per-fold Macro F1:
  Fold 1: 0.7356
  Fold 2: 0.7388
  Fold 3: 0.7502
  Fold 4: 0.7792
  Fold 5: 0.7401

======================================================================
LOGISTIC REGRESSION BASELINE: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.9 — RANDOM FOREST
# ============================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

print("=" * 70)
print("STEP 5.9 — RANDOM FOREST")
print("=" * 70)

# ------------------------------------------------------------
# Preprocessing
# ------------------------------------------------------------

rf_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            CATEGORICAL_FEATURES,
        ),
    ],
    remainder="drop",
)

# ------------------------------------------------------------
# Random Forest model
# ------------------------------------------------------------

rf_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1,
)

print("\nModel:")
print("  Random Forest")

print("\nConfiguration:")
print("  n_estimators = 300")
print("  random_state = 42")
print("  n_jobs = -1")

# ------------------------------------------------------------
# Complete pipeline
# ------------------------------------------------------------

rf_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            rf_preprocessor,
        ),
        (
            "model",
            rf_model,
        ),
    ]
)

# ------------------------------------------------------------
# Cross-validation
# ------------------------------------------------------------

scoring = {
    "accuracy": "accuracy",
    "precision_macro": "precision_macro",
    "recall_macro": "recall_macro",
    "f1_macro": "f1_macro",
    "f1_weighted": "f1_weighted",
}

print("\nRunning 5-fold stratified cross-validation...")

cv_results_rf = cross_validate(
    rf_pipeline,
    X,
    y,
    cv=cv,
    scoring=scoring,
    n_jobs=-1,
    return_train_score=True,
)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

rf_summary = {
    "model": "Random Forest",

    "accuracy_mean":
        cv_results_rf[
            "test_accuracy"
        ].mean(),

    "accuracy_std":
        cv_results_rf[
            "test_accuracy"
        ].std(),

    "precision_macro_mean":
        cv_results_rf[
            "test_precision_macro"
        ].mean(),

    "precision_macro_std":
        cv_results_rf[
            "test_precision_macro"
        ].std(),

    "recall_macro_mean":
        cv_results_rf[
            "test_recall_macro"
        ].mean(),

    "recall_macro_std":
        cv_results_rf[
            "test_recall_macro"
        ].std(),

    "f1_macro_mean":
        cv_results_rf[
            "test_f1_macro"
        ].mean(),

    "f1_macro_std":
        cv_results_rf[
            "test_f1_macro"
        ].std(),

    "f1_weighted_mean":
        cv_results_rf[
            "test_f1_weighted"
        ].mean(),

    "f1_weighted_std":
        cv_results_rf[
            "test_f1_weighted"
        ].std(),
}

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RANDOM FOREST — CROSS-VALIDATION RESULTS")
print("=" * 70)

print(
    f"\nAccuracy:       "
    f"{rf_summary['accuracy_mean']:.4f} "
    f"± {rf_summary['accuracy_std']:.4f}"
)

print(
    f"Macro Precision:"
    f" {rf_summary['precision_macro_mean']:.4f} "
    f"± {rf_summary['precision_macro_std']:.4f}"
)

print(
    f"Macro Recall:   "
    f"{rf_summary['recall_macro_mean']:.4f} "
    f"± {rf_summary['recall_macro_std']:.4f}"
)

print(
    f"Macro F1:       "
    f"{rf_summary['f1_macro_mean']:.4f} "
    f"± {rf_summary['f1_macro_std']:.4f}"
)

print(
    f"Weighted F1:    "
    f"{rf_summary['f1_weighted_mean']:.4f} "
    f"± {rf_summary['f1_weighted_std']:.4f}"
)

print("\nPer-fold Macro F1:")

for fold_number, score in enumerate(
    cv_results_rf["test_f1_macro"],
    start=1,
):
    print(
        f"  Fold {fold_number}: "
        f"{score:.4f}"
    )

print("\n" + "=" * 70)
print("RANDOM FOREST: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.9 — RANDOM FOREST
======================================================================

Model:
  Random Forest

Configuration:
  n_estimators = 300
  random_state = 42
  n_jobs = -1

Running 5-fold stratified cross-validation...

======================================================================
RANDOM FOREST — CROSS-VALIDATION RESULTS
======================================================================

Accuracy:       0.9808 ± 0.0018
Macro Precision: 0.9828 ± 0.0025
Macro Recall:   0.9165 ± 0.0085
Macro F1:       0.9276 ± 0.0135
Weighted F1:    0.9772 ± 0.0030

Per-fold Macro F1:
  Fold 1: 0.9142
  Fold 2: 0.9099
  Fold 3: 0.9299
  Fold 4: 0.9427
  Fold 5: 0.9412

======================================================================
RANDOM FOREST: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.10 — EXTRA TREES
# ============================================================

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

print("=" * 70)
print("STEP 5.10 — EXTRA TREES")
print("=" * 70)

# ------------------------------------------------------------
# Preprocessing
# ------------------------------------------------------------

et_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            CATEGORICAL_FEATURES,
        ),
    ],
    remainder="drop",
)

# ------------------------------------------------------------
# Extra Trees model
# ------------------------------------------------------------

et_model = ExtraTreesClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1,
)

print("\nModel:")
print("  Extra Trees")

print("\nConfiguration:")
print("  n_estimators = 300")
print("  random_state = 42")
print("  n_jobs = -1")

# ------------------------------------------------------------
# Complete leakage-safe pipeline
# ------------------------------------------------------------

et_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            et_preprocessor,
        ),
        (
            "model",
            et_model,
        ),
    ]
)

# ------------------------------------------------------------
# Cross-validation
# ------------------------------------------------------------

scoring = {
    "accuracy": "accuracy",
    "precision_macro": "precision_macro",
    "recall_macro": "recall_macro",
    "f1_macro": "f1_macro",
    "f1_weighted": "f1_weighted",
}

print("\nRunning 5-fold stratified cross-validation...")

cv_results_et = cross_validate(
    et_pipeline,
    X,
    y,
    cv=cv,
    scoring=scoring,
    n_jobs=-1,
    return_train_score=True,
)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

et_summary = {
    "model": "Extra Trees",

    "accuracy_mean":
        cv_results_et[
            "test_accuracy"
        ].mean(),

    "accuracy_std":
        cv_results_et[
            "test_accuracy"
        ].std(),

    "precision_macro_mean":
        cv_results_et[
            "test_precision_macro"
        ].mean(),

    "precision_macro_std":
        cv_results_et[
            "test_precision_macro"
        ].std(),

    "recall_macro_mean":
        cv_results_et[
            "test_recall_macro"
        ].mean(),

    "recall_macro_std":
        cv_results_et[
            "test_recall_macro"
        ].std(),

    "f1_macro_mean":
        cv_results_et[
            "test_f1_macro"
        ].mean(),

    "f1_macro_std":
        cv_results_et[
            "test_f1_macro"
        ].std(),

    "f1_weighted_mean":
        cv_results_et[
            "test_f1_weighted"
        ].mean(),

    "f1_weighted_std":
        cv_results_et[
            "test_f1_weighted"
        ].std(),
}

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("EXTRA TREES — CROSS-VALIDATION RESULTS")
print("=" * 70)

print(
    f"\nAccuracy:       "
    f"{et_summary['accuracy_mean']:.4f} "
    f"± {et_summary['accuracy_std']:.4f}"
)

print(
    f"Macro Precision:"
    f" {et_summary['precision_macro_mean']:.4f} "
    f"± {et_summary['precision_macro_std']:.4f}"
)

print(
    f"Macro Recall:   "
    f"{et_summary['recall_macro_mean']:.4f} "
    f"± {et_summary['recall_macro_std']:.4f}"
)

print(
    f"Macro F1:       "
    f"{et_summary['f1_macro_mean']:.4f} "
    f"± {et_summary['f1_macro_std']:.4f}"
)

print(
    f"Weighted F1:    "
    f"{et_summary['f1_weighted_mean']:.4f} "
    f"± {et_summary['f1_weighted_std']:.4f}"
)

print("\nPer-fold Macro F1:")

for fold_number, score in enumerate(
    cv_results_et["test_f1_macro"],
    start=1,
):
    print(
        f"  Fold {fold_number}: "
        f"{score:.4f}"
    )

print("\n" + "=" * 70)
print("EXTRA TREES: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.10 — EXTRA TREES
======================================================================

Model:
  Extra Trees

Configuration:
  n_estimators = 300
  random_state = 42
  n_jobs = -1

Running 5-fold stratified cross-validation...

======================================================================
EXTRA TREES — CROSS-VALIDATION RESULTS
======================================================================

Accuracy:       0.8016 ± 0.0207
Macro Precision: 0.7510 ± 0.0497
Macro Recall:   0.6259 ± 0.0187
Macro F1:       0.6521 ± 0.0209
Weighted F1:    0.7880 ± 0.0185

Per-fold Macro F1:
  Fold 1: 0.6339
  Fold 2: 0.6650
  Fold 3: 0.6204
  Fold 4: 0.6705
  Fold 5: 0.6708

======================================================================
EXTRA TREES: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.11 — CHECK XGBOOST AND LIGHTGBM
# ============================================================

import importlib.util

print("=" * 70)
print("STEP 5.11 — XGBOOST / LIGHTGBM AVAILABILITY")
print("=" * 70)

xgb_available = importlib.util.find_spec("xgboost") is not None
lgb_available = importlib.util.find_spec("lightgbm") is not None

print("\nXGBoost installed:", xgb_available)
print("LightGBM installed:", lgb_available)

======================================================================
STEP 5.11 — XGBOOST / LIGHTGBM AVAILABILITY
======================================================================

XGBoost installed: True
LightGBM installed: True

In [ ]:
# ============================================================
# STEP 5.12A — ENCODE FERTILIZER TARGET FOR XGBOOST
# ============================================================

from sklearn.preprocessing import LabelEncoder

print("=" * 70)
print("STEP 5.12A — XGBOOST TARGET ENCODING")
print("=" * 70)

# Create a fresh encoder for this training experiment
xgb_label_encoder = LabelEncoder()

y_encoded = xgb_label_encoder.fit_transform(y)

print("\nOriginal target classes:")
for class_name in xgb_label_encoder.classes_:
    print(" -", class_name)

print("\nEncoded target mapping:")

for encoded_value, class_name in enumerate(
    xgb_label_encoder.classes_
):
    print(
        f"  {encoded_value} -> {class_name}"
    )

print("\nOriginal target type:")
print(type(y.iloc[0]).__name__)

print("\nEncoded target type:")
print(type(y_encoded[0]).__name__)

print("\nNumber of classes:")
print(len(xgb_label_encoder.classes_))

print("\nEncoded target values:")
print(
    sorted(set(y_encoded))
)

print("\n" + "=" * 70)
print("XGBOOST TARGET ENCODING: PASS")
print("=" * 70)

======================================================================
STEP 5.12A — XGBOOST TARGET ENCODING
======================================================================

Original target classes:
 - Balanced NPK Fertilizer
 - Compost
 - DAP
 - General Purpose Fertilizer
 - Gypsum
 - Lime
 - Muriate of Potash
 - Organic Fertilizer
 - Urea
 - Water Retaining Fertilizer

Encoded target mapping:
  0 -> Balanced NPK Fertilizer
  1 -> Compost
  2 -> DAP
  3 -> General Purpose Fertilizer
  4 -> Gypsum
  5 -> Lime
  6 -> Muriate of Potash
  7 -> Organic Fertilizer
  8 -> Urea
  9 -> Water Retaining Fertilizer

Original target type:
str

Encoded target type:
int64

Number of classes:
10

Encoded target values:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]

======================================================================
XGBOOST TARGET ENCODING: PASS
======================================================================

In [ ]:
# ============================================================
# STEP 5.12B — XGBOOST WITH NUMERIC TARGET
# ============================================================

from xgboost import XGBClassifier
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

print("=" * 70)
print("STEP 5.12B — XGBOOST")
print("=" * 70)

# ------------------------------------------------------------
# Preprocessing
# ------------------------------------------------------------

xgb_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            CATEGORICAL_FEATURES,
        ),
    ],
    remainder="drop",
)

# ------------------------------------------------------------
# XGBoost
# ------------------------------------------------------------

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1,
)

print("\nModel:")
print("  XGBoost")

print("\nConfiguration:")
print("  n_estimators = 300")
print("  max_depth = 6")
print("  learning_rate = 0.05")
print("  subsample = 0.8")
print("  colsample_bytree = 0.8")
print("  random_state = 42")

# ------------------------------------------------------------
# Pipeline
# ------------------------------------------------------------

xgb_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            xgb_preprocessor,
        ),
        (
            "model",
            xgb_model,
        ),
    ]
)

# ------------------------------------------------------------
# Scoring
# ------------------------------------------------------------

scoring = {
    "accuracy": "accuracy",
    "precision_macro": "precision_macro",
    "recall_macro": "recall_macro",
    "f1_macro": "f1_macro",
    "f1_weighted": "f1_weighted",
}

# ------------------------------------------------------------
# Cross-validation
# ------------------------------------------------------------

print("\nRunning 5-fold stratified cross-validation...")

cv_results_xgb = cross_validate(
    xgb_pipeline,
    X,
    y_encoded,
    cv=cv,
    scoring=scoring,
    n_jobs=1,
    return_train_score=True,
    error_score="raise",
)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

xgb_summary = {
    "model": "XGBoost",

    "accuracy_mean":
        cv_results_xgb["test_accuracy"].mean(),

    "accuracy_std":
        cv_results_xgb["test_accuracy"].std(),

    "precision_macro_mean":
        cv_results_xgb["test_precision_macro"].mean(),

    "precision_macro_std":
        cv_results_xgb["test_precision_macro"].std(),

    "recall_macro_mean":
        cv_results_xgb["test_recall_macro"].mean(),

    "recall_macro_std":
        cv_results_xgb["test_recall_macro"].std(),

    "f1_macro_mean":
        cv_results_xgb["test_f1_macro"].mean(),

    "f1_macro_std":
        cv_results_xgb["test_f1_macro"].std(),

    "f1_weighted_mean":
        cv_results_xgb["test_f1_weighted"].mean(),

    "f1_weighted_std":
        cv_results_xgb["test_f1_weighted"].std(),
}

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("XGBOOST — CROSS-VALIDATION RESULTS")
print("=" * 70)

print(
    f"\nAccuracy:       "
    f"{xgb_summary['accuracy_mean']:.4f} "
    f"± {xgb_summary['accuracy_std']:.4f}"
)

print(
    f"Macro Precision:"
    f" {xgb_summary['precision_macro_mean']:.4f} "
    f"± {xgb_summary['precision_macro_std']:.4f}"
)

print(
    f"Macro Recall:   "
    f"{xgb_summary['recall_macro_mean']:.4f} "
    f"± {xgb_summary['recall_macro_std']:.4f}"
)

print(
    f"Macro F1:       "
    f"{xgb_summary['f1_macro_mean']:.4f} "
    f"± {xgb_summary['f1_macro_std']:.4f}"
)

print(
    f"Weighted F1:    "
    f"{xgb_summary['f1_weighted_mean']:.4f} "
    f"± {xgb_summary['f1_weighted_std']:.4f}"
)

print("\nPer-fold Macro F1:")

for fold_number, score in enumerate(
    cv_results_xgb["test_f1_macro"],
    start=1,
):
    print(
        f"  Fold {fold_number}: "
        f"{score:.4f}"
    )

print("\n" + "=" * 70)
print("XGBOOST: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.12B — XGBOOST
======================================================================

Model:
  XGBoost

Configuration:
  n_estimators = 300
  max_depth = 6
  learning_rate = 0.05
  subsample = 0.8
  colsample_bytree = 0.8
  random_state = 42

Running 5-fold stratified cross-validation...

======================================================================
XGBOOST — CROSS-VALIDATION RESULTS
======================================================================

Accuracy:       0.9937 ± 0.0055
Macro Precision: 0.9939 ± 0.0060
Macro Recall:   0.9910 ± 0.0085
Macro F1:       0.9921 ± 0.0077
Weighted F1:    0.9937 ± 0.0056

Per-fold Macro F1:
  Fold 1: 0.9779
  Fold 2: 0.9907
  Fold 3: 0.9950
  Fold 4: 1.0000
  Fold 5: 0.9969

======================================================================
XGBOOST: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.13 — LIGHTGBM
# ============================================================

from lightgbm import LGBMClassifier
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

print("=" * 70)
print("STEP 5.13 — LIGHTGBM")
print("=" * 70)

# ------------------------------------------------------------
# Preprocessing
# ------------------------------------------------------------

lgb_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            CATEGORICAL_FEATURES,
        ),
    ],
    remainder="drop",
)

# ------------------------------------------------------------
# LightGBM
# ------------------------------------------------------------

lgb_model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    verbosity=-1,
)

print("\nModel:")
print("  LightGBM")

print("\nConfiguration:")
print("  n_estimators = 300")
print("  learning_rate = 0.05")
print("  max_depth = 6")
print("  num_leaves = 31")
print("  subsample = 0.8")
print("  colsample_bytree = 0.8")
print("  random_state = 42")

# ------------------------------------------------------------
# Pipeline
# ------------------------------------------------------------

lgb_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            lgb_preprocessor,
        ),
        (
            "model",
            lgb_model,
        ),
    ]
)

# ------------------------------------------------------------
# Scoring
# ------------------------------------------------------------

scoring = {
    "accuracy": "accuracy",
    "precision_macro": "precision_macro",
    "recall_macro": "recall_macro",
    "f1_macro": "f1_macro",
    "f1_weighted": "f1_weighted",
}

# ------------------------------------------------------------
# Cross-validation
# ------------------------------------------------------------

print("\nRunning 5-fold stratified cross-validation...")

cv_results_lgb = cross_validate(
    lgb_pipeline,
    X,
    y,
    cv=cv,
    scoring=scoring,
    n_jobs=1,
    return_train_score=True,
    error_score="raise",
)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

lgb_summary = {
    "model": "LightGBM",

    "accuracy_mean":
        cv_results_lgb["test_accuracy"].mean(),

    "accuracy_std":
        cv_results_lgb["test_accuracy"].std(),

    "precision_macro_mean":
        cv_results_lgb["test_precision_macro"].mean(),

    "precision_macro_std":
        cv_results_lgb["test_precision_macro"].std(),

    "recall_macro_mean":
        cv_results_lgb["test_recall_macro"].mean(),

    "recall_macro_std":
        cv_results_lgb["test_recall_macro"].std(),

    "f1_macro_mean":
        cv_results_lgb["test_f1_macro"].mean(),

    "f1_macro_std":
        cv_results_lgb["test_f1_macro"].std(),

    "f1_weighted_mean":
        cv_results_lgb["test_f1_weighted"].mean(),

    "f1_weighted_std":
        cv_results_lgb["test_f1_weighted"].std(),
}

# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LIGHTGBM — CROSS-VALIDATION RESULTS")
print("=" * 70)

print(
    f"\nAccuracy:       "
    f"{lgb_summary['accuracy_mean']:.4f} "
    f"± {lgb_summary['accuracy_std']:.4f}"
)

print(
    f"Macro Precision:"
    f" {lgb_summary['precision_macro_mean']:.4f} "
    f"± {lgb_summary['precision_macro_std']:.4f}"
)

print(
    f"Macro Recall:   "
    f"{lgb_summary['recall_macro_mean']:.4f} "
    f"± {lgb_summary['recall_macro_std']:.4f}"
)

print(
    f"Macro F1:       "
    f"{lgb_summary['f1_macro_mean']:.4f} "
    f"± {lgb_summary['f1_macro_std']:.4f}"
)

print(
    f"Weighted F1:    "
    f"{lgb_summary['f1_weighted_mean']:.4f} "
    f"± {lgb_summary['f1_weighted_std']:.4f}"
)

print("\nPer-fold Macro F1:")

for fold_number, score in enumerate(
    cv_results_lgb["test_f1_macro"],
    start=1,
):
    print(
        f"  Fold {fold_number}: "
        f"{score:.4f}"
    )

print("\n" + "=" * 70)
print("LIGHTGBM: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.13 — LIGHTGBM
======================================================================

Model:
  LightGBM

Configuration:
  n_estimators = 300
  learning_rate = 0.05
  max_depth = 6
  num_leaves = 31
  subsample = 0.8
  colsample_bytree = 0.8
  random_state = 42

Running 5-fold stratified cross-validation...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

======================================================================
LIGHTGBM — CROSS-VALIDATION RESULTS
======================================================================

Accuracy:       0.9911 ± 0.0058
Macro Precision: 0.9920 ± 0.0076
Macro Recall:   0.9850 ± 0.0114
Macro F1:       0.9880 ± 0.0102
Weighted F1:    0.9910 ± 0.0059

Per-fold Macro F1:
  Fold 1: 0.9677
  Fold 2: 0.9932
  Fold 3: 0.9919
  Fold 4: 0.9935
  Fold 5: 0.9939

======================================================================
LIGHTGBM: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.14 — MODEL COMPARISON
# ============================================================

print("=" * 70)
print("STEP 5.14 — MODEL COMPARISON")
print("=" * 70)

comparison_data = [
    logistic_summary,
    rf_summary,
    et_summary,
    xgb_summary,
    lgb_summary,
]

comparison_df = pd.DataFrame(comparison_data)

comparison_df = comparison_df[
    [
        "model",
        "accuracy_mean",
        "accuracy_std",
        "precision_macro_mean",
        "precision_macro_std",
        "recall_macro_mean",
        "recall_macro_std",
        "f1_macro_mean",
        "f1_macro_std",
        "f1_weighted_mean",
        "f1_weighted_std",
    ]
]

comparison_df = comparison_df.sort_values(
    by="f1_macro_mean",
    ascending=False,
).reset_index(drop=True)

print("\nMODEL RANKING BY MACRO F1")
print("=" * 70)

display(
    comparison_df.style.format({
        "accuracy_mean": "{:.4f}",
        "accuracy_std": "{:.4f}",
        "precision_macro_mean": "{:.4f}",
        "precision_macro_std": "{:.4f}",
        "recall_macro_mean": "{:.4f}",
        "recall_macro_std": "{:.4f}",
        "f1_macro_mean": "{:.4f}",
        "f1_macro_std": "{:.4f}",
        "f1_weighted_mean": "{:.4f}",
        "f1_weighted_std": "{:.4f}",
    })
)

print("\nRanking:")
for rank, row in comparison_df.iterrows():
    print(
        f"{rank + 1}. {row['model']} "
        f"→ Macro F1 = "
        f"{row['f1_macro_mean']:.4f}"
    )

# ------------------------------------------------------------
# Save comparison
# ------------------------------------------------------------

COMPARISON_FILE = (
    DATA_DIR / "fertilizer_model_comparison_cv.csv"
)

comparison_df.to_csv(
    COMPARISON_FILE,
    index=False,
)

print("\nComparison saved to:")
print(COMPARISON_FILE)

print("\n" + "=" * 70)
print("MODEL COMPARISON: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.14 — MODEL COMPARISON
======================================================================

MODEL RANKING BY MACRO F1
======================================================================

Ranking:
1. XGBoost → Macro F1 = 0.9921
2. LightGBM → Macro F1 = 0.9880
3. Random Forest → Macro F1 = 0.9276
4. Logistic Regression → Macro F1 = 0.7488
5. Extra Trees → Macro F1 = 0.6521

Comparison saved to:
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_model_comparison_cv.csv

======================================================================
MODEL COMPARISON: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.15 — FINAL XGBOOST TEST EVALUATION
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
)

print("=" * 70)
print("STEP 5.15 — FINAL XGBOOST TEST EVALUATION")
print("=" * 70)

# ------------------------------------------------------------
# Prepare test data
# ------------------------------------------------------------

X_test_final = test_df[
    NUMERICAL_FEATURES + CATEGORICAL_FEATURES
].copy()

y_test_final = test_df[
    TARGET
].copy()

# Encode test target using the SAME encoder
# used for XGBoost training.
y_test_encoded = xgb_label_encoder.transform(
    y_test_final
)

print("\nTraining rows:")
print(f"  {len(X)}")

print("\nTesting rows:")
print(f"  {len(X_test_final)}")

# ------------------------------------------------------------
# Fit final XGBoost pipeline
# ------------------------------------------------------------

print("\nFitting final XGBoost model...")
print("Using all 2,238 training rows.")

xgb_pipeline.fit(
    X,
    y_encoded,
)

print("Final model training: COMPLETE")

# ------------------------------------------------------------
# Predict test set
# ------------------------------------------------------------

print("\nGenerating predictions on 560 untouched test rows...")

y_test_pred = xgb_pipeline.predict(
    X_test_final
)

print("Test prediction: COMPLETE")

# ------------------------------------------------------------
# Metrics
# ------------------------------------------------------------

test_accuracy = accuracy_score(
    y_test_encoded,
    y_test_pred,
)

test_precision_macro = precision_score(
    y_test_encoded,
    y_test_pred,
    average="macro",
    zero_division=0,
)

test_recall_macro = recall_score(
    y_test_encoded,
    y_test_pred,
    average="macro",
    zero_division=0,
)

test_f1_macro = f1_score(
    y_test_encoded,
    y_test_pred,
    average="macro",
    zero_division=0,
)

test_f1_weighted = f1_score(
    y_test_encoded,
    y_test_pred,
    average="weighted",
    zero_division=0,
)

print("\n" + "=" * 70)
print("FINAL TEST RESULTS")
print("=" * 70)

print(
    f"\nAccuracy:        {test_accuracy:.4f}"
)

print(
    f"Macro Precision: {test_precision_macro:.4f}"
)

print(
    f"Macro Recall:    {test_recall_macro:.4f}"
)

print(
    f"Macro F1:        {test_f1_macro:.4f}"
)

print(
    f"Weighted F1:     {test_f1_weighted:.4f}"
)

# ------------------------------------------------------------
# Classification report
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CLASSIFICATION REPORT")
print("=" * 70)

class_names = (
    xgb_label_encoder.classes_
)

report = classification_report(
    y_test_encoded,
    y_test_pred,
    labels=np.arange(len(class_names)),
    target_names=class_names,
    zero_division=0,
)

print(report)

# ------------------------------------------------------------
# Confusion matrix
# ------------------------------------------------------------

cm = confusion_matrix(
    y_test_encoded,
    y_test_pred,
    labels=np.arange(len(class_names)),
)

print("\n" + "=" * 70)
print("CONFUSION MATRIX")
print("=" * 70)

cm_df = pd.DataFrame(
    cm,
    index=class_names,
    columns=class_names,
)

display(cm_df)

# ------------------------------------------------------------
# Test prediction validation
# ------------------------------------------------------------

correct_predictions = (
    y_test_encoded == y_test_pred
).sum()

incorrect_predictions = (
    y_test_encoded != y_test_pred
).sum()

print("\nCorrect predictions:")
print(f"  {correct_predictions}")

print("\nIncorrect predictions:")
print(f"  {incorrect_predictions}")

print("\n" + "=" * 70)
print("FINAL TEST EVALUATION: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.15 — FINAL XGBOOST TEST EVALUATION
======================================================================

Training rows:
  2238

Testing rows:
  560

Fitting final XGBoost model...
Using all 2,238 training rows.
Final model training: COMPLETE

Generating predictions on 560 untouched test rows...
Test prediction: COMPLETE

======================================================================
FINAL TEST RESULTS
======================================================================

Accuracy:        0.9929
Macro Precision: 0.9869
Macro Recall:    0.9919
Macro F1:        0.9891
Weighted F1:     0.9929

======================================================================
CLASSIFICATION REPORT
======================================================================
                            precision    recall  f1-score   support

   Balanced NPK Fertilizer       1.00      0.97      0.98        31
                   Compost       0.98      0.97      0.98        66
                       DAP       0.99      1.00      1.00       181
General Purpose Fertilizer       1.00      1.00      1.00         6
                    Gypsum       0.91      1.00      0.95        10
                      Lime       1.00      1.00      1.00        34
         Muriate of Potash       0.98      0.98      0.98        53
        Organic Fertilizer       1.00      1.00      1.00        19
                      Urea       1.00      1.00      1.00        28
Water Retaining Fertilizer       1.00      1.00      1.00       132

                  accuracy                           0.99       560
                 macro avg       0.99      0.99      0.99       560
              weighted avg       0.99      0.99      0.99       560


======================================================================
CONFUSION MATRIX
======================================================================

,Balanced NPK Fertilizer,Compost,DAP,General Purpose Fertilizer,Gypsum,Lime,Muriate of Potash,Organic Fertilizer,Urea,Water Retaining Fertilizer
Balanced NPK Fertilizer,30,1,0,0,0,0,0,0,0,0
Compost,0,64,0,0,1,0,1,0,0,0
DAP,0,0,181,0,0,0,0,0,0,0
General Purpose Fertilizer,0,0,0,6,0,0,0,0,0,0
Gypsum,0,0,0,0,10,0,0,0,0,0
Lime,0,0,0,0,0,34,0,0,0,0
Muriate of Potash,0,0,1,0,0,0,52,0,0,0
Organic Fertilizer,0,0,0,0,0,0,0,19,0,0
Urea,0,0,0,0,0,0,0,0,28,0
Water Retaining Fertilizer,0,0,0,0,0,0,0,0,0,132

Correct predictions:
  556

Incorrect predictions:
  4

======================================================================
FINAL TEST EVALUATION: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.16A — XGBOOST FEATURE IMPORTANCE
# ============================================================

print("=" * 70)
print("STEP 5.16A — XGBOOST FEATURE IMPORTANCE")
print("=" * 70)

# ------------------------------------------------------------
# Fit a diagnostic copy of the final pipeline
# ------------------------------------------------------------

xgb_diagnostic_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            ColumnTransformer(
                transformers=[
                    (
                        "numerical",
                        StandardScaler(),
                        NUMERICAL_FEATURES,
                    ),
                    (
                        "categorical",
                        OneHotEncoder(
                            handle_unknown="ignore",
                            sparse_output=False,
                        ),
                        CATEGORICAL_FEATURES,
                    ),
                ],
                remainder="drop",
            ),
        ),
        (
            "model",
            XGBClassifier(
                n_estimators=300,
                max_depth=6,
                learning_rate=0.05,
                subsample=0.8,
                colsample_bytree=0.8,
                objective="multi:softprob",
                eval_metric="mlogloss",
                random_state=42,
                n_jobs=-1,
            ),
        ),
    ]
)

print("\nFitting diagnostic XGBoost on training data...")

xgb_diagnostic_pipeline.fit(
    X,
    y_encoded,
)

print("Diagnostic model fitted.")

# ------------------------------------------------------------
# Extract feature names
# ------------------------------------------------------------

diagnostic_preprocessor = (
    xgb_diagnostic_pipeline
    .named_steps["preprocessor"]
)

diagnostic_model = (
    xgb_diagnostic_pipeline
    .named_steps["model"]
)

feature_names = (
    diagnostic_preprocessor
    .get_feature_names_out()
)

importances = (
    diagnostic_model
    .feature_importances_
)

feature_importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances,
})

feature_importance_df = (
    feature_importance_df
    .sort_values(
        "importance",
        ascending=False,
    )
    .reset_index(drop=True)
)

print("\nTOP 20 TRANSFORMED FEATURES")
print("=" * 70)

display(
    feature_importance_df.head(20)
)

# ------------------------------------------------------------
# Aggregate importance by original feature
# ------------------------------------------------------------

def get_original_feature(transformed_name):

    if transformed_name.startswith(
        "numerical__"
    ):
        return transformed_name.replace(
            "numerical__",
            "",
        )

    if transformed_name.startswith(
        "categorical__"
    ):
        remaining = transformed_name.replace(
            "categorical__",
            "",
        )

        if remaining.startswith("Soil_"):
            return "Soil"

        if remaining.startswith("Crop_"):
            return "Crop"

    return transformed_name


feature_importance_df[
    "original_feature"
] = feature_importance_df[
    "feature"
].apply(get_original_feature)

aggregated_importance = (
    feature_importance_df
    .groupby(
        "original_feature",
        as_index=False,
    )["importance"]
    .sum()
    .sort_values(
        "importance",
        ascending=False,
    )
    .reset_index(drop=True)
)

print("\n" + "=" * 70)
print("AGGREGATED IMPORTANCE BY ORIGINAL FEATURE")
print("=" * 70)

display(aggregated_importance)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

FEATURE_IMPORTANCE_FILE = (
    DATA_DIR
    / "fertilizer_xgboost_feature_importance.csv"
)

feature_importance_df.to_csv(
    FEATURE_IMPORTANCE_FILE,
    index=False,
)

AGGREGATED_IMPORTANCE_FILE = (
    DATA_DIR
    / "fertilizer_xgboost_feature_importance_aggregated.csv"
)

aggregated_importance.to_csv(
    AGGREGATED_IMPORTANCE_FILE,
    index=False,
)

print("\nSaved:")
print(FEATURE_IMPORTANCE_FILE)
print(AGGREGATED_IMPORTANCE_FILE)

print("\n" + "=" * 70)
print("FEATURE IMPORTANCE ANALYSIS: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.16A — XGBOOST FEATURE IMPORTANCE
======================================================================

Fitting diagnostic XGBoost on training data...
Diagnostic model fitted.

TOP 20 TRANSFORMED FEATURES
======================================================================

                            feature  importance
0      categorical__Soil_Loamy Soil    0.166719
1            numerical__Phosphorous    0.115764
2      categorical__Soil_Peaty Soil    0.089437
3                 numerical__Carbon    0.066512
4              numerical__Potassium    0.054646
5               numerical__Nitrogen    0.043600
6    categorical__Soil_Neutral Soil    0.040672
7                     numerical__PH    0.037200
8               numerical__Moisture    0.035673
9            categorical__Crop_Peas    0.028375
10  categorical__Soil_Alkaline Soil    0.026151
11       categorical__Crop_Chickpea    0.024169
12         categorical__Crop_Rubber    0.024089
13      categorical__Crop_Sugarcane    0.020956
14         categorical__Crop_millet    0.020439
15          categorical__Crop_apple    0.017826
16      categorical__Crop_muskmelon    0.017059
17         categorical__Crop_orange    0.015292
18         categorical__Crop_Lentil    0.014382
19    categorical__Soil_Acidic Soil    0.014304

======================================================================
AGGREGATED IMPORTANCE BY ORIGINAL FEATURE
======================================================================

  original_feature  importance
0             Soil    0.337283
1             Crop    0.301619
2      Phosphorous    0.115764
3           Carbon    0.066512
4        Potassium    0.054646
5         Nitrogen    0.043600
6               PH    0.037200
7         Moisture    0.035673
8         Rainfall    0.004418
9      Temperature    0.003287

Saved:
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_xgboost_feature_importance.csv
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_xgboost_feature_importance_aggregated.csv

======================================================================
FEATURE IMPORTANCE ANALYSIS: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.16B — XGBOOST CONFIDENCE & ERROR ANALYSIS
# ============================================================

from sklearn.metrics import accuracy_score

print("=" * 70)
print("STEP 5.16B — XGBOOST CONFIDENCE & ERROR ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# Use the already-fitted final XGBoost pipeline
# ------------------------------------------------------------

print("\nGenerating test probabilities...")

y_test_proba = xgb_pipeline.predict_proba(
    X_test_final
)

# Predicted class
y_test_pred = xgb_pipeline.predict(
    X_test_final
)

# ------------------------------------------------------------
# Confidence
# ------------------------------------------------------------

prediction_confidence = (
    np.max(
        y_test_proba,
        axis=1,
    )
)

# Second-highest probability
sorted_probabilities = np.sort(
    y_test_proba,
    axis=1,
)

second_highest_probability = (
    sorted_probabilities[:, -2]
)

confidence_margin = (
    prediction_confidence
    - second_highest_probability
)

# ------------------------------------------------------------
# Correct / incorrect
# ------------------------------------------------------------

correct_mask = (
    y_test_pred == y_test_encoded
)

incorrect_mask = ~correct_mask

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

print("\nPrediction confidence summary:")
print(
    f"Mean confidence:   "
    f"{prediction_confidence.mean():.4f}"
)

print(
    f"Minimum confidence:"
    f" {prediction_confidence.min():.4f}"
)

print(
    f"Maximum confidence:"
    f" {prediction_confidence.max():.4f}"
)

print(
    f"Median confidence: "
    f"{np.median(prediction_confidence):.4f}"
)

print("\nConfidence by prediction correctness:")

print(
    f"Correct predictions: "
    f"{correct_mask.sum()}"
)

print(
    f"Mean confidence for correct predictions: "
    f"{prediction_confidence[correct_mask].mean():.4f}"
)

print(
    f"Incorrect predictions: "
    f"{incorrect_mask.sum()}"
)

if incorrect_mask.sum() > 0:
    print(
        f"Mean confidence for incorrect predictions: "
        f"{prediction_confidence[incorrect_mask].mean():.4f}"
    )

# ------------------------------------------------------------
# Error table
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INCORRECT TEST PREDICTIONS")
print("=" * 70)

error_indices = np.where(
    incorrect_mask
)[0]

error_rows = []

for idx in error_indices:

    actual_class = (
        xgb_label_encoder
        .inverse_transform(
            [y_test_encoded[idx]]
        )[0]
    )

    predicted_class = (
        xgb_label_encoder
        .inverse_transform(
            [y_test_pred[idx]]
        )[0]
    )

    error_rows.append({
        "test_row": idx,
        "actual": actual_class,
        "predicted": predicted_class,
        "confidence": prediction_confidence[idx],
        "second_best_probability":
            second_highest_probability[idx],
        "confidence_margin":
            confidence_margin[idx],
        "crop":
            X_test_final.iloc[idx]["Crop"],
        "soil":
            X_test_final.iloc[idx]["Soil"],
        "phosphorous":
            X_test_final.iloc[idx]["Phosphorous"],
        "potassium":
            X_test_final.iloc[idx]["Potassium"],
        "nitrogen":
            X_test_final.iloc[idx]["Nitrogen"],
        "carbon":
            X_test_final.iloc[idx]["Carbon"],
        "moisture":
            X_test_final.iloc[idx]["Moisture"],
        "rainfall":
            X_test_final.iloc[idx]["Rainfall"],
        "temperature":
            X_test_final.iloc[idx]["Temperature"],
        "PH":
            X_test_final.iloc[idx]["PH"],
    })

error_df = pd.DataFrame(
    error_rows
)

if len(error_df) > 0:
    display(error_df)
else:
    print("No incorrect predictions.")

# ------------------------------------------------------------
# Confidence bins
# ------------------------------------------------------------

confidence_bins = pd.cut(
    prediction_confidence,
    bins=[
        0.0,
        0.50,
        0.70,
        0.80,
        0.90,
        0.95,
        1.00,
    ],
    include_lowest=True,
)

confidence_analysis = (
    pd.DataFrame({
        "confidence_bin": confidence_bins,
        "correct": correct_mask,
    })
    .groupby(
        "confidence_bin",
        observed=False,
    )
    .agg(
        samples=("correct", "size"),
        correct=("correct", "sum"),
    )
)

confidence_analysis[
    "accuracy"
] = (
    confidence_analysis["correct"]
    / confidence_analysis["samples"]
)

print("\n" + "=" * 70)
print("CONFIDENCE BIN ANALYSIS")
print("=" * 70)

display(confidence_analysis)

# ------------------------------------------------------------
# Save error analysis
# ------------------------------------------------------------

ERROR_FILE = (
    DATA_DIR
    / "fertilizer_xgboost_test_errors.csv"
)

error_df.to_csv(
    ERROR_FILE,
    index=False,
)

CONFIDENCE_FILE = (
    DATA_DIR
    / "fertilizer_xgboost_confidence_analysis.csv"
)

confidence_analysis.to_csv(
    CONFIDENCE_FILE
)

print("\nSaved:")
print(ERROR_FILE)
print(CONFIDENCE_FILE)

print("\n" + "=" * 70)
print("CONFIDENCE & ERROR ANALYSIS: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.16B — XGBOOST CONFIDENCE & ERROR ANALYSIS
======================================================================

Generating test probabilities...

Prediction confidence summary:
Mean confidence:   0.9891
Minimum confidence: 0.5109
Maximum confidence: 0.9998
Median confidence: 0.9980

Confidence by prediction correctness:
Correct predictions: 556
Mean confidence for correct predictions: 0.9912
Incorrect predictions: 4
Mean confidence for incorrect predictions: 0.6954

======================================================================
INCORRECT TEST PREDICTIONS
======================================================================

,test_row,actual,predicted,confidence,second_best_probability,confidence_margin,crop,soil,phosphorous,potassium,nitrogen,carbon,moisture,rainfall,temperature,PH
0,57,Compost,Gypsum,0.961365,0.033313,0.928052,orange,Alkaline Soil,55.896612,56.721840,65.235062,0.929163,0.716413,103.534827,24.187242,7.993819
1,91,Balanced NPK Fertilizer,Compost,0.747385,0.251294,0.496091,watermelon,Loamy Soil,151.628528,123.600209,55.369267,1.001326,0.772859,44.761161,25.709723,7.110970
2,430,Compost,Muriate of Potash,0.510878,0.484243,0.026635,grapes,Acidic Soil,67.656830,50.011211,58.708213,0.933777,0.699428,84.822270,28.580877,6.220273
3,491,Muriate of Potash,DAP,0.562038,0.424706,0.137331,Tea,Acidic Soil,50.086379,45.836415,68.850664,1.019499,0.470287,247.145994,25.135528,4.630736

======================================================================
CONFIDENCE BIN ANALYSIS
======================================================================

                samples  correct  accuracy
confidence_bin
(-0.001, 0.5]         0        0       NaN
(0.5, 0.7]            6        4  0.666667
(0.7, 0.8]            2        1  0.500000
(0.8, 0.9]            4        4  1.000000
(0.9, 0.95]          10       10  1.000000
(0.95, 1.0]         538      537  0.998141

Saved:
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_xgboost_test_errors.csv
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_xgboost_confidence_analysis.csv

======================================================================
CONFIDENCE & ERROR ANALYSIS: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.17 — XGBOOST FEATURE ABLATION STUDY
# ============================================================

from xgboost import XGBClassifier
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

print("=" * 70)
print("STEP 5.17 — XGBOOST FEATURE ABLATION STUDY")
print("=" * 70)

# ------------------------------------------------------------
# Define feature groups
# ------------------------------------------------------------

ALL_FEATURES = (
    NUMERICAL_FEATURES +
    CATEGORICAL_FEATURES
)

CROP_SOIL_FEATURES = [
    "Crop",
    "Soil",
]

NO_CROP_FEATURES = [
    feature
    for feature in ALL_FEATURES
    if feature != "Crop"
]

NO_SOIL_FEATURES = [
    feature
    for feature in ALL_FEATURES
    if feature != "Soil"
]

EXPERIMENTS = {
    "All Features": ALL_FEATURES,
    "Crop + Soil Only": CROP_SOIL_FEATURES,
    "Without Crop": NO_CROP_FEATURES,
    "Without Soil": NO_SOIL_FEATURES,
}

# ------------------------------------------------------------
# Function
# ------------------------------------------------------------

def run_ablation_experiment(
    experiment_name,
    features,
):

    numerical_features = [
        feature
        for feature in features
        if feature in NUMERICAL_FEATURES
    ]

    categorical_features = [
        feature
        for feature in features
        if feature in CATEGORICAL_FEATURES
    ]

    transformers = []

    if numerical_features:
        transformers.append(
            (
                "numerical",
                StandardScaler(),
                numerical_features,
            )
        )

    if categorical_features:
        transformers.append(
            (
                "categorical",
                OneHotEncoder(
                    handle_unknown="ignore",
                    sparse_output=False,
                ),
                categorical_features,
            )
        )

    preprocessor = ColumnTransformer(
        transformers=transformers,
        remainder="drop",
    )

    model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="multi:softprob",
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1,
    )

    pipeline = Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor,
            ),
            (
                "model",
                model,
            ),
        ]
    )

    results = cross_validate(
        pipeline,
        X[features],
        y_encoded,
        cv=cv,
        scoring={
            "accuracy": "accuracy",
            "precision_macro": "precision_macro",
            "recall_macro": "recall_macro",
            "f1_macro": "f1_macro",
            "f1_weighted": "f1_weighted",
        },
        n_jobs=1,
        return_train_score=True,
        error_score="raise",
    )

    return {
        "experiment": experiment_name,
        "features": ", ".join(features),
        "feature_count": len(features),

        "accuracy_mean":
            results["test_accuracy"].mean(),

        "accuracy_std":
            results["test_accuracy"].std(),

        "precision_macro_mean":
            results["test_precision_macro"].mean(),

        "recall_macro_mean":
            results["test_recall_macro"].mean(),

        "f1_macro_mean":
            results["test_f1_macro"].mean(),

        "f1_macro_std":
            results["test_f1_macro"].std(),

        "f1_weighted_mean":
            results["test_f1_weighted"].mean(),
    }


# ------------------------------------------------------------
# Run experiments
# ------------------------------------------------------------

ablation_results = []

for experiment_name, features in EXPERIMENTS.items():

    print("\n" + "-" * 70)
    print(
        f"Running: {experiment_name}"
    )
    print(
        f"Features ({len(features)}): {features}"
    )
    print("-" * 70)

    result = run_ablation_experiment(
        experiment_name,
        features,
    )

    ablation_results.append(result)

    print(
        f"Accuracy: {result['accuracy_mean']:.4f}"
    )

    print(
        f"Macro F1: {result['f1_macro_mean']:.4f}"
    )

# ------------------------------------------------------------
# Comparison
# ------------------------------------------------------------

ablation_df = pd.DataFrame(
    ablation_results
)

ablation_df = (
    ablation_df
    .sort_values(
        "f1_macro_mean",
        ascending=False,
    )
    .reset_index(drop=True)
)

print("\n" + "=" * 70)
print("FEATURE ABLATION RESULTS")
print("=" * 70)

display(
    ablation_df[
        [
            "experiment",
            "feature_count",
            "accuracy_mean",
            "accuracy_std",
            "precision_macro_mean",
            "recall_macro_mean",
            "f1_macro_mean",
            "f1_macro_std",
            "f1_weighted_mean",
        ]
    ].style.format({
        "accuracy_mean": "{:.4f}",
        "accuracy_std": "{:.4f}",
        "precision_macro_mean": "{:.4f}",
        "recall_macro_mean": "{:.4f}",
        "f1_macro_mean": "{:.4f}",
        "f1_macro_std": "{:.4f}",
        "f1_weighted_mean": "{:.4f}",
    })
)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

ABLATION_FILE = (
    DATA_DIR
    / "fertilizer_xgboost_feature_ablation.csv"
)

ablation_df.to_csv(
    ABLATION_FILE,
    index=False,
)

print("\nSaved:")
print(ABLATION_FILE)

print("\n" + "=" * 70)
print("FEATURE ABLATION STUDY: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.17 — XGBOOST FEATURE ABLATION STUDY
======================================================================

----------------------------------------------------------------------
Running: All Features
Features (10): ['Temperature', 'Moisture', 'Rainfall', 'PH', 'Nitrogen', 'Phosphorous', 'Potassium', 'Carbon', 'Soil', 'Crop']
----------------------------------------------------------------------
Accuracy: 0.9937
Macro F1: 0.9921

----------------------------------------------------------------------
Running: Crop + Soil Only
Features (2): ['Crop', 'Soil']
----------------------------------------------------------------------

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Accuracy: 0.5067
Macro F1: 0.3030

----------------------------------------------------------------------
Running: Without Crop
Features (9): ['Temperature', 'Moisture', 'Rainfall', 'PH', 'Nitrogen', 'Phosphorous', 'Potassium', 'Carbon', 'Soil']
----------------------------------------------------------------------
Accuracy: 0.9933
Macro F1: 0.9916

----------------------------------------------------------------------
Running: Without Soil
Features (9): ['Temperature', 'Moisture', 'Rainfall', 'PH', 'Nitrogen', 'Phosphorous', 'Potassium', 'Carbon', 'Crop']
----------------------------------------------------------------------
Accuracy: 0.9821
Macro F1: 0.9332

======================================================================
FEATURE ABLATION RESULTS
======================================================================

Saved:
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_xgboost_feature_ablation.csv

======================================================================
FEATURE ABLATION STUDY: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.18 — FINAL MODEL SELECTION
# ============================================================

print("=" * 70)
print("STEP 5.18 — FINAL MODEL SELECTION")
print("=" * 70)

# ------------------------------------------------------------
# Select model based on CV Macro F1
# ------------------------------------------------------------

best_model_row = comparison_df.iloc[0]

selected_model_name = best_model_row["model"]
selected_cv_macro_f1 = best_model_row["f1_macro_mean"]

print("\nModel selection criterion:")
print("  Primary metric: Macro F1")
print("  Validation method: 5-fold Stratified CV")
print("  Test set: untouched until final evaluation")

print("\nModel ranking:")

for rank, row in comparison_df.iterrows():

    print(
        f"  {rank + 1}. "
        f"{row['model']}: "
        f"Macro F1 = "
        f"{row['f1_macro_mean']:.4f}"
    )

print("\n" + "=" * 70)
print("SELECTED MODEL")
print("=" * 70)

print(
    f"\nModel: {selected_model_name}"
)

print(
    f"CV Macro F1: "
    f"{selected_cv_macro_f1:.4f}"
)

print(
    f"Final Test Macro F1: "
    f"{test_f1_macro:.4f}"
)

print(
    f"Final Test Accuracy: "
    f"{test_accuracy:.4f}"
)

print(
    f"Correct Test Predictions: "
    f"{correct_predictions}/{len(y_test_final)}"
)

print(
    f"Incorrect Test Predictions: "
    f"{incorrect_predictions}/{len(y_test_final)}"
)

# ------------------------------------------------------------
# Selection decision
# ------------------------------------------------------------

if selected_model_name == "XGBoost":

    selection_reason = (
        "XGBoost achieved the highest 5-fold CV Macro F1 "
        "among all evaluated candidate models and maintained "
        "strong performance on the untouched test set."
    )

else:

    selection_reason = (
        f"{selected_model_name} achieved the highest "
        "5-fold CV Macro F1 among evaluated models."
    )

print("\nSelection reason:")
print(selection_reason)

# ------------------------------------------------------------
# Save selection report
# ------------------------------------------------------------

selection_report = pd.DataFrame([
    {
        "selected_model": selected_model_name,
        "selection_metric": "Macro F1",
        "cv_macro_f1": selected_cv_macro_f1,
        "cv_accuracy": best_model_row["accuracy_mean"],
        "test_macro_f1": test_f1_macro,
        "test_accuracy": test_accuracy,
        "test_macro_precision": test_precision_macro,
        "test_macro_recall": test_recall_macro,
        "test_weighted_f1": test_f1_weighted,
        "test_correct": correct_predictions,
        "test_incorrect": incorrect_predictions,
        "selection_reason": selection_reason,
    }
])

SELECTION_FILE = (
    DATA_DIR
    / "fertilizer_final_model_selection.csv"
)

selection_report.to_csv(
    SELECTION_FILE,
    index=False,
)

print("\nSelection report saved:")
print(SELECTION_FILE)

print("\n" + "=" * 70)
print("FINAL MODEL SELECTION: COMPLETE")
print("=" * 70)

======================================================================
STEP 5.18 — FINAL MODEL SELECTION
======================================================================

Model selection criterion:
  Primary metric: Macro F1
  Validation method: 5-fold Stratified CV
  Test set: untouched until final evaluation

Model ranking:
  1. XGBoost: Macro F1 = 0.9921
  2. LightGBM: Macro F1 = 0.9880
  3. Random Forest: Macro F1 = 0.9276
  4. Logistic Regression: Macro F1 = 0.7488
  5. Extra Trees: Macro F1 = 0.6521

======================================================================
SELECTED MODEL
======================================================================

Model: XGBoost
CV Macro F1: 0.9921
Final Test Macro F1: 0.9891
Final Test Accuracy: 0.9929
Correct Test Predictions: 556/560
Incorrect Test Predictions: 4/560

Selection reason:
XGBoost achieved the highest 5-fold CV Macro F1 among all evaluated candidate models and maintained strong performance on the untouched test set.

Selection report saved:
/content/drive/MyDrive/ KrishiTrust_AI/datasets/fertilizer_final_model_selection.csv

======================================================================
FINAL MODEL SELECTION: COMPLETE
======================================================================

In [ ]:
# ============================================================
# STEP 5.19 — CORRECTED FINAL XGBOOST MODEL PACKAGING
# ============================================================

import joblib
import json
from pathlib import Path
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from xgboost import XGBClassifier

print("=" * 70)
print("STEP 5.19 — CORRECTED FINAL XGBOOST MODEL PACKAGING")
print("=" * 70)

# ------------------------------------------------------------
# 1. Directories
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/KrishiTrust_AI"
)

MODEL_DIR = PROJECT_ROOT / "model"
PREPROCESSING_DIR = MODEL_DIR / "preprocessing"
REPORT_DIR = PROJECT_ROOT / "reports" / "phase05_model_training"

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

PREPROCESSING_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

REPORT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

# ------------------------------------------------------------
# 2. Create final preprocessor
# ------------------------------------------------------------

final_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            CATEGORICAL_FEATURES,
        ),
    ],
    remainder="drop",
)

print("\nPreprocessor:")
print("  Numerical: StandardScaler")
print("  Categorical: OneHotEncoder")
print("  Unknown categories: ignored")

# ------------------------------------------------------------
# 3. Create final XGBoost
# ------------------------------------------------------------

final_xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1,
)

print("\nXGBoost:")
print("  n_estimators = 300")
print("  max_depth = 6")
print("  learning_rate = 0.05")
print("  subsample = 0.8")
print("  colsample_bytree = 0.8")
print("  random_state = 42")

# ------------------------------------------------------------
# 4. Create COMPLETE pipeline
# ------------------------------------------------------------

final_xgb_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            final_preprocessor,
        ),
        (
            "model",
            final_xgb_model,
        ),
    ]
)

print("\nComplete pipeline created.")

# ------------------------------------------------------------
# 5. Train on ALL training rows
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TRAINING FINAL PIPELINE")
print("=" * 70)

print("\nTraining rows:")
print(len(X))

print("\nTraining final pipeline...")

final_xgb_pipeline.fit(
    X,
    y_encoded,
)

print("\nFinal pipeline training: COMPLETE")

# ------------------------------------------------------------
# 6. Save COMPLETE pipeline
# ------------------------------------------------------------

FINAL_PIPELINE_FILE = (
    MODEL_DIR
    / "fertilizer_xgboost_pipeline.joblib"
)

joblib.dump(
    final_xgb_pipeline,
    FINAL_PIPELINE_FILE,
)

print("\nComplete XGBoost pipeline saved:")
print(FINAL_PIPELINE_FILE)

# ------------------------------------------------------------
# 7. Save separate preprocessor
# ------------------------------------------------------------

FINAL_PREPROCESSOR_FILE = (
    PREPROCESSING_DIR
    / "fertilizer_preprocessor.joblib"
)

joblib.dump(
    final_preprocessor,
    FINAL_PREPROCESSOR_FILE,
)

print("\nPreprocessor saved:")
print(FINAL_PREPROCESSOR_FILE)

# ------------------------------------------------------------
# 8. Save label encoder
# ------------------------------------------------------------

FINAL_LABEL_ENCODER_FILE = (
    PREPROCESSING_DIR
    / "fertilizer_label_encoder.joblib"
)

joblib.dump(
    xgb_label_encoder,
    FINAL_LABEL_ENCODER_FILE,
)

print("\nLabel encoder saved:")
print(FINAL_LABEL_ENCODER_FILE)

# ------------------------------------------------------------
# 9. Save feature configuration
# ------------------------------------------------------------

FEATURE_CONFIG_FILE = (
    PREPROCESSING_DIR
    / "fertilizer_feature_config.json"
)

feature_config = {
    "target": TARGET,

    "numerical_features":
        NUMERICAL_FEATURES,

    "categorical_features":
        CATEGORICAL_FEATURES,

    "all_features":
        NUMERICAL_FEATURES +
        CATEGORICAL_FEATURES,

    "excluded_features": [
        "Remark"
    ],

    "original_feature_count": 10,

    "transformed_feature_count": 44,

    "number_of_classes":
        len(xgb_label_encoder.classes_),

    "classes":
        xgb_label_encoder.classes_.tolist(),

    "model": "XGBoost",

    "pipeline": True,

    "model_parameters": {
        "n_estimators": 300,
        "max_depth": 6,
        "learning_rate": 0.05,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "random_state": 42,
    },

    "cv_folds": 5,

    "cv_macro_f1":
        float(selected_cv_macro_f1),

    "test_accuracy":
        float(test_accuracy),

    "test_macro_precision":
        float(test_precision_macro),

    "test_macro_recall":
        float(test_recall_macro),

    "test_macro_f1":
        float(test_f1_macro),

    "test_weighted_f1":
        float(test_f1_weighted),
}

with open(
    FEATURE_CONFIG_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        feature_config,
        f,
        indent=4,
    )

print("\nFeature configuration saved:")
print(FEATURE_CONFIG_FILE)

# ------------------------------------------------------------
# 10. Save metadata
# ------------------------------------------------------------

MODEL_METADATA_FILE = (
    MODEL_DIR
    / "fertilizer_model_metadata.json"
)

metadata = {
    "model_name":
        "fertilizer_xgboost_pipeline",

    "model_type":
        "XGBClassifier",

    "purpose":
        "Fertilizer recommendation based on crop and agricultural conditions",

    "training_rows":
        int(len(X)),

    "test_rows":
        int(len(X_test_final)),

    "classes":
        xgb_label_encoder.classes_.tolist(),

    "cv_macro_f1":
        float(selected_cv_macro_f1),

    "test_accuracy":
        float(test_accuracy),

    "test_macro_precision":
        float(test_precision_macro),

    "test_macro_recall":
        float(test_recall_macro),

    "test_macro_f1":
        float(test_f1_macro),

    "test_weighted_f1":
        float(test_f1_weighted),

    "correct_test_predictions":
        int(correct_predictions),

    "incorrect_test_predictions":
        int(incorrect_predictions),

    "feature_count":
        10,

    "transformed_feature_count":
        44,

    "excluded_features": [
        "Remark"
    ],

    "random_state":
        42,
}

with open(
    MODEL_METADATA_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        metadata,
        f,
        indent=4,
    )

print("\nModel metadata saved:")
print(MODEL_METADATA_FILE)

# ------------------------------------------------------------
# 11. Validate saved files
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PACKAGING VALIDATION")
print("=" * 70)

required_files = [
    FINAL_PIPELINE_FILE,
    FINAL_PREPROCESSOR_FILE,
    FINAL_LABEL_ENCODER_FILE,
    FEATURE_CONFIG_FILE,
    MODEL_METADATA_FILE,
]

all_files_exist = True

for file_path in required_files:

    exists = file_path.exists()

    print(
        f"{file_path.name}: "
        f"{'PASS' if exists else 'FAIL'}"
    )

    if not exists:
        all_files_exist = False

# ------------------------------------------------------------
# 12. Final status
# ------------------------------------------------------------

print("\n" + "=" * 70)

if all_files_exist:
    print("FINAL MODEL PACKAGING: PASS")
else:
    print("FINAL MODEL PACKAGING: FAIL")

print("=" * 70)

======================================================================
STEP 5.19 — CORRECTED FINAL XGBOOST MODEL PACKAGING
======================================================================

Preprocessor:
  Numerical: StandardScaler
  Categorical: OneHotEncoder
  Unknown categories: ignored

XGBoost:
  n_estimators = 300
  max_depth = 6
  learning_rate = 0.05
  subsample = 0.8
  colsample_bytree = 0.8
  random_state = 42

Complete pipeline created.

======================================================================
TRAINING FINAL PIPELINE
======================================================================

Training rows:
2238

Training final pipeline...

Final pipeline training: COMPLETE

Complete XGBoost pipeline saved:
/content/drive/MyDrive/KrishiTrust_AI/model/fertilizer_xgboost_pipeline.joblib

Preprocessor saved:
/content/drive/MyDrive/KrishiTrust_AI/model/preprocessing/fertilizer_preprocessor.joblib

Label encoder saved:
/content/drive/MyDrive/KrishiTrust_AI/model/preprocessing/fertilizer_label_encoder.joblib

Feature configuration saved:
/content/drive/MyDrive/KrishiTrust_AI/model/preprocessing/fertilizer_feature_config.json

Model metadata saved:
/content/drive/MyDrive/KrishiTrust_AI/model/fertilizer_model_metadata.json

======================================================================
PACKAGING VALIDATION
======================================================================
fertilizer_xgboost_pipeline.joblib: PASS
fertilizer_preprocessor.joblib: PASS
fertilizer_label_encoder.joblib: PASS
fertilizer_feature_config.json: PASS
fertilizer_model_metadata.json: PASS

======================================================================
FINAL MODEL PACKAGING: PASS
======================================================================

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/ KrishiTrust_AI")

print("Checking final model files...\n")

files = [
    PROJECT_ROOT / "model/fertilizer_xgboost_pipeline.joblib",
    PROJECT_ROOT / "model/fertilizer_model_metadata.json",
    PROJECT_ROOT / "model/preprocessing/fertilizer_preprocessor.joblib",
    PROJECT_ROOT / "model/preprocessing/fertilizer_label_encoder.joblib",
    PROJECT_ROOT / "model/preprocessing/fertilizer_feature_config.json",
]

for file in files:
    print(
        f"{'FOUND ✅' if file.exists() else 'NOT FOUND ❌'}  {file}"
    )

Checking final model files...

NOT FOUND ❌  /content/drive/MyDrive/ KrishiTrust_AI/model/fertilizer_xgboost_pipeline.joblib
NOT FOUND ❌  /content/drive/MyDrive/ KrishiTrust_AI/model/fertilizer_model_metadata.json
NOT FOUND ❌  /content/drive/MyDrive/ KrishiTrust_AI/model/preprocessing/fertilizer_preprocessor.joblib
NOT FOUND ❌  /content/drive/MyDrive/ KrishiTrust_AI/model/preprocessing/fertilizer_label_encoder.joblib
NOT FOUND ❌  /content/drive/MyDrive/ KrishiTrust_AI/model/preprocessing/fertilizer_feature_config.json

In [ ]:
# ============================================================
# STEP 5.19 — FINAL XGBOOST MODEL PACKAGING
# SELF-CONTAINED VERSION
# ============================================================

from pathlib import Path
import joblib
import json

import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from xgboost import XGBClassifier


print("=" * 70)
print("STEP 5.19 — FINAL XGBOOST MODEL PACKAGING")
print("=" * 70)


# ============================================================
# 1. PROJECT PATH
# ============================================================

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/KrishiTrust_AI"
)

MODEL_DIR = PROJECT_ROOT / "model"
PREPROCESSING_DIR = MODEL_DIR / "preprocessing"

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PREPROCESSING_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("\nProject root:")
print(PROJECT_ROOT)


# ============================================================
# 2. DEFINE FEATURES EXPLICITLY
# ============================================================

NUMERICAL_FEATURES = [
    "Temperature",
    "Moisture",
    "Rainfall",
    "PH",
    "Nitrogen",
    "Phosphorous",
    "Potassium",
    "Carbon"
]

CATEGORICAL_FEATURES = [
    "Soil",
    "Crop"
]

ALL_FEATURES = (
    NUMERICAL_FEATURES +
    CATEGORICAL_FEATURES
)

TARGET = "Fertilizer"

print("\nNumerical features:")
for feature in NUMERICAL_FEATURES:
    print("  -", feature)

print("\nCategorical features:")
for feature in CATEGORICAL_FEATURES:
    print("  -", feature)

print("\nTarget:")
print(" ", TARGET)


# ============================================================
# 3. VALIDATE REQUIRED VARIABLES
# ============================================================

required_variables = [
    "X",
    "y_encoded",
    "xgb_label_encoder",
    "selected_cv_macro_f1",
    "test_accuracy",
    "test_precision_macro",
    "test_recall_macro",
    "test_f1_macro",
    "test_f1_weighted",
    "correct_predictions",
    "incorrect_predictions"
]

print("\n" + "=" * 70)
print("NOTEBOOK VARIABLE VALIDATION")
print("=" * 70)

missing_variables = []

for variable_name in required_variables:

    if variable_name in globals():

        print(
            f"{variable_name}: PASS"
        )

    else:

        print(
            f"{variable_name}: NOT FOUND"
        )

        missing_variables.append(
            variable_name
        )

if missing_variables:

    raise NameError(
        "Required notebook variables are missing: "
        + ", ".join(missing_variables)
        + ". Run the earlier model-training/evaluation cells first."
    )

print("\nNotebook variable validation: PASS")


# ============================================================
# 4. VALIDATE TRAINING DATA
# ============================================================

print("\n" + "=" * 70)
print("TRAINING DATA VALIDATION")
print("=" * 70)

missing_features = [
    feature
    for feature in ALL_FEATURES
    if feature not in X.columns
]

if missing_features:

    raise ValueError(
        "Missing training features: "
        + ", ".join(missing_features)
    )

print(
    "Training feature validation: PASS"
)

print(
    "Training rows:",
    len(X)
)

print(
    "Training features:",
    len(ALL_FEATURES)
)


# ============================================================
# 5. CREATE PREPROCESSOR
# ============================================================

print("\n" + "=" * 70)
print("CREATING FINAL PREPROCESSOR")
print("=" * 70)

final_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            CATEGORICAL_FEATURES
        )
    ],
    remainder="drop"
)

print("\nPreprocessor created:")
print("  Numerical: StandardScaler")
print("  Categorical: OneHotEncoder")
print("  Unknown categories: ignored")


# ============================================================
# 6. CREATE FINAL XGBOOST MODEL
# ============================================================

print("\n" + "=" * 70)
print("CREATING FINAL XGBOOST MODEL")
print("=" * 70)

final_xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1
)

print("\nConfiguration:")
print("  n_estimators = 300")
print("  max_depth = 6")
print("  learning_rate = 0.05")
print("  subsample = 0.8")
print("  colsample_bytree = 0.8")
print("  random_state = 42")


# ============================================================
# 7. CREATE COMPLETE PIPELINE
# ============================================================

final_xgb_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            final_preprocessor
        ),
        (
            "model",
            final_xgb_model
        )
    ]
)

print("\nComplete pipeline created.")


# ============================================================
# 8. TRAIN FINAL PIPELINE
# ============================================================

print("\n" + "=" * 70)
print("TRAINING FINAL PIPELINE")
print("=" * 70)

print(
    "\nTraining rows:",
    len(X)
)

print(
    "Training target rows:",
    len(y_encoded)
)

print(
    "Number of classes:",
    len(xgb_label_encoder.classes_)
)

final_xgb_pipeline.fit(
    X[ALL_FEATURES],
    y_encoded
)

print(
    "\nFinal pipeline training: COMPLETE"
)


# ============================================================
# 9. CHECK TRANSFORMED FEATURE COUNT
# ============================================================

transformed_feature_names = (
    final_xgb_pipeline
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

transformed_feature_count = (
    len(transformed_feature_names)
)

print("\nTransformed feature count:")
print(
    transformed_feature_count
)

if transformed_feature_count != 44:

    print(
        "\nWARNING:"
        "\nExpected 44 transformed features."
        f"\nActual: {transformed_feature_count}"
    )

else:

    print(
        "Transformed feature validation: PASS"
    )


# ============================================================
# 10. SAVE COMPLETE PIPELINE
# ============================================================

PIPELINE_FILE = (
    MODEL_DIR /
    "fertilizer_xgboost_pipeline.joblib"
)

joblib.dump(
    final_xgb_pipeline,
    PIPELINE_FILE
)

print("\nComplete XGBoost pipeline saved:")
print(PIPELINE_FILE)


# ============================================================
# 11. SAVE PREPROCESSOR
# ============================================================

PREPROCESSOR_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_preprocessor.joblib"
)

joblib.dump(
    final_preprocessor,
    PREPROCESSOR_FILE
)

print("\nPreprocessor saved:")
print(PREPROCESSOR_FILE)


# ============================================================
# 12. SAVE LABEL ENCODER
# ============================================================

LABEL_ENCODER_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_label_encoder.joblib"
)

joblib.dump(
    xgb_label_encoder,
    LABEL_ENCODER_FILE
)

print("\nLabel encoder saved:")
print(LABEL_ENCODER_FILE)


# ============================================================
# 13. SAVE FEATURE CONFIGURATION
# ============================================================

FEATURE_CONFIG_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_feature_config.json"
)

feature_config = {

    "target":
        TARGET,

    "numerical_features":
        NUMERICAL_FEATURES,

    "categorical_features":
        CATEGORICAL_FEATURES,

    "all_features":
        ALL_FEATURES,

    "excluded_features":
        ["Remark"],

    "original_feature_count":
        len(ALL_FEATURES),

    "transformed_feature_count":
        transformed_feature_count,

    "number_of_classes":
        len(xgb_label_encoder.classes_),

    "classes":
        xgb_label_encoder.classes_.tolist(),

    "model":
        "XGBoost",

    "model_type":
        "XGBClassifier",

    "pipeline":
        True,

    "parameters": {

        "n_estimators": 300,

        "max_depth": 6,

        "learning_rate": 0.05,

        "subsample": 0.8,

        "colsample_bytree": 0.8,

        "random_state": 42
    }
}

with open(
    FEATURE_CONFIG_FILE,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        feature_config,
        file,
        indent=4
    )

print("\nFeature configuration saved:")
print(FEATURE_CONFIG_FILE)


# ============================================================
# 14. SAVE MODEL METADATA
# ============================================================

METADATA_FILE = (
    MODEL_DIR /
    "fertilizer_model_metadata.json"
)

metadata = {

    "model_name":
        "fertilizer_xgboost_pipeline",

    "purpose":
        "Fertilizer recommendation",

    "training_rows":
        int(len(X)),

    "number_of_classes":
        int(len(xgb_label_encoder.classes_)),

    "classes":
        xgb_label_encoder.classes_.tolist(),

    "cv_macro_f1":
        float(selected_cv_macro_f1),

    "test_accuracy":
        float(test_accuracy),

    "test_macro_precision":
        float(test_precision_macro),

    "test_macro_recall":
        float(test_recall_macro),

    "test_macro_f1":
        float(test_f1_macro),

    "test_weighted_f1":
        float(test_f1_weighted),

    "correct_test_predictions":
        int(correct_predictions),

    "incorrect_test_predictions":
        int(incorrect_predictions),

    "feature_count":
        len(ALL_FEATURES),

    "transformed_feature_count":
        transformed_feature_count,

    "excluded_features":
        ["Remark"],

    "random_state":
        42
}

with open(
    METADATA_FILE,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        metadata,
        file,
        indent=4
    )

print("\nModel metadata saved:")
print(METADATA_FILE)


# ============================================================
# 15. FINAL FILE VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("PACKAGING VALIDATION")
print("=" * 70)

required_files = [

    PIPELINE_FILE,

    PREPROCESSOR_FILE,

    LABEL_ENCODER_FILE,

    FEATURE_CONFIG_FILE,

    METADATA_FILE
]

all_files_exist = True

for file_path in required_files:

    if file_path.exists():

        size_mb = (
            file_path.stat().st_size
            / (1024 * 1024)
        )

        print(
            f"FOUND ✅  "
            f"{file_path.name} "
            f"({size_mb:.2f} MB)"
        )

    else:

        print(
            f"NOT FOUND ❌  "
            f"{file_path}"
        )

        all_files_exist = False


# ============================================================
# 16. FINAL STATUS
# ============================================================

print("\n" + "=" * 70)

if all_files_exist:

    print(
        "FINAL MODEL PACKAGING: PASS ✅"
    )

else:

    print(
        "FINAL MODEL PACKAGING: FAIL ❌"
    )

print("=" * 70)

======================================================================
STEP 5.19 — FINAL XGBOOST MODEL PACKAGING
======================================================================

Project root:
/content/drive/MyDrive/KrishiTrust_AI

Numerical features:
  - Temperature
  - Moisture
  - Rainfall
  - PH
  - Nitrogen
  - Phosphorous
  - Potassium
  - Carbon

Categorical features:
  - Soil
  - Crop

Target:
  Fertilizer

======================================================================
NOTEBOOK VARIABLE VALIDATION
======================================================================
X: NOT FOUND
y_encoded: NOT FOUND
xgb_label_encoder: NOT FOUND
selected_cv_macro_f1: NOT FOUND
test_accuracy: NOT FOUND
test_precision_macro: NOT FOUND
test_recall_macro: NOT FOUND
test_f1_macro: NOT FOUND
test_f1_weighted: NOT FOUND
correct_predictions: NOT FOUND
incorrect_predictions: NOT FOUND

NameError: Required notebook variables are missing: X, y_encoded, xgb_label_encoder, selected_cv_macro_f1, test_accuracy, test_precision_macro, test_recall_macro, test_f1_macro, test_f1_weighted, correct_predictions, incorrect_predictions. Run the earlier model-training/evaluation cells first.

In [ ]:
# ============================================================
# STEP 5.19A — RELOAD TRAINING DATA AND ARTIFACTS
# ============================================================

from pathlib import Path
import pandas as pd
import joblib

print("=" * 70)
print("STEP 5.19A — RELOAD TRAINING DATA AND ARTIFACTS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/KrishiTrust_AI"
)

DATA_DIR = PROJECT_ROOT / "datasets"
MODEL_DIR = PROJECT_ROOT / "model"
PREPROCESSING_DIR = MODEL_DIR / "preprocessing"

TRAIN_FILE = DATA_DIR / "fertilizer_train.csv"
TEST_FILE = DATA_DIR / "fertilizer_test.csv"

PREPROCESSOR_FILE = (
    DATA_DIR / "fertilizer_preprocessor.joblib"
)

LABEL_ENCODER_FILE = (
    DATA_DIR / "fertilizer_label_encoder.joblib"
)

# ------------------------------------------------------------
# 2. Load datasets
# ------------------------------------------------------------

print("\nLoading training dataset...")

train_df = pd.read_csv(TRAIN_FILE)

print(
    f"Training dataset: {train_df.shape}"
)

print("\nLoading testing dataset...")

test_df = pd.read_csv(TEST_FILE)

print(
    f"Testing dataset: {test_df.shape}"
)

# ------------------------------------------------------------
# 3. Define features
# ------------------------------------------------------------

NUMERICAL_FEATURES = [
    "Temperature",
    "Moisture",
    "Rainfall",
    "PH",
    "Nitrogen",
    "Phosphorous",
    "Potassium",
    "Carbon"
]

CATEGORICAL_FEATURES = [
    "Soil",
    "Crop"
]

ALL_FEATURES = (
    NUMERICAL_FEATURES +
    CATEGORICAL_FEATURES
)

TARGET = "Fertilizer"

# ------------------------------------------------------------
# 4. Validate columns
# ------------------------------------------------------------

required_columns = ALL_FEATURES + [TARGET]

missing_train = [
    col
    for col in required_columns
    if col not in train_df.columns
]

missing_test = [
    col
    for col in required_columns
    if col not in test_df.columns
]

if missing_train:
    raise ValueError(
        f"Missing training columns: {missing_train}"
    )

if missing_test:
    raise ValueError(
        f"Missing testing columns: {missing_test}"
    )

print("\nColumn validation: PASS")

# ------------------------------------------------------------
# 5. Separate X and y
# ------------------------------------------------------------

X_train = train_df[ALL_FEATURES].copy()
X_test = test_df[ALL_FEATURES].copy()

y_train_text = train_df[TARGET].copy()
y_test_text = test_df[TARGET].copy()

print("\nFeature shapes:")
print(
    "X_train:",
    X_train.shape
)

print(
    "X_test:",
    X_test.shape
)

# ------------------------------------------------------------
# 6. Load label encoder
# ------------------------------------------------------------

print("\nLoading label encoder...")

if LABEL_ENCODER_FILE.exists():

    label_encoder = joblib.load(
        LABEL_ENCODER_FILE
    )

    print(
        "Label encoder loaded: PASS"
    )

else:

    raise FileNotFoundError(
        f"Label encoder not found:\n"
        f"{LABEL_ENCODER_FILE}"
    )

# ------------------------------------------------------------
# 7. Encode targets
# ------------------------------------------------------------

y_train = label_encoder.transform(
    y_train_text
)

y_test = label_encoder.transform(
    y_test_text
)

print("\nTarget encoding: PASS")

print(
    "Number of classes:",
    len(label_encoder.classes_)
)

print("\nClass mapping:")

for i, class_name in enumerate(
    label_encoder.classes_
):

    print(
        f"  {i} -> {class_name}"
    )

# ------------------------------------------------------------
# 8. Final validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RELOAD VALIDATION")
print("=" * 70)

print(
    f"Training rows: {len(X_train)}"
)

print(
    f"Testing rows:  {len(X_test)}"
)

print(
    f"Features:      {len(ALL_FEATURES)}"
)

print(
    f"Classes:       {len(label_encoder.classes_)}"
)

print(
    "\nRELOAD STEP: PASS"
)

print("=" * 70)

======================================================================
STEP 5.19A — RELOAD TRAINING DATA AND ARTIFACTS
======================================================================

Loading training dataset...

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/KrishiTrust_AI/datasets/fertilizer_train.csv'

In [ ]:
from pathlib import Path

print("=" * 70)
print("SEARCHING GOOGLE DRIVE FOR FERTILIZER FILES")
print("=" * 70)

SEARCH_ROOT = Path("/content/drive/MyDrive")

files_to_find = [
    "fertilizer_train.csv",
    "fertilizer_test.csv",
    "fertilizer_preprocessor.joblib",
    "fertilizer_label_encoder.joblib"
]

found = {}

for filename in files_to_find:

    matches = list(
        SEARCH_ROOT.rglob(filename)
    )

    print(f"\n{filename}")

    if matches:

        for match in matches:
            print("  FOUND ✅")
            print(" ", match)

        found[filename] = matches[0]

    else:

        print("  NOT FOUND ❌")


print("\n" + "=" * 70)
print("SEARCH COMPLETE")
print("=" * 70)

======================================================================
SEARCHING GOOGLE DRIVE FOR FERTILIZER FILES
======================================================================

fertilizer_train.csv
  NOT FOUND ❌

fertilizer_test.csv
  NOT FOUND ❌

fertilizer_preprocessor.joblib
  NOT FOUND ❌

fertilizer_label_encoder.joblib
  NOT FOUND ❌

======================================================================
SEARCH COMPLETE
======================================================================

In [ ]:
from pathlib import Path

root = Path("/content/drive/MyDrive")

print("=" * 70)
print("GOOGLE DRIVE — TOP LEVEL")
print("=" * 70)

for item in sorted(root.iterdir()):
    print(item.name)

print("\n" + "=" * 70)
print("SEARCHING FOR KRISHITRUST FOLDERS")
print("=" * 70)

for item in root.iterdir():
    if "Krishi" in item.name or "krishi" in item.name:
        print(repr(item.name))
        print(item)

======================================================================
GOOGLE DRIVE — TOP LEVEL
======================================================================
KrishiTrust_AI

======================================================================
SEARCHING FOR KRISHITRUST FOLDERS
======================================================================
'KrishiTrust_AI'
/content/drive/MyDrive/KrishiTrust_AI

In [ ]:
from pathlib import Path

ROOT = Path("/content/drive/MyDrive/KrishiTrust_AI/")

print("=" * 70)
print("KrishiTrust_AI — COMPLETE STRUCTURE")
print("=" * 70)

for path in sorted(ROOT.rglob("*")):

    relative = path.relative_to(ROOT)

    if path.is_dir():
        print(f"[DIR ] {relative}")
    else:
        size_mb = path.stat().st_size / (1024 * 1024)
        print(f"[FILE] {relative} ({size_mb:.2f} MB)")

print("\n" + "=" * 70)
print("STRUCTURE CHECK COMPLETE")
print("=" * 70)

======================================================================
KrishiTrust_AI — COMPLETE STRUCTURE
======================================================================
[DIR ] model
[DIR ] model/preprocessing

======================================================================
STRUCTURE CHECK COMPLETE
======================================================================

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

ValueError: Mountpoint must not already contain files

In [ ]:
!rm -rf /content/drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path

root = Path("/content/drive/MyDrive/KrishiTrust_AI")

print("Project exists:", root.exists())
print("\nContents:")

for item in root.iterdir():
    print(item)

Project exists: True

Contents:
/content/drive/MyDrive/KrishiTrust_AI/models
/content/drive/MyDrive/KrishiTrust_AI/model
/content/drive/MyDrive/KrishiTrust_AI/reports

In [ ]:
from pathlib import Path

dataset_dir = Path(
    "/content/drive/MyDrive/ KrishiTrust_AI/datasets"
)

print("=" * 70)
print("FERTILIZER FILE CHECK")
print("=" * 70)

files = [
    "fertilizer_train.csv",
    "fertilizer_test.csv",
    "fertilizer_preprocessor.joblib",
    "fertilizer_label_encoder.joblib"
]

for filename in files:

    path = dataset_dir / filename

    if path.exists():
        print(f"FOUND ✅  {filename}")
    else:
        print(f"NOT FOUND ❌  {filename}")

======================================================================
FERTILIZER FILE CHECK
======================================================================
FOUND ✅  fertilizer_train.csv
FOUND ✅  fertilizer_test.csv
FOUND ✅  fertilizer_preprocessor.joblib
FOUND ✅  fertilizer_label_encoder.joblib

In [ ]:
# ============================================================
# STEP 5.19 — FINAL XGBOOST MODEL PACKAGING
# ============================================================

from pathlib import Path
import pandas as pd
import joblib
import json

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from xgboost import XGBClassifier


print("=" * 70)
print("STEP 5.19 — FINAL XGBOOST MODEL PACKAGING")
print("=" * 70)


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/ KrishiTrust_AI"
)

DATA_DIR = PROJECT_ROOT / "datasets"
MODEL_DIR = PROJECT_ROOT / "model"
PREPROCESSING_DIR = MODEL_DIR / "preprocessing"

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PREPROCESSING_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TRAIN_FILE = DATA_DIR / "fertilizer_train.csv"
TEST_FILE = DATA_DIR / "fertilizer_test.csv"

LABEL_ENCODER_FILE = (
    DATA_DIR / "fertilizer_label_encoder.joblib"
)


# ============================================================
# 2. LOAD DATA
# ============================================================

print("\nLoading training dataset...")

train_df = pd.read_csv(TRAIN_FILE)

print(
    "Training shape:",
    train_df.shape
)

print("\nLoading testing dataset...")

test_df = pd.read_csv(TEST_FILE)

print(
    "Testing shape:",
    test_df.shape
)


# ============================================================
# 3. DEFINE FEATURES
# ============================================================

NUMERICAL_FEATURES = [
    "Temperature",
    "Moisture",
    "Rainfall",
    "PH",
    "Nitrogen",
    "Phosphorous",
    "Potassium",
    "Carbon"
]

CATEGORICAL_FEATURES = [
    "Soil",
    "Crop"
]

ALL_FEATURES = (
    NUMERICAL_FEATURES +
    CATEGORICAL_FEATURES
)

TARGET = "Fertilizer"


# ============================================================
# 4. VALIDATE COLUMNS
# ============================================================

required_columns = (
    ALL_FEATURES +
    [TARGET]
)

for column in required_columns:

    if column not in train_df.columns:
        raise ValueError(
            f"Missing training column: {column}"
        )

    if column not in test_df.columns:
        raise ValueError(
            f"Missing testing column: {column}"
        )

print("\nColumn validation: PASS")


# ============================================================
# 5. PREPARE TRAINING DATA
# ============================================================

X_train = train_df[
    ALL_FEATURES
].copy()

X_test = test_df[
    ALL_FEATURES
].copy()

y_train_text = train_df[
    TARGET
].copy()

y_test_text = test_df[
    TARGET
].copy()


# ============================================================
# 6. LOAD LABEL ENCODER
# ============================================================

print("\nLoading label encoder...")

label_encoder = joblib.load(
    LABEL_ENCODER_FILE
)

print(
    "Label encoder loaded: PASS"
)


# ============================================================
# 7. ENCODE TARGET
# ============================================================

y_train = label_encoder.transform(
    y_train_text
)

y_test = label_encoder.transform(
    y_test_text
)

print("\nTarget encoding: PASS")

print(
    "Number of classes:",
    len(label_encoder.classes_)
)

print("\nClass mapping:")

for index, class_name in enumerate(
    label_encoder.classes_
):

    print(
        f"  {index} -> {class_name}"
    )


# ============================================================
# 8. CREATE PREPROCESSOR
# ============================================================

print("\n" + "=" * 70)
print("CREATING FINAL PREPROCESSOR")
print("=" * 70)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            CATEGORICAL_FEATURES
        )
    ],
    remainder="drop"
)

print(
    "\nPreprocessor created."
)


# ============================================================
# 9. CREATE XGBOOST
# ============================================================

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1
)

print("\nXGBoost configuration:")

print("  n_estimators = 300")
print("  max_depth = 6")
print("  learning_rate = 0.05")
print("  subsample = 0.8")
print("  colsample_bytree = 0.8")
print("  random_state = 42")


# ============================================================
# 10. COMPLETE PIPELINE
# ============================================================

final_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "model",
            xgb_model
        )
    ]
)

print(
    "\nComplete pipeline created."
)


# ============================================================
# 11. TRAIN FINAL MODEL
# ============================================================

print("\n" + "=" * 70)
print("TRAINING FINAL XGBOOST PIPELINE")
print("=" * 70)

print(
    "\nTraining rows:",
    len(X_train)
)

print(
    "Training features:",
    len(ALL_FEATURES)
)

print(
    "\nTraining..."
)

final_pipeline.fit(
    X_train,
    y_train
)

print(
    "\nFinal XGBoost pipeline training: COMPLETE"
)


# ============================================================
# 12. VALIDATE TRANSFORMED FEATURES
# ============================================================

transformed_features = (
    final_pipeline
    .named_steps[
        "preprocessor"
    ]
    .get_feature_names_out()
)

print(
    "\nTransformed feature count:",
    len(transformed_features)
)

if len(transformed_features) == 44:

    print(
        "Transformed feature validation: PASS"
    )

else:

    print(
        "WARNING: transformed feature count "
        f"is {len(transformed_features)}, "
        "expected 44."
    )


# ============================================================
# 13. SAVE COMPLETE PIPELINE
# ============================================================

PIPELINE_FILE = (
    MODEL_DIR /
    "fertilizer_xgboost_pipeline.joblib"
)

joblib.dump(
    final_pipeline,
    PIPELINE_FILE
)

print("\nComplete pipeline saved:")
print(
    PIPELINE_FILE
)


# ============================================================
# 14. SAVE PREPROCESSOR
# ============================================================

PREPROCESSOR_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_preprocessor.joblib"
)

joblib.dump(
    preprocessor,
    PREPROCESSOR_FILE
)

print("\nPreprocessor saved:")
print(
    PREPROCESSOR_FILE
)


# ============================================================
# 15. SAVE LABEL ENCODER
# ============================================================

FINAL_LABEL_ENCODER_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_label_encoder.joblib"
)

joblib.dump(
    label_encoder,
    FINAL_LABEL_ENCODER_FILE
)

print("\nLabel encoder saved:")
print(
    FINAL_LABEL_ENCODER_FILE
)


# ============================================================
# 16. SAVE FEATURE CONFIG
# ============================================================

FEATURE_CONFIG_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_feature_config.json"
)

feature_config = {

    "target":
        TARGET,

    "numerical_features":
        NUMERICAL_FEATURES,

    "categorical_features":
        CATEGORICAL_FEATURES,

    "all_features":
        ALL_FEATURES,

    "excluded_features":
        ["Remark"],

    "original_feature_count":
        len(ALL_FEATURES),

    "transformed_feature_count":
        len(transformed_features),

    "number_of_classes":
        len(label_encoder.classes_),

    "classes":
        label_encoder.classes_.tolist(),

    "model":
        "XGBoost",

    "pipeline":
        True,

    "random_state":
        42
}

with open(
    FEATURE_CONFIG_FILE,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        feature_config,
        file,
        indent=4
    )

print("\nFeature configuration saved:")
print(
    FEATURE_CONFIG_FILE
)


# ============================================================
# 17. SAVE MODEL METADATA
# ============================================================

METADATA_FILE = (
    MODEL_DIR /
    "fertilizer_model_metadata.json"
)

metadata = {

    "model_name":
        "fertilizer_xgboost_pipeline",

    "purpose":
        "Fertilizer recommendation",

    "training_rows":
        int(len(X_train)),

    "testing_rows":
        int(len(X_test)),

    "number_of_classes":
        int(len(label_encoder.classes_)),

    "classes":
        label_encoder.classes_.tolist(),

    "cv_macro_f1":
        0.9921,

    "test_accuracy":
        0.9929,

    "test_macro_precision":
        0.9869,

    "test_macro_recall":
        0.9919,

    "test_macro_f1":
        0.9891,

    "test_weighted_f1":
        0.9929,

    "correct_test_predictions":
        556,

    "incorrect_test_predictions":
        4,

    "feature_count":
        len(ALL_FEATURES),

    "transformed_feature_count":
        len(transformed_features),

    "excluded_features":
        ["Remark"],

    "random_state":
        42
}

with open(
    METADATA_FILE,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        metadata,
        file,
        indent=4
    )

print("\nModel metadata saved:")
print(
    METADATA_FILE
)


# ============================================================
# 18. FINAL FILE VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("FINAL PACKAGING VALIDATION")
print("=" * 70)

required_files = [

    PIPELINE_FILE,

    PREPROCESSOR_FILE,

    FINAL_LABEL_ENCODER_FILE,

    FEATURE_CONFIG_FILE,

    METADATA_FILE
]

all_files_exist = True

for file_path in required_files:

    if file_path.exists():

        size_mb = (
            file_path.stat().st_size
            / (1024 * 1024)
        )

        print(
            f"FOUND ✅  "
            f"{file_path.name} "
            f"({size_mb:.2f} MB)"
        )

    else:

        print(
            f"NOT FOUND ❌  "
            f"{file_path}"
        )

        all_files_exist = False


# ============================================================
# 19. FINAL STATUS
# ============================================================

print("\n" + "=" * 70)

if all_files_exist:

    print(
        "FINAL MODEL PACKAGING: PASS ✅"
    )

else:

    print(
        "FINAL MODEL PACKAGING: FAIL ❌"
    )

print("=" * 70)

======================================================================
STEP 5.19 — FINAL XGBOOST MODEL PACKAGING
======================================================================

Loading training dataset...
Training shape: (2238, 12)

Loading testing dataset...
Testing shape: (560, 12)

Column validation: PASS

Loading label encoder...

/usr/local/lib/python3.13/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.6.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

Label encoder loaded: PASS

Target encoding: PASS
Number of classes: 10

Class mapping:
  0 -> Balanced NPK Fertilizer
  1 -> Compost
  2 -> DAP
  3 -> General Purpose Fertilizer
  4 -> Gypsum
  5 -> Lime
  6 -> Muriate of Potash
  7 -> Organic Fertilizer
  8 -> Urea
  9 -> Water Retaining Fertilizer

======================================================================
CREATING FINAL PREPROCESSOR
======================================================================

Preprocessor created.

XGBoost configuration:
  n_estimators = 300
  max_depth = 6
  learning_rate = 0.05
  subsample = 0.8
  colsample_bytree = 0.8
  random_state = 42

Complete pipeline created.

======================================================================
TRAINING FINAL XGBOOST PIPELINE
======================================================================

Training rows: 2238
Training features: 10

Training...

Final XGBoost pipeline training: COMPLETE

Transformed feature count: 44
Transformed feature validation: PASS

Complete pipeline saved:
/content/drive/MyDrive/ KrishiTrust_AI/model/fertilizer_xgboost_pipeline.joblib

Preprocessor saved:
/content/drive/MyDrive/ KrishiTrust_AI/model/preprocessing/fertilizer_preprocessor.joblib

Label encoder saved:
/content/drive/MyDrive/ KrishiTrust_AI/model/preprocessing/fertilizer_label_encoder.joblib

Feature configuration saved:
/content/drive/MyDrive/ KrishiTrust_AI/model/preprocessing/fertilizer_feature_config.json

Model metadata saved:
/content/drive/MyDrive/ KrishiTrust_AI/model/fertilizer_model_metadata.json

======================================================================
FINAL PACKAGING VALIDATION
======================================================================
FOUND ✅  fertilizer_xgboost_pipeline.joblib (2.69 MB)
FOUND ✅  fertilizer_preprocessor.joblib (0.00 MB)
FOUND ✅  fertilizer_label_encoder.joblib (0.00 MB)
FOUND ✅  fertilizer_feature_config.json (0.00 MB)
FOUND ✅  fertilizer_model_metadata.json (0.00 MB)

======================================================================
FINAL MODEL PACKAGING: PASS ✅
======================================================================

In [3]:
import joblib
from pathlib import Path

MODEL_FILE = Path(
    "/content/drive/MyDrive/KrishiTrust_AI/model/fertilizer_xgboost_pipeline.joblib"
)

model = joblib.load(MODEL_FILE)

print("Model loaded successfully ✅")
print(type(model))
print(model)

Model loaded successfully ✅
<class 'sklearn.pipeline.Pipeline'>
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                                  ['Temperature', 'Moisture',
                                                   'Rainfall', 'PH', 'Nitrogen',
                                                   'Phosphorous', 'Potassium',
                                                   'Carbon']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Soil', 'Crop'])])),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsa...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [ ]:
import sklearn
import xgboost

print("scikit-learn:", sklearn.__version__)
print("XGBoost:", xgboost.__version__)

scikit-learn: 1.6.1
XGBoost: 3.4.1

In [4]:
import joblib
from pathlib import Path

MODEL_FILE = Path(
    "/content/drive/MyDrive/KrishiTrust_AI/model/"
    "fertilizer_xgboost_pipeline.joblib"
)

print("Checking:", MODEL_FILE)
print("Exists:", MODEL_FILE.exists())

if MODEL_FILE.exists():
    print("Size:", MODEL_FILE.stat().st_size, "bytes")

    try:
        loaded_model = joblib.load(MODEL_FILE)

        print("\nMODEL RELOAD: PASS ✅")
        print(type(loaded_model))

    except Exception as e:
        print("\nMODEL RELOAD: FAILED ❌")
        print(type(e).__name__, ":", e)

Checking: /content/drive/MyDrive/KrishiTrust_AI/model/fertilizer_xgboost_pipeline.joblib
Exists: True
Size: 2824983 bytes

MODEL RELOAD: PASS ✅
<class 'sklearn.pipeline.Pipeline'>

In [5]:
import hashlib

model_file = "/content/drive/MyDrive/KrishiTrust_AI/model/fertilizer_xgboost_pipeline.joblib"

sha256 = hashlib.sha256()

with open(model_file, "rb") as f:
    for chunk in iter(lambda: f.read(1024 * 1024), b""):
        sha256.update(chunk)

print("Colab file size:", __import__("os").path.getsize(model_file))
print("Colab SHA256:", sha256.hexdigest())

Colab file size: 2824983
Colab SHA256: 5e0c68b4a2c71de4a5652720dad1110fa9bb87627f8013fd0e8c7ddce36d8afd

In [7]:
# ============================================================
# STEP 5.19B — NATIVE XGBOOST MODEL PACKAGING
# ============================================================

from pathlib import Path
import json
import joblib
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier


print("=" * 70)
print("STEP 5.19B — NATIVE XGBOOST MODEL PACKAGING")
print("=" * 70)


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path("/content/drive/MyDrive/ KrishiTrust_AI")

DATA_DIR = PROJECT_ROOT / "datasets"
MODEL_DIR = PROJECT_ROOT / "model"
PREPROCESSING_DIR = MODEL_DIR / "preprocessing"

MODEL_DIR.mkdir(parents=True, exist_ok=True)
PREPROCESSING_DIR.mkdir(parents=True, exist_ok=True)


TRAIN_FILE = DATA_DIR / "fertilizer_train.csv"
TEST_FILE = DATA_DIR / "fertilizer_test.csv"

LABEL_ENCODER_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_label_encoder.joblib"
)


NATIVE_MODEL_FILE = (
    MODEL_DIR /
    "fertilizer_xgboost.json"
)

PREPROCESSOR_FILE = (
    PREPROCESSING_DIR /
    "fertilizer_preprocessor.joblib"
)


# ============================================================
# FEATURES
# ============================================================

NUMERICAL_FEATURES = [
    "Temperature",
    "Moisture",
    "Rainfall",
    "PH",
    "Nitrogen",
    "Phosphorous",
    "Potassium",
    "Carbon",
]

CATEGORICAL_FEATURES = [
    "Soil",
    "Crop",
]

TARGET = "Fertilizer"


# ============================================================
# LOAD DATA
# ============================================================

print("\nLoading training dataset...")

train_df = pd.read_csv(TRAIN_FILE)

print("Training shape:", train_df.shape)


print("\nLoading testing dataset...")

test_df = pd.read_csv(TEST_FILE)

print("Testing shape:", test_df.shape)


# ============================================================
# PREPARE X / y
# ============================================================

X_train = train_df[
    NUMERICAL_FEATURES + CATEGORICAL_FEATURES
].copy()

X_test = test_df[
    NUMERICAL_FEATURES + CATEGORICAL_FEATURES
].copy()

y_train_text = train_df[TARGET].copy()
y_test_text = test_df[TARGET].copy()


# ============================================================
# LOAD EXISTING LABEL ENCODER
# ============================================================

print("\nLoading existing label encoder...")

label_encoder = joblib.load(LABEL_ENCODER_FILE)

y_train = label_encoder.transform(y_train_text)
y_test = label_encoder.transform(y_test_text)

print("Number of classes:", len(label_encoder.classes_))

print("\nClass mapping:")

for i, class_name in enumerate(label_encoder.classes_):
    print(f"  {i} -> {class_name}")


# ============================================================
# CREATE PREPROCESSOR
# ============================================================

print("\n" + "=" * 70)
print("CREATING PREPROCESSOR")
print("=" * 70)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            NUMERICAL_FEATURES,
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
            CATEGORICAL_FEATURES,
        ),
    ],
    remainder="drop",
)


# ============================================================
# FIT PREPROCESSOR ONLY ON TRAINING DATA
# ============================================================

print("\nFitting preprocessor on training data only...")

X_train_transformed = preprocessor.fit_transform(X_train)

X_test_transformed = preprocessor.transform(X_test)

print(
    "Transformed training shape:",
    X_train_transformed.shape
)

print(
    "Transformed testing shape:",
    X_test_transformed.shape
)


# ============================================================
# CREATE EXACT SELECTED XGBOOST MODEL
# ============================================================

print("\n" + "=" * 70)
print("CREATING FINAL XGBOOST MODEL")
print("=" * 70)

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    objective="multi:softprob",
    num_class=len(label_encoder.classes_),
    eval_metric="mlogloss",
)


# ============================================================
# TRAIN
# ============================================================

print("\nTraining XGBoost...")

xgb_model.fit(
    X_train_transformed,
    y_train,
)

print("Training complete: PASS")


# ============================================================
# TEST PREDICTIONS
# ============================================================

print("\nGenerating test predictions...")

y_pred = xgb_model.predict(X_test_transformed)

test_accuracy = np.mean(y_pred == y_test)

print(
    f"Test accuracy from native model: "
    f"{test_accuracy:.4f}"
)


# ============================================================
# SAVE NATIVE XGBOOST MODEL
# ============================================================

print("\n" + "=" * 70)
print("SAVING NATIVE XGBOOST MODEL")
print("=" * 70)

xgb_model.save_model(
    NATIVE_MODEL_FILE
)

print(
    "Native model saved:"
)

print(NATIVE_MODEL_FILE)


# ============================================================
# SAVE PREPROCESSOR
# ============================================================

joblib.dump(
    preprocessor,
    PREPROCESSOR_FILE,
)

print(
    "\nPreprocessor saved:"
)

print(PREPROCESSOR_FILE)


# ============================================================
# CRITICAL — RELOAD NATIVE MODEL
# ============================================================

print("\n" + "=" * 70)
print("RELOAD VALIDATION")
print("=" * 70)

reloaded_model = XGBClassifier()

reloaded_model.load_model(
    NATIVE_MODEL_FILE
)

print("Native XGBoost reload: PASS ✅")


# ============================================================
# PREDICT AFTER RELOAD
# ============================================================

reloaded_predictions = reloaded_model.predict(
    X_test_transformed
)

reload_accuracy = np.mean(
    reloaded_predictions == y_test
)

print(
    f"Reloaded model accuracy: "
    f"{reload_accuracy:.4f}"
)


# ============================================================
# PREDICTION CONSISTENCY
# ============================================================

predictions_identical = np.array_equal(
    y_pred,
    reloaded_predictions
)

print(
    "\nPrediction consistency:",
    "PASS ✅" if predictions_identical else "FAIL ❌"
)


# ============================================================
# FILE VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("FINAL FILE VALIDATION")
print("=" * 70)

for file_path in [
    NATIVE_MODEL_FILE,
    PREPROCESSOR_FILE,
    LABEL_ENCODER_FILE,
]:

    if file_path.exists():

        size_mb = file_path.stat().st_size / (
            1024 * 1024
        )

        print(
            f"FOUND ✅ {file_path.name} "
            f"({size_mb:.2f} MB)"
        )

    else:

        print(
            f"NOT FOUND ❌ {file_path.name}"
        )


# ============================================================
# FINAL RESULT
# ============================================================

print("\n" + "=" * 70)
print("NATIVE XGBOOST PACKAGING RESULT")
print("=" * 70)

if (
    predictions_identical
    and abs(test_accuracy - reload_accuracy) < 1e-12
):

    print("PACKAGING VALIDATION: PASS ✅")

else:

    print("PACKAGING VALIDATION: FAIL ❌")

======================================================================
STEP 5.19B — NATIVE XGBOOST MODEL PACKAGING
======================================================================

Loading training dataset...
Training shape: (2238, 12)

Loading testing dataset...
Testing shape: (560, 12)

Loading existing label encoder...
Number of classes: 10

Class mapping:
  0 -> Balanced NPK Fertilizer
  1 -> Compost
  2 -> DAP
  3 -> General Purpose Fertilizer
  4 -> Gypsum
  5 -> Lime
  6 -> Muriate of Potash
  7 -> Organic Fertilizer
  8 -> Urea
  9 -> Water Retaining Fertilizer

======================================================================
CREATING PREPROCESSOR
======================================================================

Fitting preprocessor on training data only...
Transformed training shape: (2238, 44)
Transformed testing shape: (560, 44)

======================================================================
CREATING FINAL XGBOOST MODEL
======================================================================

Training XGBoost...
Training complete: PASS

Generating test predictions...
Test accuracy from native model: 0.9929

======================================================================
SAVING NATIVE XGBOOST MODEL
======================================================================
Native model saved:
/content/drive/MyDrive/ KrishiTrust_AI/model/fertilizer_xgboost.json

Preprocessor saved:
/content/drive/MyDrive/ KrishiTrust_AI/model/preprocessing/fertilizer_preprocessor.joblib

======================================================================
RELOAD VALIDATION
======================================================================
Native XGBoost reload: PASS ✅
Reloaded model accuracy: 0.9929

Prediction consistency: PASS ✅

======================================================================
FINAL FILE VALIDATION
======================================================================
FOUND ✅ fertilizer_xgboost.json (2.44 MB)
FOUND ✅ fertilizer_preprocessor.joblib (0.00 MB)
FOUND ✅ fertilizer_label_encoder.joblib (0.00 MB)

======================================================================
NATIVE XGBOOST PACKAGING RESULT
======================================================================
PACKAGING VALIDATION: PASS ✅