In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

import pandas as pd
import numpy as np
import os

file_path = "/content/drive/MyDrive/yield prediction /crop_production_124_with_weather_soil.csv"

if not os.path.exists(file_path):
    raise FileNotFoundError(
        f"File not found: {file_path}\n"
        "Please check the file's location in Google Drive."
    )

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
display(df.head())

Dataset loaded successfully!
Shape: (246091, 11)

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,temperature,humidity,rainfall_mm,soil_type
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0,27.618000,84.0040,1626.0,Laterite
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0,27.618000,84.0040,1626.0,Alluvial
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0,27.618000,84.0040,1626.0,Alluvial
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0,27.493333,81.7475,2520.3,Alluvial
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0,27.493333,81.7475,2520.3,Laterite

In [ ]:

missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

display(missing_report)

               Missing_Count  Missing_Percentage
State_Name                 0                0.00
District_Name              0                0.00
Crop_Year                  0                0.00
Season                     0                0.00
Crop                       0                0.00
Area                       0                0.00
Production              3730                1.52
temperature                0                0.00
humidity                   0                0.00
rainfall_mm                0                0.00
soil_type                  0                0.00

In [ ]:

key_columns = [
    "State_Name",
    "District_Name",
    "Crop_Year",
    "Season",
    "Crop"
]

print("Fully duplicated rows:", df.duplicated().sum())

print(
    "Duplicate crop-location-year-season keys:",
    df.duplicated(subset=key_columns).sum()
)

Fully duplicated rows: 0
Duplicate crop-location-year-season keys: 0

In [ ]:

print("Unique crops:", df["Crop"].nunique())
print("Unique states:", df["State_Name"].nunique())
print("Unique districts:", df["District_Name"].nunique())
print("Unique seasons:", df["Season"].nunique())

print("\nYear range:")
print("Minimum:", df["Crop_Year"].min())
print("Maximum:", df["Crop_Year"].max())

print("\nRecords per year:")
display(df["Crop_Year"].value_counts().sort_index())

print("\nRecords per crop:")
display(df["Crop"].value_counts().to_frame("Record_Count"))

Unique crops: 124
Unique states: 33
Unique districts: 646
Unique seasons: 6

Year range:
Minimum: 1997
Maximum: 2015

Records per year:

Crop_Year
1997     8899
1998    11533
1999    12515
2000    13658
2001    13361
2002    16671
2003    17287
2004    14117
2005    13799
2006    14328
2007    14526
2008    14550
2009    14116
2010    14065
2011    14071
2012    13410
2013    13650
2014    10973
2015      562
Name: count, dtype: int64

Records per crop:

                   Record_Count
Crop
Rice                      15104
Maize                     13947
Moong(Green Gram)         10318
Urad                       9850
Sesamum                    9046
...                         ...
Pear                          6
Litchi                        6
Peach                         4
Apple                         4
Other Dry Fruit               1

[124 rows x 1 columns]

In [ ]:

numeric_columns = [
    "Area",
    "Production",
    "temperature",
    "humidity",
    "rainfall_mm"
]

display(df[numeric_columns].describe().T)

print("Area <= 0:", (df["Area"] <= 0).sum())
print("Missing production:", df["Production"].isna().sum())
print("Zero production:", (df["Production"] == 0).sum())
print("Negative production:", (df["Production"] < 0).sum())

print("\nSoil distribution:")
display(df["soil_type"].value_counts(dropna=False))

,count,mean,std,min,25%,50%,75%,max
Area,246091.0,12002.820864,5.052340e+04,0.0400,80.000,582.0000,4392.000,8.580100e+06
Production,242361.0,582503.442251,1.706581e+07,0.0000,88.000,729.0000,7023.000,1.250800e+09
temperature,246091.0,24.711056,4.682965e+00,-12.5340,22.096,25.6500,27.750,3.522200e+01
humidity,246091.0,62.581318,1.604321e+01,17.9925,50.600,65.6575,75.778,9.272800e+01
rainfall_mm,246091.0,680.196746,5.982700e+02,0.0000,156.000,591.3000,1009.300,4.787100e+03

Area <= 0: 0
Missing production: 3730
Zero production: 3523
Negative production: 0

Soil distribution:

soil_type
Alluvial             131128
Black                 50346
Red                   39319
Mountain (Forest)      9999
Laterite               8499
Red and Yellow         4742
Arid (Desert)          2042
Saline-Alkaline          16
Name: count, dtype: int64

In [ ]:

# STEP 2: YIELD TARGET VALIDATION
# Does not modify the original df.

yield_audit = df.copy()

valid_mask = (
    yield_audit["Area"].notna()
    & yield_audit["Production"].notna()
    & (yield_audit["Area"] > 0)
    & (yield_audit["Production"] >= 0)
)

yield_audit["calculated_yield"] = np.nan

yield_audit.loc[valid_mask, "calculated_yield"] = (
    yield_audit.loc[valid_mask, "Production"]
    / yield_audit.loc[valid_mask, "Area"]
)

print("Total rows:", len(yield_audit))
print("Rows with calculable yield:", valid_mask.sum())
print("Rows without calculable yield:", (~valid_mask).sum())

print("\nYield ratio summary:")
display(
    yield_audit["calculated_yield"].describe(
        percentiles=[0.01, 0.05, 0.50, 0.95, 0.99]
    ).to_frame("Calculated_Yield_Ratio")
)

print("\nHighest 20 yield ratios:")
display(
    yield_audit.nlargest(20, "calculated_yield")[
        [
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Crop", "Area", "Production",
            "calculated_yield"
        ]
    ]
)

Total rows: 246091
Rows with calculable yield: 242361
Rows without calculable yield: 3730

Yield ratio summary:

       Calculated_Yield_Ratio
count           242361.000000
mean                41.649059
std                817.572839
min                  0.000000
1%                   0.000000
5%                   0.185049
50%                  1.000000
95%                 22.448276
99%                 82.663712
max              88000.000000

Highest 20 yield ratios:

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,calculated_yield
163866,Punjab,PATIALA,2011,Whole Year,Sugarcane,3.0,264000.0,88000.000000
164316,Punjab,SANGRUR,2011,Whole Year,Sugarcane,2.0,163000.0,81500.000000
163003,Punjab,LUDHIANA,2011,Whole Year,Sugarcane,2.0,161000.0,80500.000000
161948,Punjab,FATEHGARH SAHIB,2011,Whole Year,Sugarcane,2.0,151000.0,75500.000000
164038,Punjab,RUPNAGAR,2011,Whole Year,Sugarcane,3.0,224000.0,74666.666667
162328,Punjab,GURDASPUR,2011,Whole Year,Sugarcane,20.0,1491000.0,74550.000000
163678,Punjab,PATHANKOT,2011,Whole Year,Sugarcane,4.0,298000.0,74500.000000
162835,Punjab,KAPURTHALA,2011,Whole Year,Sugarcane,3.0,221000.0,73666.666667
161967,Punjab,FAZILKA,2011,Whole Year,Sugarcane,1.0,73000.0,73000.000000
163657,Punjab,NAWANSHAHR,2011,Whole Year,Sugarcane,6.0,407000.0,67833.333333
161430,Punjab,AMRITSAR,2011,Whole Year,Sugarcane,3.0,203000.0,67666.666667
162701,Punjab,JALANDHAR,2011,Whole Year,Sugarcane,9.0,599000.0,66555.555556
164113,Punjab,S.A.S NAGAR,2011,Whole Year,Sugarcane,1.0,65000.0,65000.000000
162523,Punjab,HOSHIARPUR,2011,Whole Year,Sugarcane,20.0,1293000.0,64650.000000
164411,Punjab,TARN TARAN,2011,Whole Year,Sugarcane,1.0,40000.0,40000.000000
238912,West Bengal,BIRBHUM,2006,Whole Year,Coconut,509.0,19749200.0,38800.000000
9829,Andhra Pradesh,WEST GODAVARI,2014,Whole Year,Coconut,21729.0,718991000.0,33089.005477
20171,Assam,KAMRUP,2004,Whole Year,Coconut,2026.0,57405000.0,28334.155972
22705,Assam,LAKHIMPUR,2001,Whole Year,Coconut,192.0,5044000.0,26270.833333
185975,Tamil Nadu,THANJAVUR,2011,Whole Year,Coconut,33742.0,823800000.0,24414.676071

In [ ]:

import pandas as pd
import numpy as np

# Recreate the audit dataframe
valid_mask = (
    df["Area"].notna()
    & df["Production"].notna()
    & (df["Area"] > 0)
    & (df["Production"] >= 0)
)

audit = df.loc[valid_mask].copy()

audit["calculated_yield"] = (
    audit["Production"] / audit["Area"]
)

print("Audit dataframe created:", audit.shape)

# 1. Count extreme yield ratios
print("\nYIELD RATIO THRESHOLD COUNTS")

for threshold in [10, 50, 100, 1000, 10000]:
    count = (audit["calculated_yield"] > threshold).sum()
    print(f"Yield ratio > {threshold:>5}: {count:,}")

# 2. Yield summary by crop
print("\nCROPS WITH HIGHEST MAXIMUM YIELD RATIOS")

crop_yield_summary = (
    audit.groupby("Crop")["calculated_yield"]
    .agg(
        Records="count",
        Median="median",
        Mean="mean",
        Maximum="max"
    )
    .sort_values("Maximum", ascending=False)
)

display(crop_yield_summary.head(20))

# 3. Inspect extreme sugarcane records
print("\nSUGARCANE RECORDS WITH YIELD RATIO > 100")

sugarcane = audit[
    audit["Crop"].str.lower().eq("sugarcane")
    & (audit["calculated_yield"] > 100)
]

display(
    sugarcane[
        [
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "Production", "calculated_yield"
        ]
    ].sort_values(
        "calculated_yield", ascending=False
    ).head(30)
)

# 4. Inspect area and production scales
print("\nAREA AND PRODUCTION QUANTILES")

display(
    audit[["Area", "Production"]]
    .quantile([0, 0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99, 1])
)

Audit dataframe created: (242361, 12)

YIELD RATIO THRESHOLD COUNTS
Yield ratio >    10: 23,738
Yield ratio >    50: 5,766
Yield ratio >   100: 1,628
Yield ratio >  1000: 969
Yield ratio > 10000: 287

CROPS WITH HIGHEST MAXIMUM YIELD RATIOS

              Records     Median         Mean       Maximum
Crop
Sugarcane        7827  53.241379   195.003397  88000.000000
Coconut          1958  43.120000  4040.403568  38800.000000
Cashewnut        1068   0.396104     9.675758   9801.000000
Onion            6984  10.297120    11.855243   2150.000000
Maize           13787   1.795918     2.632770   1494.000000
Cotton(lint)     4382   1.367349     2.063290    300.000000
Sesamum          8821   0.333333     0.459043    235.000000
Rice            15082   1.938529     1.995014    223.727273
Potato           6914  10.833194    12.867025    213.846154
Banana           3133  21.804276    27.064755    138.421053
Papaya            483  15.500000    28.659374    134.142636
Niger seed       2018   0.285714     0.385644     71.000000
Tapioca          1584  11.443750    18.773412     70.516091
Sunflower        5483   0.800000     0.944233     70.000000
Mesta            1770   5.000000     5.566799     68.000000
Cabbage           204   0.000000    11.920462     67.212346
Pome Fruit        297   3.137500     4.706793     57.139836
Sannhamp         2183   0.500000     1.200310     55.550000
Tomato            368   7.185687     7.826413     50.205080
Groundnut        8770   1.043478     1.195074     49.000000

SUGARCANE RECORDS WITH YIELD RATIO > 100

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield
163866,Punjab,PATIALA,2011,Whole Year,3.0,264000.0,88000.000000
164316,Punjab,SANGRUR,2011,Whole Year,2.0,163000.0,81500.000000
163003,Punjab,LUDHIANA,2011,Whole Year,2.0,161000.0,80500.000000
161948,Punjab,FATEHGARH SAHIB,2011,Whole Year,2.0,151000.0,75500.000000
164038,Punjab,RUPNAGAR,2011,Whole Year,3.0,224000.0,74666.666667
162328,Punjab,GURDASPUR,2011,Whole Year,20.0,1491000.0,74550.000000
163678,Punjab,PATHANKOT,2011,Whole Year,4.0,298000.0,74500.000000
162835,Punjab,KAPURTHALA,2011,Whole Year,3.0,221000.0,73666.666667
161967,Punjab,FAZILKA,2011,Whole Year,1.0,73000.0,73000.000000
163657,Punjab,NAWANSHAHR,2011,Whole Year,6.0,407000.0,67833.333333
161430,Punjab,AMRITSAR,2011,Whole Year,3.0,203000.0,67666.666667
162701,Punjab,JALANDHAR,2011,Whole Year,9.0,599000.0,66555.555556
164113,Punjab,S.A.S NAGAR,2011,Whole Year,1.0,65000.0,65000.000000
162523,Punjab,HOSHIARPUR,2011,Whole Year,20.0,1293000.0,64650.000000
164411,Punjab,TARN TARAN,2011,Whole Year,1.0,40000.0,40000.000000
182001,Tamil Nadu,MADURAI,1997,Whole Year,8108.0,18223000.0,2247.533300
186870,Tamil Nadu,THIRUVALLUR,1997,Whole Year,5964.0,11811000.0,1980.382294
180534,Tamil Nadu,KANCHIPURAM,1997,Whole Year,6735.0,9896000.0,1469.339272
182819,Tamil Nadu,NAMAKKAL,1997,Whole Year,9415.0,13608000.0,1445.353160
187574,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,4315.0,5806000.0,1345.538818
178362,Tamil Nadu,CUDDALORE,1997,Whole Year,23826.0,28322000.0,1188.701419
181195,Tamil Nadu,KARUR,1997,Whole Year,5961.0,7081000.0,1187.887938
184641,Tamil Nadu,SALEM,1997,Whole Year,13759.0,15866000.0,1153.136129
177823,Tamil Nadu,COIMBATORE,1997,Whole Year,10756.0,12272000.0,1140.944589
190249,Tamil Nadu,VILLUPURAM,1997,Whole Year,33175.0,37158000.0,1120.060286
179974,Tamil Nadu,ERODE,1997,Whole Year,24112.0,26930000.0,1116.871267
186359,Tamil Nadu,THENI,1997,Whole Year,9524.0,10598000.0,1112.767745
186037,Tamil Nadu,THE NILGIRIS,1997,Whole Year,22.0,24000.0,1090.909091
189255,Tamil Nadu,TUTICORIN,1997,Whole Year,90.0,97000.0,1077.777778
188084,Tamil Nadu,TIRUNELVELI,1997,Whole Year,2237.0,2402000.0,1073.759499

AREA AND PRODUCTION QUANTILES

           Area    Production
0.00        0.1  0.000000e+00
0.01        1.0  0.000000e+00
0.05        5.0  3.000000e+00
0.25       87.0  8.800000e+01
0.50      603.0  7.290000e+02
0.75     4545.0  7.023000e+03
0.95    68526.0  1.820000e+05
0.99   190247.8  9.825800e+05
1.00  8580100.0  1.250800e+09

In [ ]:

# STEP 2B: CROP-SPECIFIC AND YEAR-SPECIFIC DIAGNOSTICS

# 1. Yield distribution by crop
crop_diagnostics = (
    audit.groupby("Crop")["calculated_yield"]
    .agg(
        Records="count",
        Median_Yield="median",
        P95_Yield=lambda x: x.quantile(0.95),
        P99_Yield=lambda x: x.quantile(0.99),
        Maximum_Yield="max"
    )
    .round(3)
    .sort_values("Maximum_Yield", ascending=False)
)

print("Crops with the highest maximum ratios:")
display(crop_diagnostics.head(25))

# 2. Sugarcane yield distribution by year
sugarcane_by_year = (
    audit[audit["Crop"].str.lower() == "sugarcane"]
    .groupby("Crop_Year")["calculated_yield"]
    .agg(
        Records="count",
        Median="median",
        P95=lambda x: x.quantile(0.95),
        Maximum="max"
    )
    .round(3)
)

print("\nSugarcane ratios by year:")
display(sugarcane_by_year)

# 3. Inspect all Punjab sugarcane records from 2011
print("\nPunjab sugarcane records for 2011:")

display(
    audit[
        (audit["State_Name"].str.strip().str.lower() == "punjab")
        & (audit["Crop"].str.strip().str.lower() == "sugarcane")
        & (audit["Crop_Year"] == 2011)
    ][
        [
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "Production", "calculated_yield"
        ]
    ].sort_values("District_Name")
)

# 4. Inspect records with ratios above 100
print("\nExtreme ratios by crop:")
display(
    audit[audit["calculated_yield"] > 100]
    ["Crop"]
    .value_counts()
    .head(20)
    .to_frame("Records_Above_100")
)

Crops with the highest maximum ratios:

                Records  Median_Yield  P95_Yield  P99_Yield  Maximum_Yield
Crop
Sugarcane          7827        53.241    107.086    146.145      88000.000
Coconut            1958        43.120  13817.544  19909.530      38800.000
Cashewnut          1068         0.396      1.030      1.894       9801.000
Onion              6984        10.297     25.740     33.000       2150.000
Maize             13787         1.796      4.817      7.230       1494.000
Cotton(lint)       4382         1.367      3.999      5.786        300.000
Sesamum            8821         0.333      0.882      1.102        235.000
Rice              15082         1.939      3.638      4.518        223.727
Potato             6914        10.833     25.998     31.350        213.846
Banana             3133        21.804     63.567     80.259        138.421
Papaya              483        15.500    108.934    130.473        134.143
Niger seed         2018         0.286      0.638      1.004         71.000
Tapioca            1584        11.444     42.165     49.874         70.516
Sunflower          5483         0.800      1.955      2.304         70.000
Mesta              1770         5.000     12.475     15.617         68.000
Cabbage             204         0.000     58.744     64.000         67.212
Pome Fruit          297         3.138     11.204     56.896         57.140
Sannhamp           2183         0.500      4.567      6.500         55.550
Tomato              368         7.186     21.831     28.859         50.205
Groundnut          8770         1.043      2.267      3.218         49.000
Grapes              129        20.924     30.533     39.538         42.928
Guar seed          1257         0.816      1.003     10.593         40.000
Dry ginger         2987         2.492     19.500     31.859         39.065
Sweet potato       4122         8.222     16.333     21.185         38.125
other oilseeds      594         0.500      5.733     22.479         32.575

Sugarcane ratios by year:

           Records  Median       P95    Maximum
Crop_Year
1997           330  55.366  1073.573   2247.533
1998           408  51.851   121.505    303.485
1999           444  54.189   111.969    162.500
2000           466  49.522   107.116    162.000
2001           461  51.933   100.173    158.573
2002           466  49.890    92.380    162.000
2003           461  49.284   100.000    163.333
2004           423  51.275   100.691    162.500
2005           469  53.788    99.201    147.258
2006           402  54.237   113.604    188.415
2007           460  52.400   107.538    138.984
2008           482  51.147   106.531    314.736
2009           458  53.191   101.650    150.000
2010           463  53.494   108.330    157.375
2011           405  56.412   136.557  88000.000
2012           443  58.800   104.243    159.633
2013           411  58.400   103.574    220.618
2014           347  60.116   107.014    179.867
2015            28  57.110    75.187     78.830

Punjab sugarcane records for 2011:

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield
161430,Punjab,AMRITSAR,2011,Whole Year,3.0,203000.0,67666.666667
161948,Punjab,FATEHGARH SAHIB,2011,Whole Year,2.0,151000.0,75500.000000
161967,Punjab,FAZILKA,2011,Whole Year,1.0,73000.0,73000.000000
162328,Punjab,GURDASPUR,2011,Whole Year,20.0,1491000.0,74550.000000
162523,Punjab,HOSHIARPUR,2011,Whole Year,20.0,1293000.0,64650.000000
162701,Punjab,JALANDHAR,2011,Whole Year,9.0,599000.0,66555.555556
162835,Punjab,KAPURTHALA,2011,Whole Year,3.0,221000.0,73666.666667
163003,Punjab,LUDHIANA,2011,Whole Year,2.0,161000.0,80500.000000
163657,Punjab,NAWANSHAHR,2011,Whole Year,6.0,407000.0,67833.333333
163678,Punjab,PATHANKOT,2011,Whole Year,4.0,298000.0,74500.000000
163866,Punjab,PATIALA,2011,Whole Year,3.0,264000.0,88000.000000
164038,Punjab,RUPNAGAR,2011,Whole Year,3.0,224000.0,74666.666667
164113,Punjab,S.A.S NAGAR,2011,Whole Year,1.0,65000.0,65000.000000
164316,Punjab,SANGRUR,2011,Whole Year,2.0,163000.0,81500.000000
164411,Punjab,TARN TARAN,2011,Whole Year,1.0,40000.0,40000.000000

Extreme ratios by crop:

              Records_Above_100
Crop
Coconut                     958
Sugarcane                   607
Papaya                       37
Cotton(lint)                  7
Banana                        6
Maize                         6
Onion                         3
Potato                        1
Sesamum                       1
Rice                          1
Cashewnut                     1

In [ ]:

# STEP 2C: INVESTIGATE COCONUT AND SUGARCANE

crops_to_check = ["Sugarcane", "Coconut"]

for crop_name in crops_to_check:
    crop_df = audit[
        audit["Crop"].str.strip().str.lower()
        == crop_name.lower()
    ].copy()

    print(f"\n{'=' * 65}")
    print(f"CROP: {crop_name.upper()}")
    print(f"{'=' * 65}")

    # Overall distribution
    print("\nArea distribution:")
    display(crop_df["Area"].describe(
        percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
    ).to_frame())

    print("\nProduction distribution:")
    display(crop_df["Production"].describe(
        percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
    ).to_frame())

    # Annual statistics
    print("\nAnnual yield-ratio statistics:")
    annual = crop_df.groupby("Crop_Year").agg(
        Records=("calculated_yield", "size"),
        Median_Yield=("calculated_yield", "median"),
        P95_Yield=("calculated_yield",
                   lambda x: x.quantile(0.95)),
        Maximum_Yield=("calculated_yield", "max"),
        Median_Area=("Area", "median"),
        Median_Production=("Production", "median")
    ).round(3)

    display(annual)

    # Highest ratios for this crop
    print("\nTop 10 highest ratios:")
    display(
        crop_df.nlargest(10, "calculated_yield")[
            [
                "State_Name", "District_Name", "Crop_Year",
                "Season", "Area", "Production",
                "calculated_yield"
            ]
        ]
    )

# Compare Punjab sugarcane in 2010–2012
print("\nPUNJAB SUGARCANE: 2010–2012")

display(
    audit[
        audit["State_Name"].str.strip().str.lower().eq("punjab")
        & audit["Crop"].str.strip().str.lower().eq("sugarcane")
        & audit["Crop_Year"].between(2010, 2012)
    ][
        [
            "District_Name", "Crop_Year", "Area",
            "Production", "calculated_yield"
        ]
    ].sort_values(["Crop_Year", "District_Name"])
)

=================================================================
CROP: SUGARCANE
=================================================================

Area distribution:

                Area
count    7827.000000
mean     9793.819184
std     26703.309773
min         0.200000
1%          1.000000
5%          7.000000
25%       129.000000
50%       818.000000
75%      6126.000000
95%     53474.500000
99%    140352.880000
max    268653.000000

Production distribution:

         Production
count  7.827000e+03
mean   7.072546e+05
std    2.045078e+06
min    0.000000e+00
1%     9.260000e+00
5%     1.043000e+02
25%    4.720500e+03
50%    3.742200e+04
75%    3.953635e+05
95%    3.874741e+06
99%    1.169001e+07
max    3.715800e+07

Annual yield-ratio statistics:

,Records,Median_Yield,P95_Yield,Maximum_Yield,Median_Area,Median_Production
Crop_Year,,,,,,
1997,330,55.366,1073.573,2247.533,1805.0,92307.5
1998,408,51.851,121.505,303.485,1188.0,54700.0
1999,444,54.189,111.969,162.500,1090.0,56685.0
2000,466,49.522,107.116,162.000,1009.5,37010.0
2001,461,51.933,100.173,158.573,1000.0,43201.0
2002,466,49.890,92.380,162.000,862.0,32049.0
2003,461,49.284,100.000,163.333,807.0,38673.0
2004,423,51.275,100.691,162.500,759.0,34395.0
2005,469,53.788,99.201,147.258,704.0,31833.0
2006,402,54.237,113.604,188.415,648.0,27150.0
2007,460,52.400,107.538,138.984,568.5,23572.5
2008,482,51.147,106.531,314.736,724.0,32580.0
2009,458,53.191,101.650,150.000,554.0,23683.0
2010,463,53.494,108.330,157.375,673.0,28586.0
2011,405,56.412,136.557,88000.000,802.0,56000.0
2012,443,58.800,104.243,159.633,939.0,54407.0
2013,411,58.400,103.574,220.618,910.0,48862.2
2014,347,60.116,107.014,179.867,830.0,45809.0
2015,28,57.110,75.187,78.830,106.5,6405.9

Top 10 highest ratios:

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield
163866,Punjab,PATIALA,2011,Whole Year,3.0,264000.0,88000.000000
164316,Punjab,SANGRUR,2011,Whole Year,2.0,163000.0,81500.000000
163003,Punjab,LUDHIANA,2011,Whole Year,2.0,161000.0,80500.000000
161948,Punjab,FATEHGARH SAHIB,2011,Whole Year,2.0,151000.0,75500.000000
164038,Punjab,RUPNAGAR,2011,Whole Year,3.0,224000.0,74666.666667
162328,Punjab,GURDASPUR,2011,Whole Year,20.0,1491000.0,74550.000000
163678,Punjab,PATHANKOT,2011,Whole Year,4.0,298000.0,74500.000000
162835,Punjab,KAPURTHALA,2011,Whole Year,3.0,221000.0,73666.666667
161967,Punjab,FAZILKA,2011,Whole Year,1.0,73000.0,73000.000000
163657,Punjab,NAWANSHAHR,2011,Whole Year,6.0,407000.0,67833.333333

=================================================================
CROP: COCONUT
=================================================================

Area distribution:

                Area
count    1958.000000
mean    14472.251951
std     26972.084752
min         1.000000
1%          6.710000
5%         59.700000
25%       452.000000
50%      1926.000000
75%     14462.250000
95%     81775.900000
99%    125116.560000
max    149419.000000

Production distribution:

         Production
count  1.958000e+03
mean   6.638490e+07
std    1.779915e+08
min    0.000000e+00
1%     1.000000e+02
5%     6.522500e+02
25%    1.046310e+04
50%    2.391565e+05
75%    1.169568e+07
95%    5.275930e+08
99%    8.740200e+08
max    1.250800e+09

Annual yield-ratio statistics:

,Records,Median_Yield,P95_Yield,Maximum_Yield,Median_Area,Median_Production
Crop_Year,,,,,,
1997,57,5.607,19.280,20.975,1040.0,8766.0
1998,83,17.328,7705.035,9908.819,1174.0,75720.0
1999,86,17.768,10404.054,16500.000,1161.5,180378.0
2000,108,3752.314,10739.733,18000.000,1172.5,493405.0
2001,107,3583.784,11055.351,26270.833,1264.0,530400.0
2002,134,15.443,11255.634,14432.862,2105.5,158800.0
2003,134,15.635,11824.384,16906.298,2075.5,119740.0
2004,138,48.245,11789.000,28334.156,2177.5,354800.0
2005,114,5.016,8749.046,16500.000,4480.0,19252.0
2006,139,4073.969,14166.312,38800.000,2101.0,641000.0
2007,123,1777.778,13793.741,21954.617,2310.0,683765.0
2008,138,177.509,10758.794,21082.308,1706.5,919500.0
2009,122,2181.642,12649.531,18829.769,2301.5,418425.5
2010,78,4974.790,12794.771,15584.977,1388.0,2888000.0
2011,124,5610.686,17617.893,24414.676,2303.5,638759.0
2012,87,9.846,17085.856,21285.001,1394.0,33947.0
2013,122,917.341,16574.061,21021.026,2793.5,412047.0
2014,64,19.295,21680.133,33089.005,6409.5,305731.0

Top 10 highest ratios:

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield
238912,West Bengal,BIRBHUM,2006,Whole Year,509.0,19749200.0,38800.000000
9829,Andhra Pradesh,WEST GODAVARI,2014,Whole Year,21729.0,718991000.0,33089.005477
20171,Assam,KAMRUP,2004,Whole Year,2026.0,57405000.0,28334.155972
22705,Assam,LAKHIMPUR,2001,Whole Year,192.0,5044000.0,26270.833333
185975,Tamil Nadu,THANJAVUR,2011,Whole Year,33742.0,823800000.0,24414.676071
18503,Assam,GOLAGHAT,2004,Whole Year,658.0,16062000.0,24410.334347
7697,Andhra Pradesh,SRIKAKULAM,2014,Whole Year,13811.0,328149000.0,23759.973934
236732,West Bengal,24 PARAGANAS NORTH,2006,Whole Year,3338.0,75095000.0,22497.004194
18565,Assam,GOLAGHAT,2006,Whole Year,612.0,13555000.0,22148.692810
18598,Assam,GOLAGHAT,2007,Whole Year,639.0,14029000.0,21954.616588

PUNJAB SUGARCANE: 2010–2012

          District_Name  Crop_Year     Area  Production  calculated_yield
161430         AMRITSAR       2011      3.0    203000.0      67666.666667
161948  FATEHGARH SAHIB       2011      2.0    151000.0      75500.000000
161967          FAZILKA       2011      1.0     73000.0      73000.000000
162328        GURDASPUR       2011     20.0   1491000.0      74550.000000
162523       HOSHIARPUR       2011     20.0   1293000.0      64650.000000
162701        JALANDHAR       2011      9.0    599000.0      66555.555556
162835       KAPURTHALA       2011      3.0    221000.0      73666.666667
163003         LUDHIANA       2011      2.0    161000.0      80500.000000
163657       NAWANSHAHR       2011      6.0    407000.0      67833.333333
163678        PATHANKOT       2011      4.0    298000.0      74500.000000
163866          PATIALA       2011      3.0    264000.0      88000.000000
164038         RUPNAGAR       2011      3.0    224000.0      74666.666667
164113      S.A.S NAGAR       2011      1.0     65000.0      65000.000000
164316          SANGRUR       2011      2.0    163000.0      81500.000000
164411       TARN TARAN       2011      1.0     40000.0      40000.000000
161440         AMRITSAR       2012   2000.0    141000.0         70.500000
161955  FATEHGARH SAHIB       2012   3000.0    258000.0         86.000000
161976          FAZILKA       2012   1000.0     82000.0         82.000000
162168        FIROZEPUR       2012   1000.0     67000.0         67.000000
162336        GURDASPUR       2012  22000.0   1594000.0         72.454545
162537       HOSHIARPUR       2012  19000.0   1321000.0         69.526316
162711        JALANDHAR       2012  10000.0    651000.0         65.100000
162840       KAPURTHALA       2012   4000.0    258000.0         64.500000
163016         LUDHIANA       2012   2000.0    136000.0         68.000000
163663       NAWANSHAHR       2012   5000.0    327000.0         65.400000
163688        PATHANKOT       2012   4000.0    297000.0         74.250000
163875          PATIALA       2012   2000.0    184000.0         92.000000
164047         RUPNAGAR       2012   3000.0    227000.0         75.666667
164122      S.A.S NAGAR       2012   1000.0     57000.0         57.000000
164329          SANGRUR       2012   2000.0    161000.0         80.500000
164424       TARN TARAN       2012   1000.0     71000.0         71.000000

In [ ]:

# Flag suspicious records; do not delete them yet.

audit["yield_review_flag"] = False

# Coconut uses an incompatible raw production unit
audit.loc[
    audit["Crop"].str.strip().str.lower().eq("coconut"),
    "yield_review_flag"
] = True

# Flag extreme ratios for investigation, not automatic deletion
audit.loc[
    audit["calculated_yield"] > 200,
    "yield_review_flag"
] = True

# Specifically flag Punjab sugarcane records from 2011
audit.loc[
    audit["State_Name"].str.strip().str.lower().eq("punjab")
    & audit["Crop"].str.strip().str.lower().eq("sugarcane")
    & (audit["Crop_Year"] == 2011),
    "yield_review_flag"
] = True

print("Records flagged for review:",
      audit["yield_review_flag"].sum())

print("\nFlagged records by crop:")
display(
    audit.loc[audit["yield_review_flag"], "Crop"]
    .value_counts()
    .to_frame("Flagged_Records")
)

print("\nFlagged record examples:")
display(
    audit.loc[audit["yield_review_flag"]].head(20)[
        [
            "State_Name", "District_Name", "Crop_Year",
            "Crop", "Area", "Production", "calculated_yield"
        ]
    ]
)

Records flagged for review: 2023

Flagged records by crop:

              Flagged_Records
Crop
Coconut                  1958
Sugarcane                  50
Maize                       6
Cotton(lint)                3
Onion                       2
Potato                      1
Sesamum                     1
Rice                        1
Cashewnut                   1

Flagged record examples:

,State_Name,District_Name,Crop_Year,Crop,Area,Production,calculated_yield
5,Andaman and Nicobar Islands,NICOBARS,2000,Coconut,18168.00,65100000.0,3583.223250
14,Andaman and Nicobar Islands,NICOBARS,2001,Coconut,18190.00,64430000.0,3542.056075
23,Andaman and Nicobar Islands,NICOBARS,2002,Coconut,18240.00,67490000.0,3700.109649
32,Andaman and Nicobar Islands,NICOBARS,2003,Coconut,18284.74,68580000.0,3750.668590
41,Andaman and Nicobar Islands,NICOBARS,2004,Coconut,18394.70,52380000.0,2847.559351
50,Andaman and Nicobar Islands,NICOBARS,2005,Coconut,13876.57,52030000.0,3749.485644
57,Andaman and Nicobar Islands,NICOBARS,2006,Coconut,14358.00,59370000.0,4134.977016
77,Andaman and Nicobar Islands,NICOBARS,2010,Coconut,14560.00,71300000.0,4896.978022
84,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2000,Coconut,6992.00,23900000.0,3418.192220
94,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2001,Coconut,7015.00,25250000.0,3599.429793
103,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2006,Coconut,3575.00,15400000.0,4307.692308
127,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2010,Coconut,3668.00,12700000.0,3462.377317
134,Andaman and Nicobar Islands,SOUTH ANDAMANS,2002,Coconut,7060.00,26830000.0,3800.283286
144,Andaman and Nicobar Islands,SOUTH ANDAMANS,2003,Coconut,7110.00,26660000.0,3749.648383
154,Andaman and Nicobar Islands,SOUTH ANDAMANS,2004,Coconut,7156.70,34750000.0,4855.589867
164,Andaman and Nicobar Islands,SOUTH ANDAMANS,2005,Coconut,7050.45,26430000.0,3748.696892
177,Andaman and Nicobar Islands,SOUTH ANDAMANS,2006,Coconut,3483.09,14190000.0,4073.968804
201,Andaman and Nicobar Islands,SOUTH ANDAMANS,2010,Coconut,3540.00,11000000.0,3107.344633
329,Andhra Pradesh,ANANTAPUR,2000,Coconut,908.00,3896970.0,4291.817181
375,Andhra Pradesh,ANANTAPUR,2001,Coconut,851.00,3053700.0,3588.366627

In [ ]:
# STEP: Review suspicious yield records by crop

flagged = audit[audit["yield_review_flag"]].copy()

print("Total flagged records:", len(flagged))

print("\n1. Flagged records by crop:")
display(
    flagged.groupby("Crop")
    .agg(
        records=("calculated_yield", "size"),
        min_yield=("calculated_yield", "min"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max")
    )
    .sort_values("records", ascending=False)
)

print("\n2. Sugarcane records from Punjab in 2011:")
display(
    flagged[
        flagged["State_Name"].str.strip().str.lower().eq("punjab")
        & flagged["Crop"].str.strip().str.lower().eq("sugarcane")
        & (flagged["Crop_Year"] == 2011)
    ][[
        "State_Name", "District_Name", "Crop_Year",
        "Crop", "Area", "Production", "calculated_yield"
    ]]
)

print("\n3. Number of flagged records by year:")
display(
    flagged.groupby("Crop_Year")
    .size()
    .sort_index()
    .to_frame("Flagged_Records")
)

Total flagged records: 2023

1. Flagged records by crop:

              records    min_yield  median_yield     max_yield
Crop
Coconut          1958     0.000000     43.120000  38800.000000
Sugarcane          50   220.617757   1118.465777  88000.000000
Maize               6   725.250000   1134.750000   1494.000000
Cotton(lint)        3   234.375000    235.555556    300.000000
Onion               2   204.078947   1177.039474   2150.000000
Cashewnut           1  9801.000000   9801.000000   9801.000000
Potato              1   213.846154    213.846154    213.846154
Rice                1   223.727273    223.727273    223.727273
Sesamum             1   235.000000    235.000000    235.000000

2. Sugarcane records from Punjab in 2011:

,State_Name,District_Name,Crop_Year,Crop,Area,Production,calculated_yield
161430,Punjab,AMRITSAR,2011,Sugarcane,3.0,203000.0,67666.666667
161948,Punjab,FATEHGARH SAHIB,2011,Sugarcane,2.0,151000.0,75500.000000
161967,Punjab,FAZILKA,2011,Sugarcane,1.0,73000.0,73000.000000
162328,Punjab,GURDASPUR,2011,Sugarcane,20.0,1491000.0,74550.000000
162523,Punjab,HOSHIARPUR,2011,Sugarcane,20.0,1293000.0,64650.000000
162701,Punjab,JALANDHAR,2011,Sugarcane,9.0,599000.0,66555.555556
162835,Punjab,KAPURTHALA,2011,Sugarcane,3.0,221000.0,73666.666667
163003,Punjab,LUDHIANA,2011,Sugarcane,2.0,161000.0,80500.000000
163657,Punjab,NAWANSHAHR,2011,Sugarcane,6.0,407000.0,67833.333333
163678,Punjab,PATHANKOT,2011,Sugarcane,4.0,298000.0,74500.000000
163866,Punjab,PATIALA,2011,Sugarcane,3.0,264000.0,88000.000000
164038,Punjab,RUPNAGAR,2011,Sugarcane,3.0,224000.0,74666.666667
164113,Punjab,S.A.S NAGAR,2011,Sugarcane,1.0,65000.0,65000.000000
164316,Punjab,SANGRUR,2011,Sugarcane,2.0,163000.0,81500.000000
164411,Punjab,TARN TARAN,2011,Sugarcane,1.0,40000.0,40000.000000

3. Number of flagged records by year:

           Flagged_Records
Crop_Year
1997                    96
1998                    86
1999                    86
2000                   108
2001                   107
2002                   135
2003                   134
2004                   138
2005                   114
2006                   139
2007                   123
2008                   143
2009                   122
2010                    78
2011                   139
2012                    88
2013                   123
2014                    64

In [ ]:
# STEP: Inspect suspicious yield records excluding Coconut

non_coconut_flags = audit[
    audit["yield_review_flag"]
    & ~audit["Crop"].str.strip().str.lower().eq("coconut")
].copy()

print("Suspicious non-coconut records:", len(non_coconut_flags))

display(
    non_coconut_flags[
        [
            "State_Name",
            "District_Name",
            "Crop_Year",
            "Season",
            "Crop",
            "Area",
            "Production",
            "calculated_yield"
        ]
    ].sort_values(
        "calculated_yield",
        ascending=False
    ).reset_index(drop=True)
)

Suspicious non-coconut records: 65

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,calculated_yield
0,Punjab,PATIALA,2011,Whole Year,Sugarcane,3.0,264000.0,88000.000000
1,Punjab,SANGRUR,2011,Whole Year,Sugarcane,2.0,163000.0,81500.000000
2,Punjab,LUDHIANA,2011,Whole Year,Sugarcane,2.0,161000.0,80500.000000
3,Punjab,FATEHGARH SAHIB,2011,Whole Year,Sugarcane,2.0,151000.0,75500.000000
4,Punjab,RUPNAGAR,2011,Whole Year,Sugarcane,3.0,224000.0,74666.666667
...,...,...,...,...,...,...,...,...
60,Tamil Nadu,THENI,1998,Whole Year,Sugarcane,16133.0,3617820.0,224.249675
61,Maharashtra,KOLHAPUR,1997,Kharif,Rice,1100.0,246100.0,223.727273
62,West Bengal,MEDINIPUR WEST,2013,Whole Year,Sugarcane,3210.0,708183.0,220.617757
63,Haryana,PANIPAT,2002,Whole Year,Potato,195.0,41700.0,213.846154
64,Tamil Nadu,KARUR,1997,Whole Year,Onion,228.0,46530.0,204.078947

In [ ]:
# STEP: Compare suspicious records with nearby years
# This cell only inspects data; it does not delete or modify records.

# 1. Punjab sugarcane: compare 2010, 2011 and 2012
print("PUNJAB SUGARCANE: 2010–2012")

punjab_sugarcane = audit[
    audit["State_Name"].str.strip().str.lower().eq("punjab")
    & audit["Crop"].str.strip().str.lower().eq("sugarcane")
    & audit["Crop_Year"].between(2010, 2012)
].copy()

display(
    punjab_sugarcane[
        [
            "State_Name", "District_Name", "Crop_Year",
            "Area", "Production", "calculated_yield"
        ]
    ].sort_values(["District_Name", "Crop_Year"])
)

# 2. Compare the other suspicious crops with nearby years
print("\nOTHER SUSPICIOUS RECORDS: NEARBY-YEAR COMPARISON")

other_flags = non_coconut_flags[
    ~non_coconut_flags["Crop"].str.strip().str.lower().eq("sugarcane")
]

comparison_rows = []

for _, flagged_row in other_flags.iterrows():
    same_location_crop = audit[
        audit["State_Name"].eq(flagged_row["State_Name"])
        & audit["District_Name"].eq(flagged_row["District_Name"])
        & audit["Crop"].eq(flagged_row["Crop"])
        & audit["Crop_Year"].between(
            flagged_row["Crop_Year"] - 2,
            flagged_row["Crop_Year"] + 2
        )
    ].copy()

    same_location_crop["Flagged_Year"] = flagged_row["Crop_Year"]
    comparison_rows.append(same_location_crop)

if comparison_rows:
    comparison = pd.concat(comparison_rows, ignore_index=True)
    display(
        comparison[
            [
                "State_Name", "District_Name", "Crop",
                "Crop_Year", "Flagged_Year", "Season",
                "Area", "Production", "calculated_yield"
            ]
        ].sort_values(
            ["Crop", "State_Name", "District_Name", "Crop_Year"]
        ).reset_index(drop=True)
    )
else:
    print("No comparison records found.")

PUNJAB SUGARCANE: 2010–2012

,State_Name,District_Name,Crop_Year,Area,Production,calculated_yield
161430,Punjab,AMRITSAR,2011,3.0,203000.0,67666.666667
161440,Punjab,AMRITSAR,2012,2000.0,141000.0,70.500000
161948,Punjab,FATEHGARH SAHIB,2011,2.0,151000.0,75500.000000
161955,Punjab,FATEHGARH SAHIB,2012,3000.0,258000.0,86.000000
161967,Punjab,FAZILKA,2011,1.0,73000.0,73000.000000
161976,Punjab,FAZILKA,2012,1000.0,82000.0,82.000000
162168,Punjab,FIROZEPUR,2012,1000.0,67000.0,67.000000
162328,Punjab,GURDASPUR,2011,20.0,1491000.0,74550.000000
162336,Punjab,GURDASPUR,2012,22000.0,1594000.0,72.454545
162523,Punjab,HOSHIARPUR,2011,20.0,1293000.0,64650.000000
162537,Punjab,HOSHIARPUR,2012,19000.0,1321000.0,69.526316
162701,Punjab,JALANDHAR,2011,9.0,599000.0,66555.555556
162711,Punjab,JALANDHAR,2012,10000.0,651000.0,65.100000
162835,Punjab,KAPURTHALA,2011,3.0,221000.0,73666.666667
162840,Punjab,KAPURTHALA,2012,4000.0,258000.0,64.500000
163003,Punjab,LUDHIANA,2011,2.0,161000.0,80500.000000
163016,Punjab,LUDHIANA,2012,2000.0,136000.0,68.000000
163657,Punjab,NAWANSHAHR,2011,6.0,407000.0,67833.333333
163663,Punjab,NAWANSHAHR,2012,5000.0,327000.0,65.400000
163678,Punjab,PATHANKOT,2011,4.0,298000.0,74500.000000
163688,Punjab,PATHANKOT,2012,4000.0,297000.0,74.250000
163866,Punjab,PATIALA,2011,3.0,264000.0,88000.000000
163875,Punjab,PATIALA,2012,2000.0,184000.0,92.000000
164038,Punjab,RUPNAGAR,2011,3.0,224000.0,74666.666667
164047,Punjab,RUPNAGAR,2012,3000.0,227000.0,75.666667
164113,Punjab,S.A.S NAGAR,2011,1.0,65000.0,65000.000000
164122,Punjab,S.A.S NAGAR,2012,1000.0,57000.0,57.000000
164316,Punjab,SANGRUR,2011,2.0,163000.0,81500.000000
164329,Punjab,SANGRUR,2012,2000.0,161000.0,80.500000
164411,Punjab,TARN TARAN,2011,1.0,40000.0,40000.000000
164424,Punjab,TARN TARAN,2012,1000.0,71000.0,71.000000

OTHER SUSPICIOUS RECORDS: NEARBY-YEAR COMPARISON

,State_Name,District_Name,Crop,Crop_Year,Flagged_Year,Season,Area,Production,calculated_yield
0,Tamil Nadu,PERAMBALUR,Cashewnut,2006,2008,Whole Year,35522.0,7114.0,0.200270
1,Tamil Nadu,PERAMBALUR,Cashewnut,2007,2008,Whole Year,33231.0,9130.0,0.274743
2,Tamil Nadu,PERAMBALUR,Cashewnut,2008,2008,Whole Year,1.0,9801.0,9801.000000
3,Tamil Nadu,PERAMBALUR,Cashewnut,2009,2008,Whole Year,2.0,1.0,0.500000
4,Maharashtra,PUNE,Cotton(lint),1997,1997,Whole Year,2.0,600.0,300.000000
...,...,...,...,...,...,...,...,...,...
86,Maharashtra,KOLHAPUR,Rice,1999,1997,Kharif,103200.0,261900.0,2.537791
87,Maharashtra,KOLHAPUR,Rice,1999,1997,Summer,300.0,700.0,2.333333
88,Gujarat,NARMADA,Sesamum,2011,2012,Kharif,100.0,100.0,1.000000
89,Gujarat,NARMADA,Sesamum,2012,2012,Kharif,200.0,100.0,0.500000
90,Gujarat,NARMADA,Sesamum,2012,2012,Summer,100.0,23500.0,235.000000

In [ ]:
# STEP: Review all suspicious non-coconut records

review_columns = [
    "State_Name",
    "District_Name",
    "Crop_Year",
    "Season",
    "Crop",
    "Area",
    "Production",
    "calculated_yield"
]

print("Total suspicious non-coconut records:", len(non_coconut_flags))

review_df = (
    non_coconut_flags[review_columns]
    .sort_values(
        ["Crop", "State_Name", "District_Name", "Crop_Year", "Season"]
    )
    .reset_index(drop=True)
)

display(review_df)

Total suspicious non-coconut records: 65

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,calculated_yield
0,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.0,9801.000000
1,Maharashtra,PUNE,1997,Whole Year,Cotton(lint),2.0,600.0,300.000000
2,Maharashtra,SANGLI,1997,Whole Year,Cotton(lint),32.0,7500.0,234.375000
3,Maharashtra,SATARA,1997,Whole Year,Cotton(lint),45.0,10600.0,235.555556
4,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000000
...,...,...,...,...,...,...,...,...
60,Tamil Nadu,TUTICORIN,1997,Whole Year,Sugarcane,90.0,97000.0,1077.777778
61,Tamil Nadu,VELLORE,1997,Whole Year,Sugarcane,29072.0,22069000.0,759.115300
62,Tamil Nadu,VILLUPURAM,1997,Whole Year,Sugarcane,33175.0,37158000.0,1120.060286
63,Tamil Nadu,VIRUDHUNAGAR,1997,Whole Year,Sugarcane,2639.0,2833000.0,1073.512694
64,West Bengal,MEDINIPUR WEST,2013,Whole Year,Sugarcane,3210.0,708183.0,220.617757

In [ ]:
# STEP: Audit records with very small reported area

small_area = audit[audit["Area"] <= 20].copy()

print("Total records with Area <= 20:", len(small_area))

print("\nRecords by crop:")
display(
    small_area["Crop"]
    .value_counts()
    .head(30)
    .to_frame("Record_Count")
)

print("\nRecords by year:")
display(
    small_area["Crop_Year"]
    .value_counts()
    .sort_index()
    .to_frame("Record_Count")
)

print("\nSmall-area records with high calculated yield:")
display(
    small_area[small_area["calculated_yield"] > 200][[
        "State_Name",
        "District_Name",
        "Crop_Year",
        "Season",
        "Crop",
        "Area",
        "Production",
        "calculated_yield"
    ]].sort_values(
        "calculated_yield",
        ascending=False
    ).head(50)
)

Total records with Area <= 20: 31142

Records by crop:

                    Record_Count
Crop
Turmeric                    1482
Maize                       1329
Moong(Green Gram)           1280
Sweet potato                1181
Sunflower                   1130
Urad                        1017
Tobacco                      951
Garlic                       945
Castor seed                  878
Groundnut                    858
Sesamum                      848
Dry ginger                   834
Ragi                         787
Onion                        776
Potato                       765
Sannhamp                     762
Sugarcane                    762
Linseed                      743
Coriander                    728
Gram                         695
Dry chillies                 676
Cotton(lint)                 657
Small millets                626
Bajra                        599
Jowar                        568
Soyabean                     523
Banana                       523
Mesta                        481
Rice                         428
Other  Rabi pulses           426

Records by year:

           Record_Count
Crop_Year
1997                747
1998               1187
1999               1335
2000               1539
2001               1638
2002               2412
2003               2577
2004               1746
2005               1705
2006               1747
2007               2146
2008               1869
2009               1756
2010               1740
2011               1793
2012               1727
2013               1888
2014               1471
2015                119

Small-area records with high calculated yield:

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,calculated_yield
163866,Punjab,PATIALA,2011,Whole Year,Sugarcane,3.0,264000.0,88000.000000
164316,Punjab,SANGRUR,2011,Whole Year,Sugarcane,2.0,163000.0,81500.000000
163003,Punjab,LUDHIANA,2011,Whole Year,Sugarcane,2.0,161000.0,80500.000000
161948,Punjab,FATEHGARH SAHIB,2011,Whole Year,Sugarcane,2.0,151000.0,75500.000000
164038,Punjab,RUPNAGAR,2011,Whole Year,Sugarcane,3.0,224000.0,74666.666667
162328,Punjab,GURDASPUR,2011,Whole Year,Sugarcane,20.0,1491000.0,74550.000000
163678,Punjab,PATHANKOT,2011,Whole Year,Sugarcane,4.0,298000.0,74500.000000
162835,Punjab,KAPURTHALA,2011,Whole Year,Sugarcane,3.0,221000.0,73666.666667
161967,Punjab,FAZILKA,2011,Whole Year,Sugarcane,1.0,73000.0,73000.000000
163657,Punjab,NAWANSHAHR,2011,Whole Year,Sugarcane,6.0,407000.0,67833.333333
161430,Punjab,AMRITSAR,2011,Whole Year,Sugarcane,3.0,203000.0,67666.666667
162701,Punjab,JALANDHAR,2011,Whole Year,Sugarcane,9.0,599000.0,66555.555556
164113,Punjab,S.A.S NAGAR,2011,Whole Year,Sugarcane,1.0,65000.0,65000.000000
162523,Punjab,HOSHIARPUR,2011,Whole Year,Sugarcane,20.0,1293000.0,64650.000000
164411,Punjab,TARN TARAN,2011,Whole Year,Sugarcane,1.0,40000.0,40000.000000
196200,Telangana,RANGAREDDI,2011,Whole Year,Coconut,1.0,14606.0,14606.000000
193627,Telangana,MAHBUBNAGAR,2011,Whole Year,Coconut,4.0,58424.0,14606.000000
194879,Telangana,NALGONDA,2011,Whole Year,Coconut,3.0,43818.0,14606.000000
195521,Telangana,NIZAMABAD,2011,Whole Year,Coconut,2.0,29212.0,14606.000000
193455,Telangana,MAHBUBNAGAR,2006,Whole Year,Coconut,9.0,117153.0,13017.000000
196014,Telangana,RANGAREDDI,2006,Whole Year,Coconut,11.0,143187.0,13017.000000
194146,Telangana,MEDAK,2006,Whole Year,Coconut,1.0,13017.0,13017.000000
193376,Telangana,MAHBUBNAGAR,2004,Whole Year,Coconut,12.0,141468.0,11789.000000
195932,Telangana,RANGAREDDI,2004,Whole Year,Coconut,14.0,165046.0,11789.000000
194058,Telangana,MEDAK,2004,Whole Year,Coconut,1.0,11789.0,11789.000000
193327,Telangana,MAHBUBNAGAR,2003,Whole Year,Coconut,12.0,141360.0,11780.000000
195877,Telangana,RANGAREDDI,2003,Whole Year,Coconut,11.0,129580.0,11780.000000
195818,Telangana,RANGAREDDI,2002,Whole Year,Coconut,13.0,148564.0,11428.000000
193940,Telangana,MEDAK,2002,Whole Year,Coconut,1.0,11428.0,11428.000000
193269,Telangana,MAHBUBNAGAR,2002,Whole Year,Coconut,11.0,125708.0,11428.000000
195073,Telangana,NIZAMABAD,2000,Whole Year,Coconut,5.0,56210.0,11242.000000
195444,Telangana,NIZAMABAD,2009,Whole Year,Coconut,4.0,44688.0,11172.000000
196112,Telangana,RANGAREDDI,2009,Whole Year,Coconut,2.0,22344.0,11172.000000
193553,Telangana,MAHBUBNAGAR,2009,Whole Year,Coconut,2.0,22344.0,11172.000000
193224,Telangana,MAHBUBNAGAR,2001,Whole Year,Coconut,10.0,110200.0,11020.000000
193887,Telangana,MEDAK,2001,Whole Year,Coconut,2.0,22040.0,11020.000000
195769,Telangana,RANGAREDDI,2001,Whole Year,Coconut,13.0,143260.0,11020.000000
193178,Telangana,MAHBUBNAGAR,2000,Whole Year,Coconut,17.0,179872.0,10580.705882
194558,Telangana,NALGONDA,2001,Whole Year,Coconut,18.0,187340.0,10407.777778
193842,Telangana,MEDAK,2000,Whole Year,Coconut,12.0,123662.0,10305.166667
194524,Telangana,NALGONDA,2000,Whole Year,Coconut,20.0,202356.0,10117.800000
183660,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.0,9801.000000
196074,Telangana,RANGAREDDI,2008,Whole Year,Coconut,1.0,9321.0,9321.000000
193517,Telangana,MAHBUBNAGAR,2008,Whole Year,Coconut,8.0,74568.0,9321.000000
195406,Telangana,NIZAMABAD,2008,Whole Year,Coconut,12.0,111852.0,9321.000000
194101,Telangana,MEDAK,2005,Whole Year,Coconut,1.0,8702.0,8702.000000
193414,Telangana,MAHBUBNAGAR,2005,Whole Year,Coconut,13.0,113126.0,8702.000000
195972,Telangana,RANGAREDDI,2005,Whole Year,Coconut,13.0,113126.0,8702.000000
5390,Andhra Pradesh,KURNOOL,2012,Whole Year,Coconut,16.0,138000.0,8625.000000
5518,Andhra Pradesh,KURNOOL,2014,Whole Year,Coconut,8.0,67000.0,8375.000000

In [ ]:
# STEP: Create a review list for known suspicious records

review = audit.copy()

review["review_reason"] = ""

# Coconut: production units need verification
coconut_mask = (
    review["Crop"].str.strip().str.lower() == "coconut"
)

review.loc[coconut_mask, "review_reason"] = (
    "Verify production unit before yield modelling"
)

# Punjab sugarcane, 2011: suspected area-scale/data-entry issue
punjab_sugarcane_mask = (
    review["State_Name"].str.strip().str.lower().eq("punjab")
    & review["Crop"].str.strip().str.lower().eq("sugarcane")
    & review["Crop_Year"].eq(2011)
)

review.loc[punjab_sugarcane_mask, "review_reason"] = (
    "Verify suspicious area and production values"
)

# Cashewnut anomaly: Perambalur, 2008
cashew_mask = (
    review["State_Name"].str.strip().str.lower().eq("tamil nadu")
    & review["District_Name"].str.strip().str.upper().eq("PERAMBALUR")
    & review["Crop"].str.strip().str.lower().eq("cashewnut")
    & review["Crop_Year"].eq(2008)
)

review.loc[cashew_mask, "review_reason"] = (
    "Verify unusually small area against original source"
)

review_list = review[review["review_reason"] != ""]

print("Records marked for review:", len(review_list))

display(
    review_list[
        [
            "State_Name",
            "District_Name",
            "Crop_Year",
            "Season",
            "Crop",
            "Area",
            "Production",
            "calculated_yield",
            "review_reason"
        ]
    ].head(30)
)

Records marked for review: 1974

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,calculated_yield,review_reason
5,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Coconut,18168.00,65100000.0,3583.223250,Verify production unit before yield modelling
14,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Coconut,18190.00,64430000.0,3542.056075,Verify production unit before yield modelling
23,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Coconut,18240.00,67490000.0,3700.109649,Verify production unit before yield modelling
32,Andaman and Nicobar Islands,NICOBARS,2003,Whole Year,Coconut,18284.74,68580000.0,3750.668590,Verify production unit before yield modelling
41,Andaman and Nicobar Islands,NICOBARS,2004,Whole Year,Coconut,18394.70,52380000.0,2847.559351,Verify production unit before yield modelling
50,Andaman and Nicobar Islands,NICOBARS,2005,Whole Year,Coconut,13876.57,52030000.0,3749.485644,Verify production unit before yield modelling
57,Andaman and Nicobar Islands,NICOBARS,2006,Whole Year,Coconut,14358.00,59370000.0,4134.977016,Verify production unit before yield modelling
77,Andaman and Nicobar Islands,NICOBARS,2010,Whole Year,Coconut,14560.00,71300000.0,4896.978022,Verify production unit before yield modelling
84,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2000,Whole Year,Coconut,6992.00,23900000.0,3418.192220,Verify production unit before yield modelling
94,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2001,Whole Year,Coconut,7015.00,25250000.0,3599.429793,Verify production unit before yield modelling
103,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2006,Whole Year,Coconut,3575.00,15400000.0,4307.692308,Verify production unit before yield modelling
127,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,2010,Whole Year,Coconut,3668.00,12700000.0,3462.377317,Verify production unit before yield modelling
134,Andaman and Nicobar Islands,SOUTH ANDAMANS,2002,Whole Year,Coconut,7060.00,26830000.0,3800.283286,Verify production unit before yield modelling
144,Andaman and Nicobar Islands,SOUTH ANDAMANS,2003,Whole Year,Coconut,7110.00,26660000.0,3749.648383,Verify production unit before yield modelling
154,Andaman and Nicobar Islands,SOUTH ANDAMANS,2004,Whole Year,Coconut,7156.70,34750000.0,4855.589867,Verify production unit before yield modelling
164,Andaman and Nicobar Islands,SOUTH ANDAMANS,2005,Whole Year,Coconut,7050.45,26430000.0,3748.696892,Verify production unit before yield modelling
177,Andaman and Nicobar Islands,SOUTH ANDAMANS,2006,Whole Year,Coconut,3483.09,14190000.0,4073.968804,Verify production unit before yield modelling
201,Andaman and Nicobar Islands,SOUTH ANDAMANS,2010,Whole Year,Coconut,3540.00,11000000.0,3107.344633,Verify production unit before yield modelling
329,Andhra Pradesh,ANANTAPUR,2000,Whole Year,Coconut,908.00,3896970.0,4291.817181,Verify production unit before yield modelling
375,Andhra Pradesh,ANANTAPUR,2001,Whole Year,Coconut,851.00,3053700.0,3588.366627,Verify production unit before yield modelling
422,Andhra Pradesh,ANANTAPUR,2002,Whole Year,Coconut,869.00,3691149.0,4247.582278,Verify production unit before yield modelling
479,Andhra Pradesh,ANANTAPUR,2003,Whole Year,Coconut,839.00,3285828.0,3916.362336,Verify production unit before yield modelling
528,Andhra Pradesh,ANANTAPUR,2004,Whole Year,Coconut,837.00,6413350.0,7662.305854,Verify production unit before yield modelling
569,Andhra Pradesh,ANANTAPUR,2005,Whole Year,Coconut,836.00,3358992.0,4017.933014,Verify production unit before yield modelling
609,Andhra Pradesh,ANANTAPUR,2006,Whole Year,Coconut,790.00,6404076.0,8106.425316,Verify production unit before yield modelling
665,Andhra Pradesh,ANANTAPUR,2008,Whole Year,Coconut,786.00,7141464.0,9085.832061,Verify production unit before yield modelling
705,Andhra Pradesh,ANANTAPUR,2009,Whole Year,Coconut,725.00,4247685.0,5858.875862,Verify production unit before yield modelling
790,Andhra Pradesh,ANANTAPUR,2011,Whole Year,Coconut,895.00,7165320.0,8005.944134,Verify production unit before yield modelling
855,Andhra Pradesh,ANANTAPUR,2012,Whole Year,Coconut,646.00,5571000.0,8623.839009,Verify production unit before yield modelling
920,Andhra Pradesh,ANANTAPUR,2013,Whole Year,Coconut,552.00,3969000.0,7190.217391,Verify production unit before yield modelling

In [ ]:
# STEP: Verify review categories

print("Records by review reason:")
display(
    review_list["review_reason"]
    .value_counts()
    .to_frame("Record_Count")
)

print("\nAll non-coconut records marked for review:")

display(
    review_list[
        review_list["Crop"].str.strip().str.lower().ne("coconut")
    ][
        [
            "State_Name",
            "District_Name",
            "Crop_Year",
            "Crop",
            "Area",
            "Production",
            "calculated_yield",
            "review_reason"
        ]
    ].reset_index(drop=True)
)

Records by review reason:

                                                    Record_Count
review_reason
Verify production unit before yield modelling               1958
Verify suspicious area and production values                  15
Verify unusually small area against original so...             1

All non-coconut records marked for review:

,State_Name,District_Name,Crop_Year,Crop,Area,Production,calculated_yield,review_reason
0,Punjab,AMRITSAR,2011,Sugarcane,3.0,203000.0,67666.666667,Verify suspicious area and production values
1,Punjab,FATEHGARH SAHIB,2011,Sugarcane,2.0,151000.0,75500.000000,Verify suspicious area and production values
2,Punjab,FAZILKA,2011,Sugarcane,1.0,73000.0,73000.000000,Verify suspicious area and production values
3,Punjab,GURDASPUR,2011,Sugarcane,20.0,1491000.0,74550.000000,Verify suspicious area and production values
4,Punjab,HOSHIARPUR,2011,Sugarcane,20.0,1293000.0,64650.000000,Verify suspicious area and production values
5,Punjab,JALANDHAR,2011,Sugarcane,9.0,599000.0,66555.555556,Verify suspicious area and production values
6,Punjab,KAPURTHALA,2011,Sugarcane,3.0,221000.0,73666.666667,Verify suspicious area and production values
7,Punjab,LUDHIANA,2011,Sugarcane,2.0,161000.0,80500.000000,Verify suspicious area and production values
8,Punjab,NAWANSHAHR,2011,Sugarcane,6.0,407000.0,67833.333333,Verify suspicious area and production values
9,Punjab,PATHANKOT,2011,Sugarcane,4.0,298000.0,74500.000000,Verify suspicious area and production values
10,Punjab,PATIALA,2011,Sugarcane,3.0,264000.0,88000.000000,Verify suspicious area and production values
11,Punjab,RUPNAGAR,2011,Sugarcane,3.0,224000.0,74666.666667,Verify suspicious area and production values
12,Punjab,S.A.S NAGAR,2011,Sugarcane,1.0,65000.0,65000.000000,Verify suspicious area and production values
13,Punjab,SANGRUR,2011,Sugarcane,2.0,163000.0,81500.000000,Verify suspicious area and production values
14,Punjab,TARN TARAN,2011,Sugarcane,1.0,40000.0,40000.000000,Verify suspicious area and production values
15,Tamil Nadu,PERAMBALUR,2008,Cashewnut,1.0,9801.0,9801.000000,Verify unusually small area against original s...

In [ ]:
# STEP: Create a candidate dataset for yield modelling
# The original df and audit remain unchanged.

candidate = audit.copy()

# Exclude Coconut until production units are verified
coconut_mask = (
    candidate["Crop"].str.strip().str.lower().eq("coconut")
)

# Exclude suspicious Punjab sugarcane records from 2011
punjab_sugarcane_mask = (
    candidate["State_Name"].str.strip().str.lower().eq("punjab")
    & candidate["Crop"].str.strip().str.lower().eq("sugarcane")
    & candidate["Crop_Year"].eq(2011)
)

# Exclude the suspicious Cashewnut record
cashew_mask = (
    candidate["State_Name"].str.strip().str.lower().eq("tamil nadu")
    & candidate["District_Name"].str.strip().str.upper().eq("PERAMBALUR")
    & candidate["Crop"].str.strip().str.lower().eq("cashewnut")
    & candidate["Crop_Year"].eq(2008)
)

exclude_mask = (
    coconut_mask
    | punjab_sugarcane_mask
    | cashew_mask
)

candidate = candidate.loc[~exclude_mask].copy()

print("Original dataset rows:", len(df))
print("Valid area/production rows before exclusions:", len(audit))
print("Coconut records excluded:", int(coconut_mask.sum()))
print("Punjab sugarcane records excluded:", int(punjab_sugarcane_mask.sum()))
print("Cashewnut record excluded:", int(cashew_mask.sum()))
print("Candidate dataset rows:", len(candidate))
print("Remaining crop classes:", candidate["Crop"].nunique())

print("\nYield summary:")
display(candidate["calculated_yield"].describe().to_frame("Value"))

Original dataset rows: 246091
Valid area/production rows before exclusions: 242361
Coconut records excluded: 1958
Punjab sugarcane records excluded: 15
Cashewnut record excluded: 1
Candidate dataset rows: 240387
Remaining crop classes: 123

Yield summary:

               Value
count  240387.000000
mean        4.599282
std        18.990898
min         0.000000
25%         0.510204
50%         1.000000
75%         2.290162
max      2247.533300

In [ ]:
# STEP: Inspect remaining extreme yield values
# This is an inspection only; no records are removed.

print("Top 30 highest calculated yields:")

display(
    candidate[
        [
            "State_Name",
            "District_Name",
            "Crop_Year",
            "Season",
            "Crop",
            "Area",
            "Production",
            "calculated_yield"
        ]
    ]
    .sort_values("calculated_yield", ascending=False)
    .head(30)
    .reset_index(drop=True)
)

print("\nCrop-level yield summary:")

crop_yield_summary = (
    candidate.groupby("Crop")["calculated_yield"]
    .agg(
        records="count",
        median_yield="median",
        p95_yield=lambda x: x.quantile(0.95),
        max_yield="max"
    )
    .sort_values("max_yield", ascending=False)
)

display(crop_yield_summary.head(25))

Top 30 highest calculated yields:

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,calculated_yield
0,Tamil Nadu,MADURAI,1997,Whole Year,Sugarcane,8108.0,18223000.0,2247.533300
1,Haryana,KARNAL,2008,Whole Year,Onion,2.0,4300.0,2150.000000
2,Tamil Nadu,THIRUVALLUR,1997,Whole Year,Sugarcane,5964.0,11811000.0,1980.382294
3,Maharashtra,NASHIK,1997,Autumn,Maize,1.0,1494.0,1494.000000
4,Tamil Nadu,KANCHIPURAM,1997,Whole Year,Sugarcane,6735.0,9896000.0,1469.339272
5,Tamil Nadu,NAMAKKAL,1997,Whole Year,Sugarcane,9415.0,13608000.0,1445.353160
6,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,Sugarcane,4315.0,5806000.0,1345.538818
7,Maharashtra,JALGAON,1997,Autumn,Maize,3.0,3980.0,1326.666667
8,Tamil Nadu,CUDDALORE,1997,Whole Year,Sugarcane,23826.0,28322000.0,1188.701419
9,Tamil Nadu,KARUR,1997,Whole Year,Sugarcane,5961.0,7081000.0,1187.887938
10,Tamil Nadu,SALEM,1997,Whole Year,Sugarcane,13759.0,15866000.0,1153.136129
11,Maharashtra,PUNE,1997,Autumn,Maize,4.0,4570.0,1142.500000
12,Tamil Nadu,COIMBATORE,1997,Whole Year,Sugarcane,10756.0,12272000.0,1140.944589
13,Maharashtra,OSMANABAD,1997,Autumn,Maize,5.0,5635.0,1127.000000
14,Tamil Nadu,VILLUPURAM,1997,Whole Year,Sugarcane,33175.0,37158000.0,1120.060286
15,Tamil Nadu,ERODE,1997,Whole Year,Sugarcane,24112.0,26930000.0,1116.871267
16,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000000
17,Tamil Nadu,THENI,1997,Whole Year,Sugarcane,9524.0,10598000.0,1112.767745
18,Tamil Nadu,THE NILGIRIS,1997,Whole Year,Sugarcane,22.0,24000.0,1090.909091
19,Tamil Nadu,TUTICORIN,1997,Whole Year,Sugarcane,90.0,97000.0,1077.777778
20,Tamil Nadu,TIRUNELVELI,1997,Whole Year,Sugarcane,2237.0,2402000.0,1073.759499
21,Tamil Nadu,NAGAPATTINAM,1997,Whole Year,Sugarcane,4601.0,4940000.0,1073.679635
22,Tamil Nadu,PUDUKKOTTAI,1997,Whole Year,Sugarcane,2377.0,2552000.0,1073.622213
23,Tamil Nadu,VIRUDHUNAGAR,1997,Whole Year,Sugarcane,2639.0,2833000.0,1073.512694
24,Tamil Nadu,RAMANATHAPURAM,1997,Whole Year,Sugarcane,182.0,195000.0,1071.428571
25,Tamil Nadu,DHARMAPURI,1997,Whole Year,Sugarcane,18938.0,18100000.0,955.750343
26,Tamil Nadu,PERAMBALUR,1997,Whole Year,Sugarcane,11508.0,10448000.0,907.890163
27,Tamil Nadu,TIRUVANNAMALAI,1997,Whole Year,Sugarcane,27636.0,23914000.0,865.320596
28,Tamil Nadu,DINDIGUL,1997,Whole Year,Sugarcane,6826.0,5749000.0,842.220920
29,Tamil Nadu,SIVAGANGA,1997,Whole Year,Sugarcane,4794.0,3938000.0,821.443471

Crop-level yield summary:

                records  median_yield   p95_yield    max_yield
Crop
Sugarcane          7812     53.170909  106.838291  2247.533300
Onion              6984     10.297120   25.739948  2150.000000
Maize             13787      1.795918    4.816606  1494.000000
Cotton(lint)       4382      1.367349    3.999432   300.000000
Sesamum            8821      0.333333    0.882353   235.000000
Rice              15082      1.938529    3.638213   223.727273
Potato             6914     10.833194   25.997861   213.846154
Banana             3133     21.804276   63.566667   138.421053
Papaya              483     15.500000  108.934491   134.142636
Niger seed         2018      0.285714    0.638458    71.000000
Tapioca            1584     11.443750   42.164587    70.516091
Sunflower          5483      0.800000    1.954958    70.000000
Mesta              1770      5.000000   12.474921    68.000000
Cabbage             204      0.000000   58.743750    67.212346
Pome Fruit          297      3.137500   11.204002    57.139836
Sannhamp           2183      0.500000    4.567068    55.550000
Tomato              368      7.185687   21.831136    50.205080
Groundnut          8770      1.043478    2.266667    49.000000
Grapes              129     20.924138   30.532840    42.927829
Guar seed          1257      0.816327    1.003391    40.000000
Dry ginger         2987      2.491803   19.500000    39.065445
Sweet potato       4122      8.222222   16.333078    38.125000
other oilseeds      594      0.500000    5.732898    32.574815
Pineapple           247     14.647059   26.167125    32.098935
Brinjal             386      6.450432   21.220374    29.983498

In [ ]:
# STEP: Investigate extreme yields by year and district

# 1. Sugarcane yield summary by year
sugarcane = candidate[
    candidate["Crop"].str.strip().str.lower().eq("sugarcane")
].copy()

print("SUGARCANE: YEAR-WISE YIELD SUMMARY")

display(
    sugarcane.groupby("Crop_Year")["calculated_yield"]
    .agg(
        records="count",
        median_yield="median",
        p95_yield=lambda x: x.quantile(0.95),
        max_yield="max"
    )
    .sort_index()
)

# 2. Tamil Nadu sugarcane records for 1997
print("\nTAMIL NADU SUGARCANE: 1997")

display(
    sugarcane[
        sugarcane["State_Name"].str.strip().str.lower().eq("tamil nadu")
        & sugarcane["Crop_Year"].eq(1997)
    ][
        [
            "District_Name", "Area", "Production",
            "calculated_yield"
        ]
    ].sort_values("calculated_yield", ascending=False)
)

# 3. Onion records for Karnal around 2008
print("\nONION: KARNAL, 2006–2010")

display(
    candidate[
        candidate["District_Name"].str.strip().str.upper().eq("KARNAL")
        & candidate["Crop"].str.strip().str.lower().eq("onion")
        & candidate["Crop_Year"].between(2006, 2010)
    ][
        [
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "Production", "calculated_yield"
        ]
    ].sort_values(["Crop_Year", "Season"])
)

SUGARCANE: YEAR-WISE YIELD SUMMARY

           records  median_yield    p95_yield    max_yield
Crop_Year
1997           330     55.366046  1073.572929  2247.533300
1998           408     51.851274   121.504860   303.484773
1999           444     54.189472   111.969394   162.500000
2000           466     49.522222   107.116143   162.000000
2001           461     51.933015   100.172612   158.572753
2002           466     49.889998    92.379624   162.000000
2003           461     49.284046   100.000000   163.333333
2004           423     51.274725   100.691208   162.500000
2005           469     53.787998    99.200822   147.258056
2006           402     54.237262   113.603758   188.414997
2007           460     52.400000   107.538172   138.983531
2008           482     51.146757   106.530661   314.736149
2009           458     53.191390   101.650010   150.000000
2010           463     53.494253   108.330000   157.375283
2011           390     55.891670   116.395691   176.166667
2012           443     58.800000   104.242895   159.632964
2013           411     58.400000   103.574105   220.617757
2014           347     60.116008   107.014312   179.866515
2015            28     57.110000    75.187148    78.830142

TAMIL NADU SUGARCANE: 1997

          District_Name     Area  Production  calculated_yield
182001          MADURAI   8108.0  18223000.0       2247.533300
186870      THIRUVALLUR   5964.0  11811000.0       1980.382294
180534      KANCHIPURAM   6735.0   9896000.0       1469.339272
182819         NAMAKKAL   9415.0  13608000.0       1445.353160
187574  TIRUCHIRAPPALLI   4315.0   5806000.0       1345.538818
178362        CUDDALORE  23826.0  28322000.0       1188.701419
181195            KARUR   5961.0   7081000.0       1187.887938
184641            SALEM  13759.0  15866000.0       1153.136129
177823       COIMBATORE  10756.0  12272000.0       1140.944589
190249       VILLUPURAM  33175.0  37158000.0       1120.060286
179974            ERODE  24112.0  26930000.0       1116.871267
186359            THENI   9524.0  10598000.0       1112.767745
186037     THE NILGIRIS     22.0     24000.0       1090.909091
189255        TUTICORIN     90.0     97000.0       1077.777778
188084      TIRUNELVELI   2237.0   2402000.0       1073.759499
182490     NAGAPATTINAM   4601.0   4940000.0       1073.679635
183826      PUDUKKOTTAI   2377.0   2552000.0       1073.622213
190745     VIRUDHUNAGAR   2639.0   2833000.0       1073.512694
184256   RAMANATHAPURAM    182.0    195000.0       1071.428571
178830       DHARMAPURI  18938.0  18100000.0        955.750343
183346       PERAMBALUR  11508.0  10448000.0        907.890163
188758   TIRUVANNAMALAI  27636.0  23914000.0        865.320596
179376         DINDIGUL   6826.0   5749000.0        842.220920
185205        SIVAGANGA   4794.0   3938000.0        821.443471
185626        THANJAVUR  12604.0   9900000.0        785.464932
189731          VELLORE  29072.0  22069000.0        759.115300
187264       THIRUVARUR   3669.0   2287000.0        623.330608

ONION: KARNAL, 2006–2010

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield
68458,Haryana,KARNAL,2007,Whole Year,5.0,100.0,20.000000
68479,Haryana,KARNAL,2008,Whole Year,2.0,4300.0,2150.000000
68524,Haryana,KARNAL,2010,Whole Year,22.0,400.0,18.181818

In [ ]:
# STEP: Locate extreme sugarcane yields by state and year
# Inspection only — no records are deleted.

sugarcane_extremes = sugarcane[
    sugarcane["calculated_yield"] > 200
].copy()

print("Sugarcane records with calculated yield > 200:",
      len(sugarcane_extremes))

print("\nExtreme sugarcane records by year:")
display(
    sugarcane_extremes.groupby("Crop_Year")
    .agg(
        flagged_records=("calculated_yield", "size"),
        affected_states=("State_Name", "nunique"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max")
    )
    .sort_index()
)

print("\nExtreme sugarcane records by state:")
display(
    sugarcane_extremes.groupby("State_Name")
    .agg(
        flagged_records=("calculated_yield", "size"),
        affected_years=("Crop_Year", "nunique"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max")
    )
    .sort_values("flagged_records", ascending=False)
)

print("\nTamil Nadu sugarcane records from 1997:")
display(
    sugarcane[
        sugarcane["State_Name"].str.strip().str.lower().eq("tamil nadu")
        & sugarcane["Crop_Year"].eq(1997)
    ][
        [
            "District_Name", "Area", "Production",
            "calculated_yield"
        ]
    ].sort_values("calculated_yield", ascending=False)
)

Sugarcane records with calculated yield > 200: 35

Extreme sugarcane records by year:

           flagged_records  affected_states  median_yield    max_yield
Crop_Year
1997                    28                2   1075.768639  2247.533300
1998                     3                1    242.657872   303.484773
2008                     3                2    258.352766   314.736149
2013                     1                1    220.617757   220.617757

Extreme sugarcane records by state:

             flagged_records  affected_years  median_yield    max_yield
State_Name
Tamil Nadu                32               3   1073.650924  2247.533300
Bihar                      1               1    500.491525   500.491525
Kerala                     1               1    229.285714   229.285714
West Bengal                1               1    220.617757   220.617757

Tamil Nadu sugarcane records from 1997:

          District_Name     Area  Production  calculated_yield
182001          MADURAI   8108.0  18223000.0       2247.533300
186870      THIRUVALLUR   5964.0  11811000.0       1980.382294
180534      KANCHIPURAM   6735.0   9896000.0       1469.339272
182819         NAMAKKAL   9415.0  13608000.0       1445.353160
187574  TIRUCHIRAPPALLI   4315.0   5806000.0       1345.538818
178362        CUDDALORE  23826.0  28322000.0       1188.701419
181195            KARUR   5961.0   7081000.0       1187.887938
184641            SALEM  13759.0  15866000.0       1153.136129
177823       COIMBATORE  10756.0  12272000.0       1140.944589
190249       VILLUPURAM  33175.0  37158000.0       1120.060286
179974            ERODE  24112.0  26930000.0       1116.871267
186359            THENI   9524.0  10598000.0       1112.767745
186037     THE NILGIRIS     22.0     24000.0       1090.909091
189255        TUTICORIN     90.0     97000.0       1077.777778
188084      TIRUNELVELI   2237.0   2402000.0       1073.759499
182490     NAGAPATTINAM   4601.0   4940000.0       1073.679635
183826      PUDUKKOTTAI   2377.0   2552000.0       1073.622213
190745     VIRUDHUNAGAR   2639.0   2833000.0       1073.512694
184256   RAMANATHAPURAM    182.0    195000.0       1071.428571
178830       DHARMAPURI  18938.0  18100000.0        955.750343
183346       PERAMBALUR  11508.0  10448000.0        907.890163
188758   TIRUVANNAMALAI  27636.0  23914000.0        865.320596
179376         DINDIGUL   6826.0   5749000.0        842.220920
185205        SIVAGANGA   4794.0   3938000.0        821.443471
185626        THANJAVUR  12604.0   9900000.0        785.464932
189731          VELLORE  29072.0  22069000.0        759.115300
187264       THIRUVARUR   3669.0   2287000.0        623.330608

In [ ]:
# STEP: Review all 35 extreme sugarcane records
# Inspection only — no records are modified or deleted.

sugarcane_review = sugarcane[
    sugarcane["calculated_yield"] > 200
].copy()

print("Total records requiring review:", len(sugarcane_review))

display(
    sugarcane_review[
        [
            "State_Name",
            "District_Name",
            "Crop_Year",
            "Area",
            "Production",
            "calculated_yield"
        ]
    ]
    .sort_values(
        ["Crop_Year", "State_Name", "calculated_yield"],
        ascending=[True, True, False]
    )
    .reset_index(drop=True)
)

Total records requiring review: 35

,State_Name,District_Name,Crop_Year,Area,Production,calculated_yield
0,Bihar,BUXAR,1997,59.0,29529.0,500.491525
1,Tamil Nadu,MADURAI,1997,8108.0,18223000.0,2247.533300
2,Tamil Nadu,THIRUVALLUR,1997,5964.0,11811000.0,1980.382294
3,Tamil Nadu,KANCHIPURAM,1997,6735.0,9896000.0,1469.339272
4,Tamil Nadu,NAMAKKAL,1997,9415.0,13608000.0,1445.353160
5,Tamil Nadu,TIRUCHIRAPPALLI,1997,4315.0,5806000.0,1345.538818
6,Tamil Nadu,CUDDALORE,1997,23826.0,28322000.0,1188.701419
7,Tamil Nadu,KARUR,1997,5961.0,7081000.0,1187.887938
8,Tamil Nadu,SALEM,1997,13759.0,15866000.0,1153.136129
9,Tamil Nadu,COIMBATORE,1997,10756.0,12272000.0,1140.944589
10,Tamil Nadu,VILLUPURAM,1997,33175.0,37158000.0,1120.060286
11,Tamil Nadu,ERODE,1997,24112.0,26930000.0,1116.871267
12,Tamil Nadu,THENI,1997,9524.0,10598000.0,1112.767745
13,Tamil Nadu,THE NILGIRIS,1997,22.0,24000.0,1090.909091
14,Tamil Nadu,TUTICORIN,1997,90.0,97000.0,1077.777778
15,Tamil Nadu,TIRUNELVELI,1997,2237.0,2402000.0,1073.759499
16,Tamil Nadu,NAGAPATTINAM,1997,4601.0,4940000.0,1073.679635
17,Tamil Nadu,PUDUKKOTTAI,1997,2377.0,2552000.0,1073.622213
18,Tamil Nadu,VIRUDHUNAGAR,1997,2639.0,2833000.0,1073.512694
19,Tamil Nadu,RAMANATHAPURAM,1997,182.0,195000.0,1071.428571
20,Tamil Nadu,DHARMAPURI,1997,18938.0,18100000.0,955.750343
21,Tamil Nadu,PERAMBALUR,1997,11508.0,10448000.0,907.890163
22,Tamil Nadu,TIRUVANNAMALAI,1997,27636.0,23914000.0,865.320596
23,Tamil Nadu,DINDIGUL,1997,6826.0,5749000.0,842.220920
24,Tamil Nadu,SIVAGANGA,1997,4794.0,3938000.0,821.443471
25,Tamil Nadu,THANJAVUR,1997,12604.0,9900000.0,785.464932
26,Tamil Nadu,VELLORE,1997,29072.0,22069000.0,759.115300
27,Tamil Nadu,THIRUVARUR,1997,3669.0,2287000.0,623.330608
28,Tamil Nadu,MADURAI,1998,10081.0,3059430.0,303.484773
29,Tamil Nadu,KANCHIPURAM,1998,23801.0,5775500.0,242.657872
30,Tamil Nadu,THENI,1998,16133.0,3617820.0,224.249675
31,Kerala,PATHANAMTHITTA,2008,14.0,3210.0,229.285714
32,Tamil Nadu,COIMBATORE,2008,2581.0,812334.0,314.736149
33,Tamil Nadu,PERAMBALUR,2008,3688.0,952805.0,258.352766
34,West Bengal,MEDINIPUR WEST,2013,3210.0,708183.0,220.617757

In [ ]:
# STEP: Save extreme sugarcane records for source verification

sugarcane_review = candidate[
    candidate["Crop"].str.strip().str.lower().eq("sugarcane")
    & (candidate["calculated_yield"] > 200)
].copy()

print("Sugarcane records requiring verification:",
      len(sugarcane_review))

# Save a review copy; the candidate dataset remains unchanged
sugarcane_review.to_csv(
    "sugarcane_extreme_yield_review.csv",
    index=False
)

print("Saved: sugarcane_extreme_yield_review.csv")

Sugarcane records requiring verification: 35
Saved: sugarcane_extreme_yield_review.csv

In [ ]:
import os

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"
os.makedirs(DRIVE_FOLDER, exist_ok=True)

print("Google Drive folder:", DRIVE_FOLDER)
print("Files in folder:", os.listdir(DRIVE_FOLDER))

Google Drive folder: /content/drive/MyDrive/yield prediction
Files in folder: []

In [ ]:
import os

output_path = os.path.join(
    DRIVE_FOLDER,
    "sugarcane_extreme_yield_review.csv"
)

sugarcane_review.to_csv(output_path, index=False)

print("Saved successfully to Google Drive!")
print("File path:", output_path)
print("Rows saved:", len(sugarcane_review))

Saved successfully to Google Drive!
File path: /content/drive/MyDrive/yield prediction/sugarcane_extreme_yield_review.csv
Rows saved: 35

In [ ]:
import os

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

output_path = os.path.join(
    DRIVE_FOLDER,
    "sugarcane_extreme_yield_review.csv"
)

sugarcane_review.to_csv(output_path, index=False)

print("Saved successfully to Google Drive!")
print("File path:", output_path)
print("Rows saved:", len(sugarcane_review))

Saved successfully to Google Drive!
File path: /content/drive/MyDrive/yield prediction/sugarcane_extreme_yield_review.csv
Rows saved: 35

In [ ]:
import pandas as pd
import os

review_path = os.path.join(
    "/content/drive/MyDrive/yield prediction",
    "sugarcane_extreme_yield_review.csv"
)

sugarcane_review = pd.read_csv(review_path)

display(
    sugarcane_review[
        [
            "State_Name",
            "District_Name",
            "Crop_Year",
            "Season",
            "Area",
            "Production",
            "calculated_yield"
        ]
    ].sort_values("calculated_yield", ascending=False)
)

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield
11,Tamil Nadu,MADURAI,1997,Whole Year,8108.0,18223000.0,2247.533300
25,Tamil Nadu,THIRUVALLUR,1997,Whole Year,5964.0,11811000.0,1980.382294
8,Tamil Nadu,KANCHIPURAM,1997,Whole Year,6735.0,9896000.0,1469.339272
14,Tamil Nadu,NAMAKKAL,1997,Whole Year,9415.0,13608000.0,1445.353160
27,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,4315.0,5806000.0,1345.538818
4,Tamil Nadu,CUDDALORE,1997,Whole Year,23826.0,28322000.0,1188.701419
10,Tamil Nadu,KARUR,1997,Whole Year,5961.0,7081000.0,1187.887938
19,Tamil Nadu,SALEM,1997,Whole Year,13759.0,15866000.0,1153.136129
2,Tamil Nadu,COIMBATORE,1997,Whole Year,10756.0,12272000.0,1140.944589
32,Tamil Nadu,VILLUPURAM,1997,Whole Year,33175.0,37158000.0,1120.060286
7,Tamil Nadu,ERODE,1997,Whole Year,24112.0,26930000.0,1116.871267
23,Tamil Nadu,THENI,1997,Whole Year,9524.0,10598000.0,1112.767745
22,Tamil Nadu,THE NILGIRIS,1997,Whole Year,22.0,24000.0,1090.909091
30,Tamil Nadu,TUTICORIN,1997,Whole Year,90.0,97000.0,1077.777778
28,Tamil Nadu,TIRUNELVELI,1997,Whole Year,2237.0,2402000.0,1073.759499
13,Tamil Nadu,NAGAPATTINAM,1997,Whole Year,4601.0,4940000.0,1073.679635
17,Tamil Nadu,PUDUKKOTTAI,1997,Whole Year,2377.0,2552000.0,1073.622213
33,Tamil Nadu,VIRUDHUNAGAR,1997,Whole Year,2639.0,2833000.0,1073.512694
18,Tamil Nadu,RAMANATHAPURAM,1997,Whole Year,182.0,195000.0,1071.428571
5,Tamil Nadu,DHARMAPURI,1997,Whole Year,18938.0,18100000.0,955.750343
15,Tamil Nadu,PERAMBALUR,1997,Whole Year,11508.0,10448000.0,907.890163
29,Tamil Nadu,TIRUVANNAMALAI,1997,Whole Year,27636.0,23914000.0,865.320596
6,Tamil Nadu,DINDIGUL,1997,Whole Year,6826.0,5749000.0,842.220920
20,Tamil Nadu,SIVAGANGA,1997,Whole Year,4794.0,3938000.0,821.443471
21,Tamil Nadu,THANJAVUR,1997,Whole Year,12604.0,9900000.0,785.464932
31,Tamil Nadu,VELLORE,1997,Whole Year,29072.0,22069000.0,759.115300
26,Tamil Nadu,THIRUVARUR,1997,Whole Year,3669.0,2287000.0,623.330608
0,Bihar,BUXAR,1997,Whole Year,59.0,29529.0,500.491525
3,Tamil Nadu,COIMBATORE,2008,Whole Year,2581.0,812334.0,314.736149
12,Tamil Nadu,MADURAI,1998,Whole Year,10081.0,3059430.0,303.484773
16,Tamil Nadu,PERAMBALUR,2008,Whole Year,3688.0,952805.0,258.352766
9,Tamil Nadu,KANCHIPURAM,1998,Whole Year,23801.0,5775500.0,242.657872
1,Kerala,PATHANAMTHITTA,2008,Whole Year,14.0,3210.0,229.285714
24,Tamil Nadu,THENI,1998,Whole Year,16133.0,3617820.0,224.249675
34,West Bengal,MEDINIPUR WEST,2013,Whole Year,3210.0,708183.0,220.617757

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

# Districts from the flagged Tamil Nadu sugarcane records
tn_districts = sugarcane_review.loc[
    sugarcane_review["State_Name"].str.strip().str.lower().eq("tamil nadu"),
    "District_Name"
].dropna().unique()

# Use the original dataset for comparison
comparison = df[
    df["State_Name"].str.strip().str.lower().eq("tamil nadu")
    & df["Crop"].str.strip().str.lower().eq("sugarcane")
    & df["District_Name"].isin(tn_districts)
    & df["Crop_Year"].between(1997, 2000)
].copy()

comparison["calculated_yield"] = (
    comparison["Production"] / comparison["Area"]
)

columns = [
    "State_Name",
    "District_Name",
    "Crop_Year",
    "Season",
    "Area",
    "Production",
    "calculated_yield"
]

comparison = comparison[columns].sort_values(
    ["District_Name", "Crop_Year", "Season"]
)

display(comparison)

output_path = os.path.join(
    DRIVE_FOLDER,
    "sugarcane_nearby_years_comparison.csv"
)

comparison.to_csv(output_path, index=False)

print("Saved comparison to:", output_path)
print("Records compared:", len(comparison))

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield
177823,Tamil Nadu,COIMBATORE,1997,Whole Year,10756.0,12272000.0,1140.944589
177856,Tamil Nadu,COIMBATORE,1998,Whole Year,13193.0,1467460.0,111.230198
177884,Tamil Nadu,COIMBATORE,1999,Whole Year,11939.0,1195037.0,100.095234
177915,Tamil Nadu,COIMBATORE,2000,Whole Year,11167.0,1117764.0,100.095281
178362,Tamil Nadu,CUDDALORE,1997,Whole Year,23826.0,28322000.0,1188.701419
...,...,...,...,...,...,...,...
190338,Tamil Nadu,VILLUPURAM,2000,Whole Year,40233.0,4380107.0,108.868516
190745,Tamil Nadu,VIRUDHUNAGAR,1997,Whole Year,2639.0,2833000.0,1073.512694
190774,Tamil Nadu,VIRUDHUNAGAR,1998,Whole Year,3707.0,454970.0,122.732668
190798,Tamil Nadu,VIRUDHUNAGAR,1999,Whole Year,3052.0,317444.0,104.011796
190824,Tamil Nadu,VIRUDHUNAGAR,2000,Whole Year,3475.0,361441.0,104.011799

Saved comparison to: /content/drive/MyDrive/yield prediction/sugarcane_nearby_years_comparison.csv
Records compared: 108

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

comparison_path = os.path.join(
    DRIVE_FOLDER,
    "sugarcane_nearby_years_comparison.csv"
)

comparison = pd.read_csv(comparison_path)

year_summary = (
    comparison.groupby("Crop_Year")
    .agg(
        records=("calculated_yield", "size"),
        median_yield=("calculated_yield", "median"),
        min_yield=("calculated_yield", "min"),
        max_yield=("calculated_yield", "max"),
        total_area=("Area", "sum"),
        total_production=("Production", "sum")
    )
    .round(2)
    .reset_index()
)

display(year_summary)

summary_path = os.path.join(
    DRIVE_FOLDER,
    "sugarcane_yearwise_quality_summary.csv"
)

year_summary.to_csv(summary_path, index=False)

print("Saved summary to:", summary_path)

,Crop_Year,records,median_yield,min_yield,max_yield,total_area,total_production
0,1997,27,1077.78,623.33,2247.53,282845.0,307019000.0
1,1998,27,122.73,79.58,303.48,347910.0,46672800.0
2,1999,27,107.18,87.14,133.61,332332.0,35501817.0
3,2000,27,107.14,87.14,133.61,317473.0,34062855.0

Saved summary to: /content/drive/MyDrive/yield prediction/sugarcane_yearwise_quality_summary.csv

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

# Select Tamil Nadu sugarcane records from 1997
tn_sugarcane_1997 = comparison[
    comparison["State_Name"].str.strip().str.lower().eq("tamil nadu")
    & comparison["Crop_Year"].eq(1997)
].copy()

tn_sugarcane_1997["review_status"] = "Needs official-source verification"

output_path = os.path.join(
    DRIVE_FOLDER,
    "tamil_nadu_sugarcane_1997_review.csv"
)

tn_sugarcane_1997.to_csv(output_path, index=False)

print("Records saved:", len(tn_sugarcane_1997))
print("Saved to:", output_path)

display(tn_sugarcane_1997.sort_values(
    "calculated_yield", ascending=False
))

Records saved: 27
Saved to: /content/drive/MyDrive/yield prediction/tamil_nadu_sugarcane_1997_review.csv

,State_Name,District_Name,Crop_Year,Season,Area,Production,calculated_yield,review_status
28,Tamil Nadu,MADURAI,1997,Whole Year,8108.0,18223000.0,2247.533300,Needs official-source verification
72,Tamil Nadu,THIRUVALLUR,1997,Whole Year,5964.0,11811000.0,1980.382294,Needs official-source verification
20,Tamil Nadu,KANCHIPURAM,1997,Whole Year,6735.0,9896000.0,1469.339272,Needs official-source verification
36,Tamil Nadu,NAMAKKAL,1997,Whole Year,9415.0,13608000.0,1445.353160,Needs official-source verification
80,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,4315.0,5806000.0,1345.538818,Needs official-source verification
4,Tamil Nadu,CUDDALORE,1997,Whole Year,23826.0,28322000.0,1188.701419,Needs official-source verification
24,Tamil Nadu,KARUR,1997,Whole Year,5961.0,7081000.0,1187.887938,Needs official-source verification
52,Tamil Nadu,SALEM,1997,Whole Year,13759.0,15866000.0,1153.136129,Needs official-source verification
0,Tamil Nadu,COIMBATORE,1997,Whole Year,10756.0,12272000.0,1140.944589,Needs official-source verification
100,Tamil Nadu,VILLUPURAM,1997,Whole Year,33175.0,37158000.0,1120.060286,Needs official-source verification
16,Tamil Nadu,ERODE,1997,Whole Year,24112.0,26930000.0,1116.871267,Needs official-source verification
68,Tamil Nadu,THENI,1997,Whole Year,9524.0,10598000.0,1112.767745,Needs official-source verification
64,Tamil Nadu,THE NILGIRIS,1997,Whole Year,22.0,24000.0,1090.909091,Needs official-source verification
92,Tamil Nadu,TUTICORIN,1997,Whole Year,90.0,97000.0,1077.777778,Needs official-source verification
84,Tamil Nadu,TIRUNELVELI,1997,Whole Year,2237.0,2402000.0,1073.759499,Needs official-source verification
32,Tamil Nadu,NAGAPATTINAM,1997,Whole Year,4601.0,4940000.0,1073.679635,Needs official-source verification
44,Tamil Nadu,PUDUKKOTTAI,1997,Whole Year,2377.0,2552000.0,1073.622213,Needs official-source verification
104,Tamil Nadu,VIRUDHUNAGAR,1997,Whole Year,2639.0,2833000.0,1073.512694,Needs official-source verification
48,Tamil Nadu,RAMANATHAPURAM,1997,Whole Year,182.0,195000.0,1071.428571,Needs official-source verification
8,Tamil Nadu,DHARMAPURI,1997,Whole Year,18938.0,18100000.0,955.750343,Needs official-source verification
40,Tamil Nadu,PERAMBALUR,1997,Whole Year,11508.0,10448000.0,907.890163,Needs official-source verification
88,Tamil Nadu,TIRUVANNAMALAI,1997,Whole Year,27636.0,23914000.0,865.320596,Needs official-source verification
12,Tamil Nadu,DINDIGUL,1997,Whole Year,6826.0,5749000.0,842.220920,Needs official-source verification
56,Tamil Nadu,SIVAGANGA,1997,Whole Year,4794.0,3938000.0,821.443471,Needs official-source verification
60,Tamil Nadu,THANJAVUR,1997,Whole Year,12604.0,9900000.0,785.464932,Needs official-source verification
96,Tamil Nadu,VELLORE,1997,Whole Year,29072.0,22069000.0,759.115300,Needs official-source verification
76,Tamil Nadu,THIRUVARUR,1997,Whole Year,3669.0,2287000.0,623.330608,Needs official-source verification

In [ ]:
import requests
from getpass import getpass

API_KEY = getpass("Enter your NEW API key: ")

url = "https://data.gov.in/api/datastore/resource.json"

params = {
    "resource_id": "35be999b-0208-4354-b557-f6ca9a5355de",
    "api-key": API_KEY,
    "limit": 10
}

try:
    response = requests.get(url, params=params, timeout=30)
    print("HTTP status:", response.status_code)
    print("Response:", response.text[:2000])

except requests.RequestException as e:
    print("Connection error:", type(e).__name__)
    print("Details:", str(e))

Enter your NEW API key: ··········
Connection error: ConnectionError
Details: HTTPSConnectionPool(host='data.gov.in', port=443): Max retries exceeded with url: /api/datastore/resource.json?resource_id=35be999b-0208-4354-b557-f6ca9a5355de&api-key=579b464db66ec23bdd0000010d2adffafe254bfb7bf207dac74ed6f3&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7d4d49d03750>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [ ]:
import requests

for url in [
    "https://api.data.gov.in/",
    "https://www.data.gov.in/"
]:
    try:
        response = requests.get(url, timeout=15)
        print(url, "HTTP", response.status_code)
    except requests.RequestException as e:
        print(url, type(e).__name__, str(e))

https://api.data.gov.in/ ConnectionError HTTPSConnectionPool(host='api.data.gov.in', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7d4d49d03c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
https://www.data.gov.in/ HTTP 503

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

# Load the original dataset
input_path = os.path.join(
    DRIVE_FOLDER,
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(input_path)

print("Original shape:", df.shape)
print("Original crop count:", df["Crop"].nunique())

# Remove Coconut and Sugarcane
crops_to_remove = ["coconut", "sugarcane"]

cleaned_df = df[
    ~df["Crop"].str.strip().str.lower().isin(crops_to_remove)
].copy()

print("\nCleaned shape:", cleaned_df.shape)
print("Remaining crop count:", cleaned_df["Crop"].nunique())

print("\nVerify removed crops:")
print(
    cleaned_df[
        cleaned_df["Crop"].str.strip().str.lower().isin(crops_to_remove)
    ].shape[0]
)

# Save as a new file; do not overwrite the original
output_path = os.path.join(
    DRIVE_FOLDER,
    "crop_production_without_coconut_sugarcane.csv"
)

cleaned_df.to_csv(output_path, index=False)

print("\nSaved cleaned dataset to:", output_path)

Original shape: (246091, 11)
Original crop count: 124

Cleaned shape: (236185, 11)
Remaining crop count: 122

Verify removed crops:
0

Saved cleaned dataset to: /content/drive/MyDrive/yield prediction/crop_production_without_coconut_sugarcane.csv

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

INPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "crop_production_124_with_weather_soil.csv"
)

OUTPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_dataset_without_coconut.csv"
)

# Load original dataset
df = pd.read_csv(INPUT_PATH)

print("Original rows:", len(df))
print("Original crop count:", df["Crop"].nunique())

# Remove only Coconut
cleaned_df = df[
    ~df["Crop"].astype(str).str.strip().str.lower().eq("coconut")
].copy()

# Save the cleaned dataset to Google Drive
cleaned_df.to_csv(OUTPUT_PATH, index=False)

print("\nCleaning completed!")
print("Rows removed:", len(df) - len(cleaned_df))
print("Remaining rows:", len(cleaned_df))
print("Remaining crop count:", cleaned_df["Crop"].nunique())
print("Sugarcane retained:",
      cleaned_df["Crop"].astype(str).str.strip().str.lower().eq("sugarcane").sum())
print("Coconut retained:",
      cleaned_df["Crop"].astype(str).str.strip().str.lower().eq("coconut").sum())
print("\nSaved to:", OUTPUT_PATH)

Original rows: 246091
Original crop count: 124

Cleaning completed!
Rows removed: 1985
Remaining rows: 244106
Remaining crop count: 123
Sugarcane retained: 7921
Coconut retained: 0

Saved to: /content/drive/MyDrive/yield prediction/yield_prediction_dataset_without_coconut.csv

In [ ]:
import os
import pandas as pd

DATASET_PATH = (
    "/content/drive/MyDrive/yield prediction/"
    "yield_prediction_dataset_without_coconut.csv"
)

df_clean = pd.read_csv(DATASET_PATH)

print("Dataset shape:", df_clean.shape)
print("Unique crops:", df_clean["Crop"].nunique())
print("Missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())

print("\nRemaining Coconut records:",
      df_clean["Crop"].astype(str).str.strip().str.lower().eq("coconut").sum())

print("\nSugarcane records:",
      df_clean["Crop"].astype(str).str.strip().str.lower().eq("sugarcane").sum())

print("\nRecords by year:")
display(df_clean["Crop_Year"].value_counts().sort_index())

Dataset shape: (244106, 11)
Unique crops: 123
Missing values: 3703
Duplicate rows: 0

Remaining Coconut records: 0

Sugarcane records: 7921

Records by year:

Crop_Year
1997     8842
1998    11450
1999    12429
2000    13550
2001    13254
2002    16537
2003    17153
2004    13979
2005    13684
2006    14189
2007    14403
2008    14406
2009    13994
2010    13987
2011    13941
2012    13318
2013    13524
2014    10904
2015      562
Name: count, dtype: int64

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

# Count missing values in each column
missing_report = pd.DataFrame({
    "Missing_Count": df_clean.isnull().sum(),
    "Missing_Percentage": (
        df_clean.isnull().mean() * 100
    ).round(2)
}).sort_values("Missing_Count", ascending=False)

display(missing_report)

# Save report to Drive
report_path = os.path.join(
    DRIVE_FOLDER,
    "yield_missing_values_audit.csv"
)

missing_report.to_csv(report_path)

print("Saved report:", report_path)

               Missing_Count  Missing_Percentage
Production              3703                1.52
District_Name              0                0.00
State_Name                 0                0.00
Crop_Year                  0                0.00
Season                     0                0.00
Crop                       0                0.00
Area                       0                0.00
temperature                0                0.00
humidity                   0                0.00
rainfall_mm                0                0.00
soil_type                  0                0.00

Saved report: /content/drive/MyDrive/yield prediction/yield_missing_values_audit.csv

In [ ]:
# Compare the last three years
for year in [2013, 2014, 2015]:
    year_df = df_clean[df_clean["Crop_Year"] == year]

    print(f"\nYear: {year}")
    print("Total records:", len(year_df))
    print("Unique crops:", year_df["Crop"].nunique())
    print("Unique districts:", year_df["District_Name"].nunique())
    print("Missing Production:", year_df["Production"].isna().sum())

Year: 2013
Total records: 13524
Unique crops: 77
Unique districts: 506
Missing Production: 171

Year: 2014
Total records: 10904
Unique crops: 75
Unique districts: 427
Missing Production: 153

Year: 2015
Total records: 562
Unique crops: 17
Unique districts: 34
Missing Production: 1

In [ ]:
import os
import pandas as pd
import numpy as np

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

INPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_dataset_without_coconut.csv"
)

OUTPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_dataset_ready.csv"
)

# Load cleaned dataset
df_clean = pd.read_csv(INPUT_PATH)

print("Input rows:", len(df_clean))

# Keep rows where production and area are valid
valid_mask = (
    df_clean["Production"].notna()
    & df_clean["Area"].notna()
    & (df_clean["Area"] > 0)
    & (df_clean["Production"] >= 0)
)

yield_df = df_clean.loc[valid_mask].copy()

# Create yield target
yield_df["yield_tonnes_per_hectare"] = (
    yield_df["Production"] / yield_df["Area"]
)

# Save training-ready dataset
yield_df.to_csv(OUTPUT_PATH, index=False)

print("\nYield dataset created!")
print("Rows retained:", len(yield_df))
print("Rows excluded:", len(df_clean) - len(yield_df))
print("Crop classes:", yield_df["Crop"].nunique())
print("Missing yield targets:",
      yield_df["yield_tonnes_per_hectare"].isna().sum())
print("Saved to:", OUTPUT_PATH)

print("\nYield summary:")
print(yield_df["yield_tonnes_per_hectare"].describe())

Input rows: 244106

Yield dataset created!
Rows retained: 240403
Rows excluded: 3703
Crop classes: 123
Missing yield targets: 0
Saved to: /content/drive/MyDrive/yield prediction/yield_prediction_dataset_ready.csv

Yield summary:
count    240403.000000
mean          9.080575
std         568.836296
min           0.000000
25%           0.510204
50%           1.000000
75%           2.291430
max       88000.000000
Name: yield_tonnes_per_hectare, dtype: float64

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

INPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_dataset_ready.csv"
)

df_yield = pd.read_csv(INPUT_PATH)

# Summarize yield distribution by crop
crop_summary = (
    df_yield.groupby("Crop")["yield_tonnes_per_hectare"]
    .agg(
        Records="count",
        Median_Yield="median",
        P95_Yield=lambda x: x.quantile(0.95),
        P99_Yield=lambda x: x.quantile(0.99),
        Maximum_Yield="max"
    )
    .round(3)
    .sort_values("Maximum_Yield", ascending=False)
)

display(crop_summary.head(20))

# Save the report to Google Drive
output_path = os.path.join(
    DRIVE_FOLDER,
    "yield_by_crop_quality_report.csv"
)

crop_summary.to_csv(output_path)

print("Saved report:", output_path)

              Records  Median_Yield  P95_Yield  P99_Yield  Maximum_Yield
Crop
Sugarcane        7827        53.241    107.086    146.145      88000.000
Cashewnut        1068         0.396      1.030      1.894       9801.000
Onion            6984        10.297     25.740     33.000       2150.000
Maize           13787         1.796      4.817      7.230       1494.000
Cotton(lint)     4382         1.367      3.999      5.786        300.000
Sesamum          8821         0.333      0.882      1.102        235.000
Rice            15082         1.939      3.638      4.518        223.727
Potato           6914        10.833     25.998     31.350        213.846
Banana           3133        21.804     63.567     80.259        138.421
Papaya            483        15.500    108.934    130.473        134.143
Niger seed       2018         0.286      0.638      1.004         71.000
Tapioca          1584        11.444     42.165     49.874         70.516
Sunflower        5483         0.800      1.955      2.304         70.000
Mesta            1770         5.000     12.475     15.617         68.000
Cabbage           204         0.000     58.744     64.000         67.212
Pome Fruit        297         3.138     11.204     56.896         57.140
Sannhamp         2183         0.500      4.567      6.500         55.550
Tomato            368         7.186     21.831     28.859         50.205
Groundnut        8770         1.043      2.267      3.218         49.000
Grapes            129        20.924     30.533     39.538         42.928

Saved report: /content/drive/MyDrive/yield prediction/yield_by_crop_quality_report.csv

In [ ]:
import os
import numpy as np
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

INPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_dataset_ready.csv"
)

MODEL_DATA_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_model_data_v1.csv"
)

REVIEW_PATH = os.path.join(
    DRIVE_FOLDER,
    "crop_specific_extreme_yield_review.csv"
)

df_yield = pd.read_csv(INPUT_PATH)

target = "yield_tonnes_per_hectare"

# Create a log-transformed target.
# log1p safely handles zero yields.
df_yield["log_yield_target"] = np.log1p(df_yield[target])

# Flag observations above each crop's 99th percentile.
crop_p99 = df_yield.groupby("Crop")[target].transform(
    lambda values: values.quantile(0.99)
)

extreme_mask = df_yield[target] > crop_p99

review_df = df_yield.loc[extreme_mask].copy()

# Save the review file separately.
review_df.to_csv(REVIEW_PATH, index=False)

# Save all rows for future model preparation.
df_yield.to_csv(MODEL_DATA_PATH, index=False)

print("Rows retained:", len(df_yield))
print("Crop classes:", df_yield["Crop"].nunique())
print("Extreme-yield records flagged:", int(extreme_mask.sum()))
print("Missing log targets:", df_yield["log_yield_target"].isna().sum())

print("\nModel dataset:", MODEL_DATA_PATH)
print("Review dataset:", REVIEW_PATH)

Rows retained: 240403
Crop classes: 123
Extreme-yield records flagged: 2419
Missing log targets: 0

Model dataset: /content/drive/MyDrive/yield prediction/yield_prediction_model_data_v1.csv
Review dataset: /content/drive/MyDrive/yield prediction/crop_specific_extreme_yield_review.csv

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

INPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_model_data_v1.csv"
)

df_model = pd.read_csv(INPUT_PATH)

train_df = df_model[df_model["Crop_Year"].between(1997, 2012)].copy()
val_df = df_model[df_model["Crop_Year"] == 2013].copy()
test_df = df_model[df_model["Crop_Year"] == 2014].copy()
holdout_2015 = df_model[df_model["Crop_Year"] == 2015].copy()

for name, data in [
    ("Train", train_df),
    ("Validation", val_df),
    ("Test", test_df),
    ("2015 Holdout", holdout_2015)
]:
    print(
        f"{name}: rows={len(data):,}, "
        f"crops={data['Crop'].nunique()}"
    )

print("\nCrop classes in train but missing from test:")
print(sorted(set(train_df["Crop"]) - set(test_df["Crop"])))

print("\nCrop classes in test but missing from train:")
print(sorted(set(test_df["Crop"]) - set(train_df["Crop"])))

Train: rows=215,738, crops=116
Validation: rows=13,353, crops=76
Test: rows=10,751, crops=74
2015 Holdout: rows=561, crops=17

Crop classes in train but missing from test:
['Apple', 'Arcanut (Processed)', 'Ash Gourd', 'Atcanut (Raw)', 'Beans & Mutter(Vegetable)', 'Beet Root', 'Ber', 'Bhindi', 'Bitter Gourd', 'Bottle Gourd', 'Carrot', 'Cashewnut Processed', 'Cashewnut Raw', 'Cauliflower', 'Citrus Fruit', 'Coffee', 'Cond-spcs other', 'Cucumber', 'Jack Fruit', 'Jute & mesta', 'Kapas', 'Korra', 'Lab-Lab', 'Litchi', 'Other Citrus Fruit', 'Other Dry Fruit', 'Peach', 'Pear', 'Peas  (vegetable)', 'Plums', 'Pome Fruit', 'Pump Kin', 'Redish', 'Ribed Guard', 'Rubber', 'Samai', 'Snak Guard', 'Tea', 'Turnip', 'Varagu', 'Water Melon', 'Yam', 'other fibres', 'other misc. pulses']

Crop classes in test but missing from train:
['Bean', 'Lentil']

In [ ]:
import os
import pandas as pd

DRIVE_FOLDER = "/content/drive/MyDrive/yield prediction"

INPUT_PATH = os.path.join(
    DRIVE_FOLDER,
    "yield_prediction_model_data_v1.csv"
)

df_model = pd.read_csv(INPUT_PATH)

train_df = df_model[df_model["Crop_Year"].between(1997, 2012)].copy()
val_df = df_model[df_model["Crop_Year"] == 2013].copy()
test_df = df_model[df_model["Crop_Year"] == 2014].copy()

# Use crops present in all three sets
common_crops = (
    set(train_df["Crop"])
    & set(val_df["Crop"])
    & set(test_df["Crop"])
)

train_common = train_df[train_df["Crop"].isin(common_crops)].copy()
val_common = val_df[val_df["Crop"].isin(common_crops)].copy()
test_common = test_df[test_df["Crop"].isin(common_crops)].copy()

print("Common crop classes:", len(common_crops))
print("Training records:", len(train_common))
print("Validation records:", len(val_common))
print("Test records:", len(test_common))

print("\nCrops included:")
print(sorted(common_crops))

Common crop classes: 69
Training records: 212081
Validation records: 13277
Test records: 10615

Crops included:
['Arecanut', 'Arhar/Tur', 'Bajra', 'Banana', 'Barley', 'Black pepper', 'Blackgram', 'Brinjal', 'Cabbage', 'Cardamom', 'Cashewnut', 'Castor seed', 'Coriander', 'Cotton(lint)', 'Cowpea(Lobia)', 'Drum Stick', 'Dry chillies', 'Dry ginger', 'Garlic', 'Ginger', 'Gram', 'Grapes', 'Groundnut', 'Guar seed', 'Horse-gram', 'Jowar', 'Jute', 'Khesari', 'Lemon', 'Linseed', 'Maize', 'Mango', 'Masoor', 'Mesta', 'Moong(Green Gram)', 'Moth', 'Niger seed', 'Oilseeds total', 'Onion', 'Orange', 'Other  Rabi pulses', 'Other Fresh Fruits', 'Other Kharif pulses', 'Other Vegetables', 'Paddy', 'Papaya', 'Peas & beans (Pulses)', 'Pineapple', 'Pome Granet', 'Potato', 'Ragi', 'Rapeseed &Mustard', 'Rice', 'Safflower', 'Sannhamp', 'Sapota', 'Sesamum', 'Small millets', 'Soyabean', 'Sugarcane', 'Sunflower', 'Sweet potato', 'Tapioca', 'Tobacco', 'Tomato', 'Turmeric', 'Urad', 'Wheat', 'other oilseeds']

# Yield prediction model training using random forest

In [ ]:

# ============================================================
# CROPSENSE AI - YIELD PREDICTION MODEL TRAINING
# Self-contained Google Colab cell
# ============================================================

import os
import json
import warnings
import numpy as np
import pandas as pd
import joblib
import sklearn

from google.colab import drive
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    median_absolute_error,
    r2_score
)

warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# 1. GOOGLE DRIVE
# ------------------------------------------------------------
drive.mount("/content/drive")

FOLDER = "/content/drive/MyDrive/yield prediction"
os.makedirs(FOLDER, exist_ok=True)

INPUT_FILE = os.path.join(
    FOLDER, "crop_production_124_with_weather_soil.csv"
)

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"Dataset not found: {INPUT_FILE}\n"
        "Upload the original CSV to this Google Drive folder."
    )

df = pd.read_csv(INPUT_FILE)

required = [
    "State_Name", "District_Name", "Crop_Year", "Season",
    "Crop", "Area", "Production", "temperature",
    "humidity", "rainfall_mm", "soil_type"
]

missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f"Missing required columns: {missing}")

print("Original dataset shape:", df.shape)

# ------------------------------------------------------------
# 2. CLEAN TARGET DATA
# ------------------------------------------------------------
# Remove Coconut because its production units may be inconsistent.
# Keep Sugarcane records, but investigate extreme values separately.

df = df[
    ~df["Crop"].astype(str).str.strip().str.casefold().eq("coconut")
].copy()

for col in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].notna()
    & df["Production"].ge(0)
].copy()

# Historical target
df["yield_target"] = df["Production"] / df["Area"]

# Train on log-transformed yield
df["log_yield_target"] = np.log1p(df["yield_target"])

df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["log_yield_target"].notna()].copy()

print("Rows after target cleaning:", len(df))
print("Crop classes after cleaning:", df["Crop"].nunique())

# ------------------------------------------------------------
# 3. TIME-BASED SPLIT
# ------------------------------------------------------------
train_df = df[df["Crop_Year"].between(1997, 2012)].copy()
val_df = df[df["Crop_Year"].eq(2013)].copy()
test_df = df[df["Crop_Year"].eq(2014)].copy()

common_crops = (
    set(train_df["Crop"].dropna().unique())
    & set(val_df["Crop"].dropna().unique())
    & set(test_df["Crop"].dropna().unique())
)

train_df = train_df[train_df["Crop"].isin(common_crops)].copy()
val_df = val_df[val_df["Crop"].isin(common_crops)].copy()
test_df = test_df[test_df["Crop"].isin(common_crops)].copy()

if min(len(train_df), len(val_df), len(test_df)) == 0:
    raise ValueError(
        "A split is empty. Check the year coverage in your dataset."
    )

print("\nTIME-BASED SPLIT")
print("Train (1997-2012):", len(train_df))
print("Validation (2013):", len(val_df))
print("Test (2014):", len(test_df))
print("Common crops:", len(common_crops))

# ------------------------------------------------------------
# 4. MODEL INPUT FEATURES
# ------------------------------------------------------------
# Crop_Year is intentionally excluded in this first version.
# A Random Forest cannot reliably extrapolate a year trend to 2026.
# We will test it separately if needed.

categorical_features = [
    "State_Name",
    "District_Name",
    "Crop",
    "Season",
    "soil_type"
]

numerical_features = [
    "temperature",
    "humidity",
    "rainfall_mm"
]

features = categorical_features + numerical_features
target = "log_yield_target"

X_train = train_df[features].copy()
y_train = train_df[target].copy()

X_val = val_df[features].copy()
y_val = val_df[target].copy()

X_test = test_df[features].copy()
y_test = test_df[target].copy()

# ------------------------------------------------------------
# 5. PREPROCESSING
# ------------------------------------------------------------
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(
        handle_unknown="ignore",
        min_frequency=10
    ))
])

preprocessor = ColumnTransformer([
    ("categorical", categorical_pipeline, categorical_features),
    ("numerical", numeric_pipeline, numerical_features)
])

# ------------------------------------------------------------
# 6. TRAIN RANDOM FOREST
# ------------------------------------------------------------
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=200,
        min_samples_leaf=2,
        max_features=0.8,
        random_state=42,
        n_jobs=-1
    ))
])

print("\nTraining Random Forest...")
model.fit(X_train, y_train)
print("Training completed!")

# ------------------------------------------------------------
# 7. EVALUATION
# ------------------------------------------------------------
def evaluate(name, X, y):
    pred_log = model.predict(X)

    actual = np.expm1(y.to_numpy())
    predicted = np.maximum(0, np.expm1(pred_log))

    return {
        "Dataset": name,
        "Log_MAE": mean_absolute_error(y, pred_log),
        "Log_RMSE": np.sqrt(mean_squared_error(y, pred_log)),
        "Yield_MAE": mean_absolute_error(actual, predicted),
        "Yield_RMSE": np.sqrt(mean_squared_error(actual, predicted)),
        "Yield_Median_AE": median_absolute_error(actual, predicted),
        "Yield_R2": r2_score(actual, predicted)
    }, actual, predicted

val_metrics, _, _ = evaluate(
    "Validation_2013", X_val, y_val
)
test_metrics, actual_test, predicted_test = evaluate(
    "Test_2014", X_test, y_test
)

metrics = pd.DataFrame([val_metrics, test_metrics])

print("\nMODEL RESULTS")
print(metrics.round(4).to_string(index=False))

# ------------------------------------------------------------
# 8. SAVE MODEL, METRICS AND TEST PREDICTIONS
# ------------------------------------------------------------
MODEL_FILE = os.path.join(
    FOLDER, "cropsense_yield_random_forest.joblib"
)
METRICS_FILE = os.path.join(
    FOLDER, "cropsense_yield_metrics.csv"
)
PREDICTIONS_FILE = os.path.join(
    FOLDER, "cropsense_yield_test_predictions.csv"
)
INFO_FILE = os.path.join(
    FOLDER, "cropsense_yield_model_info.json"
)

joblib.dump(model, MODEL_FILE)
metrics.to_csv(METRICS_FILE, index=False)

predictions = test_df[
    ["State_Name", "District_Name", "Crop_Year", "Season", "Crop"]
].copy()

predictions["actual_yield_ratio"] = actual_test
predictions["predicted_yield_ratio"] = predicted_test
predictions.to_csv(PREDICTIONS_FILE, index=False)

info = {
    "model": "RandomForestRegressor",
    "features": features,
    "target": "log_yield_target",
    "training_years": "1997-2012",
    "validation_year": 2013,
    "test_year": 2014,
    "common_crop_count": int(len(common_crops)),
    "training_rows": int(len(train_df)),
    "validation_rows": int(len(val_df)),
    "test_rows": int(len(test_df)),
    "area_used_as_feature": False,
    "production_used_as_feature": False,
    "sklearn_version": sklearn.__version__
}

with open(INFO_FILE, "w") as f:
    json.dump(info, f, indent=2)

print("\nFILES SAVED TO GOOGLE DRIVE")
print(MODEL_FILE)
print(METRICS_FILE)
print(PREDICTIONS_FILE)
print(INFO_FILE)
print("\nTraining pipeline finished.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Original dataset shape: (246091, 11)
Rows after target cleaning: 240403
Crop classes after cleaning: 123

TIME-BASED SPLIT
Train (1997-2012): 212081
Validation (2013): 13277
Test (2014): 10615
Common crops: 69

Training Random Forest...
Training completed!

MODEL RESULTS
        Dataset  Log_MAE  Log_RMSE  Yield_MAE  Yield_RMSE  Yield_Median_AE    Yield_R2
Validation_2013   0.1687    0.3243    56.0021   1811.3792           0.2535 -19620.6028
      Test_2014   0.1652    0.3007    26.6709   1043.4311           0.2503  -6476.5573

FILES SAVED TO GOOGLE DRIVE
/content/drive/MyDrive/yield prediction/cropsense_yield_random_forest.joblib
/content/drive/MyDrive/yield prediction/cropsense_yield_metrics.csv
/content/drive/MyDrive/yield prediction/cropsense_yield_test_predictions.csv
/content/drive/MyDrive/yield prediction/cropsense_yield_model_info.json

Training pipeline finished.

In [ ]:

import numpy as np
import pandas as pd
from sklearn.metrics import r2_score, mean_absolute_error

# Actual and predicted yields on the original scale
actual = test_df["yield_target"].to_numpy()
predicted = np.maximum(
    0,
    np.expm1(model.predict(test_df[features]))
)

print("=" * 60)
print("TEST DATA: YIELD DISTRIBUTION")
print("=" * 60)

print("\nActual yield percentiles:")
print(pd.Series(actual).describe(
    percentiles=[0.50, 0.90, 0.95, 0.99, 0.999]
))

print("\nPredicted yield percentiles:")
print(pd.Series(predicted).describe(
    percentiles=[0.50, 0.90, 0.95, 0.99, 0.999]
))

print("\nLog-scale R²:", round(
    r2_score(
        test_df["log_yield_target"],
        model.predict(test_df[features])
    ), 4
))

# Identify the records with the largest actual yields
review = test_df[
    [
        "State_Name", "District_Name", "Crop_Year",
        "Season", "Crop", "Area", "Production",
        "yield_target"
    ]
].copy()

review["predicted_yield"] = predicted
review["absolute_error"] = np.abs(
    review["yield_target"] - review["predicted_yield"]
)

print("\nTOP 20 LARGEST ACTUAL YIELDS")
print(
    review.sort_values("yield_target", ascending=False)
    .head(20)
    .to_string(index=False)
)

print("\nTOP 20 LARGEST PREDICTION ERRORS")
print(
    review.sort_values("absolute_error", ascending=False)
    .head(20)
    .to_string(index=False)
)

# Save diagnostic records to Google Drive
output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "cropsense_yield_extreme_records_review.csv"
)

review.sort_values(
    "absolute_error", ascending=False
).to_csv(output_path, index=False)

print("\nDiagnostic review saved to:", output_path)

============================================================
TEST DATA: YIELD DISTRIBUTION
============================================================

Actual yield percentiles:
count    10615.000000
mean         5.088229
std         12.965181
min          0.000000
50%          1.125000
90%         12.301949
95%         21.859996
99%         73.192964
99.9%      113.007665
max        179.866515
dtype: float64

Predicted yield percentiles:
count    10615.000000
mean        30.029545
std       1044.847410
min          0.008046
50%          1.001998
90%         10.521366
95%         19.868796
99%         66.978421
99.9%      119.123111
max      58828.863047
dtype: float64

Log-scale R²: 0.8966

TOP 20 LARGEST ACTUAL YIELDS
    State_Name  District_Name  Crop_Year      Season      Crop     Area  Production  yield_target  predicted_yield  absolute_error
   West Bengal MEDINIPUR WEST       2014 Whole Year  Sugarcane   4390.0    789614.0    179.866515        85.930774       93.935741
   West Bengal        HOOGHLY       2014 Whole Year  Sugarcane    830.0    149289.0    179.866265        72.444819      107.421446
    Puducherry    PONDICHERRY       2014 Kharif      Sugarcane   1921.0    316965.0    165.000000       119.723530       45.276470
   West Bengal          NADIA       2014 Whole Year  Sugarcane   1754.0    248215.0    141.513683        71.176491       70.337192
     Karnataka      DAVANGERE       2014 Whole Year  Sugarcane   9523.0   1221325.0    128.250026       115.124557       13.125469
     Karnataka         MANDYA       2014 Whole Year  Sugarcane  21592.0   2543538.0    117.800019       111.919388        5.880630
Andhra Pradesh        KURNOOL       2014 Kharif      Sugarcane    714.0     83391.0    116.794118        92.037314       24.756804
    Telangana      RANGAREDDI       2014 Kharif          Onion     24.0      2740.0    114.166667        10.566380      103.600287
         Bihar          ARWAL       2014 Whole Year  Sugarcane     28.0      3172.0    113.285714        44.926419       68.359295
         Bihar      JEHANABAD       2014 Whole Year  Sugarcane     18.0      2039.0    113.277778        40.124429       73.153349
         Bihar         NAWADA       2014 Whole Year  Sugarcane     23.0      2605.0    113.260870        40.310867       72.950002
         Bihar     AURANGABAD       2014 Whole Year  Sugarcane    132.0     14896.0    112.848485        44.954588       67.893897
     Karnataka       BAGALKOT       2014 Whole Year  Sugarcane  93679.0  10234431.0    109.250003        90.422506       18.827497
     Karnataka         HASSAN       2014 Whole Year  Sugarcane   1568.0    171304.0    109.250000        99.910591        9.339409
   Maharashtra         SANGLI       2014 Whole Year  Sugarcane  74500.0   8107100.0    108.820134        92.689587       16.130547
   Maharashtra           PUNE       2014 Whole Year  Sugarcane 127800.0  13833900.0    108.246479        91.068298       17.178181
Andhra Pradesh         KADAPA       2014 Kharif         Papaya    789.0     84511.0    107.111534       103.750443        3.361091
Andhra Pradesh         KADAPA       2014 Rabi           Papaya    729.0     78084.0    107.111111        79.195251       27.915860
   West Bengal     JALPAIGURI       2014 Whole Year  Sugarcane    250.0     26754.0    107.016000        84.745773       22.270227
   West Bengal     COOCHBEHAR       2014 Whole Year  Sugarcane    455.0     48692.0    107.015385        88.658301       18.357084

TOP 20 LARGEST PREDICTION ERRORS
    State_Name  District_Name  Crop_Year      Season      Crop     Area  Production  yield_target  predicted_yield  absolute_error
        Punjab     HOSHIARPUR       2014 Whole Year  Sugarcane 22000.00   1515000.0     68.863636     58828.863047    58759.999411
        Punjab      JALANDHAR       2014 Whole Year  Sugarcane 11000.00    825000.0     75.000000     58788.214810    58713.214810
        Punjab    S.A.S NAGAR       2014 Whole Year  Sugarcane  1000.00     64000.0     64.000000     48383.257760    48319.257760
        Punjab      GURDASPUR       2014 Whole Year  Sugarcane 24000.00   1840000.0     76.666667     26468.735070    26392.068403
        Punjab       AMRITSAR       2014 Whole Year  Sugarcane  4000.00    301000.0     75.250000     25508.286240    25433.036240
        Punjab     NAWANSHAHR       2014 Whole Year  Sugarcane  6000.00    395000.0     65.833333     21283.508868    21217.675534
        Punjab       RUPNAGAR       2014 Whole Year  Sugarcane  3000.00    238000.0     79.333333     20805.945719    20726.612386
        Punjab      PATHANKOT       2014 Whole Year  Sugarcane  4000.00    253000.0     63.250000      9980.862532     9917.612532
        Punjab     KAPURTHALA       2014 Whole Year  Sugarcane  4000.00    312000.0     78.000000       862.385520      784.385520
   West Bengal        HOOGHLY       2014 Whole Year  Sugarcane   830.00    149289.0    179.866265        72.444819      107.421446
    Telangana      RANGAREDDI       2014 Kharif          Onion    24.00      2740.0    114.166667        10.566380      103.600287
   West Bengal MEDINIPUR WEST       2014 Whole Year  Sugarcane  4390.00    789614.0    179.866515        85.930774       93.935741
Andhra Pradesh       CHITTOOR       2014 Kharif         Papaya   519.00     13790.0     26.570328       107.477398       80.907071
         Bihar      JEHANABAD       2014 Whole Year  Sugarcane    18.00      2039.0    113.277778        40.124429       73.153349
         Bihar         NAWADA       2014 Whole Year  Sugarcane    23.00      2605.0    113.260870        40.310867       72.950002
   West Bengal          NADIA       2014 Whole Year  Sugarcane  1754.00    248215.0    141.513683        71.176491       70.337192
         Bihar          ARWAL       2014 Whole Year  Sugarcane    28.00      3172.0    113.285714        44.926419       68.359295
         Bihar     AURANGABAD       2014 Whole Year  Sugarcane   132.00     14896.0    112.848485        44.954588       67.893897
        Kerala         IDUKKI       2014 Whole Year  Sugarcane  1068.90     11512.0     10.769950        78.516072       67.746122
        Kerala         KANNUR       2014 Whole Year  Sugarcane     3.43        46.0     13.411079        78.712354       65.301275

Diagnostic review saved to: /content/drive/MyDrive/yield prediction/cropsense_yield_extreme_records_review.csv

In [ ]:

import numpy as np
import pandas as pd

# Inspect raw model predictions before converting out of log space
raw_log_predictions = model.predict(test_df[features])

check = test_df[
    [
        "State_Name", "District_Name", "Crop",
        "Season", "Area", "Production",
        "yield_target", "log_yield_target"
    ]
].copy()

check["predicted_log_yield"] = raw_log_predictions
check["predicted_yield"] = np.expm1(raw_log_predictions)

# Show the highest predicted values
print("TOP 20 PREDICTED YIELDS")
print(
    check.sort_values("predicted_yield", ascending=False)
    .head(20)
    .to_string(index=False)
)

print("\nPUNJAB SUGARCANE RECORDS")
print(
    check[
        check["State_Name"].astype(str).str.contains(
            "Punjab", case=False, na=False
        )
        & check["Crop"].astype(str).str.contains(
            "Sugarcane", case=False, na=False
        )
    ][
        [
            "District_Name", "Area", "Production",
            "yield_target", "log_yield_target",
            "predicted_log_yield", "predicted_yield"
        ]
    ].to_string(index=False)
)

print("\nLargest predicted log value:",
      check["predicted_log_yield"].max())
print("Largest actual log target:",
      check["log_yield_target"].max())

TOP 20 PREDICTED YIELDS
    State_Name  District_Name      Crop      Season    Area  Production  yield_target  log_yield_target  predicted_log_yield  predicted_yield
        Punjab     HOSHIARPUR Sugarcane Whole Year  22000.0   1515000.0     68.863636          4.246545            10.982405     58828.863047
        Punjab      JALANDHAR Sugarcane Whole Year  11000.0    825000.0     75.000000          4.330733            10.981714     58788.214810
        Punjab    S.A.S NAGAR Sugarcane Whole Year   1000.0     64000.0     64.000000          4.174387            10.786930     48383.257760
        Punjab      GURDASPUR Sugarcane Whole Year  24000.0   1840000.0     76.666667          4.352426            10.183757     26468.735070
        Punjab       AMRITSAR Sugarcane Whole Year   4000.0    301000.0     75.250000          4.334017            10.146798     25508.286240
        Punjab     NAWANSHAHR Sugarcane Whole Year   6000.0    395000.0     65.833333          4.202202             9.965735     21283.508868
        Punjab       RUPNAGAR Sugarcane Whole Year   3000.0    238000.0     79.333333          4.386185             9.943042     20805.945719
        Punjab      PATHANKOT Sugarcane Whole Year   4000.0    253000.0     63.250000          4.162782             9.208525      9980.862532
        Punjab     KAPURTHALA Sugarcane Whole Year   4000.0    312000.0     78.000000          4.369448             6.760861       862.385520
        Punjab        PATIALA Sugarcane Whole Year   3000.0    272000.0     90.666667          4.518159             4.850944       126.860985
    Puducherry    PONDICHERRY Sugarcane Kharif       1921.0    316965.0    165.000000          5.111988             4.793503       119.723530
     Karnataka        SHIMOGA Sugarcane Whole Year   3940.0    393015.0     99.750000          4.612642             4.785370       118.745648
Andhra Pradesh         GUNTUR    Papaya Kharif        176.0     13856.0     78.727273          4.378612             4.780765       118.195462
Andhra Pradesh        KRISHNA    Papaya Kharif        121.0      9526.0     78.727273          4.378612             4.767730       116.651916
     Karnataka      DAVANGERE Sugarcane Whole Year   9523.0   1221325.0    128.250026          4.861749             4.754663       115.124557
Andhra Pradesh  WEST GODAVARI    Papaya Kharif        229.0     18034.0     78.751092          4.378910             4.754427       115.097120
Andhra Pradesh  EAST GODAVARI    Papaya Kharif        305.0     24011.0     78.724590          4.378578             4.752972       114.928257
Andhra Pradesh VISAKHAPATANAM    Papaya Kharif         91.0      7164.0     78.725275          4.378587             4.749878       114.570210
Andhra Pradesh       PRAKASAM    Papaya Kharif        657.0     45451.0     69.179604          4.251058             4.731363       112.450086
     Karnataka         MANDYA Sugarcane Whole Year  21592.0   2543538.0    117.800019          4.777442             4.726674       111.919388

PUNJAB SUGARCANE RECORDS
  District_Name    Area  Production  yield_target  log_yield_target  predicted_log_yield  predicted_yield
       AMRITSAR  4000.0    301000.0     75.250000          4.334017            10.146798     25508.286240
        BARNALA  1000.0     87000.0     87.000000          4.477337             4.563550        94.923436
FATEHGARH SAHIB  3000.0    264000.0     88.000000          4.488636             4.413338        81.544535
      FIROZEPUR  2000.0    150000.0     75.000000          4.330733             4.146074        62.185461
      GURDASPUR 24000.0   1840000.0     76.666667          4.352426            10.183757     26468.735070
     HOSHIARPUR 22000.0   1515000.0     68.863636          4.246545            10.982405     58828.863047
      JALANDHAR 11000.0    825000.0     75.000000          4.330733            10.981714     58788.214810
     KAPURTHALA  4000.0    312000.0     78.000000          4.369448             6.760861       862.385520
       LUDHIANA  3000.0    258000.0     86.000000          4.465908             4.709315       109.976153
     NAWANSHAHR  6000.0    395000.0     65.833333          4.202202             9.965735     21283.508868
      PATHANKOT  4000.0    253000.0     63.250000          4.162782             9.208525      9980.862532
        PATIALA  3000.0    272000.0     90.666667          4.518159             4.850944       126.860985
       RUPNAGAR  3000.0    238000.0     79.333333          4.386185             9.943042     20805.945719
    S.A.S NAGAR  1000.0     64000.0     64.000000          4.174387            10.786930     48383.257760
        SANGRUR  3000.0    265000.0     88.333333          4.492375             4.325712        74.619372

Largest predicted log value: 10.982404879911966
Largest actual log target: 5.1977592719307415

In [ ]:

import numpy as np
import pandas as pd

# Inspect the fitted Random Forest directly
rf = model.named_steps["regressor"]
preprocessor = model.named_steps["preprocessor"]

print("Number of trees:", len(rf.estimators_))
print("Training target log range:",
      float(y_train.min()), "to", float(y_train.max()))

print("\nMaximum predicted log yield by Punjab Sugarcane district:")

raw = model.predict(test_df[features])
check = test_df[
    ["State_Name", "District_Name", "Crop", "Season", "yield_target"]
].copy()
check["predicted_log"] = raw

print(
    check[
        check["State_Name"].astype(str).str.casefold().eq("punjab")
        & check["Crop"].astype(str).str.casefold().eq("sugarcane")
    ].sort_values("predicted_log", ascending=False).to_string(index=False)
)

# Check predictions from individual trees for the most extreme row
idx = np.argmax(raw)
X_extreme = test_df.iloc[[idx]][features]
X_encoded = preprocessor.transform(X_extreme)

tree_predictions = np.array([
    tree.predict(X_encoded)[0] for tree in rf.estimators_
])

print("\nMost extreme test record:")
print(test_df.iloc[idx][
    ["State_Name", "District_Name", "Crop", "Season", "yield_target"]
])

print("Model predicted log yield:", raw[idx])
print("Individual tree prediction percentiles:",
      np.percentile(tree_predictions, [0, 25, 50, 75, 100]))

Number of trees: 200
Training target log range: 0.0 to 11.385103457032141

Maximum predicted log yield by Punjab Sugarcane district:
State_Name   District_Name      Crop      Season  yield_target  predicted_log
    Punjab      HOSHIARPUR Sugarcane Whole Year      68.863636      10.982405
    Punjab       JALANDHAR Sugarcane Whole Year      75.000000      10.981714
    Punjab     S.A.S NAGAR Sugarcane Whole Year      64.000000      10.786930
    Punjab       GURDASPUR Sugarcane Whole Year      76.666667      10.183757
    Punjab        AMRITSAR Sugarcane Whole Year      75.250000      10.146798
    Punjab      NAWANSHAHR Sugarcane Whole Year      65.833333       9.965735
    Punjab        RUPNAGAR Sugarcane Whole Year      79.333333       9.943042
    Punjab       PATHANKOT Sugarcane Whole Year      63.250000       9.208525
    Punjab      KAPURTHALA Sugarcane Whole Year      78.000000       6.760861
    Punjab         PATIALA Sugarcane Whole Year      90.666667       4.850944
    Punjab        LUDHIANA Sugarcane Whole Year      86.000000       4.709315
    Punjab         BARNALA Sugarcane Whole Year      87.000000       4.563550
    Punjab FATEHGARH SAHIB Sugarcane Whole Year      88.000000       4.413338
    Punjab         SANGRUR Sugarcane Whole Year      88.333333       4.325712
    Punjab       FIROZEPUR Sugarcane Whole Year      75.000000       4.146074

Most extreme test record:
State_Name            Punjab
District_Name     HOSHIARPUR
Crop               Sugarcane
Season           Whole Year
yield_target       68.863636
Name: 162557, dtype: object
Model predicted log yield: 10.982404879911966
Individual tree prediction percentiles: [ 4.08560323 11.11142063 11.15213253 11.19313683 11.30533671]

In [ ]:

# Investigate extreme yield ratios in the training data

import numpy as np
import pandas as pd

# Show the largest training targets
columns_to_show = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production",
    "yield_target", "log_yield_target"
]

print("=" * 70)
print("TOP 30 EXTREME TRAINING YIELDS")
print("=" * 70)

print(
    train_df.sort_values("yield_target", ascending=False)[columns_to_show]
    .head(30)
    .to_string(index=False)
)

# Count records above selected thresholds
print("\n" + "=" * 70)
print("EXTREME TARGET COUNTS")
print("=" * 70)

for threshold in [100, 500, 1000, 5000, 10000]:
    print(
        f"Yield ratio > {threshold}:",
        int((train_df["yield_target"] > threshold).sum())
    )

# Check whether Punjab Sugarcane exists in the training data
print("\n" + "=" * 70)
print("PUNJAB SUGARCANE IN TRAINING")
print("=" * 70)

mask = (
    train_df["State_Name"].astype(str).str.strip().str.casefold().eq("punjab")
    & train_df["Crop"].astype(str).str.strip().str.casefold().eq("sugarcane")
)

punjab_sugarcane = train_df.loc[mask, columns_to_show]

print("Matching records:", len(punjab_sugarcane))

if len(punjab_sugarcane):
    print(punjab_sugarcane.to_string(index=False))

# Save a review copy without changing the training data
output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "extreme_yield_training_review.csv"
)

train_df.sort_values(
    "yield_target", ascending=False
).head(500).to_csv(output_path, index=False)

print("\nSaved review file:", output_path)

======================================================================
TOP 30 EXTREME TRAINING YIELDS
======================================================================
 State_Name   District_Name  Crop_Year      Season      Crop    Area  Production  yield_target  log_yield_target
     Punjab         PATIALA       2011 Whole Year  Sugarcane     3.0    264000.0  88000.000000         11.385103
     Punjab         SANGRUR       2011 Whole Year  Sugarcane     2.0    163000.0  81500.000000         11.308371
     Punjab        LUDHIANA       2011 Whole Year  Sugarcane     2.0    161000.0  80500.000000         11.296025
     Punjab FATEHGARH SAHIB       2011 Whole Year  Sugarcane     2.0    151000.0  75500.000000         11.231901
     Punjab        RUPNAGAR       2011 Whole Year  Sugarcane     3.0    224000.0  74666.666667         11.220802
     Punjab       GURDASPUR       2011 Whole Year  Sugarcane    20.0   1491000.0  74550.000000         11.219239
     Punjab       PATHANKOT       2011 Whole Year  Sugarcane     4.0    298000.0  74500.000000         11.218568
     Punjab      KAPURTHALA       2011 Whole Year  Sugarcane     3.0    221000.0  73666.666667         11.207319
     Punjab         FAZILKA       2011 Whole Year  Sugarcane     1.0     73000.0  73000.000000         11.198228
     Punjab      NAWANSHAHR       2011 Whole Year  Sugarcane     6.0    407000.0  67833.333333         11.124824
     Punjab        AMRITSAR       2011 Whole Year  Sugarcane     3.0    203000.0  67666.666667         11.122364
     Punjab       JALANDHAR       2011 Whole Year  Sugarcane     9.0    599000.0  66555.555556         11.105807
     Punjab     S.A.S NAGAR       2011 Whole Year  Sugarcane     1.0     65000.0  65000.000000         11.082158
     Punjab      HOSHIARPUR       2011 Whole Year  Sugarcane    20.0   1293000.0  64650.000000         11.076759
     Punjab      TARN TARAN       2011 Whole Year  Sugarcane     1.0     40000.0  40000.000000         10.596660
 Tamil Nadu      PERAMBALUR       2008 Whole Year  Cashewnut     1.0      9801.0   9801.000000          9.190342
 Tamil Nadu         MADURAI       1997 Whole Year  Sugarcane  8108.0  18223000.0   2247.533300          7.718033
    Haryana          KARNAL       2008 Whole Year      Onion     2.0      4300.0   2150.000000          7.673688
 Tamil Nadu     THIRUVALLUR       1997 Whole Year  Sugarcane  5964.0  11811000.0   1980.382294          7.591550
Maharashtra          NASHIK       1997 Autumn          Maize     1.0      1494.0   1494.000000          7.309881
 Tamil Nadu     KANCHIPURAM       1997 Whole Year  Sugarcane  6735.0   9896000.0   1469.339272          7.293248
 Tamil Nadu        NAMAKKAL       1997 Whole Year  Sugarcane  9415.0  13608000.0   1445.353160          7.276801
 Tamil Nadu TIRUCHIRAPPALLI       1997 Whole Year  Sugarcane  4315.0   5806000.0   1345.538818          7.205293
Maharashtra         JALGAON       1997 Autumn          Maize     3.0      3980.0   1326.666667          7.191178
 Tamil Nadu       CUDDALORE       1997 Whole Year  Sugarcane 23826.0  28322000.0   1188.701419          7.081458
 Tamil Nadu           KARUR       1997 Whole Year  Sugarcane  5961.0   7081000.0   1187.887938          7.080774
 Tamil Nadu           SALEM       1997 Whole Year  Sugarcane 13759.0  15866000.0   1153.136129          7.051107
Maharashtra            PUNE       1997 Autumn          Maize     4.0      4570.0   1142.500000          7.041849
 Tamil Nadu      COIMBATORE       1997 Whole Year  Sugarcane 10756.0  12272000.0   1140.944589          7.040488
Maharashtra       OSMANABAD       1997 Autumn          Maize     5.0      5635.0   1127.000000          7.028201

======================================================================
EXTREME TARGET COUNTS
======================================================================
Yield ratio > 100: 596
Yield ratio > 500: 51
Yield ratio > 1000: 41
Yield ratio > 5000: 16
Yield ratio > 10000: 15

======================================================================
PUNJAB SUGARCANE IN TRAINING
======================================================================
Matching records: 185
State_Name   District_Name  Crop_Year      Season      Crop    Area  Production  yield_target  log_yield_target
    Punjab        AMRITSAR       1997 Whole Year  Sugarcane 11000.0    600000.0     54.545455          4.017202
    Punjab        AMRITSAR       1998 Whole Year  Sugarcane  9000.0    540000.0     60.000000          4.110874
    Punjab        AMRITSAR       1999 Whole Year  Sugarcane  8000.0    530000.0     66.250000          4.208417
    Punjab        AMRITSAR       2000 Whole Year  Sugarcane 11000.0    700000.0     63.636364          4.168777
    Punjab        AMRITSAR       2001 Whole Year  Sugarcane 11000.0    750000.0     68.181818          4.236738
    Punjab        AMRITSAR       2002 Whole Year  Sugarcane 11000.0    720000.0     65.454545          4.196518
    Punjab        AMRITSAR       2003 Whole Year  Sugarcane 10000.0    570000.0     57.000000          4.060443
    Punjab        AMRITSAR       2004 Whole Year  Sugarcane  7000.0    440000.0     62.857143          4.156648
    Punjab        AMRITSAR       2005 Whole Year  Sugarcane  6000.0    367000.0     61.166667          4.129819
    Punjab        AMRITSAR       2009 Whole Year  Sugarcane   300.0     18000.0     60.000000          4.110874
    Punjab        AMRITSAR       2011 Whole Year  Sugarcane     3.0    203000.0  67666.666667         11.122364
    Punjab        AMRITSAR       2012 Whole Year  Sugarcane  2000.0    141000.0     70.500000          4.269697
    Punjab        BATHINDA       2001 Whole Year  Sugarcane  1000.0     70000.0     70.000000          4.262680
    Punjab        BATHINDA       2002 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab        BATHINDA       2003 Whole Year  Sugarcane  1000.0     50000.0     50.000000          3.931826
    Punjab        FARIDKOT       1997 Whole Year  Sugarcane  2000.0    130000.0     65.000000          4.189655
    Punjab        FARIDKOT       1998 Whole Year  Sugarcane  2000.0    120000.0     60.000000          4.110874
    Punjab        FARIDKOT       1999 Whole Year  Sugarcane  2000.0    120000.0     60.000000          4.110874
    Punjab        FARIDKOT       2000 Whole Year  Sugarcane  2000.0    130000.0     65.000000          4.189655
    Punjab        FARIDKOT       2001 Whole Year  Sugarcane  4000.0    350000.0     87.500000          4.483003
    Punjab        FARIDKOT       2002 Whole Year  Sugarcane  5000.0    260000.0     52.000000          3.970292
    Punjab        FARIDKOT       2003 Whole Year  Sugarcane  3000.0    170000.0     56.666667          4.054679
    Punjab        FARIDKOT       2004 Whole Year  Sugarcane  1000.0     70000.0     70.000000          4.262680
    Punjab        FARIDKOT       2005 Whole Year  Sugarcane  1000.0     68000.0     68.000000          4.234107
    Punjab FATEHGARH SAHIB       1997 Whole Year  Sugarcane  6000.0    380000.0     63.333333          4.164078
    Punjab FATEHGARH SAHIB       1998 Whole Year  Sugarcane  4000.0    260000.0     65.000000          4.189655
    Punjab FATEHGARH SAHIB       1999 Whole Year  Sugarcane  4000.0    250000.0     62.500000          4.151040
    Punjab FATEHGARH SAHIB       2000 Whole Year  Sugarcane  4000.0    290000.0     72.500000          4.297285
    Punjab FATEHGARH SAHIB       2001 Whole Year  Sugarcane  5000.0    370000.0     74.000000          4.317488
    Punjab FATEHGARH SAHIB       2002 Whole Year  Sugarcane  5000.0    310000.0     62.000000          4.143135
    Punjab FATEHGARH SAHIB       2003 Whole Year  Sugarcane  4000.0    250000.0     62.500000          4.151040
    Punjab FATEHGARH SAHIB       2004 Whole Year  Sugarcane  2000.0    140000.0     70.000000          4.262680
    Punjab FATEHGARH SAHIB       2005 Whole Year  Sugarcane  2000.0    151000.0     75.500000          4.337291
    Punjab FATEHGARH SAHIB       2009 Whole Year  Sugarcane   200.0     15000.0     75.000000          4.330733
    Punjab FATEHGARH SAHIB       2011 Whole Year  Sugarcane     2.0    151000.0  75500.000000         11.231901
    Punjab FATEHGARH SAHIB       2012 Whole Year  Sugarcane  3000.0    258000.0     86.000000          4.465908
    Punjab         FAZILKA       2011 Whole Year  Sugarcane     1.0     73000.0  73000.000000         11.198228
    Punjab         FAZILKA       2012 Whole Year  Sugarcane  1000.0     82000.0     82.000000          4.418841
    Punjab       FIROZEPUR       1997 Whole Year  Sugarcane  8000.0    530000.0     66.250000          4.208417
    Punjab       FIROZEPUR       1998 Whole Year  Sugarcane  7000.0    460000.0     65.714286          4.200419
    Punjab       FIROZEPUR       1999 Whole Year  Sugarcane  8000.0    570000.0     71.250000          4.280132
    Punjab       FIROZEPUR       2000 Whole Year  Sugarcane  8000.0    530000.0     66.250000          4.208417
    Punjab       FIROZEPUR       2001 Whole Year  Sugarcane  9000.0    520000.0     57.777778          4.073764
    Punjab       FIROZEPUR       2002 Whole Year  Sugarcane  9000.0    460000.0     51.111111          3.953378
    Punjab       FIROZEPUR       2003 Whole Year  Sugarcane  6000.0    280000.0     46.666667          3.864232
    Punjab       FIROZEPUR       2004 Whole Year  Sugarcane  2000.0    140000.0     70.000000          4.262680
    Punjab       FIROZEPUR       2005 Whole Year  Sugarcane  1000.0     76000.0     76.000000          4.343805
    Punjab       FIROZEPUR       2009 Whole Year  Sugarcane   100.0      6000.0     60.000000          4.110874
    Punjab       FIROZEPUR       2012 Whole Year  Sugarcane  1000.0     67000.0     67.000000          4.219508
    Punjab       GURDASPUR       1997 Whole Year  Sugarcane 19000.0    980000.0     51.578947          3.962316
    Punjab       GURDASPUR       1998 Whole Year  Sugarcane 15000.0    840000.0     56.000000          4.043051
    Punjab       GURDASPUR       1999 Whole Year  Sugarcane 16000.0   1100000.0     68.750000          4.244917
    Punjab       GURDASPUR       2000 Whole Year  Sugarcane 18000.0   1220000.0     67.777778          4.230881
    Punjab       GURDASPUR       2001 Whole Year  Sugarcane 23000.0   1570000.0     68.260870          4.237880
    Punjab       GURDASPUR       2002 Whole Year  Sugarcane 25000.0   1700000.0     68.000000          4.234107
    Punjab       GURDASPUR       2003 Whole Year  Sugarcane 22000.0   1320000.0     60.000000          4.110874
    Punjab       GURDASPUR       2004 Whole Year  Sugarcane 20000.0   1310000.0     65.500000          4.197202
    Punjab       GURDASPUR       2005 Whole Year  Sugarcane 21000.0   1412000.0     67.238095          4.223003
    Punjab       GURDASPUR       2009 Whole Year  Sugarcane  1900.0    124000.0     65.263158          4.193634
    Punjab       GURDASPUR       2011 Whole Year  Sugarcane    20.0   1491000.0  74550.000000         11.219239
    Punjab       GURDASPUR       2012 Whole Year  Sugarcane 22000.0   1594000.0     72.454545          4.296667
    Punjab      HOSHIARPUR       1997 Whole Year  Sugarcane 13000.0    770000.0     59.230769          4.098183
    Punjab      HOSHIARPUR       1998 Whole Year  Sugarcane 13000.0    780000.0     60.000000          4.110874
    Punjab      HOSHIARPUR       1999 Whole Year  Sugarcane 15000.0    900000.0     60.000000          4.110874
    Punjab      HOSHIARPUR       2000 Whole Year  Sugarcane 17000.0   1020000.0     60.000000          4.110874
    Punjab      HOSHIARPUR       2001 Whole Year  Sugarcane 21000.0   1290000.0     61.428571          4.134023
    Punjab      HOSHIARPUR       2002 Whole Year  Sugarcane 25000.0   1310000.0     52.400000          3.977811
    Punjab      HOSHIARPUR       2003 Whole Year  Sugarcane 22000.0   1170000.0     53.181818          3.992345
    Punjab      HOSHIARPUR       2004 Whole Year  Sugarcane 18000.0   1030000.0     57.222222          4.064267
    Punjab      HOSHIARPUR       2005 Whole Year  Sugarcane 21000.0   1168000.0     55.619048          4.036345
    Punjab      HOSHIARPUR       2009 Whole Year  Sugarcane  1400.0     76000.0     54.285714          4.012515
    Punjab      HOSHIARPUR       2011 Whole Year  Sugarcane    20.0   1293000.0  64650.000000         11.076759
    Punjab      HOSHIARPUR       2012 Whole Year  Sugarcane 19000.0   1321000.0     69.526316          4.255986
    Punjab       JALANDHAR       1997 Whole Year  Sugarcane 14000.0    780000.0     55.714286          4.038026
    Punjab       JALANDHAR       1998 Whole Year  Sugarcane 13000.0    730000.0     56.153846          4.045747
    Punjab       JALANDHAR       1999 Whole Year  Sugarcane 14000.0    820000.0     58.571429          4.087176
    Punjab       JALANDHAR       2000 Whole Year  Sugarcane 15000.0    920000.0     61.333333          4.132496
    Punjab       JALANDHAR       2001 Whole Year  Sugarcane 16000.0   1000000.0     62.500000          4.151040
    Punjab       JALANDHAR       2002 Whole Year  Sugarcane 17000.0   1040000.0     61.176471          4.129977
    Punjab       JALANDHAR       2003 Whole Year  Sugarcane 15000.0    690000.0     46.000000          3.850148
    Punjab       JALANDHAR       2004 Whole Year  Sugarcane 11000.0    610000.0     55.454545          4.033436
    Punjab       JALANDHAR       2005 Whole Year  Sugarcane 11000.0    676000.0     61.454545          4.134439
    Punjab       JALANDHAR       2009 Whole Year  Sugarcane   700.0     42000.0     60.000000          4.110874
    Punjab       JALANDHAR       2011 Whole Year  Sugarcane     9.0    599000.0  66555.555556         11.105807
    Punjab       JALANDHAR       2012 Whole Year  Sugarcane 10000.0    651000.0     65.100000          4.191169
    Punjab      KAPURTHALA       1997 Whole Year  Sugarcane  5000.0    270000.0     54.000000          4.007333
    Punjab      KAPURTHALA       1998 Whole Year  Sugarcane  4000.0    240000.0     60.000000          4.110874
    Punjab      KAPURTHALA       1999 Whole Year  Sugarcane  4000.0    220000.0     55.000000          4.025352
    Punjab      KAPURTHALA       2000 Whole Year  Sugarcane  5000.0    330000.0     66.000000          4.204693
    Punjab      KAPURTHALA       2001 Whole Year  Sugarcane  6000.0    370000.0     61.666667          4.137830
    Punjab      KAPURTHALA       2002 Whole Year  Sugarcane  6000.0    350000.0     58.333333          4.083171
    Punjab      KAPURTHALA       2003 Whole Year  Sugarcane  6000.0    320000.0     53.333333          3.995138
    Punjab      KAPURTHALA       2004 Whole Year  Sugarcane  5000.0    300000.0     60.000000          4.110874
    Punjab      KAPURTHALA       2005 Whole Year  Sugarcane  4000.0    231000.0     57.750000          4.073291
    Punjab      KAPURTHALA       2009 Whole Year  Sugarcane   300.0     18000.0     60.000000          4.110874
    Punjab      KAPURTHALA       2011 Whole Year  Sugarcane     3.0    221000.0  73666.666667         11.207319
    Punjab      KAPURTHALA       2012 Whole Year  Sugarcane  4000.0    258000.0     64.500000          4.182050
    Punjab        LUDHIANA       1997 Whole Year  Sugarcane  8000.0    470000.0     58.750000          4.090169
    Punjab        LUDHIANA       1998 Whole Year  Sugarcane  5000.0    330000.0     66.000000          4.204693
    Punjab        LUDHIANA       1999 Whole Year  Sugarcane  6000.0    420000.0     70.000000          4.262680
    Punjab        LUDHIANA       2000 Whole Year  Sugarcane  7000.0    470000.0     67.142857          4.221606
    Punjab        LUDHIANA       2001 Whole Year  Sugarcane  8000.0    540000.0     67.500000          4.226834
    Punjab        LUDHIANA       2002 Whole Year  Sugarcane  8000.0    510000.0     63.750000          4.170534
    Punjab        LUDHIANA       2003 Whole Year  Sugarcane  5000.0    270000.0     54.000000          4.007333
    Punjab        LUDHIANA       2004 Whole Year  Sugarcane  3000.0    140000.0     46.666667          3.864232
    Punjab        LUDHIANA       2005 Whole Year  Sugarcane  2000.0    133000.0     66.500000          4.212128
    Punjab        LUDHIANA       2009 Whole Year  Sugarcane   100.0      6000.0     60.000000          4.110874
    Punjab        LUDHIANA       2011 Whole Year  Sugarcane     2.0    161000.0  80500.000000         11.296025
    Punjab        LUDHIANA       2012 Whole Year  Sugarcane  2000.0    136000.0     68.000000          4.234107
    Punjab           MANSA       1997 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab           MANSA       1998 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab           MANSA       1999 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab           MANSA       2000 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab           MANSA       2001 Whole Year  Sugarcane  1000.0     70000.0     70.000000          4.262680
    Punjab           MANSA       2002 Whole Year  Sugarcane  1000.0     50000.0     50.000000          3.931826
    Punjab            MOGA       1997 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab            MOGA       2000 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab            MOGA       2001 Whole Year  Sugarcane  2000.0    150000.0     75.000000          4.330733
    Punjab            MOGA       2002 Whole Year  Sugarcane  2000.0    100000.0     50.000000          3.931826
    Punjab            MOGA       2003 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab            MOGA       2004 Whole Year  Sugarcane  1000.0     60000.0     60.000000          4.110874
    Punjab         MUKTSAR       1997 Whole Year  Sugarcane  2000.0    110000.0     55.000000          4.025352
    Punjab         MUKTSAR       1998 Whole Year  Sugarcane  2000.0    130000.0     65.000000          4.189655
    Punjab         MUKTSAR       1999 Whole Year  Sugarcane  2000.0    130000.0     65.000000          4.189655
    Punjab         MUKTSAR       2000 Whole Year  Sugarcane  4000.0    290000.0     72.500000          4.297285
    Punjab         MUKTSAR       2001 Whole Year  Sugarcane  5000.0    380000.0     76.000000          4.343805
    Punjab         MUKTSAR       2002 Whole Year  Sugarcane  8000.0    500000.0     62.500000          4.151040
    Punjab         MUKTSAR       2003 Whole Year  Sugarcane  4000.0    210000.0     52.500000          3.979682
    Punjab         MUKTSAR       2004 Whole Year  Sugarcane  1000.0     50000.0     50.000000          3.931826
    Punjab         MUKTSAR       2005 Whole Year  Sugarcane  1000.0     51000.0     51.000000          3.951244
    Punjab      NAWANSHAHR       1997 Whole Year  Sugarcane 13000.0    730000.0     56.153846          4.045747
    Punjab      NAWANSHAHR       1998 Whole Year  Sugarcane 11000.0    630000.0     57.272727          4.065134
    Punjab      NAWANSHAHR       1999 Whole Year  Sugarcane 12000.0    700000.0     58.333333          4.083171
    Punjab      NAWANSHAHR       2000 Whole Year  Sugarcane 12000.0    760000.0     63.333333          4.164078
    Punjab      NAWANSHAHR       2001 Whole Year  Sugarcane 12000.0    720000.0     60.000000          4.110874
    Punjab      NAWANSHAHR       2002 Whole Year  Sugarcane 12000.0    640000.0     53.333333          3.995138
    Punjab      NAWANSHAHR       2003 Whole Year  Sugarcane 10000.0    470000.0     47.000000          3.871201
    Punjab      NAWANSHAHR       2004 Whole Year  Sugarcane  7000.0    380000.0     54.285714          4.012515
    Punjab      NAWANSHAHR       2005 Whole Year  Sugarcane  7000.0    380000.0     54.285714          4.012515
    Punjab      NAWANSHAHR       2009 Whole Year  Sugarcane   500.0     31000.0     62.000000          4.143135

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

raw_df = pd.read_csv(file_path)

# Select Punjab sugarcane records
mask = (
    raw_df["State_Name"].astype(str).str.strip().str.casefold().eq("punjab")
    & raw_df["Crop"].astype(str).str.strip().str.casefold().eq("sugarcane")
)

cols = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production"
]

punjab_sc = raw_df.loc[mask, cols].copy()

punjab_sc["Area"] = pd.to_numeric(punjab_sc["Area"], errors="coerce")
punjab_sc["Production"] = pd.to_numeric(
    punjab_sc["Production"], errors="coerce"
)

punjab_sc["yield_ratio"] = (
    punjab_sc["Production"] / punjab_sc["Area"].replace(0, np.nan)
)

print("Punjab sugarcane records by year:")
print(
    punjab_sc.groupby("Crop_Year").agg(
        records=("Crop", "size"),
        min_area=("Area", "min"),
        median_area=("Area", "median"),
        max_area=("Area", "max"),
        median_production=("Production", "median"),
        max_production=("Production", "max"),
        max_yield_ratio=("yield_ratio", "max")
    ).to_string()
)

print("\n2011 Punjab sugarcane records:")
print(
    punjab_sc[punjab_sc["Crop_Year"] == 2011]
    .sort_values("Area")[cols + ["yield_ratio"]]
    .to_string(index=False)
)

print("\nRecords with Area below 100:")
print(
    punjab_sc[punjab_sc["Area"] < 100]
    .sort_values(["Crop_Year", "Area"])
    .to_string(index=False)
)

Punjab sugarcane records by year:
           records  min_area  median_area  max_area  median_production  max_production  max_yield_ratio
Crop_Year
1997            16    1000.0       7500.0   19000.0           460000.0        980000.0        66.250000
1998            15    1000.0       5000.0   15000.0           330000.0        840000.0        66.000000
1999            15    1000.0       6000.0   16000.0           420000.0       1100000.0        71.250000
2000            16    1000.0       6000.0   18000.0           400000.0       1220000.0        73.333333
2001            17    1000.0       6000.0   23000.0           380000.0       1570000.0        87.500000
2002            17    1000.0       8000.0   25000.0           460000.0       1700000.0        70.000000
2003            16    1000.0       5500.0   22000.0           275000.0       1320000.0        66.666667
2004            15    1000.0       3000.0   20000.0           150000.0       1310000.0        75.000000
2005            14    1000.0       3000.0   21000.0           191000.0       1412000.0        76.000000
2009            13     100.0        200.0    1900.0            15000.0        124000.0        80.000000
2011            15       1.0          3.0      20.0           221000.0       1491000.0     88000.000000
2012            16    1000.0       2500.0   22000.0           205500.0       1594000.0        92.000000
2013            16    1000.0       3000.0   21000.0           253500.0       1560000.0        93.666667
2014            15    1000.0       3000.0   24000.0           265000.0       1840000.0        90.666667

2011 Punjab sugarcane records:
State_Name   District_Name  Crop_Year      Season      Crop  Area  Production  yield_ratio
    Punjab         FAZILKA       2011 Whole Year  Sugarcane   1.0     73000.0 73000.000000
    Punjab      TARN TARAN       2011 Whole Year  Sugarcane   1.0     40000.0 40000.000000
    Punjab     S.A.S NAGAR       2011 Whole Year  Sugarcane   1.0     65000.0 65000.000000
    Punjab FATEHGARH SAHIB       2011 Whole Year  Sugarcane   2.0    151000.0 75500.000000
    Punjab        LUDHIANA       2011 Whole Year  Sugarcane   2.0    161000.0 80500.000000
    Punjab         SANGRUR       2011 Whole Year  Sugarcane   2.0    163000.0 81500.000000
    Punjab      KAPURTHALA       2011 Whole Year  Sugarcane   3.0    221000.0 73666.666667
    Punjab        AMRITSAR       2011 Whole Year  Sugarcane   3.0    203000.0 67666.666667
    Punjab         PATIALA       2011 Whole Year  Sugarcane   3.0    264000.0 88000.000000
    Punjab        RUPNAGAR       2011 Whole Year  Sugarcane   3.0    224000.0 74666.666667
    Punjab       PATHANKOT       2011 Whole Year  Sugarcane   4.0    298000.0 74500.000000
    Punjab      NAWANSHAHR       2011 Whole Year  Sugarcane   6.0    407000.0 67833.333333
    Punjab       JALANDHAR       2011 Whole Year  Sugarcane   9.0    599000.0 66555.555556
    Punjab       GURDASPUR       2011 Whole Year  Sugarcane  20.0   1491000.0 74550.000000
    Punjab      HOSHIARPUR       2011 Whole Year  Sugarcane  20.0   1293000.0 64650.000000

Records with Area below 100:
State_Name   District_Name  Crop_Year      Season      Crop  Area  Production  yield_ratio
    Punjab         FAZILKA       2011 Whole Year  Sugarcane   1.0     73000.0 73000.000000
    Punjab     S.A.S NAGAR       2011 Whole Year  Sugarcane   1.0     65000.0 65000.000000
    Punjab      TARN TARAN       2011 Whole Year  Sugarcane   1.0     40000.0 40000.000000
    Punjab FATEHGARH SAHIB       2011 Whole Year  Sugarcane   2.0    151000.0 75500.000000
    Punjab        LUDHIANA       2011 Whole Year  Sugarcane   2.0    161000.0 80500.000000
    Punjab         SANGRUR       2011 Whole Year  Sugarcane   2.0    163000.0 81500.000000
    Punjab        AMRITSAR       2011 Whole Year  Sugarcane   3.0    203000.0 67666.666667
    Punjab      KAPURTHALA       2011 Whole Year  Sugarcane   3.0    221000.0 73666.666667
    Punjab         PATIALA       2011 Whole Year  Sugarcane   3.0    264000.0 88000.000000
    Punjab        RUPNAGAR       2011 Whole Year  Sugarcane   3.0    224000.0 74666.666667
    Punjab       PATHANKOT       2011 Whole Year  Sugarcane   4.0    298000.0 74500.000000
    Punjab      NAWANSHAHR       2011 Whole Year  Sugarcane   6.0    407000.0 67833.333333
    Punjab       JALANDHAR       2011 Whole Year  Sugarcane   9.0    599000.0 66555.555556
    Punjab       GURDASPUR       2011 Whole Year  Sugarcane  20.0   1491000.0 74550.000000
    Punjab      HOSHIARPUR       2011 Whole Year  Sugarcane  20.0   1293000.0 64650.000000

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path)

df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(df["Production"], errors="coerce")

# Examine all 2011 records with suspiciously small area
suspect = df[
    (df["Crop_Year"] == 2011)
    & (df["Area"] > 0)
    & (df["Area"] < 100)
    & (df["Production"] > 0)
].copy()

suspect["yield_ratio"] = suspect["Production"] / suspect["Area"]

print("Total suspicious 2011 records:", len(suspect))

print("\nCounts by state and crop:")
print(
    suspect.groupby(["State_Name", "Crop"])
    .size()
    .sort_values(ascending=False)
    .to_string()
)

print("\nTop 50 suspicious records:")
cols = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production", "yield_ratio"
]

print(
    suspect.sort_values("yield_ratio", ascending=False)[cols]
    .head(50)
    .to_string(index=False)
)

output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "suspicious_area_records_2011.csv"
)
suspect.to_csv(output_path, index=False)
print("\nSaved:", output_path)

Total suspicious 2011 records: 3754

Counts by state and crop:
State_Name              Crop
Uttar Pradesh           Maize                      70
                        Onion                      70
                        Moong(Green Gram)          64
                        Guar seed                  59
                        Coriander                  49
                        Sweet potato               44
                        Dry chillies               40
Odisha                  Maize                      38
Uttar Pradesh           Garlic                     37
Karnataka               Peas & beans (Pulses)      36
Uttar Pradesh           Urad                       33
Karnataka               Dry chillies               32
Madhya Pradesh          Sannhamp                   32
Odisha                  Sesamum                    31
                        Urad                       30
Madhya Pradesh          Turmeric                   30
Tamil Nadu              Ragi                       30
Uttar Pradesh           Sunflower                  30
Madhya Pradesh          Moong(Green Gram)          29
                        Sweet potato               28
Odisha                  Groundnut                  28
Chhattisgarh            Moong(Green Gram)          28
Uttar Pradesh           Turmeric                   27
                        Linseed                    25
Madhya Pradesh          Dry ginger                 24
Karnataka               Onion                      23
Assam                   Tobacco                    23
Chhattisgarh            Banana                     22
Odisha                  Moong(Green Gram)          22
Assam                   Castor seed                21
                        Cotton(lint)               21
Madhya Pradesh          Garlic                     21
Odisha                  Wheat                      21
Tamil Nadu              Sweet potato               21
Uttar Pradesh           Sannhamp                   20
Tamil Nadu              Bajra                      20
Bihar                   Sesamum                    20
Chhattisgarh            Potato                     20
Bihar                   Moong(Green Gram)          20
Uttar Pradesh           Banana                     20
Karnataka               Potato                     19
Uttar Pradesh           Groundnut                  19
Assam                   Gram                       19
Uttar Pradesh           Sesamum                    18
                        Gram                       18
Karnataka               Sunflower                  18
Uttar Pradesh           Small millets              18
Assam                   Tapioca                    18
Chhattisgarh            Sweet potato               18
Bihar                   Sunflower                  18
Karnataka               Urad                       18
Chhattisgarh            Sannhamp                   17
Uttar Pradesh           Rice                       17
Assam                   Black pepper               17
Chhattisgarh            Sugarcane                  17
Odisha                  Ragi                       17
Chhattisgarh            Sunflower                  17
Madhya Pradesh          Sugarcane                  16
                        Linseed                    16
                        Other  Rabi pulses         16
Bihar                   Barley                     16
Chhattisgarh            Turmeric                   16
Tamil Nadu              Arecanut                   16
Odisha                  Sugarcane                  15
Tamil Nadu              Castor seed                15
Karnataka               Turmeric                   15
Madhya Pradesh          Other Kharif pulses        15
Punjab                  Sugarcane                  15
West Bengal             Moong(Green Gram)          15
Tamil Nadu              Coriander                  14
                        Jowar                      14
Chhattisgarh            Dry ginger                 14
Karnataka               Moong(Green Gram)          14
Uttar Pradesh           Tobacco                    14
Madhya Pradesh          Barley                     14
Tamil Nadu              Turmeric                   13
West Bengal             Sesamum                    13
Bihar                   Rice                       13
Chhattisgarh            Garlic                     13
Assam                   Mesta                      13
Chhattisgarh            Coriander                  13
Bihar                   Maize                      13
                        Gram                       13
Uttar Pradesh           Jowar                      13
Kerala                  Potato                     13
Chhattisgarh            Soyabean                   13
Madhya Pradesh          Bajra                      13
Karnataka               Coriander                  12
Odisha                  Potato                     12
Chhattisgarh            Other  Rabi pulses         12
Bihar                   Linseed                    12
West Bengal             Groundnut                  12
Uttar Pradesh           Barley                     12
                        Dry ginger                 12
Karnataka               Cowpea(Lobia)              12
Tamil Nadu              Sunflower                  12
Bihar                   Urad                       12
Chhattisgarh            Mesta                      12
Nagaland                Barley                     11
                        Horse-gram                 11
Bihar                   Ragi                       11
Chhattisgarh            Horse-gram                 11
Tamil Nadu              Horse-gram                 11
Assam                   Orange                     11
Madhya Pradesh          Khesari                    11
                        Dry chillies               11
Uttar Pradesh           Bajra                      11
Karnataka               Ragi                       11
                        Rapeseed &Mustard          11
Bihar                   Other  Rabi pulses         11
Madhya Pradesh          Mesta                      11
Nagaland                Bajra                      11
Uttar Pradesh           Peas & beans (Pulses)      11
Madhya Pradesh          Banana                     10
                        Coriander                  10
Karnataka               Sweet potato               10
Madhya Pradesh          Potato                     10
Bihar                   Other Kharif pulses        10
Karnataka               Cashewnut                  10
Chhattisgarh            Safflower                  10
Assam                   Maize                      10
Karnataka               Maize                      10
Assam                   Small millets              10
                        Jute                       10
Andhra Pradesh          Sweet potato               10
Tamil Nadu              Cashewnut                  10
                        Gram                       10
                        Cotton(lint)               10
Nagaland                Gram                       10
Madhya Pradesh          Jowar                      10
                        Groundnut                  10
Tamil Nadu              Maize                       9
Assam                   Arhar/Tur                   9
Madhya Pradesh          Castor seed                 9
Nagaland                Castor seed                 9
Arunachal Pradesh       Dry chillies                9
Madhya Pradesh          Urad                        9
Karnataka               Garlic                      9
Chhattisgarh            Urad                        9
Odisha                  Rapeseed &Mustard           9
Tamil Nadu              Onion                       9
Nagaland                Blackgram                   9
Uttarakhand             Gram                        9
                        Sesamum                     9
Karnataka               Small millets               9
West Bengal             Sunflower                   9
Karnataka               Jowar                       9
Assam                   Linseed                     9
                        Onion                       9
                        Niger seed                  9
Uttar Pradesh           Masoor                      9
Chhattisgarh            Jowar                       9
Karnataka               Other  Rabi pulses          9
Madhya Pradesh          Rapeseed &Mustard           8
Nagaland                Groundnut                   8
Tamil Nadu              Arhar/Tur                   8
Bihar                   Mesta                       8
                        Peas & beans (Pulses)       8
Assam                   Sweet potato                8
Bihar                   Arhar/Tur                   8
Andhra Pradesh          Arhar/Tur                   8
West Bengal             Arhar/Tur                   8
Andhra Pradesh          Cowpea(Lobia)               8
Uttarakhand             Turmeric                    8
Uttar Pradesh           Cotton(lint)                8
Haryana                 Onion                       8
Andhra Pradesh          Jowar                       8
Karnataka               Dry ginger                  8
Assam                   Wheat                       8
                        Sesamum                     8
Nagaland                Ragi                        7
Karnataka               Rice                        7
West Bengal             Maize                       7
Uttarakhand             Peas & beans (Pulses)       7
Madhya Pradesh          Sesamum                     7
Uttar Pradesh           Arhar/Tur                   7
Tamil Nadu              Small millets               7
Assam                   Masoor                      7
Chhattisgarh            Groundnut                   7
Karnataka               Castor seed                 7
Chhattisgarh            Dry chillies                7
Tamil Nadu              Dry ginger                  7
Karnataka               Horse-gram                  7
Chhattisgarh            Onion                       7
Kerala                  Sesamum                     7
Nagaland                Urad                        7
Tamil Nadu              Rapeseed &Mustard           7
Kerala                  Dry ginger                  7
Karnataka               Tapioca                     7
Tamil Nadu              Tobacco                     7
Chhattisgarh            Ragi                        6
Nagaland                Sunflower                   6
Andhra Pradesh          Onion                       6
Karnataka               Groundnut                   6
Bihar                   Tobacco                     6
Chhattisgarh            Castor seed                 6
Bihar                   Groundnut                   6
                        Jute                        6
Chhattisgarh            Barley                      6
Kerala                  Turmeric                    6
Tripura                 Groundnut                   6
Karnataka               Black pepper                6
Tamil Nadu              Tapioca                     6
Karnataka               Tobacco                     6
Arunachal Pradesh       Dry ginger                  6
                        Turmeric                    6
West Bengal             Gram                        6
Uttarakhand             Potato                      6
                        Garlic                      6
West Bengal             Barley                      6
                        Linseed                     6
                        Horse-gram                  6
Uttarakhand             Onion                       6
                        Ginger                      6
West Bengal             Sugarcane                   6
                        Safflower                   6
                        Sannhamp                    5
Uttarakhand             Arhar/Tur                   5
Madhya Pradesh          Horse-gram                  5
Uttarakhand             Other Cereals & Millets     5
Karnataka               Sesamum                     5
Madhya Pradesh          Masoor                      5
Meghalaya               Sugarcane                   5
Madhya Pradesh          Cotton(lint)                5
Andhra Pradesh          other oilseeds              5
Madhya Pradesh          Peas & beans (Pulses)       5
Karnataka               Cotton(lint)                5
Tripura                 Moong(Green Gram)           5
Andhra Pradesh          Bajra                       5
Chhattisgarh            Bajra                       5
Bihar                   Safflower                   5
Assam                   Moong(Green Gram)           5
Chhattisgarh            Masoor                      5
Telangana               Bajra                       5
Kerala                  Sugarcane                   5
Madhya Pradesh          Tobacco                     5
Bihar                   Bajra                       5
                        Horse-gram                  5
                        Jowar                       5
Assam                   Pineapple                   5
Odisha                  Horse-gram                  5
Nagaland                Jowar                       5
Andhra Pradesh          Ragi                        5
Tamil Nadu              Black pepper                5
West Bengal             Urad                        5
Meghalaya               Rice                        4
                        Peas & beans (Pulses)       4
                        Other  Rabi pulses          4
Andhra Pradesh          Sesamum                     4
Arunachal Pradesh       Sugarcane                   4
Chhattisgarh            Tobacco                     4
Meghalaya               Turmeric                    4
Haryana                 Potato                      4
Madhya Pradesh          Safflower                   4
                        Small millets               4
                        Niger seed                  4
Karnataka               Other Kharif pulses         4
                        Niger seed                  4
                        Safflower                   4
                        Sugarcane                   4
Uttar Pradesh           Soyabean                    4
Andhra Pradesh          Horse-gram                  4
Uttarakhand             Groundnut                   4
                        Maize                       4
                        Sunflower                   4
West Bengal             Masoor                      4
Andhra Pradesh          Dry ginger                  4
                        Dry chillies                4
                        Tapioca                     4
Tamil Nadu              Moong(Green Gram)           4
                        Dry chillies                4
Puducherry              Urad                        4
Nagaland                Sweet potato                4
                        Mesta                       4
Assam                   Sugarcane                   4
Bihar                   Small millets               4
Puducherry              Brinjal                     4
                        Groundnut                   4
Tamil Nadu              Potato                      4
Chhattisgarh            Sesamum                     4
Kerala                  Rice                        4
Tripura                 Gram                        4
Telangana               Coconut                     4
Chhattisgarh            Niger seed                  4
Assam                   Papaya                      4
Bihar                   Khesari                     4
Karnataka               Mesta                       4
                        Gram                        4
Chhattisgarh            Small millets               4
Tripura                 Wheat                       4
Andhra Pradesh          Castor seed                 3
West Bengal             Other Kharif pulses         3
                        Peas & beans (Pulses)       3
Andhra Pradesh          Gram                        3
West Bengal             Mesta                       3
                        Khesari                     3
                        Niger seed                  3
Uttarakhand             Tobacco                     3
                        Urad                        3
                        other oilseeds              3
Karnataka               Bajra                       3
Madhya Pradesh          Onion                       3
                        Sunflower                   3
Meghalaya               Rapeseed &Mustard           3
Arunachal Pradesh       Wheat                       3
Assam                   Coconut                     3
Meghalaya               Sesamum                     3
                        Masoor                      3
                        Black pepper                3
Telangana               Sweet potato                3
Meghalaya               Dry chillies                3
Telangana               Arhar/Tur                   3
                        Onion                       3
                        Coriander                   3
                        Horse-gram                  3
                        Soyabean                    3
Chhattisgarh            Cotton(lint)                3
                        Gram                        3
Karnataka               Linseed                     3
Meghalaya               Castor seed                 3
Tamil Nadu              Groundnut                   3
Assam                   Rice                        3
Bihar                   Castor seed                 3
Assam                   Paddy                       3
Puducherry              Sesamum                     3
                        Moong(Green Gram)           3
                        Mango                       3
Tamil Nadu              Cardamom                    3
Andhra Pradesh          Sunflower                   3
                        Soyabean                    3
                        Small millets               3
                        Potato                      3
                        Other Kharif pulses         2
                        Other  Rabi pulses          2
Uttarakhand             Soyabean                    2
                        Other  Rabi pulses          2
Andhra Pradesh          Rapeseed &Mustard           2
                        Tobacco                     2
                        Wheat                       2
Arunachal Pradesh       Oilseeds total              2
                        Potato                      2
Puducherry              Cashewnut                   2
Telangana               Banana                      2
Puducherry              Other Kharif pulses         2
                        Tapioca                     2
                        Turmeric                    2
Tamil Nadu              Garlic                      2
Puducherry              Ragi                        2
West Bengal             Other  Rabi pulses          2
                        Cotton(lint)                2
Chhattisgarh            Rapeseed &Mustard           2
                        Wheat                       2
Dadra and Nagar Haveli  Maize                       2
Uttarakhand             Barley                      2
Chhattisgarh            Khesari                     2
Karnataka               Coconut                     2
                        Banana                      2
                        Arecanut                    2
Haryana                 Arhar/Tur                   2
Puducherry              Cotton(lint)                2
                        Dry chillies                2
                        Banana                      2
                        Bajra                       2
Odisha                  Niger seed                  2
                        Jute                        2
Nagaland                Tapioca                     2
Karnataka               Sannhamp                    2
Meghalaya               Soyabean                    2

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path)

df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(df["Production"], errors="coerce")
df["Crop_Year"] = pd.to_numeric(df["Crop_Year"], errors="coerce")

df = df[
    (df["Area"] > 0)
    & (df["Production"] > 0)
].copy()

df["yield_ratio"] = df["Production"] / df["Area"]

# 1. Count extreme ratios across the full dataset
print("=" * 70)
print("EXTREME YIELD RATIOS ACROSS ALL YEARS")
print("=" * 70)

for threshold in [100, 500, 1000, 5000, 10000]:
    count = (df["yield_ratio"] > threshold).sum()
    print(f"Yield ratio > {threshold:>5}: {count:,}")

# 2. Crops contributing most to extreme ratios
extreme = df[df["yield_ratio"] > 500].copy()

print("\n" + "=" * 70)
print("CROPS WITH MOST RATIOS ABOVE 500")
print("=" * 70)

print(
    extreme.groupby("Crop").agg(
        extreme_records=("yield_ratio", "size"),
        max_ratio=("yield_ratio", "max"),
        median_ratio=("yield_ratio", "median"),
        first_year=("Crop_Year", "min"),
        last_year=("Crop_Year", "max")
    )
    .sort_values("extreme_records", ascending=False)
    .head(30)
    .to_string()
)

# 3. Check year-wise patterns for the most extreme crops
print("\n" + "=" * 70)
print("YEAR-WISE DETAILS FOR EXTREME RECORDS")
print("=" * 70)

print(
    extreme.groupby(["Crop", "Crop_Year"]).agg(
        records=("yield_ratio", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        max_ratio=("yield_ratio", "max")
    )
    .sort_values("max_ratio", ascending=False)
    .head(50)
    .to_string()
)

# Save the complete extreme-record review
output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "extreme_yield_ratios_full_dataset.csv"
)

extreme.sort_values(
    "yield_ratio", ascending=False
).to_csv(output_path, index=False)

print("\nSaved:", output_path)

======================================================================
EXTREME YIELD RATIOS ACROSS ALL YEARS
======================================================================
Yield ratio >   100: 1,628
Yield ratio >   500: 983
Yield ratio >  1000: 969
Yield ratio >  5000: 761
Yield ratio > 10000: 287

======================================================================
CROPS WITH MOST RATIOS ABOVE 500
======================================================================
           extreme_records  max_ratio  median_ratio  first_year  last_year
Crop
Coconut                932    38800.0   7701.895623        1998       2014
Sugarcane               43    88000.0   1187.887938        1997       2011
Maize                    6     1494.0   1134.750000        1997       1997
Cashewnut                1     9801.0   9801.000000        2008       2008
Onion                    1     2150.0   2150.000000        2008       2008

======================================================================
YEAR-WISE DETAILS FOR EXTREME RECORDS
======================================================================
                     records  median_area  median_production     max_ratio
Crop      Crop_Year
Sugarcane 2011            15        3.000           221000.0  88000.000000
Coconut   2006            82     1087.500         10730757.5  38800.000000
          2014            30    14807.000        116000000.0  33089.005477
          2004            63     1131.000         11482486.0  28334.155972
          2001            61     1130.000          8218000.0  26270.833333
          2011            67     7466.000         79600000.0  24414.676071
          2007            65      999.000         10750000.0  21954.616588
          2012            30    14927.000        104919000.0  21285.001040
          2008            62      924.500          7223780.0  21082.308420
          2013            61     9200.000         70000000.0  21021.025521
          2009            62      925.000          8169312.0  18829.769033
          2000            62     1099.500          7197000.0  18000.000000
          2003            60     1159.000         10045500.0  16906.298003
          1999            41     1183.000          6293000.0  16500.000000
          2005            40     9102.725         45015000.0  16500.000000
          2010            48     1116.000          9672500.0  15584.976526
          2002            61     1083.000          8101000.0  14432.862191
          1998            37     1360.000          9382000.0   9908.819431
Cashewnut 2008             1        1.000             9801.0   9801.000000
Sugarcane 1997            28     6780.500          9898000.0   2247.533300
Onion     2008             1        2.000             4300.0   2150.000000
Maize     1997             6        3.500             3440.5   1494.000000

Saved: /content/drive/MyDrive/yield prediction/extreme_yield_ratios_full_dataset.csv

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path)

df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(df["Production"], errors="coerce")

df = df[
    (df["Area"] > 0)
    & (df["Production"] > 0)
].copy()

df["yield_ratio"] = df["Production"] / df["Area"]

# Exclude coconut only from this review, not by modifying the source file
review = df[
    (df["yield_ratio"] > 500)
    & (~df["Crop"].astype(str).str.strip().str.casefold().eq("coconut"))
].copy()

cols = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production", "yield_ratio"
]

print("Extreme non-coconut records:", len(review))
print("\nCounts by crop:")
print(review.groupby("Crop").size().sort_values(ascending=False))

print("\nAll extreme sugarcane records:")
print(
    review[review["Crop"].astype(str).str.strip().str.casefold().eq("sugarcane")]
    .sort_values("yield_ratio", ascending=False)[cols]
    .to_string(index=False)
)

output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "extreme_non_coconut_yield_review.csv"
)

review.sort_values("yield_ratio", ascending=False).to_csv(
    output_path, index=False
)

print("\nSaved review file:", output_path)

Extreme non-coconut records: 51

Counts by crop:
Crop
Sugarcane    43
Maize         6
Cashewnut     1
Onion         1
dtype: int64

All extreme sugarcane records:
State_Name   District_Name  Crop_Year      Season      Crop    Area  Production  yield_ratio
    Punjab         PATIALA       2011 Whole Year  Sugarcane     3.0    264000.0 88000.000000
    Punjab         SANGRUR       2011 Whole Year  Sugarcane     2.0    163000.0 81500.000000
    Punjab        LUDHIANA       2011 Whole Year  Sugarcane     2.0    161000.0 80500.000000
    Punjab FATEHGARH SAHIB       2011 Whole Year  Sugarcane     2.0    151000.0 75500.000000
    Punjab        RUPNAGAR       2011 Whole Year  Sugarcane     3.0    224000.0 74666.666667
    Punjab       GURDASPUR       2011 Whole Year  Sugarcane    20.0   1491000.0 74550.000000
    Punjab       PATHANKOT       2011 Whole Year  Sugarcane     4.0    298000.0 74500.000000
    Punjab      KAPURTHALA       2011 Whole Year  Sugarcane     3.0    221000.0 73666.666667
    Punjab         FAZILKA       2011 Whole Year  Sugarcane     1.0     73000.0 73000.000000
    Punjab      NAWANSHAHR       2011 Whole Year  Sugarcane     6.0    407000.0 67833.333333
    Punjab        AMRITSAR       2011 Whole Year  Sugarcane     3.0    203000.0 67666.666667
    Punjab       JALANDHAR       2011 Whole Year  Sugarcane     9.0    599000.0 66555.555556
    Punjab     S.A.S NAGAR       2011 Whole Year  Sugarcane     1.0     65000.0 65000.000000
    Punjab      HOSHIARPUR       2011 Whole Year  Sugarcane    20.0   1293000.0 64650.000000
    Punjab      TARN TARAN       2011 Whole Year  Sugarcane     1.0     40000.0 40000.000000
Tamil Nadu         MADURAI       1997 Whole Year  Sugarcane  8108.0  18223000.0  2247.533300
Tamil Nadu     THIRUVALLUR       1997 Whole Year  Sugarcane  5964.0  11811000.0  1980.382294
Tamil Nadu     KANCHIPURAM       1997 Whole Year  Sugarcane  6735.0   9896000.0  1469.339272
Tamil Nadu        NAMAKKAL       1997 Whole Year  Sugarcane  9415.0  13608000.0  1445.353160
Tamil Nadu TIRUCHIRAPPALLI       1997 Whole Year  Sugarcane  4315.0   5806000.0  1345.538818
Tamil Nadu       CUDDALORE       1997 Whole Year  Sugarcane 23826.0  28322000.0  1188.701419
Tamil Nadu           KARUR       1997 Whole Year  Sugarcane  5961.0   7081000.0  1187.887938
Tamil Nadu           SALEM       1997 Whole Year  Sugarcane 13759.0  15866000.0  1153.136129
Tamil Nadu      COIMBATORE       1997 Whole Year  Sugarcane 10756.0  12272000.0  1140.944589
Tamil Nadu      VILLUPURAM       1997 Whole Year  Sugarcane 33175.0  37158000.0  1120.060286
Tamil Nadu           ERODE       1997 Whole Year  Sugarcane 24112.0  26930000.0  1116.871267
Tamil Nadu           THENI       1997 Whole Year  Sugarcane  9524.0  10598000.0  1112.767745
Tamil Nadu    THE NILGIRIS       1997 Whole Year  Sugarcane    22.0     24000.0  1090.909091
Tamil Nadu       TUTICORIN       1997 Whole Year  Sugarcane    90.0     97000.0  1077.777778
Tamil Nadu     TIRUNELVELI       1997 Whole Year  Sugarcane  2237.0   2402000.0  1073.759499
Tamil Nadu    NAGAPATTINAM       1997 Whole Year  Sugarcane  4601.0   4940000.0  1073.679635
Tamil Nadu     PUDUKKOTTAI       1997 Whole Year  Sugarcane  2377.0   2552000.0  1073.622213
Tamil Nadu    VIRUDHUNAGAR       1997 Whole Year  Sugarcane  2639.0   2833000.0  1073.512694
Tamil Nadu  RAMANATHAPURAM       1997 Whole Year  Sugarcane   182.0    195000.0  1071.428571
Tamil Nadu      DHARMAPURI       1997 Whole Year  Sugarcane 18938.0  18100000.0   955.750343
Tamil Nadu      PERAMBALUR       1997 Whole Year  Sugarcane 11508.0  10448000.0   907.890163
Tamil Nadu  TIRUVANNAMALAI       1997 Whole Year  Sugarcane 27636.0  23914000.0   865.320596
Tamil Nadu        DINDIGUL       1997 Whole Year  Sugarcane  6826.0   5749000.0   842.220920
Tamil Nadu       SIVAGANGA       1997 Whole Year  Sugarcane  4794.0   3938000.0   821.443471
Tamil Nadu       THANJAVUR       1997 Whole Year  Sugarcane 12604.0   9900000.0   785.464932
Tamil Nadu         VELLORE       1997 Whole Year  Sugarcane 29072.0  22069000.0   759.115300
Tamil Nadu      THIRUVARUR       1997 Whole Year  Sugarcane  3669.0   2287000.0   623.330608
     Bihar           BUXAR       1997 Whole Year  Sugarcane    59.0     29529.0   500.491525

Saved review file: /content/drive/MyDrive/yield prediction/extreme_non_coconut_yield_review.csv

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path)

df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(df["Production"], errors="coerce")
df["Crop_Year"] = pd.to_numeric(df["Crop_Year"], errors="coerce")

# Filter Tamil Nadu sugarcane
mask = (
    df["State_Name"].astype(str).str.strip().str.casefold().eq("tamil nadu")
    & df["Crop"].astype(str).str.strip().str.casefold().eq("sugarcane")
)

sc = df.loc[mask].copy()
sc = sc[(sc["Area"] > 0) & (sc["Production"] > 0)]
sc["yield_ratio"] = sc["Production"] / sc["Area"]

print("=" * 70)
print("TAMIL NADU SUGARCANE: YEAR-WISE COMPARISON")
print("=" * 70)

print(
    sc.groupby("Crop_Year").agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield_ratio=("yield_ratio", "median"),
        maximum_yield_ratio=("yield_ratio", "max")
    ).round(3).to_string()
)

print("\n" + "=" * 70)
print("TAMIL NADU SUGARCANE: 1997 RECORDS")
print("=" * 70)

cols = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production", "yield_ratio"
]

print(
    sc[sc["Crop_Year"] == 1997]
    .sort_values("yield_ratio", ascending=False)[cols]
    .to_string(index=False)
)

print("\n" + "=" * 70)
print("TAMIL NADU SUGARCANE: 1998 RECORDS")
print("=" * 70)

print(
    sc[sc["Crop_Year"] == 1998]
    .sort_values("District_Name")[cols]
    .to_string(index=False)
)

# Save this comparison for source verification
output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "tamil_nadu_sugarcane_year_comparison.csv"
)

sc[cols].sort_values(
    ["Crop_Year", "District_Name"]
).to_csv(output_path, index=False)

print("\nSaved:", output_path)

======================================================================
TAMIL NADU SUGARCANE: YEAR-WISE COMPARISON
======================================================================
           records  median_area  median_production  median_yield_ratio  maximum_yield_ratio
Crop_Year
1997            27       6826.0          9900000.0            1077.778             2247.533
1998            27      10081.0          1432090.0             122.732              303.485
1999            27       8926.0          1069224.0             107.179              133.613
2000            27       7163.0           860112.0             107.143              133.613
2001            27       7437.0           805700.0             100.187              158.573
2002            27       5993.0           488160.0              91.838              135.687
2003            26       4787.5           454119.0             101.678              125.810
2004            28       4327.5           444558.0             110.074              137.919
2005            28       7337.0           668121.5              99.092              147.258
2006            28       8083.5           974356.0             117.497              188.415
2007            28       6605.0           755698.5             107.537              126.363
2008            28       5456.5           623399.0             106.214              314.736
2009            30       5303.0           583496.5             101.451              146.358
2010            30       5576.5           667673.5             108.369              134.389
2011            30       6929.5           803366.5             112.531              136.766
2012            31       6091.0           548874.0              94.396              125.793
2013            31       4713.0           449019.0             101.480              119.376

======================================================================
TAMIL NADU SUGARCANE: 1997 RECORDS
======================================================================
State_Name   District_Name  Crop_Year      Season      Crop    Area  Production  yield_ratio
Tamil Nadu         MADURAI       1997 Whole Year  Sugarcane  8108.0  18223000.0  2247.533300
Tamil Nadu     THIRUVALLUR       1997 Whole Year  Sugarcane  5964.0  11811000.0  1980.382294
Tamil Nadu     KANCHIPURAM       1997 Whole Year  Sugarcane  6735.0   9896000.0  1469.339272
Tamil Nadu        NAMAKKAL       1997 Whole Year  Sugarcane  9415.0  13608000.0  1445.353160
Tamil Nadu TIRUCHIRAPPALLI       1997 Whole Year  Sugarcane  4315.0   5806000.0  1345.538818
Tamil Nadu       CUDDALORE       1997 Whole Year  Sugarcane 23826.0  28322000.0  1188.701419
Tamil Nadu           KARUR       1997 Whole Year  Sugarcane  5961.0   7081000.0  1187.887938
Tamil Nadu           SALEM       1997 Whole Year  Sugarcane 13759.0  15866000.0  1153.136129
Tamil Nadu      COIMBATORE       1997 Whole Year  Sugarcane 10756.0  12272000.0  1140.944589
Tamil Nadu      VILLUPURAM       1997 Whole Year  Sugarcane 33175.0  37158000.0  1120.060286
Tamil Nadu           ERODE       1997 Whole Year  Sugarcane 24112.0  26930000.0  1116.871267
Tamil Nadu           THENI       1997 Whole Year  Sugarcane  9524.0  10598000.0  1112.767745
Tamil Nadu    THE NILGIRIS       1997 Whole Year  Sugarcane    22.0     24000.0  1090.909091
Tamil Nadu       TUTICORIN       1997 Whole Year  Sugarcane    90.0     97000.0  1077.777778
Tamil Nadu     TIRUNELVELI       1997 Whole Year  Sugarcane  2237.0   2402000.0  1073.759499
Tamil Nadu    NAGAPATTINAM       1997 Whole Year  Sugarcane  4601.0   4940000.0  1073.679635
Tamil Nadu     PUDUKKOTTAI       1997 Whole Year  Sugarcane  2377.0   2552000.0  1073.622213
Tamil Nadu    VIRUDHUNAGAR       1997 Whole Year  Sugarcane  2639.0   2833000.0  1073.512694
Tamil Nadu  RAMANATHAPURAM       1997 Whole Year  Sugarcane   182.0    195000.0  1071.428571
Tamil Nadu      DHARMAPURI       1997 Whole Year  Sugarcane 18938.0  18100000.0   955.750343
Tamil Nadu      PERAMBALUR       1997 Whole Year  Sugarcane 11508.0  10448000.0   907.890163
Tamil Nadu  TIRUVANNAMALAI       1997 Whole Year  Sugarcane 27636.0  23914000.0   865.320596
Tamil Nadu        DINDIGUL       1997 Whole Year  Sugarcane  6826.0   5749000.0   842.220920
Tamil Nadu       SIVAGANGA       1997 Whole Year  Sugarcane  4794.0   3938000.0   821.443471
Tamil Nadu       THANJAVUR       1997 Whole Year  Sugarcane 12604.0   9900000.0   785.464932
Tamil Nadu         VELLORE       1997 Whole Year  Sugarcane 29072.0  22069000.0   759.115300
Tamil Nadu      THIRUVARUR       1997 Whole Year  Sugarcane  3669.0   2287000.0   623.330608

======================================================================
TAMIL NADU SUGARCANE: 1998 RECORDS
======================================================================
State_Name   District_Name  Crop_Year      Season      Crop    Area  Production  yield_ratio
Tamil Nadu      COIMBATORE       1998 Whole Year  Sugarcane 13193.0   1467460.0   111.230198
Tamil Nadu       CUDDALORE       1998 Whole Year  Sugarcane 32654.0   4401890.0   134.804006
Tamil Nadu      DHARMAPURI       1998 Whole Year  Sugarcane 27836.0   2772300.0    99.594051
Tamil Nadu        DINDIGUL       1998 Whole Year  Sugarcane  7051.0    886010.0   125.657354
Tamil Nadu           ERODE       1998 Whole Year  Sugarcane 21581.0   2579080.0   119.506974
Tamil Nadu     KANCHIPURAM       1998 Whole Year  Sugarcane 23801.0   5775500.0   242.657872
Tamil Nadu           KARUR       1998 Whole Year  Sugarcane 10193.0   1251010.0   122.732267
Tamil Nadu         MADURAI       1998 Whole Year  Sugarcane 10081.0   3059430.0   303.484773
Tamil Nadu    NAGAPATTINAM       1998 Whole Year  Sugarcane  3959.0    485900.0   122.733013
Tamil Nadu        NAMAKKAL       1998 Whole Year  Sugarcane  9411.0   1505330.0   159.954309
Tamil Nadu      PERAMBALUR       1998 Whole Year  Sugarcane  9029.0    871980.0    96.575479
Tamil Nadu     PUDUKKOTTAI       1998 Whole Year  Sugarcane  2829.0    347210.0   122.732414
Tamil Nadu  RAMANATHAPURAM       1998 Whole Year  Sugarcane   257.0     31540.0   122.723735
Tamil Nadu           SALEM       1998 Whole Year  Sugarcane 10765.0   1440330.0   133.797492
Tamil Nadu       SIVAGANGA       1998 Whole Year  Sugarcane  4390.0    538790.0   122.731207
Tamil Nadu       THANJAVUR       1998 Whole Year  Sugarcane 13897.0   1244250.0    89.533712
Tamil Nadu    THE NILGIRIS       1998 Whole Year  Sugarcane   104.0     12760.0   122.692308
Tamil Nadu           THENI       1998 Whole Year  Sugarcane 16133.0   3617820.0   224.249675
Tamil Nadu     THIRUVALLUR       1998 Whole Year  Sugarcane  8284.0   1432090.0   172.874215
Tamil Nadu      THIRUVARUR       1998 Whole Year  Sugarcane  3126.0    383660.0   122.731926
Tamil Nadu TIRUCHIRAPPALLI       1998 Whole Year  Sugarcane 13204.0   1899500.0   143.857922
Tamil Nadu     TIRUNELVELI       1998 Whole Year  Sugarcane  2662.0    326710.0   122.731029
Tamil Nadu  TIRUVANNAMALAI       1998 Whole Year  Sugarcane 27897.0   2731420.0    97.910886
Tamil Nadu       TUTICORIN       1998 Whole Year  Sugarcane    31.0      3800.0   122.580645
Tamil Nadu         VELLORE       1998 Whole Year  Sugarcane 27098.0   2156460.0    79.580043
Tamil Nadu      VILLUPURAM       1998 Whole Year  Sugarcane 44737.0   4995600.0   111.665959
Tamil Nadu    VIRUDHUNAGAR       1998 Whole Year  Sugarcane  3707.0    454970.0   122.732668

Saved: /content/drive/MyDrive/yield prediction/tamil_nadu_sugarcane_year_comparison.csv

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path)

for col in ["Area", "Production", "Crop_Year"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

mask = (
    df["State_Name"].astype(str).str.strip().str.casefold().eq("tamil nadu")
    & df["Crop"].astype(str).str.strip().str.casefold().eq("sugarcane")
    & df["Season"].astype(str).str.strip().str.casefold().eq("whole year")
    & df["Crop_Year"].isin([1997, 1998])
)

sc = df.loc[mask].copy()
sc = sc[(sc["Area"] > 0) & (sc["Production"] > 0)]
sc["yield_ratio"] = sc["Production"] / sc["Area"]

wide = sc.pivot_table(
    index="District_Name",
    columns="Crop_Year",
    values=["Area", "Production", "yield_ratio"],
    aggfunc="first"
)

wide.columns = [f"{metric}_{year}" for metric, year in wide.columns]
wide = wide.reset_index()

# Factor is diagnostic, not an approved correction
wide["yield_ratio_factor_1997_vs_1998"] = (
    wide["yield_ratio_1997"] / wide["yield_ratio_1998"]
)

wide["production_1997_if_1998_ratio_applied"] = (
    wide["Area_1997"] * wide["yield_ratio_1998"]
)

print(
    wide.sort_values(
        "yield_ratio_factor_1997_vs_1998", ascending=False
    ).round(3).to_string(index=False)
)

print("\nMedian 1997/1998 yield-ratio factor:")
print(wide["yield_ratio_factor_1997_vs_1998"].median())

output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "tn_sugarcane_1997_1998_district_comparison.csv"
)

wide.to_csv(output_path, index=False)
print("\nSaved:", output_path)

  District_Name  Area_1997  Area_1998  Production_1997  Production_1998  yield_ratio_1997  yield_ratio_1998  yield_ratio_factor_1997_vs_1998  production_1997_if_1998_ratio_applied
    THIRUVALLUR     5964.0     8284.0       11811000.0        1432090.0          1980.382           172.874                           11.456                            1031021.820
     COIMBATORE    10756.0    13193.0       12272000.0        1467460.0          1140.945           111.230                           10.258                            1196392.008
     VILLUPURAM    33175.0    44737.0       37158000.0        4995600.0          1120.060           111.666                           10.030                            3704518.184
          KARUR     5961.0    10193.0        7081000.0        1251010.0          1187.888           122.732                            9.679                             731607.045
     DHARMAPURI    18938.0    27836.0       18100000.0        2772300.0           955.750            99.594                            9.596                            1886112.135
        VELLORE    29072.0    27098.0       22069000.0        2156460.0           759.115            79.580                            9.539                            2313551.005
     PERAMBALUR    11508.0     9029.0       10448000.0         871980.0           907.890            96.575                            9.401                            1111390.612
TIRUCHIRAPPALLI     4315.0    13204.0        5806000.0        1899500.0          1345.539           143.858                            9.353                             620746.933
          ERODE    24112.0    21581.0       26930000.0        2579080.0          1116.871           119.507                            9.346                            2881552.151
       NAMAKKAL     9415.0     9411.0       13608000.0        1505330.0          1445.353           159.954                            9.036                            1505969.817
   THE NILGIRIS       22.0      104.0          24000.0          12760.0          1090.909           122.692                            8.891                               2699.231
 TIRUVANNAMALAI    27636.0    27897.0       23914000.0        2731420.0           865.321            97.911                            8.838                            2705865.259
      CUDDALORE    23826.0    32654.0       28322000.0        4401890.0          1188.701           134.804                            8.818                            3211840.238
      TUTICORIN       90.0       31.0          97000.0           3800.0          1077.778           122.581                            8.792                              11032.258
      THANJAVUR    12604.0    13897.0        9900000.0        1244250.0           785.465            89.534                            8.773                            1128482.910
    TIRUNELVELI     2237.0     2662.0        2402000.0         326710.0          1073.759           122.731                            8.749                             274549.313
   NAGAPATTINAM     4601.0     3959.0        4940000.0         485900.0          1073.680           122.733                            8.748                             564694.595
    PUDUKKOTTAI     2377.0     2829.0        2552000.0         347210.0          1073.622           122.732                            8.748                             291734.949
   VIRUDHUNAGAR     2639.0     3707.0        2833000.0         454970.0          1073.513           122.733                            8.747                             323891.511
 RAMANATHAPURAM      182.0      257.0         195000.0          31540.0          1071.429           122.724                            8.730                              22335.720
          SALEM    13759.0    10765.0       15866000.0        1440330.0          1153.136           133.797                            8.619                            1840919.691
        MADURAI     8108.0    10081.0       18223000.0        3059430.0          2247.533           303.485                            7.406                            2460654.542
       DINDIGUL     6826.0     7051.0        5749000.0         886010.0           842.221           125.657                            6.703                             857737.095
      SIVAGANGA     4794.0     4390.0        3938000.0         538790.0           821.443           122.731                            6.693                             588373.408
    KANCHIPURAM     6735.0    23801.0        9896000.0        5775500.0          1469.339           242.658                            6.055                            1634300.765
     THIRUVARUR     3669.0     3126.0        2287000.0         383660.0           623.331           122.732                            5.079                             450303.436
          THENI     9524.0    16133.0       10598000.0        3617820.0          1112.768           224.250                            4.962                            2135753.901

Median 1997/1998 yield-ratio factor:
8.792397660818715

Saved: /content/drive/MyDrive/yield prediction/tn_sugarcane_1997_1998_district_comparison.csv

In [ ]:
import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path, low_memory=False)

# Convert numeric columns safely
for col in ["Area", "Production", "Crop_Year"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("=" * 55)
print("DATASET AUDIT — STEP 1")
print("=" * 55)

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

# Check missing values
print("\nMissing values:")
print(df[["Area", "Production", "Crop_Year"]].isna().sum())

# Valid records for yield calculation
valid = df[
    df["Area"].gt(0) &
    df["Production"].gt(0)
].copy()

valid["calculated_yield"] = (
    valid["Production"] / valid["Area"]
)

print("\nValid area and production records:", len(valid))
print("Records with zero or negative area:",
      (df["Area"] <= 0).sum())
print("Records with zero or negative production:",
      (df["Production"] <= 0).sum())

print("\nCalculated yield distribution:")
print(
    valid["calculated_yield"]
    .describe(percentiles=[0.50, 0.90, 0.95, 0.99])
    .round(3)
)

print("\nExtreme yield ratios:")
for threshold in [100, 500, 1000, 5000, 10000]:
    count = (valid["calculated_yield"] > threshold).sum()
    print(f"Yield > {threshold:>5}: {count:,}")

print("\nTop 20 highest yield ratios:")
cols = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production",
    "calculated_yield"
]

print(
    valid.nlargest(20, "calculated_yield")[cols]
    .to_string(index=False)
)

=======================================================
DATASET AUDIT — STEP 1
=======================================================
Dataset shape: (246091, 11)
Columns: ['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area', 'Production', 'temperature', 'humidity', 'rainfall_mm', 'soil_type']

Missing values:
Area             0
Production    3730
Crop_Year        0
dtype: int64

Valid area and production records: 238838
Records with zero or negative area: 0
Records with zero or negative production: 3523

Calculated yield distribution:
count    238838.000
mean         42.263
std         823.565
min           0.000
50%           1.000
90%          10.000
95%          22.856
99%          83.545
max       88000.000
Name: calculated_yield, dtype: float64

Extreme yield ratios:
Yield >   100: 1,628
Yield >   500: 983
Yield >  1000: 969
Yield >  5000: 761
Yield > 10000: 287

Top 20 highest yield ratios:
    State_Name   District_Name  Crop_Year      Season      Crop    Area  Production  calculated_yield
        Punjab         PATIALA       2011 Whole Year  Sugarcane     3.0    264000.0      88000.000000
        Punjab         SANGRUR       2011 Whole Year  Sugarcane     2.0    163000.0      81500.000000
        Punjab        LUDHIANA       2011 Whole Year  Sugarcane     2.0    161000.0      80500.000000
        Punjab FATEHGARH SAHIB       2011 Whole Year  Sugarcane     2.0    151000.0      75500.000000
        Punjab        RUPNAGAR       2011 Whole Year  Sugarcane     3.0    224000.0      74666.666667
        Punjab       GURDASPUR       2011 Whole Year  Sugarcane    20.0   1491000.0      74550.000000
        Punjab       PATHANKOT       2011 Whole Year  Sugarcane     4.0    298000.0      74500.000000
        Punjab      KAPURTHALA       2011 Whole Year  Sugarcane     3.0    221000.0      73666.666667
        Punjab         FAZILKA       2011 Whole Year  Sugarcane     1.0     73000.0      73000.000000
        Punjab      NAWANSHAHR       2011 Whole Year  Sugarcane     6.0    407000.0      67833.333333
        Punjab        AMRITSAR       2011 Whole Year  Sugarcane     3.0    203000.0      67666.666667
        Punjab       JALANDHAR       2011 Whole Year  Sugarcane     9.0    599000.0      66555.555556
        Punjab     S.A.S NAGAR       2011 Whole Year  Sugarcane     1.0     65000.0      65000.000000
        Punjab      HOSHIARPUR       2011 Whole Year  Sugarcane    20.0   1293000.0      64650.000000
        Punjab      TARN TARAN       2011 Whole Year  Sugarcane     1.0     40000.0      40000.000000
   West Bengal         BIRBHUM       2006 Whole Year   Coconut    509.0  19749200.0      38800.000000
Andhra Pradesh   WEST GODAVARI       2014 Whole Year   Coconut  21729.0 718991000.0      33089.005477
         Assam          KAMRUP       2004 Whole Year   Coconut   2026.0  57405000.0      28334.155972
         Assam       LAKHIMPUR       2001 Whole Year   Coconut    192.0   5044000.0      26270.833333
    Tamil Nadu       THANJAVUR       2011 Whole Year   Coconut  33742.0 823800000.0      24414.676071

In [ ]:
import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path, low_memory=False)

df["Crop_Year"] = pd.to_numeric(
    df["Crop_Year"], errors="coerce"
)
df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(
    df["Production"], errors="coerce"
)

mask = (
    df["State_Name"].astype(str).str.strip().str.casefold().eq("punjab")
    & df["Crop"].astype(str).str.strip().str.casefold().eq("sugarcane")
    & df["Season"].astype(str).str.strip().str.casefold().eq("whole year")
    & df["Crop_Year"].between(2009, 2013)
)

check = df.loc[mask].copy()

check["calculated_yield"] = np.where(
    (check["Area"] > 0) & (check["Production"] > 0),
    check["Production"] / check["Area"],
    np.nan
)

print("Records by year:")
print(check.groupby("Crop_Year").size())

print("\nYear-wise summary:")
print(
    check.groupby("Crop_Year").agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max")
    ).round(3).to_string()
)

print("\nDistrict-level records:")
print(
    check[
        [
            "Crop_Year", "District_Name", "Area",
            "Production", "calculated_yield"
        ]
    ]
    .sort_values(["Crop_Year", "District_Name"])
    .to_string(index=False)
)

Records by year:
Crop_Year
2009    13
2011    15
2012    16
2013    16
dtype: int64

Year-wise summary:
           records  median_area  median_production  median_yield  max_yield
Crop_Year
2009            13        200.0            15000.0        60.000     80.000
2011            15          3.0           221000.0     73666.667  88000.000
2012            16       2500.0           205500.0        70.750     92.000
2013            16       3000.0           253500.0        78.300     93.667

District-level records:
 Crop_Year   District_Name    Area  Production  calculated_yield
      2009        AMRITSAR   300.0     18000.0         60.000000
      2009 FATEHGARH SAHIB   200.0     15000.0         75.000000
      2009       FIROZEPUR   100.0      6000.0         60.000000
      2009       GURDASPUR  1900.0    124000.0         65.263158
      2009      HOSHIARPUR  1400.0     76000.0         54.285714
      2009       JALANDHAR   700.0     42000.0         60.000000
      2009      KAPURTHALA   300.0     18000.0         60.000000
      2009        LUDHIANA   100.0      6000.0         60.000000
      2009      NAWANSHAHR   500.0     31000.0         62.000000
      2009         PATIALA   100.0      8000.0         80.000000
      2009        RUPNAGAR   200.0     13000.0         65.000000
      2009     S.A.S NAGAR   100.0      5000.0         50.000000
      2009         SANGRUR   100.0      8000.0         80.000000
      2011        AMRITSAR     3.0    203000.0      67666.666667
      2011 FATEHGARH SAHIB     2.0    151000.0      75500.000000
      2011         FAZILKA     1.0     73000.0      73000.000000
      2011       GURDASPUR    20.0   1491000.0      74550.000000
      2011      HOSHIARPUR    20.0   1293000.0      64650.000000
      2011       JALANDHAR     9.0    599000.0      66555.555556
      2011      KAPURTHALA     3.0    221000.0      73666.666667
      2011        LUDHIANA     2.0    161000.0      80500.000000
      2011      NAWANSHAHR     6.0    407000.0      67833.333333
      2011       PATHANKOT     4.0    298000.0      74500.000000
      2011         PATIALA     3.0    264000.0      88000.000000
      2011        RUPNAGAR     3.0    224000.0      74666.666667
      2011     S.A.S NAGAR     1.0     65000.0      65000.000000
      2011         SANGRUR     2.0    163000.0      81500.000000
      2011      TARN TARAN     1.0     40000.0      40000.000000
      2012        AMRITSAR  2000.0    141000.0         70.500000
      2012 FATEHGARH SAHIB  3000.0    258000.0         86.000000
      2012         FAZILKA  1000.0     82000.0         82.000000
      2012       FIROZEPUR  1000.0     67000.0         67.000000
      2012       GURDASPUR 22000.0   1594000.0         72.454545
      2012      HOSHIARPUR 19000.0   1321000.0         69.526316
      2012       JALANDHAR 10000.0    651000.0         65.100000
      2012      KAPURTHALA  4000.0    258000.0         64.500000
      2012        LUDHIANA  2000.0    136000.0         68.000000
      2012      NAWANSHAHR  5000.0    327000.0         65.400000
      2012       PATHANKOT  4000.0    297000.0         74.250000
      2012         PATIALA  2000.0    184000.0         92.000000
      2012        RUPNAGAR  3000.0    227000.0         75.666667
      2012     S.A.S NAGAR  1000.0     57000.0         57.000000
      2012         SANGRUR  2000.0    161000.0         80.500000
      2012      TARN TARAN  1000.0     71000.0         71.000000
      2013        AMRITSAR  5000.0    401000.0         80.200000
      2013         BARNALA  1000.0     90000.0         90.000000
      2013 FATEHGARH SAHIB  3000.0    243000.0         81.000000
      2013       FIROZEPUR  2000.0    170000.0         85.000000
      2013       GURDASPUR 21000.0   1560000.0         74.285714
      2013      HOSHIARPUR 21000.0   1481000.0         70.523810
      2013       JALANDHAR 10000.0    764000.0         76.400000
      2013      KAPURTHALA  4000.0    328000.0         82.000000
      2013        LUDHIANA  2000.0    170000.0         85.000000
      2013      NAWANSHAHR  6000.0    401000.0         66.833333
      2013       PATHANKOT  4000.0    234000.0         58.500000
      2013         PATIALA  3000.0    281000.0         93.666667
      2013        RUPNAGAR  2000.0    152000.0         76.000000
      2013     S.A.S NAGAR  1000.0     61000.0         61.000000
      2013         SANGRUR  3000.0    264000.0         88.000000
      2013      TARN TARAN  1000.0     75000.0         75.000000

In [ ]:
import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path, low_memory=False)

for col in ["Crop_Year", "Area", "Production"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Punjab records from 2011
punjab_2011 = df[
    df["State_Name"].astype(str).str.strip().str.casefold().eq("punjab")
    & df["Crop_Year"].eq(2011)
].copy()

punjab_2011["calculated_yield"] = np.where(
    (punjab_2011["Area"] > 0)
    & (punjab_2011["Production"] > 0),
    punjab_2011["Production"] / punjab_2011["Area"],
    np.nan
)

print("Punjab records in 2011:", len(punjab_2011))

print("\nSummary by crop:")
summary = (
    punjab_2011.groupby("Crop")
    .agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max")
    )
    .sort_values("median_yield", ascending=False)
)

print(summary.round(3).to_string())

print("\nAll Punjab 2011 records with yield ratio > 500:")
print(
    punjab_2011[punjab_2011["calculated_yield"] > 500][
        [
            "District_Name", "Crop", "Season",
            "Area", "Production", "calculated_yield"
        ]
    ].sort_values("calculated_yield", ascending=False).to_string(index=False)
)

Punjab records in 2011: 162

Summary by crop:
                       records  median_area  median_production  median_yield  max_yield
Crop
Sugarcane                   15          3.0           221000.0     73666.667  88000.000
Wheat                       20     173500.0           884000.0         5.015      5.495
Barley                       8       1000.0             4500.0         4.000      5.000
Maize                       11       6000.0            24000.0         4.000      6.000
Rice                        20     115500.0           446000.0         3.789      4.371
Cotton(lint)                11      11000.0            44000.0         3.000      4.000
Groundnut                    2       8500.0            14500.0         1.375      1.750
Peas & beans (Pulses)        8       2500.0             3000.0         1.143      1.333
Arhar/Tur                   10       2000.0             2000.0         1.000      1.000
Rapeseed &Mustard           15       1000.0             2000.0         1.000      2.000
Gram                         8       1000.0             1000.0         1.000      2.000
Bajra                        3       1000.0             1000.0         1.000      1.000
Guar seed                    4      10000.0             8500.0         0.921      1.000
Moong(Green Gram)           11       5000.0             5000.0         0.800      1.500
Masoor                       4       3000.0             2000.0         0.717      0.833
Urad                         4       4000.0             2500.0         0.500      0.667
Sesamum                      8       5000.0             2000.0         0.400      1.000

All Punjab 2011 records with yield ratio > 500:
  District_Name      Crop      Season  Area  Production  calculated_yield
        PATIALA Sugarcane Whole Year    3.0    264000.0      88000.000000
        SANGRUR Sugarcane Whole Year    2.0    163000.0      81500.000000
       LUDHIANA Sugarcane Whole Year    2.0    161000.0      80500.000000
FATEHGARH SAHIB Sugarcane Whole Year    2.0    151000.0      75500.000000
       RUPNAGAR Sugarcane Whole Year    3.0    224000.0      74666.666667
      GURDASPUR Sugarcane Whole Year   20.0   1491000.0      74550.000000
      PATHANKOT Sugarcane Whole Year    4.0    298000.0      74500.000000
     KAPURTHALA Sugarcane Whole Year    3.0    221000.0      73666.666667
        FAZILKA Sugarcane Whole Year    1.0     73000.0      73000.000000
     NAWANSHAHR Sugarcane Whole Year    6.0    407000.0      67833.333333
       AMRITSAR Sugarcane Whole Year    3.0    203000.0      67666.666667
      JALANDHAR Sugarcane Whole Year    9.0    599000.0      66555.555556
    S.A.S NAGAR Sugarcane Whole Year    1.0     65000.0      65000.000000
     HOSHIARPUR Sugarcane Whole Year   20.0   1293000.0      64650.000000
     TARN TARAN Sugarcane Whole Year    1.0     40000.0      40000.000000

In [ ]:
import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path, low_memory=False)

for col in ["Crop_Year", "Area", "Production"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

coconut = df[
    df["Crop"].astype(str).str.strip().str.casefold().eq("coconut")
].copy()

coconut["calculated_yield"] = np.where(
    (coconut["Area"] > 0) & (coconut["Production"] > 0),
    coconut["Production"] / coconut["Area"],
    np.nan
)

print("Total coconut records:", len(coconut))

print("\nCoconut records by state:")
print(
    coconut.groupby("State_Name").agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max")
    ).sort_values("max_yield", ascending=False)
    .round(3)
    .to_string()
)

print("\nCoconut records with calculated yield > 500:")
print(
    coconut[coconut["calculated_yield"] > 500][
        [
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "Production", "calculated_yield"
        ]
    ]
    .sort_values("calculated_yield", ascending=False)
    .head(30)
    .to_string(index=False)
)

Total coconut records: 1985

Coconut records by state:
                             records  median_area  median_production  median_yield  max_yield
State_Name
West Bengal                      216       858.50       1.844370e+04        14.225  38800.000
Andhra Pradesh                   169      1829.00       1.720927e+07     10282.390  33089.005
Assam                            400       556.00       2.059500e+06      5257.042  28334.156
Tamil Nadu                       295      6825.00       7.405000e+04        10.293  24414.676
Puducherry                        57       318.00       4.040000e+06     11336.127  19792.982
Telangana                         52        12.50       1.276440e+05     11105.057  14606.000
Kerala                           252     58475.00       3.778770e+08      6306.291  11051.716
Goa                               12     12738.00       5.553500e+07      4930.285   4995.104
Andaman and Nicobar Islands       18      7133.35       3.079000e+07      3749.091   4896.978
Dadra and Nagar Haveli             9       180.00       4.750000e+02         2.500    370.000
Karnataka                        479      2566.00       2.124297e+04         5.536     50.820
Mizoram                            2         7.50       2.000000e+01         2.596      2.692
Chhattisgarh                      24         3.00                NaN           NaN        NaN

Coconut records with calculated yield > 500:
    State_Name      District_Name  Crop_Year      Season    Area  Production  calculated_yield
   West Bengal            BIRBHUM       2006 Whole Year    509.0  19749200.0      38800.000000
Andhra Pradesh      WEST GODAVARI       2014 Whole Year  21729.0 718991000.0      33089.005477
         Assam             KAMRUP       2004 Whole Year   2026.0  57405000.0      28334.155972
         Assam          LAKHIMPUR       2001 Whole Year    192.0   5044000.0      26270.833333
    Tamil Nadu          THANJAVUR       2011 Whole Year  33742.0 823800000.0      24414.676071
         Assam           GOLAGHAT       2004 Whole Year    658.0  16062000.0      24410.334347
Andhra Pradesh         SRIKAKULAM       2014 Whole Year  13811.0 328149000.0      23759.973934
   West Bengal 24 PARAGANAS NORTH       2006 Whole Year   3338.0  75095000.0      22497.004194
         Assam           GOLAGHAT       2006 Whole Year    612.0  13555000.0      22148.692810
         Assam           GOLAGHAT       2007 Whole Year    639.0  14029000.0      21954.616588
Andhra Pradesh       SPSR NELLORE       2014 Whole Year    491.0  10645000.0      21680.244399
Andhra Pradesh            KRISHNA       2014 Whole Year   1829.0  39653000.0      21680.153089
Andhra Pradesh     VISAKHAPATANAM       2014 Whole Year   7416.0 160779000.0      21680.016181
Andhra Pradesh             GUNTUR       2014 Whole Year    112.0   2428000.0      21678.571429
Andhra Pradesh           PRAKASAM       2014 Whole Year     37.0    802000.0      21675.675676
    Tamil Nadu         THIRUVARUR       2011 Whole Year   4916.0 106300000.0      21623.270952
Andhra Pradesh         SRIKAKULAM       2012 Whole Year  14421.0 306951000.0      21285.001040
         Assam           GOLAGHAT       2008 Whole Year   1057.0  22284000.0      21082.308420
Andhra Pradesh      WEST GODAVARI       2013 Whole Year  21355.0 448904000.0      21021.025521
Andhra Pradesh      WEST GODAVARI       2012 Whole Year  20196.0 405213000.0      20064.022579
    Puducherry              YANAM       2012 Whole Year    285.0   5641000.0      19792.982456
    Tamil Nadu           DINDIGUL       2011 Whole Year  29478.0 574900000.0      19502.679965
    Puducherry        PONDICHERRY       2008 Whole Year   1112.0  21406000.0      19250.000000
    Tamil Nadu        KRISHNAGIRI       2011 Whole Year  15550.0 297200000.0      19112.540193
    Tamil Nadu              THENI       2011 Whole Year  19116.0 364900000.0      19088.721490
    Puducherry        PONDICHERRY       2014 Whole Year   1050.0  19950000.0      19000.000000
    Puducherry        PONDICHERRY       2009 Whole Year   1169.0  22012000.0      18829.769033
    Tamil Nadu          CUDDALORE       2011 Whole Year   2343.0  43700000.0      18651.301750
Andhra Pradesh         SRIKAKULAM       2013 Whole Year  13812.0 249859000.0      18089.994208
    Tamil Nadu        KRISHNAGIRI       2013 Whole Year  15781.0 284600000.0      18034.345099

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path, low_memory=False)

for col in ["Crop_Year", "Area", "Production"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

coconut = df[
    df["Crop"].astype(str).str.strip().str.casefold().eq("coconut")
].copy()

coconut = coconut[
    (coconut["Area"] > 0) &
    (coconut["Production"] > 0)
].copy()

coconut["calculated_yield"] = (
    coconut["Production"] / coconut["Area"]
)

# Year-wise summary
print("===== COCONUT: YEAR-WISE SUMMARY =====")

print(
    coconut.groupby("Crop_Year").agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max"),
        records_over_500=(
            "calculated_yield",
            lambda s: (s > 500).sum()
        )
    ).round(2).to_string()
)

# State and year combinations with suspiciously high ratios
print("\n===== STATE-YEAR COMBINATIONS =====")

summary = (
    coconut.groupby(["State_Name", "Crop_Year"])
    .agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max"),
        records_over_500=(
            "calculated_yield",
            lambda s: (s > 500).sum()
        )
    )
    .reset_index()
)

print(
    summary[summary["max_yield"] > 500]
    .sort_values("max_yield", ascending=False)
    .head(40)
    .round(2)
    .to_string(index=False)
)

===== COCONUT: YEAR-WISE SUMMARY =====
           records  median_area  median_production  median_yield  max_yield  records_over_500
Crop_Year
1997            57       1040.0             8766.0          5.61      20.98                 0
1998            83       1174.0            75720.0         17.33    9908.82                37
1999            86       1161.5           180378.0         17.77   16500.00                41
2000           108       1172.5           493405.0       3752.31   18000.00                62
2001           107       1264.0           530400.0       3583.78   26270.83                61
2002           134       2105.5           158800.0         15.44   14432.86                61
2003           133       2101.0           129580.0         16.10   16906.30                60
2004           138       2177.5           354800.0         48.24   28334.16                63
2005           114       4480.0            19252.0          5.02   16500.00                40
2006           139       2101.0           641000.0       4073.97   38800.00                82
2007           123       2310.0           683765.0       1777.78   21954.62                65
2008           138       1706.5           919500.0        177.51   21082.31                62
2009           122       2301.5           418425.5       2181.64   18829.77                62
2010            78       1388.0          2888000.0       4974.79   15584.98                48
2011           124       2303.5           638759.0       5610.69   24414.68                67
2012            87       1394.0            33947.0          9.85   21285.00                30
2013           122       2793.5           412047.0        917.34   21021.03                61
2014            64       6409.5           305731.0         19.30   33089.01                30

===== STATE-YEAR COMBINATIONS =====
    State_Name  Crop_Year  records  median_area  median_production  median_yield  max_yield  records_over_500
   West Bengal       2006       18        897.0         14110350.0      12915.01   38800.00                18
Andhra Pradesh       2014       13       1829.0         14190000.0      21675.68   33089.01                13
         Assam       2004       23        625.0          4264000.0       8009.16   28334.16                23
         Assam       2001       23        579.0          5039000.0       7671.72   26270.83                23
    Tamil Nadu       2011       31       7836.0        113900000.0      13161.38   24414.68                31
         Assam       2006       27        514.0          2847000.0       6615.96   22148.69                27
         Assam       2007       27        385.0          3453000.0       7613.14   21954.62                27
Andhra Pradesh       2012       13       2008.0         28899000.0      17076.92   21285.00                13
         Assam       2008       27        410.0          3155000.0       7642.75   21082.31                27
Andhra Pradesh       2013       13       2053.0         19847000.0      16564.10   21021.03                13
    Puducherry       2012        3        285.0          5641000.0      12102.44   19792.98                 3
    Puducherry       2008        4        382.5          3881000.0      10649.32   19250.00                 4
    Puducherry       2014        3        284.0          3408000.0      12000.00   19000.00                 3
    Puducherry       2009        4        381.0          3776500.0      10449.58   18829.77                 4
    Tamil Nadu       2013       31       7793.0         67600000.0       9541.72   18034.35                31
    Puducherry       2000        4        403.5          4452000.0      10374.90   18000.00                 4
Andhra Pradesh       2006       13       1648.0         21220329.0      12361.62   16934.61                13
         Assam       2003       23        606.0          3414000.0       6516.35   16906.30                23
Andhra Pradesh       2011       13       1965.0         27512912.0      13945.19   16710.77                13
    Puducherry       1999        4        404.5          4771500.0      12374.89   16500.00                 4
    Puducherry       2005        4        395.0          4237000.0      11250.83   16500.00                 4
   West Bengal       2007       18        991.5         11739400.0      12692.23   16000.00                18
    Puducherry       2003        4        398.0          4165000.0      11850.96   16000.00                 4
    Puducherry       2004        4        398.5          4050000.0      11000.00   15749.78                 4
         Assam       2009       27        481.0          4104000.0       8832.12   15584.98                27
         Assam       2010       27        481.0          4104000.0       8832.12   15584.98                27
    Puducherry       2011        4        378.0          4368500.0       9193.67   15017.48                 4
    Telangana        2011        5          3.0            43818.0      14606.00   14606.00                 5
    Puducherry       2013        3        284.0          4124000.0      11336.20   14521.13                 3
    Puducherry       2007        4        389.0          4025000.0      10950.43   14446.99                 4
         Assam       2002       23        597.0          2832000.0       7022.14   14432.86                23
Andhra Pradesh       2009       13       2090.0         22798170.0      11219.02   14116.44                13
Andhra Pradesh       2003       13       1726.0         16827552.0      10282.39   13983.94                13
Andhra Pradesh       2002       13       1889.0         17209269.0      10143.57   13863.33                13
Andhra Pradesh       2004       13       1693.0         19892568.0      11413.77   13651.52                13
    Telangana        2006        5         11.0           143187.0      13017.00   13017.00                 5
Andhra Pradesh       2001       13       1789.0         14827800.0       9661.48   12981.00                13
    Puducherry       2010        4        379.5          4072000.0      11970.47   12968.75                 4
    Puducherry       2002        4        401.5          4015000.0      10250.00   12500.00                 4
Andhra Pradesh       2005       13       1627.0         14192976.0       8723.40   12240.00                13

In [ ]:

# Inspect a small sample of coconut records from the original dataset.
# This does not modify or delete anything.

cols = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Area", "Production"
]

sample = coconut[cols + ["calculated_yield"]].copy()

print("===== COCONUT RECORDS: 1997 =====")
print(
    sample[sample["Crop_Year"] == 1997]
    .head(15)
    .to_string(index=False)
)

print("\n===== COCONUT RECORDS: 2014 =====")
print(
    sample[sample["Crop_Year"] == 2014]
    .head(15)
    .to_string(index=False)
)

print("\n===== COCONUT PRODUCTION MAGNITUDES =====")
print(
    sample.groupby("Crop_Year")["Production"]
    .agg(["count", "median", "min", "max"])
    .round(2)
    .to_string()
)

===== COCONUT RECORDS: 1997 =====
State_Name District_Name  Crop_Year      Season   Area  Production  calculated_yield
     Assam       BARPETA       1997 Whole Year  1122.0      8093.0          7.213012
     Assam    BONGAIGAON       1997 Whole Year   468.0      1156.0          2.470085
     Assam        CACHAR       1997 Whole Year  1400.0      2386.0          1.704286
     Assam       DARRANG       1997 Whole Year   864.0      8766.0         10.145833
     Assam       DHEMAJI       1997 Whole Year   114.0       267.0          2.342105
     Assam        DHUBRI       1997 Whole Year   675.0      1325.0          1.962963
     Assam     DIBRUGARH       1997 Whole Year    65.0       261.0          4.015385
     Assam    DIMA HASAO       1997 Whole Year    40.0       259.0          6.475000
     Assam      GOALPARA       1997 Whole Year   589.0      2480.0          4.210526
     Assam      GOLAGHAT       1997 Whole Year   545.0      3056.0          5.607339
     Assam    HAILAKANDI       1997 Whole Year   115.0        89.0          0.773913
     Assam        JORHAT       1997 Whole Year   415.0      1446.0          3.484337
     Assam        KAMRUP       1997 Whole Year  1866.0     12892.0          6.908896
     Assam KARBI ANGLONG       1997 Whole Year   370.0      1672.0          4.518919
     Assam     KARIMGANJ       1997 Whole Year   432.0      1038.0          2.402778

===== COCONUT RECORDS: 2014 =====
    State_Name  District_Name  Crop_Year      Season    Area  Production  calculated_yield
Andhra Pradesh      ANANTAPUR       2014 Whole Year    687.0   5756000.0       8378.457060
Andhra Pradesh       CHITTOOR       2014 Whole Year   3465.0  29033000.0       8378.932179
Andhra Pradesh  EAST GODAVARI       2014 Whole Year  46865.0 780162000.0      16647.007362
Andhra Pradesh         GUNTUR       2014 Whole Year    112.0   2428000.0      21678.571429
Andhra Pradesh         KADAPA       2014 Whole Year    121.0   1014000.0       8380.165289
Andhra Pradesh        KRISHNA       2014 Whole Year   1829.0  39653000.0      21680.153089
Andhra Pradesh        KURNOOL       2014 Whole Year      8.0     67000.0       8375.000000
Andhra Pradesh       PRAKASAM       2014 Whole Year     37.0    802000.0      21675.675676
Andhra Pradesh   SPSR NELLORE       2014 Whole Year    491.0  10645000.0      21680.244399
Andhra Pradesh     SRIKAKULAM       2014 Whole Year  13811.0 328149000.0      23759.973934
Andhra Pradesh VISAKHAPATANAM       2014 Whole Year   7416.0 160779000.0      21680.016181
Andhra Pradesh   VIZIANAGARAM       2014 Whole Year   2534.0  14190000.0       5599.842147
Andhra Pradesh  WEST GODAVARI       2014 Whole Year  21729.0 718991000.0      33089.005477
           Goa      NORTH GOA       2014 Whole Year  11399.0       564.0          0.049478
           Goa      SOUTH GOA       2014 Whole Year  14387.0       714.0          0.049628

===== COCONUT PRODUCTION MAGNITUDES =====
           count     median    min           max
Crop_Year
1997          57     8766.0    5.0  1.012000e+06
1998          83    75720.0   10.0  9.990000e+08
1999          86   180378.0   14.0  1.059000e+09
2000         108   493405.0   14.0  9.030000e+08
2001         107   530400.0  129.0  8.950000e+08
2002         134   158800.0  110.0  8.880000e+08
2003         133   129580.0  110.0  8.980000e+08
2004         138   354800.0  100.0  9.000000e+08
2005         114    19252.0   63.0  8.630000e+08
2006         139   641000.0    1.0  8.590000e+08
2007         123   683765.0    1.0  8.510000e+08
2008         138   919500.0  164.0  9.520000e+08
2009         122   418425.5  100.0  1.063000e+09
2010          78  2888000.0  191.0  9.160530e+08
2011         124   638759.0   38.0  1.250800e+09
2012          87    33947.0   46.0  1.125000e+09
2013         122   412047.0   33.0  1.212000e+09
2014          64   305731.0   42.0  1.001000e+09

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

df = pd.read_csv(file_path, low_memory=False)

for col in ["Crop_Year", "Area", "Production"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Keep only records where a ratio can be calculated.
valid = df[
    (df["Area"] > 0) &
    (df["Production"] > 0)
].copy()

valid["calculated_yield"] = (
    valid["Production"] / valid["Area"]
)

# Audit flags only — these are NOT automatic exclusions.
valid["yield_over_100"] = valid["calculated_yield"] > 100
valid["yield_over_500"] = valid["calculated_yield"] > 500

summary = (
    valid.groupby("Crop")
    .agg(
        records=("calculated_yield", "size"),
        median_yield=("calculated_yield", "median"),
        p95_yield=(
            "calculated_yield",
            lambda s: s.quantile(0.95)
        ),
        max_yield=("calculated_yield", "max"),
        records_over_100=("yield_over_100", "sum"),
        records_over_500=("yield_over_500", "sum")
    )
    .sort_values(
        ["records_over_500", "max_yield"],
        ascending=False
    )
)

print("Total valid yield records:", len(valid))
print("\n===== TOP 30 CROPS TO INVESTIGATE =====")
print(summary.head(30).round(3).to_string())

print("\n===== TOTAL EXTREME-RATIO COUNTS =====")
print("Yield > 100:", int((valid["calculated_yield"] > 100).sum()))
print("Yield > 500:", int((valid["calculated_yield"] > 500).sum()))
print("Yield > 1000:", int((valid["calculated_yield"] > 1000).sum()))

Total valid yield records: 238838

===== TOP 30 CROPS TO INVESTIGATE =====
                    records  median_yield  p95_yield  max_yield  records_over_100  records_over_500
Crop
Coconut                1957        43.120  13817.583  38800.000               958               932
Sugarcane              7814        53.287    107.106  88000.000               607                43
Maize                 13723         1.800      4.819   1494.000                 6                 6
Cashewnut              1065         0.397      1.030   9801.000                 1                 1
Onion                  6979        10.300     25.751   2150.000                 3                 1
Cotton(lint)           4350         1.383      4.000    300.000                 7                 0
Sesamum                8724         0.333      0.885    235.000                 1                 0
Rice                  15078         1.939      3.638    223.727                 1                 0
Potato                 6910        10.842     25.998    213.846                 1                 0
Banana                 3104        22.000     63.660    138.421                 6                 0
Papaya                  412        17.872    115.690    134.143                37                 0
Niger seed             2004         0.289      0.642     71.000                 0                 0
Tapioca                1583        11.450     42.165     70.516                 0                 0
Sunflower              5468         0.800      1.958     70.000                 0                 0
Mesta                  1769         5.000     12.476     68.000                 0                 0
Cabbage                  97        18.772     63.613     67.212                 0                 0
Pome Fruit              169         5.564     19.015     57.140                 0                 0
Sannhamp               2141         0.500      4.569     55.550                 0                 0
Tomato                  275         9.642     23.128     50.205                 0                 0
Groundnut              8732         1.046      2.268     49.000                 0                 0
Grapes                  110        23.948     31.360     42.928                 0                 0
Guar seed              1257         0.816      1.003     40.000                 0                 0
Dry ginger             2987         2.492     19.500     39.065                 0                 0
Sweet potato           4111         8.237     16.335     38.125                 0                 0
other oilseeds          572         0.500     12.598     32.575                 0                 0
Pineapple               247        14.647     26.167     32.099                 0                 0
Brinjal                 267         9.092     23.464     29.983                 0                 0
Other Fresh Fruits      153         3.073     10.606     25.258                 0                 0
Turmeric               4160         2.000      6.939     25.000                 0                 0
Dry chillies           6401         0.920      3.731     24.823                 0                 0

===== TOTAL EXTREME-RATIO COUNTS =====
Yield > 100: 1628
Yield > 500: 983
Yield > 1000: 969

In [ ]:

# Continue the audit — this cell does not change the original dataset.

# Reuse df and valid from your previous cell.
# If you restarted Colab, rerun the previous audit cell first.

print("===== SUGARCANE: HIGHEST YIELD RATIOS =====")

sugarcane = valid[
    valid["Crop"].astype(str).str.strip().str.casefold()
    .eq("sugarcane")
].copy()

print(
    sugarcane.sort_values("calculated_yield", ascending=False)[
        [
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "Production", "calculated_yield"
        ]
    ].head(25).to_string(index=False)
)

print("\n===== OTHER CROPS: RECORDS ABOVE 500 =====")

other_crops = valid[
    (valid["calculated_yield"] > 500) &
    (~valid["Crop"].astype(str).str.strip().str.casefold()
     .isin(["coconut", "sugarcane"]))
].copy()

print(
    other_crops[
        [
            "Crop", "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "Production", "calculated_yield"
        ]
    ].sort_values("calculated_yield", ascending=False)
    .to_string(index=False)
)

print("\n===== SUGARCANE: YEAR-WISE SUMMARY =====")

print(
    sugarcane.groupby("Crop_Year").agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield=("calculated_yield", "median"),
        max_yield=("calculated_yield", "max"),
        records_over_500=(
            "calculated_yield",
            lambda s: (s > 500).sum()
        )
    ).round(2).to_string()
)

===== SUGARCANE: HIGHEST YIELD RATIOS =====
State_Name   District_Name  Crop_Year      Season    Area  Production  calculated_yield
    Punjab         PATIALA       2011 Whole Year      3.0    264000.0      88000.000000
    Punjab         SANGRUR       2011 Whole Year      2.0    163000.0      81500.000000
    Punjab        LUDHIANA       2011 Whole Year      2.0    161000.0      80500.000000
    Punjab FATEHGARH SAHIB       2011 Whole Year      2.0    151000.0      75500.000000
    Punjab        RUPNAGAR       2011 Whole Year      3.0    224000.0      74666.666667
    Punjab       GURDASPUR       2011 Whole Year     20.0   1491000.0      74550.000000
    Punjab       PATHANKOT       2011 Whole Year      4.0    298000.0      74500.000000
    Punjab      KAPURTHALA       2011 Whole Year      3.0    221000.0      73666.666667
    Punjab         FAZILKA       2011 Whole Year      1.0     73000.0      73000.000000
    Punjab      NAWANSHAHR       2011 Whole Year      6.0    407000.0      67833.333333
    Punjab        AMRITSAR       2011 Whole Year      3.0    203000.0      67666.666667
    Punjab       JALANDHAR       2011 Whole Year      9.0    599000.0      66555.555556
    Punjab     S.A.S NAGAR       2011 Whole Year      1.0     65000.0      65000.000000
    Punjab      HOSHIARPUR       2011 Whole Year     20.0   1293000.0      64650.000000
    Punjab      TARN TARAN       2011 Whole Year      1.0     40000.0      40000.000000
Tamil Nadu         MADURAI       1997 Whole Year   8108.0  18223000.0       2247.533300
Tamil Nadu     THIRUVALLUR       1997 Whole Year   5964.0  11811000.0       1980.382294
Tamil Nadu     KANCHIPURAM       1997 Whole Year   6735.0   9896000.0       1469.339272
Tamil Nadu        NAMAKKAL       1997 Whole Year   9415.0  13608000.0       1445.353160
Tamil Nadu TIRUCHIRAPPALLI       1997 Whole Year   4315.0   5806000.0       1345.538818
Tamil Nadu       CUDDALORE       1997 Whole Year  23826.0  28322000.0       1188.701419
Tamil Nadu           KARUR       1997 Whole Year   5961.0   7081000.0       1187.887938
Tamil Nadu           SALEM       1997 Whole Year  13759.0  15866000.0       1153.136129
Tamil Nadu      COIMBATORE       1997 Whole Year  10756.0  12272000.0       1140.944589
Tamil Nadu      VILLUPURAM       1997 Whole Year  33175.0  37158000.0       1120.060286

===== OTHER CROPS: RECORDS ABOVE 500 =====
     Crop  State_Name District_Name  Crop_Year      Season  Area  Production  calculated_yield
Cashewnut  Tamil Nadu    PERAMBALUR       2008 Whole Year    1.0      9801.0       9801.000000
    Onion     Haryana        KARNAL       2008 Whole Year    2.0      4300.0       2150.000000
    Maize Maharashtra        NASHIK       1997 Autumn        1.0      1494.0       1494.000000
    Maize Maharashtra       JALGAON       1997 Autumn        3.0      3980.0       1326.666667
    Maize Maharashtra          PUNE       1997 Autumn        4.0      4570.0       1142.500000
    Maize Maharashtra     OSMANABAD       1997 Autumn        5.0      5635.0       1127.000000
    Maize Maharashtra    AHMEDNAGAR       1997 Autumn        1.0      1113.0       1113.000000
    Maize Maharashtra         DHULE       1997 Autumn        4.0      2901.0        725.250000

===== SUGARCANE: YEAR-WISE SUMMARY =====
           records  median_area  median_production  median_yield  max_yield  records_over_500
Crop_Year
1997           330       1805.0            92307.5         55.37    2247.53                28
1998           408       1188.0            54700.0         51.85     303.48                 0
1999           440       1143.5            59060.5         54.52     162.50                 0
2000           466       1009.5            37010.0         49.52     162.00                 0
2001           458       1006.5            45901.5         51.95     158.57                 0
2002           463        885.0            36160.0         50.00     162.00                 0
2003           458        838.5            39795.0         49.33     163.33                 0
2004           423        759.0            34395.0         51.27     162.50                 0
2005           469        704.0            31833.0         53.79     147.26                 0
2006           402        648.0            27150.0         54.24     188.41                 0
2007           460        568.5            23572.5         52.40     138.98                 0
2008           482        724.0            32580.0         51.15     314.74                 0
2009           458        554.0            23683.0         53.19     150.00                 0
2010           463        673.0            28586.0         53.49     157.38                 0
2011           405        802.0            56000.0         56.41   88000.00                15
2012           443        939.0            54407.0         58.80     159.63                 0
2013           411        910.0            48862.2         58.40     220.62                 0
2014           347        830.0            45809.0         60.12     179.87                 0
2015            28        106.5             6405.9         57.11      78.83                 0

In [ ]:

# Create a review file only. The original dataset remains unchanged.

import os

review = valid.copy()

review["audit_reason"] = ""

review.loc[
    review["calculated_yield"] > 500,
    "audit_reason"
] += "Yield ratio above 500; verify source and units. "

review.loc[
    (review["Area"] <= 5) &
    (review["calculated_yield"] > 100),
    "audit_reason"
] += "Very small reported area with high ratio. "

review.loc[
    (
        review["Crop"].astype(str).str.strip().str.casefold()
        .eq("coconut")
    ),
    "audit_reason"
] += "Coconut production unit needs verification. "

review.loc[
    (
        review["Crop"].astype(str).str.strip().str.casefold()
        .eq("sugarcane")
    ) &
    (
        ((review["State_Name"] == "Punjab") &
         (review["Crop_Year"] == 2011)) |
        ((review["State_Name"] == "Tamil Nadu") &
         (review["Crop_Year"] == 1997))
    ),
    "audit_reason"
] += "Known sugarcane anomaly group; verify source. "

review = review[review["audit_reason"] != ""].copy()

output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "yield_anomaly_review.csv"
)

review.to_csv(output_path, index=False)

print("Review records saved:", len(review))
print("File:", output_path)
print("\nFlagged records by crop:")
print(
    review.groupby("Crop").size()
    .sort_values(ascending=False)
    .head(20)
    .to_string()
)

Review records saved: 2033
File: /content/drive/MyDrive/yield prediction/yield_anomaly_review.csv

Flagged records by crop:
Crop
Coconut         1957
Sugarcane         66
Maize              6
Cotton(lint)       1
Cashewnut          1
Onion              1
Papaya             1

In [ ]:

import pandas as pd
import numpy as np
import os

input_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_cleaned.csv"
)

df = pd.read_csv(input_path, low_memory=False)

# Convert columns used to calculate yield.
for col in ["Area", "Production"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Calculate yield only where Area and Production are positive.
valid = (
    (df["Area"] > 0) &
    (df["Production"] > 0)
)

yield_values = pd.Series(np.nan, index=df.index, dtype=float)
yield_values.loc[valid] = (
    df.loc[valid, "Production"] / df.loc[valid, "Area"]
)

# Remove only the four individually flagged records.
# Match crop, state, district, year, season, area and production
# using the review file to identify the exact records.
review_path = (
    "/content/drive/MyDrive/yield prediction/"
    "yield_anomaly_review.csv"
)

review_df = pd.read_csv(review_path, low_memory=False)

target_crops = [
    "Cotton(lint)", "Cashewnut", "Onion", "Papaya"
]

targets = review_df[
    review_df["Crop"].isin(target_crops)
].copy()

# Keep only records flagged for a high ratio or very small area.
# The user requested the four individual records, not all records
# from these crop classes.
targets = targets[
    targets["audit_reason"].str.contains(
        "Yield ratio above 500|Very small reported area",
        case=False,
        na=False,
        regex=True
    )
]

key_cols = [
    "Crop", "State_Name", "District_Name",
    "Crop_Year", "Season", "Area", "Production"
]

# Normalize text for reliable matching.
def normalize_text(series):
    return series.astype("string").str.strip().str.casefold()

remove_mask = pd.Series(False, index=df.index)

for _, target in targets.iterrows():
    match = pd.Series(True, index=df.index)

    for col in key_cols:
        if col in ["Area", "Production", "Crop_Year"]:
            source_values = pd.to_numeric(df[col], errors="coerce")
            target_value = pd.to_numeric(
                pd.Series([target[col]]), errors="coerce"
            ).iloc[0]
            match &= source_values.eq(target_value)
        else:
            match &= normalize_text(df[col]).eq(
                str(target[col]).strip().casefold()
            )

    remove_mask |= match

cleaned_df = df.loc[~remove_mask].copy()

print("Original rows:", len(df))
print("Rows removed:", int(remove_mask.sum()))
print("Cleaned rows:", len(cleaned_df))

if int(remove_mask.sum()) != len(targets):
    print(
        "WARNING: The number of matched rows differs from the "
        "number of target records. Review matches before training."
    )
else:
    cleaned_df.to_csv(output_path, index=False)
    print("Cleaned dataset saved:", output_path)

Original rows: 246091
Rows removed: 4
Cleaned rows: 246087
Cleaned dataset saved: /content/drive/MyDrive/yield prediction/crop_production_124_cleaned.csv

In [ ]:

import pandas as pd
import numpy as np
import os

# ============================================
# 1. FILE PATHS
# ============================================

input_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_with_weather_soil.csv"
)

output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_clean.csv"
)

review_output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "remaining_yield_records_to_review.csv"
)

# ============================================
# 2. LOAD ORIGINAL DATA
# ============================================

df = pd.read_csv(input_path, low_memory=False)

print("Original dataset shape:", df.shape)

# Normalize crop, state and district text for matching.
crop_norm = df["Crop"].astype("string").str.strip().str.casefold()
state_norm = df["State_Name"].astype("string").str.strip().str.casefold()

year = pd.to_numeric(df["Crop_Year"], errors="coerce")
area = pd.to_numeric(df["Area"], errors="coerce")
production = pd.to_numeric(df["Production"], errors="coerce")

# ============================================
# 3. CALCULATE YIELD FOR AUDIT PURPOSES
# ============================================

valid_yield = (area > 0) & (production > 0)

calculated_yield = pd.Series(
    np.nan, index=df.index, dtype=float
)

calculated_yield.loc[valid_yield] = (
    production.loc[valid_yield] / area.loc[valid_yield]
)

# ============================================
# 4. EXCLUDE COCONUT
# ============================================

coconut_mask = crop_norm.eq("coconut").fillna(False)

# ============================================
# 5. EXCLUDE THE 15 PUNJAB SUGARCANE RECORDS
#    FROM 2011
# ============================================

sugarcane_mask = crop_norm.eq("sugarcane").fillna(False)

punjab_mask = state_norm.eq("punjab").fillna(False)

punjab_sugarcane_2011 = (
    sugarcane_mask &
    punjab_mask &
    year.eq(2011)
)

# ============================================
# 6. BUILD TRAINING DATASET
# ============================================

exclude_mask = coconut_mask | punjab_sugarcane_2011

training_df = df.loc[~exclude_mask].copy()

# ============================================
# 7. FLAG OTHER EXTREME RECORDS FOR REVIEW
# ============================================

remaining_indices = training_df.index

remaining_yield = calculated_yield.loc[remaining_indices]

remaining_crop = (
    training_df["Crop"]
    .astype("string")
    .str.strip()
    .str.casefold()
)

# Flag high ratios in the remaining dataset.
maize_extreme = (
    remaining_crop.eq("maize").fillna(False) &
    remaining_yield.gt(500)
)

sugarcane_tamil_nadu_1997 = (
    remaining_crop.eq("sugarcane").fillna(False) &
    training_df["State_Name"].astype("string")
    .str.strip().str.casefold().eq("tamil nadu").fillna(False) &
    pd.to_numeric(
        training_df["Crop_Year"], errors="coerce"
    ).eq(1997)
)

other_extreme = (
    remaining_yield.gt(500) |
    maize_extreme |
    sugarcane_tamil_nadu_1997
)

review_df = training_df.loc[other_extreme].copy()

review_df["calculated_yield"] = remaining_yield.loc[
    review_df.index
]

review_df["review_reason"] = np.where(
    review_df["Crop"].astype("string").str.strip()
    .str.casefold().eq("maize"),
    "Extreme maize yield ratio: verify source and units",
    np.where(
        review_df["State_Name"].astype("string").str.strip()
        .str.casefold().eq("tamil nadu") &
        pd.to_numeric(
            review_df["Crop_Year"], errors="coerce"
        ).eq(1997),
        "Tamil Nadu sugarcane 1997: verify source and units",
        "Extreme yield ratio: verify source and units"
    )
)

# ============================================
# 8. SAVE SEPARATE FILES
# ============================================

training_df.to_csv(output_path, index=False)
review_df.to_csv(review_output_path, index=False)

# ============================================
# 9. REPORT RESULTS
# ============================================

print("\n========== CLEANING SUMMARY ==========")
print("Original rows:", len(df))
print("Coconut rows excluded:", int(coconut_mask.sum()))
print(
    "Punjab Sugarcane 2011 rows excluded:",
    int(punjab_sugarcane_2011.sum())
)
print("Total rows excluded:", int(exclude_mask.sum()))
print("Training dataset rows:", len(training_df))
print("Records flagged for further review:", len(review_df))

print("\nTraining dataset shape:", training_df.shape)
print("\nFiles saved:")
print(output_path)
print(review_output_path)

print("\nRemaining crops:", training_df["Crop"].nunique())
print("Missing Production:", training_df["Production"].isna().sum())

Original dataset shape: (246091, 11)

========== CLEANING SUMMARY ==========
Original rows: 246091
Coconut rows excluded: 1985
Punjab Sugarcane 2011 rows excluded: 15
Total rows excluded: 2000
Training dataset rows: 244091
Records flagged for further review: 36

Training dataset shape: (244091, 11)

Files saved:
/content/drive/MyDrive/yield prediction/crop_production_124_training_clean.csv
/content/drive/MyDrive/yield prediction/remaining_yield_records_to_review.csv

Remaining crops: 123
Missing Production: 3703

In [ ]:

import pandas as pd
import numpy as np

input_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_clean.csv"
)

train_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

missing_path = (
    "/content/drive/MyDrive/yield prediction/"
    "records_missing_production.csv"
)

df = pd.read_csv(input_path, low_memory=False)

df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(
    df["Production"], errors="coerce"
)

# Keep rows that have a usable target and positive area.
usable = (
    df["Production"].notna() &
    df["Area"].notna() &
    (df["Area"] > 0) &
    (df["Production"] > 0)
)

training = df.loc[usable].copy()
missing = df.loc[df["Production"].isna()].copy()

# Derive the target; do not use it as a feature.
training["yield_per_area"] = (
    training["Production"] / training["Area"]
)

training.to_csv(train_path, index=False)
missing.to_csv(missing_path, index=False)

print("Original rows:", len(df))
print("Rows ready for supervised training:", len(training))
print("Rows missing production:", int(df["Production"].isna().sum()))
print("Rows excluded for missing/invalid target or area:",
      len(df) - len(training))
print("Training file:", train_path)
print("Missing-production file:", missing_path)
print("\nYield summary:")
print(training["yield_per_area"].describe().round(3))

Original rows: 244091
Rows ready for supervised training: 236866
Rows missing production: 3703
Rows excluded for missing/invalid target or area: 7225
Training file: /content/drive/MyDrive/yield prediction/crop_production_124_training_ready.csv
Missing-production file: /content/drive/MyDrive/yield prediction/records_missing_production.csv

Yield summary:
count    236866.000
mean          4.709
std          27.764
min           0.000
25%           0.529
50%           1.000
75%           2.333
max        9801.000
Name: yield_per_area, dtype: float64

In [ ]:

import pandas as pd
import numpy as np

input_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_clean.csv"
)

train_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

missing_path = (
    "/content/drive/MyDrive/yield prediction/"
    "records_missing_production.csv"
)

df = pd.read_csv(input_path, low_memory=False)

df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(
    df["Production"], errors="coerce"
)

# Keep rows that have a usable target and positive area.
usable = (
    df["Production"].notna() &
    df["Area"].notna() &
    (df["Area"] > 0) &
    (df["Production"] > 0)
)

training = df.loc[usable].copy()
missing = df.loc[df["Production"].isna()].copy()

# Derive the target; do not use it as a feature.
training["yield_per_area"] = (
    training["Production"] / training["Area"]
)

training.to_csv(train_path, index=False)
missing.to_csv(missing_path, index=False)

print("Original rows:", len(df))
print("Rows ready for supervised training:", len(training))
print("Rows missing production:", int(df["Production"].isna().sum()))
print("Rows excluded for missing/invalid target or area:",
      len(df) - len(training))
print("Training file:", train_path)
print("Missing-production file:", missing_path)
print("\nYield summary:")
print(training["yield_per_area"].describe().round(3))

Original rows: 244091
Rows ready for supervised training: 236866
Rows missing production: 3703
Rows excluded for missing/invalid target or area: 7225
Training file: /content/drive/MyDrive/yield prediction/crop_production_124_training_ready.csv
Missing-production file: /content/drive/MyDrive/yield prediction/records_missing_production.csv

Yield summary:
count    236866.000
mean          4.709
std          27.764
min           0.000
25%           0.529
50%           1.000
75%           2.333
max        9801.000
Name: yield_per_area, dtype: float64

In [ ]:

import pandas as pd
import numpy as np

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

df = pd.read_csv(file_path, low_memory=False)

df["yield_per_area"] = pd.to_numeric(
    df["yield_per_area"], errors="coerce"
)

print("===== YIELD DISTRIBUTION =====")
print(
    df["yield_per_area"]
    .quantile([0.50, 0.90, 0.95, 0.99, 0.995, 0.999, 1.0])
    .to_string()
)

print("\n===== TOP 30 HIGHEST YIELD RECORDS =====")
cols = [
    "Crop", "State_Name", "District_Name",
    "Crop_Year", "Season", "Area",
    "Production", "yield_per_area"
]

print(
    df.sort_values("yield_per_area", ascending=False)[cols]
    .head(30)
    .to_string(index=False)
)

print("\n===== COUNTS ABOVE THRESHOLDS =====")
for threshold in [100, 500, 1000]:
    print(
        f"Yield > {threshold}:",
        int((df["yield_per_area"] > threshold).sum())
    )

print("\n===== CROPS WITH HIGHEST MAXIMUM YIELD =====")
print(
    df.groupby("Crop")["yield_per_area"]
    .agg(["count", "median", "max"])
    .sort_values("max", ascending=False)
    .head(20)
    .round(3)
    .to_string()
)

===== YIELD DISTRIBUTION =====
0.500       1.000000
0.900       9.400000
0.950      20.888889
0.990      68.480678
0.995      87.681139
0.999     119.369935
1.000    9801.000000

===== TOP 30 HIGHEST YIELD RECORDS =====
     Crop  State_Name   District_Name  Crop_Year      Season    Area  Production  yield_per_area
Cashewnut  Tamil Nadu      PERAMBALUR       2008 Whole Year      1.0      9801.0     9801.000000
Sugarcane  Tamil Nadu         MADURAI       1997 Whole Year   8108.0  18223000.0     2247.533300
    Onion     Haryana          KARNAL       2008 Whole Year      2.0      4300.0     2150.000000
Sugarcane  Tamil Nadu     THIRUVALLUR       1997 Whole Year   5964.0  11811000.0     1980.382294
    Maize Maharashtra          NASHIK       1997 Autumn          1.0      1494.0     1494.000000
Sugarcane  Tamil Nadu     KANCHIPURAM       1997 Whole Year   6735.0   9896000.0     1469.339272
Sugarcane  Tamil Nadu        NAMAKKAL       1997 Whole Year   9415.0  13608000.0     1445.353160
Sugarcane  Tamil Nadu TIRUCHIRAPPALLI       1997 Whole Year   4315.0   5806000.0     1345.538818
    Maize Maharashtra         JALGAON       1997 Autumn          3.0      3980.0     1326.666667
Sugarcane  Tamil Nadu       CUDDALORE       1997 Whole Year  23826.0  28322000.0     1188.701419
Sugarcane  Tamil Nadu           KARUR       1997 Whole Year   5961.0   7081000.0     1187.887938
Sugarcane  Tamil Nadu           SALEM       1997 Whole Year  13759.0  15866000.0     1153.136129
    Maize Maharashtra            PUNE       1997 Autumn          4.0      4570.0     1142.500000
Sugarcane  Tamil Nadu      COIMBATORE       1997 Whole Year  10756.0  12272000.0     1140.944589
    Maize Maharashtra       OSMANABAD       1997 Autumn          5.0      5635.0     1127.000000
Sugarcane  Tamil Nadu      VILLUPURAM       1997 Whole Year  33175.0  37158000.0     1120.060286
Sugarcane  Tamil Nadu           ERODE       1997 Whole Year  24112.0  26930000.0     1116.871267
    Maize Maharashtra      AHMEDNAGAR       1997 Autumn          1.0      1113.0     1113.000000
Sugarcane  Tamil Nadu           THENI       1997 Whole Year   9524.0  10598000.0     1112.767745
Sugarcane  Tamil Nadu    THE NILGIRIS       1997 Whole Year     22.0     24000.0     1090.909091
Sugarcane  Tamil Nadu       TUTICORIN       1997 Whole Year     90.0     97000.0     1077.777778
Sugarcane  Tamil Nadu     TIRUNELVELI       1997 Whole Year   2237.0   2402000.0     1073.759499
Sugarcane  Tamil Nadu    NAGAPATTINAM       1997 Whole Year   4601.0   4940000.0     1073.679635
Sugarcane  Tamil Nadu     PUDUKKOTTAI       1997 Whole Year   2377.0   2552000.0     1073.622213
Sugarcane  Tamil Nadu    VIRUDHUNAGAR       1997 Whole Year   2639.0   2833000.0     1073.512694
Sugarcane  Tamil Nadu  RAMANATHAPURAM       1997 Whole Year    182.0    195000.0     1071.428571
Sugarcane  Tamil Nadu      DHARMAPURI       1997 Whole Year  18938.0  18100000.0      955.750343
Sugarcane  Tamil Nadu      PERAMBALUR       1997 Whole Year  11508.0  10448000.0      907.890163
Sugarcane  Tamil Nadu  TIRUVANNAMALAI       1997 Whole Year  27636.0  23914000.0      865.320596
Sugarcane  Tamil Nadu        DINDIGUL       1997 Whole Year   6826.0   5749000.0      842.220920

===== COUNTS ABOVE THRESHOLDS =====
Yield > 100: 655
Yield > 500: 36
Yield > 1000: 26

===== CROPS WITH HIGHEST MAXIMUM YIELD =====
              count  median       max
Crop
Cashewnut      1065   0.397  9801.000
Sugarcane      7799  53.228  2247.533
Onion          6979  10.300  2150.000
Maize         13723   1.800  1494.000
Cotton(lint)   4350   1.383   300.000
Sesamum        8724   0.333   235.000
Rice          15078   1.939   223.727
Potato         6910  10.842   213.846
Banana         3104  22.000   138.421
Papaya          412  17.872   134.143
Niger seed     2004   0.289    71.000
Tapioca        1583  11.450    70.516
Sunflower      5468   0.800    70.000
Mesta          1769   5.000    68.000
Cabbage          97  18.772    67.212
Pome Fruit      169   5.564    57.140
Sannhamp       2141   0.500    55.550
Tomato          275   9.642    50.205
Groundnut      8732   1.046    49.000
Grapes          110  23.948    42.928

In [ ]:

import pandas as pd
import numpy as np

input_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

output_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready_v2.csv"
)

df = pd.read_csv(input_path, low_memory=False)

df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(
    df["Production"], errors="coerce"
)

crop = df["Crop"].astype(str).str.strip().str.casefold()

yield_value = df["Production"] / df["Area"].where(df["Area"] > 0)

# Remove extreme records for these crops only.
# Do not remove entire crop classes.
selected_crops = crop.isin(["maize", "cashewnut", "onion"])
extreme_mask = selected_crops & (yield_value > 500)

print("Maize/Cashewnut/Onion extreme records to remove:",
      int(extreme_mask.sum()))

# Create a separate file of the removed records for traceability.
removed = df.loc[extreme_mask].copy()
removed["calculated_yield"] = yield_value.loc[extreme_mask]

removed_path = (
    "/content/drive/MyDrive/yield prediction/"
    "excluded_extreme_maize_cashew_onion.csv"
)
removed.to_csv(removed_path, index=False)

revised = df.loc[~extreme_mask].copy()
revised.to_csv(output_path, index=False)

print("Rows before:", len(df))
print("Rows removed:", int(extreme_mask.sum()))
print("Rows after:", len(revised))
print("Revised dataset:", output_path)
print("Removed records saved separately:", removed_path)

print("\nTop 10 remaining yield values:")
print(
    revised.nlargest(10, "yield_per_area")[
        ["Crop", "State_Name", "District_Name",
         "Crop_Year", "Area", "Production", "yield_per_area"]
    ].to_string(index=False)
)

Maize/Cashewnut/Onion extreme records to remove: 8
Rows before: 236866
Rows removed: 8
Rows after: 236858
Revised dataset: /content/drive/MyDrive/yield prediction/crop_production_124_training_ready_v2.csv
Removed records saved separately: /content/drive/MyDrive/yield prediction/excluded_extreme_maize_cashew_onion.csv

Top 10 remaining yield values:
     Crop State_Name   District_Name  Crop_Year    Area  Production  yield_per_area
Sugarcane Tamil Nadu         MADURAI       1997  8108.0  18223000.0     2247.533300
Sugarcane Tamil Nadu     THIRUVALLUR       1997  5964.0  11811000.0     1980.382294
Sugarcane Tamil Nadu     KANCHIPURAM       1997  6735.0   9896000.0     1469.339272
Sugarcane Tamil Nadu        NAMAKKAL       1997  9415.0  13608000.0     1445.353160
Sugarcane Tamil Nadu TIRUCHIRAPPALLI       1997  4315.0   5806000.0     1345.538818
Sugarcane Tamil Nadu       CUDDALORE       1997 23826.0  28322000.0     1188.701419
Sugarcane Tamil Nadu           KARUR       1997  5961.0   7081000.0     1187.887938
Sugarcane Tamil Nadu           SALEM       1997 13759.0  15866000.0     1153.136129
Sugarcane Tamil Nadu      COIMBATORE       1997 10756.0  12272000.0     1140.944589
Sugarcane Tamil Nadu      VILLUPURAM       1997 33175.0  37158000.0     1120.060286

In [ ]:

import pandas as pd

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready_v2.csv"
)

df = pd.read_csv(file_path, low_memory=False)

df["Crop_Year"] = pd.to_numeric(df["Crop_Year"], errors="coerce")
df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(df["Production"], errors="coerce")

crop = df["Crop"].astype(str).str.strip().str.casefold()
state = df["State_Name"].astype(str).str.strip().str.casefold()

sugarcane_tn = df[
    crop.eq("sugarcane") &
    state.eq("tamil nadu") &
    df["Crop_Year"].between(1996, 1999)
].copy()

sugarcane_tn["yield_per_area"] = (
    sugarcane_tn["Production"] / sugarcane_tn["Area"]
)

print("Records:", len(sugarcane_tn))

print(
    sugarcane_tn[
        ["State_Name", "District_Name", "Crop_Year",
         "Area", "Production", "yield_per_area"]
    ]
    .sort_values(["District_Name", "Crop_Year"])
    .to_string(index=False)
)

print("\n===== YEAR-WISE SUMMARY =====")
print(
    sugarcane_tn.groupby("Crop_Year").agg(
        records=("Crop", "size"),
        median_area=("Area", "median"),
        median_production=("Production", "median"),
        median_yield=("yield_per_area", "median"),
        max_yield=("yield_per_area", "max")
    ).round(2).to_string()
)

Records: 81
State_Name   District_Name  Crop_Year    Area  Production  yield_per_area
Tamil Nadu      COIMBATORE       1997 10756.0  12272000.0     1140.944589
Tamil Nadu      COIMBATORE       1998 13193.0   1467460.0      111.230198
Tamil Nadu      COIMBATORE       1999 11939.0   1195037.0      100.095234
Tamil Nadu       CUDDALORE       1997 23826.0  28322000.0     1188.701419
Tamil Nadu       CUDDALORE       1998 32654.0   4401890.0      134.804006
Tamil Nadu       CUDDALORE       1999 38500.0   4196384.0      108.996987
Tamil Nadu      DHARMAPURI       1997 18938.0  18100000.0      955.750343
Tamil Nadu      DHARMAPURI       1998 27836.0   2772300.0       99.594051
Tamil Nadu      DHARMAPURI       1999 25826.0   2311813.0       89.514946
Tamil Nadu        DINDIGUL       1997  6826.0   5749000.0      842.220920
Tamil Nadu        DINDIGUL       1998  7051.0    886010.0      125.657354
Tamil Nadu        DINDIGUL       1999  6655.0    799113.0      120.077085
Tamil Nadu           ERODE       1997 24112.0  26930000.0     1116.871267
Tamil Nadu           ERODE       1998 21581.0   2579080.0      119.506974
Tamil Nadu           ERODE       1999 22994.0   2933211.0      127.564191
Tamil Nadu     KANCHIPURAM       1997  6735.0   9896000.0     1469.339272
Tamil Nadu     KANCHIPURAM       1998 23801.0   5775500.0      242.657872
Tamil Nadu     KANCHIPURAM       1999  8256.0    996236.0      120.668120
Tamil Nadu           KARUR       1997  5961.0   7081000.0     1187.887938
Tamil Nadu           KARUR       1998 10193.0   1251010.0      122.732267
Tamil Nadu           KARUR       1999 11551.0   1293358.0      111.969353
Tamil Nadu         MADURAI       1997  8108.0  18223000.0     2247.533300
Tamil Nadu         MADURAI       1998 10081.0   3059430.0      303.484773
Tamil Nadu         MADURAI       1999  6971.0    863190.0      123.825850
Tamil Nadu    NAGAPATTINAM       1997  4601.0   4940000.0     1073.679635
Tamil Nadu    NAGAPATTINAM       1998  3959.0    485900.0      122.733013
Tamil Nadu    NAGAPATTINAM       1999  3852.0    344773.0       89.504933
Tamil Nadu        NAMAKKAL       1997  9415.0  13608000.0     1445.353160
Tamil Nadu        NAMAKKAL       1998  9411.0   1505330.0      159.954309
Tamil Nadu        NAMAKKAL       1999 10190.0   1361516.0      133.612954
Tamil Nadu      PERAMBALUR       1997 11508.0  10448000.0      907.890163
Tamil Nadu      PERAMBALUR       1998  9029.0    871980.0       96.575479
Tamil Nadu      PERAMBALUR       1999 12445.0   1393459.0      111.969385
Tamil Nadu     PUDUKKOTTAI       1997  2377.0   2552000.0     1073.622213
Tamil Nadu     PUDUKKOTTAI       1998  2829.0    347210.0      122.732414
Tamil Nadu     PUDUKKOTTAI       1999  3854.0    411553.0      106.785937
Tamil Nadu  RAMANATHAPURAM       1997   182.0    195000.0     1071.428571
Tamil Nadu  RAMANATHAPURAM       1998   257.0     31540.0      122.723735
Tamil Nadu  RAMANATHAPURAM       1999   352.0     37429.0      106.332386
Tamil Nadu           SALEM       1997 13759.0  15866000.0     1153.136129
Tamil Nadu           SALEM       1998 10765.0   1440330.0      133.797492
Tamil Nadu           SALEM       1999  8926.0   1192629.0      133.612929
Tamil Nadu       SIVAGANGA       1997  4794.0   3938000.0      821.443471
Tamil Nadu       SIVAGANGA       1998  4390.0    538790.0      122.731207
Tamil Nadu       SIVAGANGA       1999  5594.0    499493.0       89.290847
Tamil Nadu       THANJAVUR       1997 12604.0   9900000.0      785.464932
Tamil Nadu       THANJAVUR       1998 13897.0   1244250.0       89.533712
Tamil Nadu       THANJAVUR       1999 11718.0   1069224.0       91.246288
Tamil Nadu    THE NILGIRIS       1997    22.0     24000.0     1090.909091
Tamil Nadu    THE NILGIRIS       1998   104.0     12760.0      122.692308
Tamil Nadu    THE NILGIRIS       1999   240.0     25723.0      107.179167
Tamil Nadu           THENI       1997  9524.0  10598000.0     1112.767745
Tamil Nadu           THENI       1998 16133.0   3617820.0      224.249675
Tamil Nadu           THENI       1999 13515.0   1622842.0      120.077100
Tamil Nadu     THIRUVALLUR       1997  5964.0  11811000.0     1980.382294
Tamil Nadu     THIRUVALLUR       1998  8284.0   1432090.0      172.874215
Tamil Nadu     THIRUVALLUR       1999 11280.0   1361136.0      120.668085
Tamil Nadu      THIRUVARUR       1997  3669.0   2287000.0      623.330608
Tamil Nadu      THIRUVARUR       1998  3126.0    383660.0      122.731926
Tamil Nadu      THIRUVARUR       1999  2174.0    198369.0       91.246090
Tamil Nadu TIRUCHIRAPPALLI       1997  4315.0   5806000.0     1345.538818
Tamil Nadu TIRUCHIRAPPALLI       1998 13204.0   1899500.0      143.857922
Tamil Nadu TIRUCHIRAPPALLI       1999  6241.0    698801.0      111.969396
Tamil Nadu     TIRUNELVELI       1997  2237.0   2402000.0     1073.759499
Tamil Nadu     TIRUNELVELI       1998  2662.0    326710.0      122.731029
Tamil Nadu     TIRUNELVELI       1999  5911.0    589966.0       99.808154
Tamil Nadu  TIRUVANNAMALAI       1997 27636.0  23914000.0      865.320596
Tamil Nadu  TIRUVANNAMALAI       1998 27897.0   2731420.0       97.910886
Tamil Nadu  TIRUVANNAMALAI       1999 26753.0   2446320.0       91.440960
Tamil Nadu       TUTICORIN       1997    90.0     97000.0     1077.777778
Tamil Nadu       TUTICORIN       1998    31.0      3800.0      122.580645
Tamil Nadu       TUTICORIN       1999   131.0     14020.0      107.022901
Tamil Nadu         VELLORE       1997 29072.0  22069000.0      759.115300
Tamil Nadu         VELLORE       1998 27098.0   2156460.0       79.580043
Tamil Nadu         VELLORE       1999 30528.0   2660060.0       87.135089
Tamil Nadu      VILLUPURAM       1997 33175.0  37158000.0     1120.060286
Tamil Nadu      VILLUPURAM       1998 44737.0   4995600.0      111.665959
Tamil Nadu      VILLUPURAM       1999 42884.0   4668718.0      108.868529
Tamil Nadu    VIRUDHUNAGAR       1997  2639.0   2833000.0     1073.512694
Tamil Nadu    VIRUDHUNAGAR       1998  3707.0    454970.0      122.732668
Tamil Nadu    VIRUDHUNAGAR       1999  3052.0    317444.0      104.011796

===== YEAR-WISE SUMMARY =====
           records  median_area  median_production  median_yield  max_yield
Crop_Year
1997            27       6826.0          9900000.0       1077.78    2247.53
1998            27      10081.0          1432090.0        122.73     303.48
1999            27       8926.0          1069224.0        107.18     133.61

In [ ]:

import pandas as pd

input_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready_v2.csv"
)

df = pd.read_csv(input_path, low_memory=False)

# Normalize text for reliable filtering
crop = df["Crop"].astype(str).str.strip().str.casefold()
state = df["State_Name"].astype(str).str.strip().str.casefold()
year = pd.to_numeric(df["Crop_Year"], errors="coerce")

# Isolate the suspicious records for review
review_mask = (
    crop.eq("sugarcane")
    & state.eq("tamil nadu")
    & year.eq(1997)
)

review_records = df.loc[review_mask].copy()
remaining_records = df.loc[~review_mask].copy()

# Save both outputs separately; preserve the current dataset
review_path = (
    "/content/drive/MyDrive/yield prediction/"
    "review_tamil_nadu_sugarcane_1997.csv"
)

review_dataset_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready_review_v1.csv"
)

review_records.to_csv(review_path, index=False)
remaining_records.to_csv(review_dataset_path, index=False)

print("Records flagged:", len(review_records))
print("Original training-ready rows:", len(df))
print("Rows in review dataset:", len(remaining_records))
print("Review records saved to:", review_path)
print("Separate review dataset saved to:", review_dataset_path)

Records flagged: 27
Original training-ready rows: 236858
Rows in review dataset: 236831
Review records saved to: /content/drive/MyDrive/yield prediction/review_tamil_nadu_sugarcane_1997.csv
Separate review dataset saved to: /content/drive/MyDrive/yield prediction/crop_production_124_training_ready_review_v1.csv

# XGBoost model training

In [ ]:

# ============================================================
# CropSense AI: Complete Yield Prediction Pipeline
# Preprocessing + Train/Validation/Test + XGBoost
# ============================================================

!pip -q install xgboost scikit-learn joblib

import os
import numpy as np
import pandas as pd
import joblib

from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
from xgboost import XGBRegressor

# ------------------------------------------------------------
# 1. Mount Google Drive and load data
# ------------------------------------------------------------

drive.mount("/content/drive")

file_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

df = pd.read_csv(file_path, low_memory=False)
df.columns = df.columns.str.strip()

print("=" * 60)
print("DATASET LOADED")
print("=" * 60)
print("Original shape:", df.shape)
print("Columns:", df.columns.tolist())

# ------------------------------------------------------------
# 2. Verify required columns
# ------------------------------------------------------------

required_columns = [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production",
    "temperature", "humidity", "rainfall_mm", "soil_type"
]

missing_columns = [
    c for c in required_columns if c not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing columns: {missing_columns}. "
        "Check your dataset's actual column names."
    )

# ------------------------------------------------------------
# 3. Data cleaning and target calculation
# ------------------------------------------------------------

numeric_columns = [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Remove rows that cannot provide a valid supervised target
df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

# Target: production per unit area
df["yield_per_area"] = df["Production"] / df["Area"]

df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

print("\nRows after target validation:", len(df))
print("Unique crops:", df["Crop"].nunique())
print(
    "Year range:",
    int(df["Crop_Year"].min()),
    "to",
    int(df["Crop_Year"].max())
)

# ------------------------------------------------------------
# 4. Define features and target
# ------------------------------------------------------------

categorical_features = [
    "State_Name",
    "District_Name",
    "Season",
    "Crop",
    "soil_type"
]

numeric_features = [
    "Crop_Year",
    "temperature",
    "humidity",
    "rainfall_mm"
]

feature_columns = categorical_features + numeric_features

# IMPORTANT:
# Area and Production are NOT input features.
X = df[feature_columns].copy()
y = df["yield_per_area"].copy()

# Normalize categorical data; remaining missing values are
# handled inside the preprocessing pipeline.
for col in categorical_features:
    X[col] = (
        X[col]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace("", "Unknown")
    )

# ------------------------------------------------------------
# 5. Chronological train/validation/test split
# ------------------------------------------------------------
# Train: 1997–2011
# Validation: 2012–2013
# Test: 2014–2015
#
# This simulates predicting future years from historical data.

train_mask = df["Crop_Year"] <= 2011
val_mask = df["Crop_Year"].isin([2012, 2013])
test_mask = df["Crop_Year"].isin([2014, 2015])

if not train_mask.any() or not val_mask.any() or not test_mask.any():
    raise ValueError(
        "One or more splits are empty. Check the year range."
    )

X_train, y_train = X.loc[train_mask], y.loc[train_mask]
X_val, y_val = X.loc[val_mask], y.loc[val_mask]
X_test, y_test = X.loc[test_mask], y.loc[test_mask]

print("\n" + "=" * 60)
print("TRAIN / VALIDATION / TEST SPLIT")
print("=" * 60)

for name, mask, target in [
    ("TRAIN", train_mask, y_train),
    ("VALIDATION", val_mask, y_val),
    ("TEST", test_mask, y_test)
]:
    years = df.loc[mask, "Crop_Year"]
    print(
        f"{name:12} | Rows: {len(target):,} | "
        f"Years: {int(years.min())}-{int(years.max())}"
    )

# ------------------------------------------------------------
# 6. Build preprocessing pipeline
# ------------------------------------------------------------

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# ------------------------------------------------------------
# 7. Build XGBoost regression model
# ------------------------------------------------------------

xgb = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.85,
    colsample_bytree=0.85,
    reg_lambda=5,
    random_state=42,
    n_jobs=-1,
    tree_method="hist"
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", xgb)
])

# ------------------------------------------------------------
# 8. Train
# ------------------------------------------------------------

print("\nTraining XGBoost model...")
model.fit(X_train, y_train)
print("Training completed!")

# ------------------------------------------------------------
# 9. Evaluate validation and test sets
# ------------------------------------------------------------

def evaluate_model(name, actual, predicted):
    mae = mean_absolute_error(actual, predicted)
    rmse = np.sqrt(mean_squared_error(actual, predicted))
    r2 = r2_score(actual, predicted)
    median_ae = np.median(
        np.abs(np.asarray(actual) - np.asarray(predicted))
    )

    print(f"\n{name}")
    print("-" * 40)
    print(f"MAE:        {mae:.4f}")
    print(f"RMSE:       {rmse:.4f}")
    print(f"R²:         {r2:.4f}")
    print(f"Median AE:  {median_ae:.4f}")

    return {
        "Dataset": name,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "Median_AE": median_ae
    }

val_predictions = model.predict(X_val)
test_predictions = model.predict(X_test)

val_metrics = evaluate_model(
    "VALIDATION RESULTS (2012–2013)",
    y_val,
    val_predictions
)

test_metrics = evaluate_model(
    "FINAL HELD-OUT TEST RESULTS (2014–2015)",
    y_test,
    test_predictions
)

metrics_df = pd.DataFrame([val_metrics, test_metrics])

# ------------------------------------------------------------
# 10. Save model, metrics and test predictions
# ------------------------------------------------------------

output_dir = "/content/drive/MyDrive/yield prediction"
os.makedirs(output_dir, exist_ok=True)

model_path = os.path.join(
    output_dir,
    "cropsense_xgboost_yield_pipeline.joblib"
)

metrics_path = os.path.join(
    output_dir,
    "cropsense_yield_evaluation_metrics.csv"
)

predictions_path = os.path.join(
    output_dir,
    "cropsense_yield_test_predictions.csv"
)

joblib.dump(model, model_path)
metrics_df.to_csv(metrics_path, index=False)

test_results = df.loc[test_mask, [
    "State_Name", "District_Name", "Crop_Year",
    "Season", "Crop", "Area", "Production",
    "yield_per_area"
]].copy()

test_results["predicted_yield"] = test_predictions
test_results["predicted_production"] = (
    test_results["predicted_yield"] * test_results["Area"]
)

test_results.to_csv(predictions_path, index=False)

print("\n" + "=" * 60)
print("SAVED OUTPUTS")
print("=" * 60)
print("Model:", model_path)
print("Metrics:", metrics_path)
print("Test predictions:", predictions_path)

print("\nSample test predictions:")
print(
    test_results[[
        "Crop", "Crop_Year", "Area",
        "yield_per_area", "predicted_yield",
        "Production", "predicted_production"
    ]].head(10).round(3).to_string(index=False)
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
============================================================
DATASET LOADED
============================================================
Original shape: (236866, 12)
Columns: ['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area', 'Production', 'temperature', 'humidity', 'rainfall_mm', 'soil_type', 'yield_per_area']

Rows after target validation: 236866
Unique crops: 104
Year range: 1997 to 2015

============================================================
TRAIN / VALIDATION / TEST SPLIT
============================================================
TRAIN        | Rows: 199,107 | Years: 1997-2011
VALIDATION   | Rows: 26,448 | Years: 2012-2013
TEST         | Rows: 11,311 | Years: 2014-2015

Training XGBoost model...
Training completed!

VALIDATION RESULTS (2012–2013)
----------------------------------------
MAE:        1.5811
RMSE:       5.0798
R²:         0.8473
Median AE:  0.5053

FINAL HELD-OUT TEST RESULTS (2014–2015)
----------------------------------------
MAE:        1.4705
RMSE:       4.5478
R²:         0.8756
Median AE:  0.4899

============================================================
SAVED OUTPUTS
============================================================
Model: /content/drive/MyDrive/yield prediction/cropsense_xgboost_yield_pipeline.joblib
Metrics: /content/drive/MyDrive/yield prediction/cropsense_yield_evaluation_metrics.csv
Test predictions: /content/drive/MyDrive/yield prediction/cropsense_yield_test_predictions.csv

Sample test predictions:
         Crop  Crop_Year    Area  yield_per_area  predicted_yield  Production  predicted_production
    Arhar/Tur       2014 37562.0           0.129         1.283000      4845.0             48208.215
        Bajra       2014  1752.0           0.587         1.399000      1028.0              2450.321
      Brinjal       2014   320.0          23.738        11.441000      7596.0              3661.052
      Cabbage       2014    10.0          12.300        50.353001       123.0               503.525
    Cashewnut       2014    19.0           0.368        -0.328000         7.0                -6.237
  Castor seed       2014 10320.0           0.572         1.382000      5903.0             14258.390
    Coriander       2014   162.0           0.519         1.399000        84.0               226.571
 Cotton(lint)       2014 73734.0           1.407         1.627000    103779.0            119981.381
Cowpea(Lobia)       2014   982.0           0.418         1.399000       410.0              1373.411
 Dry chillies       2014  2799.0           4.233         2.193000     11848.0              6137.121

In [ ]:

import numpy as np
import pandas as pd
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

path = (
    "/content/drive/MyDrive/yield prediction/"
    "cropsense_yield_test_predictions.csv"
)

results = pd.read_csv(path)

actual = results["yield_per_area"]
predicted = results["predicted_yield"]

# 1. Overall prediction checks
print("=" * 60)
print("TEST PREDICTION QUALITY AUDIT")
print("=" * 60)

print("Test records:", len(results))
print("Negative predicted yields:", int((predicted < 0).sum()))
print(
    "Negative prediction percentage:",
    round((predicted < 0).mean() * 100, 3), "%"
)
print("Actual yields <= 0:", int((actual <= 0).sum()))

# 2. Largest absolute prediction errors
results["absolute_error"] = np.abs(actual - predicted)

print("\n===== 20 LARGEST ABSOLUTE ERRORS =====")
print(
    results.sort_values("absolute_error", ascending=False)[[
        "State_Name", "District_Name", "Crop_Year",
        "Season", "Crop", "Area",
        "yield_per_area", "predicted_yield",
        "absolute_error"
    ]].head(20).round(4).to_string(index=False)
)

# 3. Crop-wise evaluation
crop_metrics = results.groupby("Crop").apply(
    lambda group: pd.Series({
        "records": len(group),
        "actual_median_yield": group["yield_per_area"].median(),
        "predicted_median_yield": group["predicted_yield"].median(),
        "MAE": mean_absolute_error(
            group["yield_per_area"], group["predicted_yield"]
        ),
        "RMSE": np.sqrt(mean_squared_error(
            group["yield_per_area"], group["predicted_yield"]
        )),
        "negative_predictions": int(
            (group["predicted_yield"] < 0).sum()
        )
    }),
    include_groups=False
).reset_index()

print("\n===== 20 CROPS WITH HIGHEST MAE =====")
print(
    crop_metrics.sort_values("MAE", ascending=False)
    .head(20).round(4).to_string(index=False)
)

# Save the audit report
out_path = (
    "/content/drive/MyDrive/yield prediction/"
    "cropsense_yield_cropwise_audit.csv"
)
crop_metrics.to_csv(out_path, index=False)

print("\nCrop-wise audit saved to:", out_path)

============================================================
TEST PREDICTION QUALITY AUDIT
============================================================
Test records: 11311
Negative predicted yields: 39
Negative prediction percentage: 0.345 %
Actual yields <= 0: 0

===== 20 LARGEST ABSOLUTE ERRORS =====
    State_Name  District_Name  Crop_Year      Season      Crop    Area  yield_per_area  predicted_yield  absolute_error
    Telangana      RANGAREDDI       2014 Kharif          Onion   24.00        114.1667          12.1718        101.9948
   West Bengal        HOOGHLY       2014 Whole Year  Sugarcane  830.00        179.8663          81.8572         98.0091
        Kerala         KANNUR       2014 Whole Year  Sugarcane    3.43         13.4111         109.9885         96.5774
   West Bengal MEDINIPUR WEST       2014 Whole Year  Sugarcane 4390.00        179.8665          97.7659         82.1006
        Kerala       PALAKKAD       2014 Whole Year  Sugarcane  371.81          8.4506          81.9844         73.5338
        Kerala         IDUKKI       2014 Whole Year  Sugarcane 1068.90         10.7700          82.1097         71.3397
        Kerala      ALAPPUZHA       2014 Whole Year  Sugarcane   54.90          0.4554          71.4665         71.0111
         Bihar          ARWAL       2014 Whole Year  Sugarcane   28.00        113.2857          44.9769         68.3088
         Bihar     AURANGABAD       2014 Whole Year  Sugarcane  132.00        112.8485          44.9769         67.8716
         Bihar      JEHANABAD       2014 Whole Year  Sugarcane   18.00        113.2778          45.5355         67.7423
         Bihar         NAWADA       2014 Whole Year  Sugarcane   23.00        113.2609          45.5355         67.7254
        Kerala       THRISSUR       2014 Whole Year  Sugarcane    0.24          8.3333          72.6385         64.3052
        Kerala PATHANAMTHITTA       2014 Whole Year  Sugarcane    5.30         10.0000          69.3012         59.3012
   West Bengal          NADIA       2014 Whole Year  Sugarcane 1754.00        141.5137          82.3639         59.1498
Andhra Pradesh       CHITTOOR       2014 Kharif         Papaya  519.00         26.5703          83.6847         57.1144
        Kerala       KOTTAYAM       2014 Whole Year  Sugarcane   10.21          7.1499          64.0203         56.8704
    Puducherry    PONDICHERRY       2014 Kharif      Sugarcane 1921.00        165.0000         114.8084         50.1916
Andhra Pradesh VISAKHAPATANAM       2014 Kharif        Cabbage  143.00          0.8392          49.8443         49.0051
Andhra Pradesh VISAKHAPATANAM       2014 Rabi          Cabbage   88.00          0.8409          49.8313         48.9904
Andhra Pradesh        KRISHNA       2014 Rabi          Cabbage   91.00          2.5824          50.0189         47.4365

===== 20 CROPS WITH HIGHEST MAE =====
              Crop  records  actual_median_yield  predicted_median_yield     MAE    RMSE  negative_predictions
           Cabbage     19.0              12.3210                 49.8623 38.6506 39.3322                   0.0
         Sugarcane    375.0              60.0000                 54.2545 12.4733 18.9057                   0.0
            Tomato     26.0              14.3766                  5.2315 11.7856 12.9473                   0.0
            Grapes      4.0              23.0000                 14.4541  9.8984 10.2782                   0.0
       Pome Granet      9.0              10.3636                  1.3986  8.8660  8.8697                   0.0
    other oilseeds     24.0               1.6851                  1.3429  8.1544 11.8559                   0.0
            Papaya     44.0              24.2875                 18.1309  7.6658 13.0834                   0.0
  Other Vegetables      2.0              11.4062                  3.7833  7.6229  7.6229                   0.0
Other Fresh Fruits      2.0              10.6448                  3.0885  7.5563  7.5563                   0.0
           Brinjal     29.0              14.9286                 10.8290  7.0321  8.5903                   0.0
            Sapota     13.0               8.3648                  1.3986  6.8954  6.9031                   0.0
        Dry ginger     99.0               4.6126                  3.9634  6.3976 10.7787                   0.0
             Mango     18.0               7.0750                  1.5711  6.2014  7.6546                   0.0
             Lemon     13.0               6.2000                  1.3986  6.1804  6.9856                   0.0
            Banana    119.0              31.1379                 27.9904  4.8504  6.1110                   0.0
          Arecanut     49.0               1.9365                  2.5952  3.4733  4.6701                   0.0
           Tapioca     73.0               9.5753                  9.1679  3.1930  4.7687                   0.0
              Jute     86.0              10.8822                  9.1329  3.0773  3.8320                   0.0
         Pineapple     30.0              16.0556                 14.1270  2.8851  3.7802                   0.0
            Potato    357.0              10.6102                 10.1180  2.8447  3.8090                   0.0

Crop-wise audit saved to: /content/drive/MyDrive/yield prediction/cropsense_yield_cropwise_audit.csv

# XGBoost Model

In [ ]:

import os
import numpy as np
import pandas as pd
import joblib

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

# Load the same dataset used for the original baseline
path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)
df = pd.read_csv(path, low_memory=False)
df.columns = df.columns.str.strip()

for col in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]
df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

categorical = [
    "State_Name", "District_Name", "Season", "Crop", "soil_type"
]
numeric = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = categorical + numeric

X = df[features].copy()
y = df["yield_per_area"].copy()

for col in categorical:
    X[col] = (
        X[col].fillna("Unknown").astype(str).str.strip()
        .replace("", "Unknown")
    )

train_mask = df["Crop_Year"] <= 2011
val_mask = df["Crop_Year"].isin([2012, 2013])
test_mask = df["Crop_Year"].isin([2014, 2015])

X_train, y_train = X.loc[train_mask], y.loc[train_mask]
X_val, y_val = X.loc[val_mask], y.loc[val_mask]
X_test, y_test = X.loc[test_mask], y.loc[test_mask]

preprocessor = ColumnTransformer([
    ("numeric", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), numeric),
    ("categorical", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical)
])

# Train on log-transformed target.
# Keep the pipeline so preprocessing is fitted on training data only.
log_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(
        objective="reg:squarederror",
        n_estimators=800,
        max_depth=8,
        learning_rate=0.05,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_lambda=5,
        random_state=42,
        n_jobs=-1,
        tree_method="hist"
    ))
])

print("Training log-target XGBoost...")
log_model.fit(X_train, np.log1p(y_train))
print("Training completed!")

# Convert predictions back to original yield units
val_pred = np.expm1(log_model.predict(X_val))
test_pred_raw = np.expm1(log_model.predict(X_test))

# Enforce physically valid nonnegative yield estimates
val_pred = np.maximum(val_pred, 0)
test_pred = np.maximum(test_pred_raw, 0)

def report(name, actual, predicted):
    print(f"\n{name}")
    print("MAE:", round(mean_absolute_error(actual, predicted), 4))
    print("RMSE:", round(np.sqrt(mean_squared_error(actual, predicted)), 4))
    print("R²:", round(r2_score(actual, predicted), 4))
    print("Negative predictions:", int((predicted < 0).sum()))

report("LOG MODEL — VALIDATION", y_val, val_pred)
report("LOG MODEL — TEST", y_test, test_pred)

# Crop-level test comparison
test_comparison = df.loc[test_mask, [
    "Crop", "yield_per_area"
]].copy()
test_comparison["predicted_yield"] = test_pred
test_comparison["absolute_error"] = np.abs(
    test_comparison["yield_per_area"]
    - test_comparison["predicted_yield"]
)

crop_report = test_comparison.groupby("Crop").agg(
    records=("absolute_error", "size"),
    actual_median=("yield_per_area", "median"),
    predicted_median=("predicted_yield", "median"),
    MAE=("absolute_error", "mean")
).sort_values("MAE", ascending=False)

print("\nTOP 15 CROPS BY MAE — LOG MODEL")
print(crop_report.head(15).round(4).to_string())

out_dir = "/content/drive/MyDrive/yield prediction"
joblib.dump(
    log_model,
    os.path.join(out_dir, "cropsense_xgboost_log_yield_pipeline.joblib")
)

test_comparison.to_csv(
    os.path.join(out_dir, "cropsense_log_model_test_predictions.csv"),
    index=False
)

print("\nLog-target model and test predictions saved.")

Training log-target XGBoost...
Training completed!

LOG MODEL — VALIDATION
MAE: 1.4189
RMSE: 5.2798
R²: 0.835
Negative predictions: 0

LOG MODEL — TEST
MAE: 1.3732
RMSE: 4.832
R²: 0.8596
Negative predictions: 0

TOP 15 CROPS BY MAE — LOG MODEL
                    records  actual_median  predicted_median      MAE
Crop
Grapes                    4        23.0000          6.300000  18.0596
Papaya                   44        24.2875         18.402201  17.2655
Cabbage                  19        12.3210         28.121599  17.0668
Sugarcane               375        60.0000         52.695301  13.7080
Tomato                   26        14.3766          4.102100  13.1284
Pome Granet               9        10.3636          1.164600   9.0964
Brinjal                  29        14.9286          8.026400   7.9519
other oilseeds           24         1.6851          1.440900   7.9291
Other Fresh Fruits        2        10.6448          2.837200   7.8075
Other Vegetables          2        11.4062          3.928400   7.4778
Sapota                   13         8.3648          1.168100   7.1203
Dry ginger               99         4.6126          3.818700   6.6801
Lemon                    13         6.2000          1.168200   6.3782
Mango                    18         7.0750          2.752600   5.2438
Banana                  119        31.1379         21.439600   4.7646

Log-target model and test predictions saved.

In [ ]:

import pandas as pd
import numpy as np

data_path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

pred_path = (
    "/content/drive/MyDrive/yield prediction/"
    "cropsense_log_model_test_predictions.csv"
)

# Load original data and predictions
df = pd.read_csv(data_path, low_memory=False)
results = pd.read_csv(pred_path)

# Recreate the same filtering used during training
df.columns = df.columns.str.strip()

for col in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]
df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

# Recreate the chronological test split
test_mask = df["Crop_Year"].isin([2014, 2015])
test_df = df.loc[test_mask].copy().reset_index(drop=True)

# Confirm row counts before attaching predictions
print("Test rows in source dataset:", len(test_df))
print("Rows in prediction file:", len(results))

if len(test_df) != len(results):
    raise ValueError(
        "Row counts do not match. Do not merge by row position; "
        "inspect the prediction file and training filtering."
    )

# The saved predictions were generated from this same ordered test split.
results = results.reset_index(drop=True)

test_df["predicted_yield"] = results["predicted_yield"].to_numpy()
test_df["absolute_error"] = np.abs(
    test_df["yield_per_area"] - test_df["predicted_yield"]
)

# 1. Target distribution
print("\n===== TEST TARGET DISTRIBUTION =====")
print(
    test_df["yield_per_area"]
    .quantile([0.50, 0.90, 0.95, 0.99, 0.995, 0.999])
    .round(4).to_string()
)

# 2. Largest actual yields
print("\n===== 25 LARGEST ACTUAL YIELDS =====")
print(
    test_df.sort_values("yield_per_area", ascending=False)[[
        "State_Name", "District_Name", "Crop_Year",
        "Season", "Crop", "Area",
        "yield_per_area", "predicted_yield", "absolute_error"
    ]].head(25).round(4).to_string(index=False)
)

# 3. Sugarcane performance by year
print("\n===== SUGARCANE TEST PERFORMANCE BY YEAR =====")
sugarcane = test_df[
    test_df["Crop"].astype(str).str.strip().str.casefold()
    .eq("sugarcane")
]

if not sugarcane.empty:
    print(
        sugarcane.groupby("Crop_Year").agg(
            records=("absolute_error", "size"),
            median_actual_yield=("yield_per_area", "median"),
            median_predicted_yield=("predicted_yield", "median"),
            MAE=("absolute_error", "mean"),
            max_actual_yield=("yield_per_area", "max")
        ).round(4).to_string()
    )

# 4. All cabbage test records
print("\n===== CABBAGE TEST RECORDS =====")
cabbage = test_df[
    test_df["Crop"].astype(str).str.strip().str.casefold().eq("cabbage")
]

if cabbage.empty:
    print("No cabbage records found in the test set.")
else:
    print(
        cabbage[[
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "yield_per_area",
            "predicted_yield", "absolute_error"
        ]].round(4).to_string(index=False)
    )

Test rows in source dataset: 11311
Rows in prediction file: 11311

===== TEST TARGET DISTRIBUTION =====
0.500      1.1000
0.900     11.4839
0.950     21.3953
0.990     71.7908
0.995     88.1500
0.999    111.7330

===== 25 LARGEST ACTUAL YIELDS =====
    State_Name  District_Name  Crop_Year      Season      Crop     Area  yield_per_area  predicted_yield  absolute_error
   West Bengal MEDINIPUR WEST       2014 Whole Year  Sugarcane   4390.0        179.8665          80.7061         99.1604
   West Bengal        HOOGHLY       2014 Whole Year  Sugarcane    830.0        179.8663          72.1258        107.7405
    Puducherry    PONDICHERRY       2014 Kharif      Sugarcane   1921.0        165.0000          69.7319         95.2681
   West Bengal          NADIA       2014 Whole Year  Sugarcane   1754.0        141.5137          72.9714         68.5423
     Karnataka      DAVANGERE       2014 Whole Year  Sugarcane   9523.0        128.2500          91.5120         36.7381
     Karnataka         MANDYA       2014 Whole Year  Sugarcane  21592.0        117.8000          91.3774         26.4226
Andhra Pradesh        KURNOOL       2014 Kharif      Sugarcane    714.0        116.7941          63.3277         53.4664
    Telangana      RANGAREDDI       2014 Kharif          Onion     24.0        114.1667          11.9528        102.2139
         Bihar          ARWAL       2014 Whole Year  Sugarcane     28.0        113.2857          43.5768         69.7089
         Bihar      JEHANABAD       2014 Whole Year  Sugarcane     18.0        113.2778          44.6772         68.6006
         Bihar         NAWADA       2014 Whole Year  Sugarcane     23.0        113.2609          44.3344         68.9265
         Bihar     AURANGABAD       2014 Whole Year  Sugarcane    132.0        112.8485          43.5768         69.2717
     Karnataka       BAGALKOT       2014 Whole Year  Sugarcane  93679.0        109.2500          80.9286         28.3215
     Karnataka         HASSAN       2014 Whole Year  Sugarcane   1568.0        109.2500          86.9737         22.2763
   Maharashtra         SANGLI       2014 Whole Year  Sugarcane  74500.0        108.8201          76.5544         32.2657
   Maharashtra           PUNE       2014 Whole Year  Sugarcane 127800.0        108.2465          77.0917         31.1548
Andhra Pradesh         KADAPA       2014 Kharif         Papaya    789.0        107.1115          36.7334         70.3781
Andhra Pradesh         KADAPA       2014 Rabi           Papaya    729.0        107.1111          22.5200         84.5911
   West Bengal     JALPAIGURI       2014 Whole Year  Sugarcane    250.0        107.0160          80.3167         26.6993
   West Bengal     COOCHBEHAR       2014 Whole Year  Sugarcane    455.0        107.0154          77.4392         29.5762
   West Bengal         MALDAH       2014 Whole Year  Sugarcane   1945.0        107.0144          73.2713         33.7431
   West Bengal DINAJPUR UTTAR       2014 Whole Year  Sugarcane    425.0        107.0141          76.2507         30.7634
   West Bengal     DARJEELING       2014 Whole Year  Sugarcane      2.0        107.0000          57.0357         49.9643
     Karnataka          GADAG       2014 Whole Year  Sugarcane   1870.0        105.4503          85.8946         19.5556
     Karnataka         HAVERI       2014 Whole Year  Sugarcane  10376.0        105.4500          85.7005         19.7495

===== SUGARCANE TEST PERFORMANCE BY YEAR =====
           records  median_actual_yield  median_predicted_yield      MAE  max_actual_yield
Crop_Year
2014           347               60.116                 52.4765  14.4235          179.8665
2015            28               57.110                 52.4981  10.5907           78.8301

===== CABBAGE TEST RECORDS =====
    State_Name  District_Name  Crop_Year      Season  Area  yield_per_area  predicted_yield  absolute_error
Andhra Pradesh      ANANTAPUR       2014 Kharif       10.0         12.3000          22.4598         10.1598
Andhra Pradesh      ANANTAPUR       2014 Rabi          2.0         12.5000          22.6903         10.1903
Andhra Pradesh       CHITTOOR       2014 Kharif      120.0         29.0917          22.4598          6.6319
Andhra Pradesh       CHITTOOR       2014 Rabi        161.0         29.0932          22.7424          6.3508
Andhra Pradesh  EAST GODAVARI       2014 Kharif       22.0         12.3182          24.3457         12.0275
Andhra Pradesh  EAST GODAVARI       2014 Rabi         23.0         12.3478          24.6218         12.2739
Andhra Pradesh         GUNTUR       2014 Kharif       48.0         12.3333          24.4558         12.1225
Andhra Pradesh         GUNTUR       2014 Rabi         29.0         12.3103          24.7331         12.4228
Andhra Pradesh        KRISHNA       2014 Kharif       57.0          2.5789          25.3342         22.7552
Andhra Pradesh        KRISHNA       2014 Rabi         91.0          2.5824          25.9133         23.3309
Andhra Pradesh        KURNOOL       2014 Kharif       11.0         12.3636          22.4598         10.0961
Andhra Pradesh        KURNOOL       2014 Rabi        131.0         12.3282          22.6903         10.3621
Andhra Pradesh       PRAKASAM       2014 Rabi        101.0         12.3267          24.6133         12.2866
Andhra Pradesh     SRIKAKULAM       2014 Kharif      137.0          7.6131          24.4009         16.7877
Andhra Pradesh     SRIKAKULAM       2014 Rabi        170.0          7.6118          24.6218         17.0100
Andhra Pradesh VISAKHAPATANAM       2014 Kharif      143.0          0.8392          24.4009         23.5617
Andhra Pradesh VISAKHAPATANAM       2014 Rabi         88.0          0.8409          24.6218         23.7808
Andhra Pradesh   VIZIANAGARAM       2014 Kharif       74.0         12.3243          24.4009         12.0766
Andhra Pradesh   VIZIANAGARAM       2014 Rabi         81.0         12.3210          24.6594         12.3384

In [ ]:

import pandas as pd
import numpy as np

path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

df = pd.read_csv(path, low_memory=False)

for col in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]

df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

# Compare crops that showed large test errors
selected_crops = ["Sugarcane", "Cabbage", "Papaya", "Onion", "Tomato"]

for crop_name in selected_crops:
    crop_df = df[
        df["Crop"].astype(str).str.strip().str.casefold()
        == crop_name.casefold()
    ].copy()

    if crop_df.empty:
        continue

    train = crop_df[crop_df["Crop_Year"] <= 2011]
    validation = crop_df[crop_df["Crop_Year"].isin([2012, 2013])]
    test = crop_df[crop_df["Crop_Year"].isin([2014, 2015])]

    print("\n" + "=" * 65)
    print(f"CROP: {crop_name}")
    print("=" * 65)

    for split_name, split_df in [
        ("TRAIN (1997–2011)", train),
        ("VALIDATION (2012–2013)", validation),
        ("TEST (2014–2015)", test)
    ]:
        if split_df.empty:
            print(f"\n{split_name}: No records")
            continue


        median_yield = split_df["yield_per_area"].median()
        p90_yield = split_df["yield_per_area"].quantile(0.90)
        max_yield = split_df["yield_per_area"].max()

        print(
            "Yield median / p90 / max:",
            round(float(median_yield), 3),
            round(float(p90_yield), 3),
            round(float(max_yield), 3)
        )


        if crop_name == "Cabbage":
            print("\nState-wise yield summary:")
            print(
                split_df.groupby("State_Name")["yield_per_area"]
                .agg(["count", "median", "max"])
                .round(3).to_string()
            )

=================================================================
CROP: Sugarcane
=================================================================
Yield median / p90 / max: 52.203 94.502 2247.533
Yield median / p90 / max: 58.547 96.484 220.618
Yield median / p90 / max: 60.0 91.204 179.867

=================================================================
CROP: Cabbage
=================================================================
Yield median / p90 / max: 49.0 63.8 67.212

State-wise yield summary:
            count  median     max
State_Name
Manipur        18  12.200  13.200
Tamil Nadu     19  63.529  67.212
Yield median / p90 / max: 18.786 26.333 26.5

State-wise yield summary:
                count  median   max
State_Name
Andhra Pradesh     41  18.786  26.5
Yield median / p90 / max: 12.321 15.818 29.093

State-wise yield summary:
                count  median     max
State_Name
Andhra Pradesh     19  12.321  29.093

=================================================================
CROP: Papaya
=================================================================
Yield median / p90 / max: 15.082 90.815 130.5
Yield median / p90 / max: 21.298 108.931 134.143
Yield median / p90 / max: 24.287 78.785 107.112

=================================================================
CROP: Onion
=================================================================
Yield median / p90 / max: 10.127 21.83 2150.0
Yield median / p90 / max: 11.694 23.002 74.043
Yield median / p90 / max: 15.0 17.957 114.167

=================================================================
CROP: Tomato
=================================================================
Yield median / p90 / max: 7.682 12.325 19.259
Yield median / p90 / max: 17.877 24.395 50.205
Yield median / p90 / max: 14.377 25.658 31.795

# CatBoost Model

In [ ]:

!pip -q install catboost

import os
import numpy as np
import pandas as pd
import joblib
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load dataset
path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)
df = pd.read_csv(path, low_memory=False)
df.columns = df.columns.str.strip()

for c in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]
df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

# Features and target
cat_cols = ["State_Name", "District_Name", "Season", "Crop", "soil_type"]
num_cols = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = cat_cols + num_cols

X = df[features].copy()
y = df["yield_per_area"].copy()

for c in cat_cols:
    X[c] = X[c].fillna("Unknown").astype(str).str.strip()
    X[c] = X[c].replace("", "Unknown")

# Same chronological split as previous models
train = df["Crop_Year"] <= 2011
val = df["Crop_Year"].isin([2012, 2013])
test = df["Crop_Year"].isin([2014, 2015])

X_train, y_train = X.loc[train], y.loc[train]
X_val, y_val = X.loc[val], y.loc[val]
X_test, y_test = X.loc[test], y.loc[test]

# CatBoost handles categorical columns directly
model = CatBoostRegressor(
    iterations=1000,
    depth=8,
    learning_rate=0.05,
    loss_function="RMSE",
    eval_metric="RMSE",
    random_seed=42,
    verbose=100,
    allow_writing_files=False
)

print("Training CatBoost...")
model.fit(
    X_train, y_train,
    cat_features=cat_cols,
    eval_set=(X_val, y_val),
    early_stopping_rounds=100,
    verbose=100
)

def evaluate(label, actual, predicted):
    print(f"\n{label}")
    print("MAE:", round(mean_absolute_error(actual, predicted), 4))
    print("RMSE:", round(np.sqrt(mean_squared_error(actual, predicted)), 4))
    print("R²:", round(r2_score(actual, predicted), 4))
    print("Negative predictions:", int((predicted < 0).sum()))

val_pred = model.predict(X_val)
test_pred = model.predict(X_test)

evaluate("CATBOOST VALIDATION (2012–2013)", y_val, val_pred)
evaluate("CATBOOST TEST (2014–2015)", y_test, test_pred)

# Save separately; do not overwrite previous models
out_dir = "/content/drive/MyDrive/yield prediction"
model_path = os.path.join(out_dir, "cropsense_catboost_yield.cbm")
joblib_path = os.path.join(out_dir, "cropsense_catboost_yield.joblib")

model.save_model(model_path)
joblib.dump(model, joblib_path)

print("\nSaved CatBoost model:", model_path)
print("Saved joblib model:", joblib_path)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 4.3 MB/s eta 0:00:00
Training CatBoost...
0:	learn: 29.3244639	test: 12.5517073	best: 12.5517073 (0)	total: 441ms	remaining: 7m 20s
100:	learn: 21.8053240	test: 6.2553114	best: 6.2510513 (94)	total: 20.8s	remaining: 3m 5s
200:	learn: 18.6124125	test: 6.3737164	best: 6.1378199 (154)	total: 45.2s	remaining: 2m 59s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 6.137819886
bestIteration = 154

Shrink model to first 155 iterations.

CATBOOST VALIDATION (2012–2013)
MAE: 1.8119
RMSE: 6.1378
R²: 0.777
Negative predictions: 240

CATBOOST TEST (2014–2015)
MAE: 1.8071
RMSE: 5.8668
R²: 0.793
Negative predictions: 146

Saved CatBoost model: /content/drive/MyDrive/yield prediction/cropsense_catboost_yield.cbm
Saved joblib model: /content/drive/MyDrive/yield prediction/cropsense_catboost_yield.joblib

# XGBoost Model

In [ ]:

import os
import numpy as np
import pandas as pd
import joblib

from xgboost import XGBRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# 1. Load dataset
path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

df = pd.read_csv(path, low_memory=False)
df.columns = df.columns.str.strip()

for c in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]
df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

# 2. Features and target
cat_cols = [
    "State_Name", "District_Name", "Season", "Crop", "soil_type"
]
num_cols = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = cat_cols + num_cols

X = df[features].copy()
y = df["yield_per_area"].copy()

for c in cat_cols:
    X[c] = X[c].fillna("Unknown").astype(str).str.strip()
    X[c] = X[c].replace("", "Unknown")

# 3. Same chronological split
train_mask = df["Crop_Year"] <= 2011
val_mask = df["Crop_Year"].isin([2012, 2013])
test_mask = df["Crop_Year"].isin([2014, 2015])

X_train, y_train = X.loc[train_mask], y.loc[train_mask]
X_val, y_val = X.loc[val_mask], y.loc[val_mask]
X_test, y_test = X.loc[test_mask], y.loc[test_mask]

# 4. Preprocessing
preprocessor = ColumnTransformer([
    ("numeric", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), num_cols),
    ("categorical", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

# 5. XGBoost with 800 trees
model_800 = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(
        objective="reg:squarederror",
        n_estimators=800,       # Increased from 500 to 800
        max_depth=8,
        learning_rate=0.05,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_lambda=5,
        random_state=42,
        n_jobs=-1,
        tree_method="hist"
    ))
])

# 6. Train
print("Training XGBoost with 800 trees...")
model_800.fit(X_train, y_train)
print("Training completed!")

# 7. Evaluate validation and test sets
def evaluate(name, actual, predicted):
    print(f"\n{name}")
    print("MAE:", round(mean_absolute_error(actual, predicted), 4))
    print("RMSE:", round(np.sqrt(mean_squared_error(actual, predicted)), 4))
    print("R²:", round(r2_score(actual, predicted), 4))
    print("Negative predictions:", int((predicted < 0).sum()))

val_pred = model_800.predict(X_val)
test_pred = model_800.predict(X_test)

evaluate("800-TREE VALIDATION (2012–2013)", y_val, val_pred)
evaluate("800-TREE TEST (2014–2015)", y_test, test_pred)

# 8. Save as a new model
out_dir = "/content/drive/MyDrive/yield prediction"

model_path = os.path.join(
    out_dir, "cropsense_xgboost_yield_800_trees.joblib"
)
joblib.dump(model_800, model_path)

print("\nSaved model:", model_path)

Training XGBoost with 800 trees...
Training completed!

800-TREE VALIDATION (2012–2013)
MAE: 1.5097
RMSE: 5.1439
R²: 0.8434
Negative predictions: 118

800-TREE TEST (2014–2015)
MAE: 1.4033
RMSE: 4.4761
R²: 0.8795
Negative predictions: 41

Saved model: /content/drive/MyDrive/yield prediction/cropsense_xgboost_yield_800_trees.joblib

In [ ]:

!pip -q install -U xgboost scikit-learn joblib

import os
import joblib
import numpy as np
import pandas as pd
import xgboost as xgb

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ============================================================
# 1. LOAD AND PREPARE DATA
# ============================================================

path = (
    "/content/drive/MyDrive/yield prediction/"
    "crop_production_124_training_ready.csv"
)

df = pd.read_csv(path, low_memory=False)
df.columns = df.columns.str.strip()

for col in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]
df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

cat_cols = [
    "State_Name", "District_Name", "Season", "Crop", "soil_type"
]
num_cols = [
    "Crop_Year", "temperature", "humidity", "rainfall_mm"
]
features = cat_cols + num_cols

X = df[features].copy()
y = df["yield_per_area"].copy()

for col in cat_cols:
    X[col] = (
        X[col].fillna("Unknown")
        .astype(str).str.strip()
        .replace("", "Unknown")
    )

# Same chronological split
train_mask = df["Crop_Year"] <= 2011
val_mask = df["Crop_Year"].isin([2012, 2013])
test_mask = df["Crop_Year"].isin([2014, 2015])

X_train, y_train = X.loc[train_mask], y.loc[train_mask]
X_val, y_val = X.loc[val_mask], y.loc[val_mask]
X_test, y_test = X.loc[test_mask], y.loc[test_mask]

print("Train:", len(X_train))
print("Validation:", len(X_val))
print("Test (held out):", len(X_test))

# ============================================================
# 2. FIT PREPROCESSING ON TRAINING DATA ONLY
# ============================================================

preprocessor = ColumnTransformer([
    ("numeric", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), num_cols),
    ("categorical", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

X_train_t = preprocessor.fit_transform(X_train)
X_val_t = preprocessor.transform(X_val)

# ============================================================
# 3. HYPERPARAMETER EXPERIMENTS
# ============================================================

experiments = [
    {"max_depth": 4, "learning_rate": 0.03,
     "min_child_weight": 5, "reg_lambda": 10, "subsample": 0.85},
    {"max_depth": 5, "learning_rate": 0.03,
     "min_child_weight": 5, "reg_lambda": 10, "subsample": 0.85},
    {"max_depth": 6, "learning_rate": 0.03,
     "min_child_weight": 5, "reg_lambda": 10, "subsample": 0.85},
    {"max_depth": 8, "learning_rate": 0.03,
     "min_child_weight": 5, "reg_lambda": 10, "subsample": 0.85},
    {"max_depth": 4, "learning_rate": 0.05,
     "min_child_weight": 3, "reg_lambda": 5, "subsample": 0.90},
    {"max_depth": 5, "learning_rate": 0.05,
     "min_child_weight": 3, "reg_lambda": 5, "subsample": 0.90},
    {"max_depth": 6, "learning_rate": 0.05,
     "min_child_weight": 3, "reg_lambda": 5, "subsample": 0.90},
    {"max_depth": 8, "learning_rate": 0.05,
     "min_child_weight": 3, "reg_lambda": 5, "subsample": 0.90},
    {"max_depth": 4, "learning_rate": 0.08,
     "min_child_weight": 3, "reg_lambda": 10, "subsample": 0.85},
    {"max_depth": 6, "learning_rate": 0.08,
     "min_child_weight": 5, "reg_lambda": 10, "subsample": 0.85},
    {"max_depth": 5, "learning_rate": 0.03,
     "min_child_weight": 10, "reg_lambda": 20, "subsample": 0.90},
    {"max_depth": 6, "learning_rate": 0.03,
     "min_child_weight": 10, "reg_lambda": 20, "subsample": 0.90},
]

results = []
best_model = None
best_params = None
best_rmse = float("inf")

for i, params in enumerate(experiments, start=1):
    print(f"\nExperiment {i}/{len(experiments)}: {params}")

    model = xgb.XGBRegressor(
        objective="reg:squarederror",
        n_estimators=2000,
        max_depth=params["max_depth"],
        learning_rate=params["learning_rate"],
        min_child_weight=params["min_child_weight"],
        reg_lambda=params["reg_lambda"],
        subsample=params["subsample"],
        colsample_bytree=0.85,
        early_stopping_rounds=100,
        eval_metric="rmse",
        random_state=42,
        n_jobs=-1,
        tree_method="hist"
    )

    model.fit(
        X_train_t, y_train,
        eval_set=[(X_val_t, y_val)],
        verbose=False
    )

    val_pred = model.predict(X_val_t)

    mae = mean_absolute_error(y_val, val_pred)
    rmse = np.sqrt(mean_squared_error(y_val, val_pred))
    r2 = r2_score(y_val, val_pred)

    results.append({
        **params,
        "best_iteration": model.best_iteration,
        "validation_MAE": mae,
        "validation_RMSE": rmse,
        "validation_R2": r2
    })

    print(
        f"Best trees: {model.best_iteration + 1} | "
        f"MAE: {mae:.4f} | RMSE: {rmse:.4f} | R2: {r2:.4f}"
    )

    if rmse < best_rmse:
        best_rmse = rmse
        best_model = model
        best_params = params.copy()

# ============================================================
# 4. SHOW BEST VALIDATION RESULT
# ============================================================

results_df = pd.DataFrame(results).sort_values("validation_RMSE")

print("\n===== TOP 5 CONFIGURATIONS =====")
print(results_df.head(5).round(4).to_string(index=False))

print("\nBest parameters:", best_params)
print("Best validation RMSE:", round(best_rmse, 4))

# Save separately; do not overwrite previous models
out_dir = "/content/drive/MyDrive/yield prediction"

joblib.dump(
    {
        "preprocessor": preprocessor,
        "model": best_model,
        "features": features,
        "categorical_features": cat_cols,
        "numeric_features": num_cols,
        "best_parameters": best_params
    },
    os.path.join(out_dir, "cropsense_xgboost_tuned_candidate.joblib")
)

results_df.to_csv(
    os.path.join(out_dir, "cropsense_xgboost_tuning_results.csv"),
    index=False
)

print("\nSaved tuned candidate and experiment results.")
print("The test set has not been used to select the model.")

Train: 199107
Validation: 26448
Test (held out): 11311

Experiment 1/12: {'max_depth': 4, 'learning_rate': 0.03, 'min_child_weight': 5, 'reg_lambda': 10, 'subsample': 0.85}
Best trees: 914 | MAE: 1.9824 | RMSE: 5.4791 | R2: 0.8223

Experiment 2/12: {'max_depth': 5, 'learning_rate': 0.03, 'min_child_weight': 5, 'reg_lambda': 10, 'subsample': 0.85}
Best trees: 838 | MAE: 1.8564 | RMSE: 5.3220 | R2: 0.8324

Experiment 3/12: {'max_depth': 6, 'learning_rate': 0.03, 'min_child_weight': 5, 'reg_lambda': 10, 'subsample': 0.85}
Best trees: 610 | MAE: 1.8027 | RMSE: 5.2273 | R2: 0.8383

Experiment 4/12: {'max_depth': 8, 'learning_rate': 0.03, 'min_child_weight': 5, 'reg_lambda': 10, 'subsample': 0.85}
Best trees: 399 | MAE: 1.7037 | RMSE: 5.0971 | R2: 0.8462

Experiment 5/12: {'max_depth': 4, 'learning_rate': 0.05, 'min_child_weight': 3, 'reg_lambda': 5, 'subsample': 0.9}
Best trees: 454 | MAE: 1.9275 | RMSE: 5.4727 | R2: 0.8227

Experiment 6/12: {'max_depth': 5, 'learning_rate': 0.05, 'min_child_weight': 3, 'reg_lambda': 5, 'subsample': 0.9}
Best trees: 298 | MAE: 1.8975 | RMSE: 5.4331 | R2: 0.8253

Experiment 7/12: {'max_depth': 6, 'learning_rate': 0.05, 'min_child_weight': 3, 'reg_lambda': 5, 'subsample': 0.9}
Best trees: 235 | MAE: 1.8655 | RMSE: 5.4945 | R2: 0.8213

Experiment 8/12: {'max_depth': 8, 'learning_rate': 0.05, 'min_child_weight': 3, 'reg_lambda': 5, 'subsample': 0.9}
Best trees: 130 | MAE: 1.8396 | RMSE: 5.3646 | R2: 0.8297

Experiment 9/12: {'max_depth': 4, 'learning_rate': 0.08, 'min_child_weight': 3, 'reg_lambda': 10, 'subsample': 0.85}
Best trees: 262 | MAE: 2.0538 | RMSE: 5.5816 | R2: 0.8156

Experiment 10/12: {'max_depth': 6, 'learning_rate': 0.08, 'min_child_weight': 5, 'reg_lambda': 10, 'subsample': 0.85}
Best trees: 223 | MAE: 1.8234 | RMSE: 5.2359 | R2: 0.8378

Experiment 11/12: {'max_depth': 5, 'learning_rate': 0.03, 'min_child_weight': 10, 'reg_lambda': 20, 'subsample': 0.9}
Best trees: 923 | MAE: 1.8823 | RMSE: 5.3309 | R2: 0.8318

Experiment 12/12: {'max_depth': 6, 'learning_rate': 0.03, 'min_child_weight': 10, 'reg_lambda': 20, 'subsample': 0.9}
Best trees: 742 | MAE: 1.8155 | RMSE: 5.2354 | R2: 0.8378

===== TOP 5 CONFIGURATIONS =====
 max_depth  learning_rate  min_child_weight  reg_lambda  subsample  best_iteration  validation_MAE  validation_RMSE  validation_R2
         8           0.03                 5          10       0.85             398          1.7037           5.0971         0.8462
         6           0.03                 5          10       0.85             609          1.8027           5.2273         0.8383
         6           0.03                10          20       0.90             741          1.8155           5.2354         0.8378
         6           0.08                 5          10       0.85             222          1.8234           5.2359         0.8378
         5           0.03                 5          10       0.85             837          1.8564           5.3220         0.8324

Best parameters: {'max_depth': 8, 'learning_rate': 0.03, 'min_child_weight': 5, 'reg_lambda': 10, 'subsample': 0.85}
Best validation RMSE: 5.0971

Saved tuned candidate and experiment results.
The test set has not been used to select the model.

In [ ]:

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:

import os

folder = "/content/drive/MyDrive/yield prediction"

print("Files related to XGBoost tuning:")
for f in os.listdir(folder):
    if "tuned" in f.lower() or "tuning" in f.lower():
        print(f)

Files related to XGBoost tuning:
cropsense_xgboost_tuning_results.csv
cropsense_xgboost_tuned_candidate.joblib

In [ ]:

import os
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

BASE = "/content/drive/MyDrive/yield prediction"
DATA_PATH = os.path.join(BASE, "crop_production_124_training_ready.csv")
MODEL_PATH = os.path.join(BASE, "cropsense_xgboost_tuned_candidate.joblib")

# Load the tuned candidate and dataset
candidate = joblib.load(MODEL_PATH)
df = pd.read_csv(DATA_PATH)

# Recreate the chronological split used during tuning
df["Crop_Year"] = pd.to_numeric(df["Crop_Year"], errors="coerce")
df["yield_per_area"] = pd.to_numeric(df["yield_per_area"], errors="coerce")
df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna(subset=["Crop_Year", "yield_per_area"])
df = df[(df["Area"] > 0) & (df["Production"] > 0)]

cat_cols = ["State_Name", "District_Name", "Season", "Crop", "soil_type"]
num_cols = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = cat_cols + num_cols

train = df[df["Crop_Year"] <= 2011]
valid = df[df["Crop_Year"].between(2012, 2013)]
test = df[df["Crop_Year"].between(2014, 2015)]

X_test = test[features]
y_test = test["yield_per_area"]

# Load preprocessor and model from saved candidate
print("Saved candidate type:", type(candidate))
if isinstance(candidate, dict):
    print("Saved keys:", candidate.keys())
    preprocessor = candidate.get("preprocessor")
    model = candidate.get("model", candidate.get("best_model"))
else:
    raise ValueError("Candidate is not a dictionary. Check the saved artifact structure.")

if preprocessor is None or model is None:
    raise ValueError("Could not find preprocessor/model in candidate. Share the printed keys.")

X_test_processed = preprocessor.transform(X_test)
predictions = model.predict(X_test_processed)

# Evaluate on the held-out test set
predictions = np.maximum(predictions, 0)

print("\n===== TUNED XGBOOST TEST RESULTS =====")
print("Test samples:", len(y_test))
print(f"MAE:  {mean_absolute_error(y_test, predictions):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, predictions)):.4f}")
print(f"R²:   {r2_score(y_test, predictions):.4%}")
print("\nPrevious model test R²: 87.95%")

Saved candidate type: <class 'dict'>
Saved keys: dict_keys(['preprocessor', 'model', 'features', 'categorical_features', 'numeric_features', 'best_parameters'])

===== TUNED XGBOOST TEST RESULTS =====
Test samples: 11311
MAE:  1.8101
RMSE: 4.8928
R²:   85.6051%

Previous model test R²: 87.95%

In [ ]:

import pandas as pd
import os

folder = "/content/drive/MyDrive/yield prediction"
results_path = os.path.join(
    folder, "cropsense_xgboost_tuning_results.csv"
)

results = pd.read_csv(results_path)
display(results.sort_values("validation_RMSE").head(12))

,max_depth,learning_rate,min_child_weight,reg_lambda,subsample,best_iteration,validation_MAE,validation_RMSE,validation_R2
0,8,0.03,5,10,0.85,398,1.703736,5.097128,0.846235
1,6,0.03,5,10,0.85,609,1.802730,5.227293,0.838281
2,6,0.03,10,20,0.90,741,1.815496,5.235361,0.837782
3,6,0.08,5,10,0.85,222,1.823446,5.235871,0.837750
4,5,0.03,5,10,0.85,837,1.856388,5.322047,0.832365
5,5,0.03,10,20,0.90,922,1.882301,5.330871,0.831809
6,8,0.05,3,5,0.90,129,1.839614,5.364640,0.829671
7,5,0.05,3,5,0.90,297,1.897466,5.433077,0.825298
8,4,0.05,3,5,0.90,453,1.927464,5.472746,0.822737
9,4,0.03,5,10,0.85,913,1.982354,5.479088,0.822326
10,6,0.05,3,5,0.90,234,1.865469,5.494474,0.821327
11,4,0.08,3,10,0.85,261,2.053778,5.581559,0.815618

In [ ]:

import pandas as pd
import numpy as np

path = "/content/drive/MyDrive/yield prediction/crop_production_124_training_ready.csv"
df = pd.read_csv(path)

df["yield_per_area"] = pd.to_numeric(
    df["yield_per_area"], errors="coerce"
)
df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna(subset=["yield_per_area", "Crop_Year"])

# Training period only: do not inspect test labels to choose cleaning rules
train = df[df["Crop_Year"] <= 2011].copy()

# Crop-level distribution and extreme-value counts
summary = (
    train.groupby("Crop")["yield_per_area"]
    .agg(
        records="count",
        median="median",
        p90=lambda x: x.quantile(0.90),
        p95=lambda x: x.quantile(0.95),
        p99=lambda x: x.quantile(0.99),
        maximum="max"
    )
    .sort_values("maximum", ascending=False)
)

print("Top 20 crops by maximum training yield:")
display(summary.head(20).round(3))

# Inspect the most extreme individual training records
thresholds = train.groupby("Crop")["yield_per_area"].quantile(0.99)
train["crop_p99"] = train["Crop"].map(thresholds)

extreme = train[train["yield_per_area"] > train["crop_p99"]].copy()
extreme = extreme.sort_values("yield_per_area", ascending=False)

print("\nTop 30 records above their crop-specific 99th percentile:")
display(
    extreme[
        ["State_Name", "District_Name", "Crop_Year",
         "Season", "Crop", "Area", "Production", "yield_per_area"]
    ].head(30).round(3)
)

Top 20 crops by maximum training yield:

              records  median     p90      p95      p99   maximum
Crop
Cashewnut         856   0.401   0.804    1.000    1.396  9801.000
Sugarcane        6570  52.203  94.502  107.118  137.970  2247.533
Onion            5843  10.127  21.830   25.997   32.708  2150.000
Maize           11294   1.671   3.513    4.546    6.967  1494.000
Cotton(lint)     3720   1.316   3.077    4.000    6.000   300.000
Rice            12589   1.853   3.142    3.572    4.451   223.727
Potato           5828  10.705  23.200   25.836   30.076   213.846
Banana           2693  21.664  49.695   64.101   80.270   137.400
Papaya            273  15.082  90.815  130.441  130.476   130.500
Tapioca          1326  11.690  38.809   42.195   50.406    70.516
Sunflower        4687   0.796   1.672    1.967    2.336    70.000
Mesta            1429   5.000   9.279   10.933   15.140    68.000
Cabbage            37  49.000  63.800   64.433   66.835    67.212
Pome Fruit        169   5.564  10.607   19.015   57.009    57.140
Sannhamp         1824   0.500   3.402    4.698    6.723    55.550
Grapes             98  24.053  29.750   31.017   42.106    42.928
Dry ginger       2610   2.333  12.712   16.000   31.667    38.422
Sweet potato     3440   8.000  14.065   15.931   20.958    38.125
Guar seed        1008   0.816   1.000    1.138   10.869    33.609
Pineapple         147  13.624  18.692   31.000   31.647    32.099

Top 30 records above their crop-specific 99th percentile:

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
175865,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.0,9801.000
174381,Tamil Nadu,MADURAI,1997,Whole Year,Sugarcane,8108.0,18223000.0,2247.533
66324,Haryana,KARNAL,2008,Whole Year,Onion,2.0,4300.0,2150.000
178746,Tamil Nadu,THIRUVALLUR,1997,Whole Year,Sugarcane,5964.0,11811000.0,1980.382
126592,Maharashtra,NASHIK,1997,Autumn,Maize,1.0,1494.0,1494.000
173083,Tamil Nadu,KANCHIPURAM,1997,Whole Year,Sugarcane,6735.0,9896000.0,1469.339
175100,Tamil Nadu,NAMAKKAL,1997,Whole Year,Sugarcane,9415.0,13608000.0,1445.353
179359,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,Sugarcane,4315.0,5806000.0,1345.539
123689,Maharashtra,JALGAON,1997,Autumn,Maize,3.0,3980.0,1326.667
171139,Tamil Nadu,CUDDALORE,1997,Whole Year,Sugarcane,23826.0,28322000.0,1188.701
173658,Tamil Nadu,KARUR,1997,Whole Year,Sugarcane,5961.0,7081000.0,1187.888
176767,Tamil Nadu,SALEM,1997,Whole Year,Sugarcane,13759.0,15866000.0,1153.136
127977,Maharashtra,PUNE,1997,Autumn,Maize,4.0,4570.0,1142.500
170659,Tamil Nadu,COIMBATORE,1997,Whole Year,Sugarcane,10756.0,12272000.0,1140.945
127043,Maharashtra,OSMANABAD,1997,Autumn,Maize,5.0,5635.0,1127.000
181749,Tamil Nadu,VILLUPURAM,1997,Whole Year,Sugarcane,33175.0,37158000.0,1120.060
172592,Tamil Nadu,ERODE,1997,Whole Year,Sugarcane,24112.0,26930000.0,1116.871
119266,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000
178287,Tamil Nadu,THENI,1997,Whole Year,Sugarcane,9524.0,10598000.0,1112.768
178014,Tamil Nadu,THE NILGIRIS,1997,Whole Year,Sugarcane,22.0,24000.0,1090.909
180862,Tamil Nadu,TUTICORIN,1997,Whole Year,Sugarcane,90.0,97000.0,1077.778
179814,Tamil Nadu,TIRUNELVELI,1997,Whole Year,Sugarcane,2237.0,2402000.0,1073.759
174820,Tamil Nadu,NAGAPATTINAM,1997,Whole Year,Sugarcane,4601.0,4940000.0,1073.680
176021,Tamil Nadu,PUDUKKOTTAI,1997,Whole Year,Sugarcane,2377.0,2552000.0,1073.622
182202,Tamil Nadu,VIRUDHUNAGAR,1997,Whole Year,Sugarcane,2639.0,2833000.0,1073.513
176409,Tamil Nadu,RAMANATHAPURAM,1997,Whole Year,Sugarcane,182.0,195000.0,1071.429
171571,Tamil Nadu,DHARMAPURI,1997,Whole Year,Sugarcane,18938.0,18100000.0,955.750
175585,Tamil Nadu,PERAMBALUR,1997,Whole Year,Sugarcane,11508.0,10448000.0,907.890
180411,Tamil Nadu,TIRUVANNAMALAI,1997,Whole Year,Sugarcane,27636.0,23914000.0,865.321
172057,Tamil Nadu,DINDIGUL,1997,Whole Year,Sugarcane,6826.0,5749000.0,842.221

In [ ]:

import pandas as pd
import numpy as np
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "crop_production_124_training_ready.csv")

df = pd.read_csv(path)

# Keep the original dataset untouched
df["Crop_Year"] = pd.to_numeric(df["Crop_Year"], errors="coerce")
df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(df["Production"], errors="coerce")

# Training period only
train = df[df["Crop_Year"] <= 2011].copy()
train["calculated_yield"] = train["Production"] / train["Area"]

# Crop-specific 99th percentile thresholds
p99 = train.groupby("Crop")["calculated_yield"].quantile(0.99)
train["crop_p99"] = train["Crop"].map(p99)

extreme = train[
    (train["Area"] > 0) &
    (train["calculated_yield"] > train["crop_p99"])
].copy()

extreme = extreme.sort_values("calculated_yield", ascending=False)

columns = [
    "State_Name", "District_Name", "Crop_Year", "Season",
    "Crop", "Area", "Production", "calculated_yield", "crop_p99"
]

report_path = os.path.join(base, "crop_yield_extreme_training_records.csv")
extreme[columns].to_csv(report_path, index=False)

print("Extreme training records:", len(extreme))
print("Report saved:", report_path)
display(extreme[columns].head(30).round(3))

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/yield prediction/crop_production_124_training_ready.csv'

In [ ]:

import pandas as pd
import numpy as np
import os

path = "/content/drive/MyDrive/yield prediction/crop_production_124_training_ready.csv"
df = pd.read_csv(path)

print("DATASET SHAPE:", df.shape)
print("\n1. MISSING VALUES")
print(df.isna().sum().sort_values(ascending=False).to_string())

print("\n2. DUPLICATE ROWS")
print("Exact duplicate rows:", df.duplicated().sum())

print("\n3. AREA AND PRODUCTION CHECKS")
area = pd.to_numeric(df["Area"], errors="coerce")
production = pd.to_numeric(df["Production"], errors="coerce")
target = pd.to_numeric(df["yield_per_area"], errors="coerce")

print("Area <= 0:", (area <= 0).sum())
print("Production < 0:", (production < 0).sum())
print("Missing/non-numeric Area:", area.isna().sum())
print("Missing/non-numeric Production:", production.isna().sum())

valid = area.gt(0) & production.notna() & target.notna()
recalculated = production[valid] / area[valid]
difference = (recalculated - target[valid]).abs()

print("\n4. TARGET CONSISTENCY")
print("Rows checked:", len(difference))
print("Rows differing by > 0.01:", (difference > 0.01).sum())
print("Maximum absolute difference:", difference.max())

print("\n5. EXTREME YIELD VALUES")
check = df.copy()
check["Area"] = area
check["Production"] = production
check["yield_per_area"] = target
check = check.replace([np.inf, -np.inf], np.nan)
check = check[check["Area"] > 0].copy()
check["calculated_yield"] = check["Production"] / check["Area"]

display(
    check.sort_values("calculated_yield", ascending=False)[
        ["State_Name", "District_Name", "Crop_Year", "Season",
         "Crop", "Area", "Production", "yield_per_area",
         "calculated_yield"]
    ].head(20)
)

print("\nAudit complete. Original dataset was not modified.")

DATASET SHAPE: (236866, 12)

1. MISSING VALUES
State_Name        0
District_Name     0
Crop_Year         0
Season            0
Crop              0
Area              0
Production        0
temperature       0
humidity          0
rainfall_mm       0
soil_type         0
yield_per_area    0

2. DUPLICATE ROWS
Exact duplicate rows: 0

3. AREA AND PRODUCTION CHECKS
Area <= 0: 0
Production < 0: 0
Missing/non-numeric Area: 0
Missing/non-numeric Production: 0

4. TARGET CONSISTENCY
Rows checked: 236866
Rows differing by > 0.01: 0
Maximum absolute difference: 2.2737367544323206e-13

5. EXTREME YIELD VALUES

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area,calculated_yield
175865,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.0,9801.000000,9801.000000
174381,Tamil Nadu,MADURAI,1997,Whole Year,Sugarcane,8108.0,18223000.0,2247.533300,2247.533300
66324,Haryana,KARNAL,2008,Whole Year,Onion,2.0,4300.0,2150.000000,2150.000000
178746,Tamil Nadu,THIRUVALLUR,1997,Whole Year,Sugarcane,5964.0,11811000.0,1980.382294,1980.382294
126592,Maharashtra,NASHIK,1997,Autumn,Maize,1.0,1494.0,1494.000000,1494.000000
173083,Tamil Nadu,KANCHIPURAM,1997,Whole Year,Sugarcane,6735.0,9896000.0,1469.339272,1469.339272
175100,Tamil Nadu,NAMAKKAL,1997,Whole Year,Sugarcane,9415.0,13608000.0,1445.353160,1445.353160
179359,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,Sugarcane,4315.0,5806000.0,1345.538818,1345.538818
123689,Maharashtra,JALGAON,1997,Autumn,Maize,3.0,3980.0,1326.666667,1326.666667
171139,Tamil Nadu,CUDDALORE,1997,Whole Year,Sugarcane,23826.0,28322000.0,1188.701419,1188.701419
173658,Tamil Nadu,KARUR,1997,Whole Year,Sugarcane,5961.0,7081000.0,1187.887938,1187.887938
176767,Tamil Nadu,SALEM,1997,Whole Year,Sugarcane,13759.0,15866000.0,1153.136129,1153.136129
127977,Maharashtra,PUNE,1997,Autumn,Maize,4.0,4570.0,1142.500000,1142.500000
170659,Tamil Nadu,COIMBATORE,1997,Whole Year,Sugarcane,10756.0,12272000.0,1140.944589,1140.944589
127043,Maharashtra,OSMANABAD,1997,Autumn,Maize,5.0,5635.0,1127.000000,1127.000000
181749,Tamil Nadu,VILLUPURAM,1997,Whole Year,Sugarcane,33175.0,37158000.0,1120.060286,1120.060286
172592,Tamil Nadu,ERODE,1997,Whole Year,Sugarcane,24112.0,26930000.0,1116.871267,1116.871267
119266,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000000,1113.000000
178287,Tamil Nadu,THENI,1997,Whole Year,Sugarcane,9524.0,10598000.0,1112.767745,1112.767745
178014,Tamil Nadu,THE NILGIRIS,1997,Whole Year,Sugarcane,22.0,24000.0,1090.909091,1090.909091

Audit complete. Original dataset was not modified.

In [ ]:

import pandas as pd
import numpy as np

path = "/content/drive/MyDrive/yield prediction/crop_production_124_training_ready.csv"
df = pd.read_csv(path)

df["yield_per_area"] = df["Production"] / df["Area"]

# Calculate crop-specific statistics
stats = df.groupby("Crop")["yield_per_area"].agg(
    records="count",
    median="median",
    p99=lambda x: x.quantile(0.99),
    maximum="max"
)

stats["max_to_median"] = (
    stats["maximum"] / stats["median"].replace(0, np.nan)
)

# Flag records above their crop's 99th percentile
p99 = df.groupby("Crop")["yield_per_area"].quantile(0.99)
df["crop_p99"] = df["Crop"].map(p99)

counts = (
    df[df["yield_per_area"] > df["crop_p99"]]
    .groupby("Crop")
    .size()
    .rename("above_p99_records")
)

stats = stats.join(counts).fillna({"above_p99_records": 0})
stats["above_p99_records"] = stats["above_p99_records"].astype(int)

display(
    stats.sort_values("max_to_median", ascending=False)
    .head(20).round(3)
)

,records,median,p99,maximum,max_to_median,above_p99_records
Crop,,,,,,
Cashewnut,1065,0.397,1.898,9801.000,24682.044,11
Maize,13723,1.800,7.231,1494.000,830.000,138
Sesamum,8724,0.333,1.108,235.000,705.000,88
Niger seed,2004,0.289,1.005,71.000,245.310,21
Cotton(lint),4350,1.383,5.788,300.000,216.959,44
Onion,6979,10.300,33.000,2150.000,208.738,69
Rice,15078,1.939,4.518,223.727,115.394,151
Sannhamp,2141,0.500,6.500,55.550,111.100,21
Sunflower,5468,0.800,2.304,70.000,87.500,55
other oilseeds,572,0.500,22.564,32.575,65.150,6
Guar seed,1257,0.816,10.593,40.000,49.000,13
Groundnut,8732,1.046,3.219,49.000,46.845,88
Sugarcane,7799,53.228,137.585,2247.533,42.225,78
Other Rabi pulses,3054,0.542,2.146,22.707,41.882,31
Small millets,4570,0.600,1.746,21.667,36.111,46
Cardamom,352,0.083,1.598,2.873,34.482,4
Other Kharif pulses,3522,0.450,1.545,12.667,28.141,36
Dry chillies,6401,0.920,6.686,24.823,26.981,64
Urad,9669,0.463,1.064,10.000,21.598,97
Potato,6910,10.842,31.350,213.846,19.724,70

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "crop_production_124_training_ready.csv")

df = pd.read_csv(path)
df["yield_per_area"] = df["Production"] / df["Area"]

# Crop-specific 99th percentile for comparison
p99 = df.groupby("Crop")["yield_per_area"].quantile(0.99)
df["crop_p99"] = df["Crop"].map(p99)

extreme = df.sort_values("yield_per_area", ascending=False).head(50)

cols = [
    "State_Name", "District_Name", "Crop_Year", "Season",
    "Crop", "Area", "Production", "yield_per_area", "crop_p99"
]

display(extreme[cols].round(3))

out = os.path.join(base, "top_50_extreme_yield_records.csv")
extreme[cols].to_csv(out, index=False)
print("\nReport saved to:", out)

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area,crop_p99
175865,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.0,9801.000,1.898
174381,Tamil Nadu,MADURAI,1997,Whole Year,Sugarcane,8108.0,18223000.0,2247.533,137.585
66324,Haryana,KARNAL,2008,Whole Year,Onion,2.0,4300.0,2150.000,33.000
178746,Tamil Nadu,THIRUVALLUR,1997,Whole Year,Sugarcane,5964.0,11811000.0,1980.382,137.585
126592,Maharashtra,NASHIK,1997,Autumn,Maize,1.0,1494.0,1494.000,7.231
173083,Tamil Nadu,KANCHIPURAM,1997,Whole Year,Sugarcane,6735.0,9896000.0,1469.339,137.585
175100,Tamil Nadu,NAMAKKAL,1997,Whole Year,Sugarcane,9415.0,13608000.0,1445.353,137.585
179359,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,Sugarcane,4315.0,5806000.0,1345.539,137.585
123689,Maharashtra,JALGAON,1997,Autumn,Maize,3.0,3980.0,1326.667,7.231
171139,Tamil Nadu,CUDDALORE,1997,Whole Year,Sugarcane,23826.0,28322000.0,1188.701,137.585
173658,Tamil Nadu,KARUR,1997,Whole Year,Sugarcane,5961.0,7081000.0,1187.888,137.585
176767,Tamil Nadu,SALEM,1997,Whole Year,Sugarcane,13759.0,15866000.0,1153.136,137.585
127977,Maharashtra,PUNE,1997,Autumn,Maize,4.0,4570.0,1142.500,7.231
170659,Tamil Nadu,COIMBATORE,1997,Whole Year,Sugarcane,10756.0,12272000.0,1140.945,137.585
127043,Maharashtra,OSMANABAD,1997,Autumn,Maize,5.0,5635.0,1127.000,7.231
181749,Tamil Nadu,VILLUPURAM,1997,Whole Year,Sugarcane,33175.0,37158000.0,1120.060,137.585
172592,Tamil Nadu,ERODE,1997,Whole Year,Sugarcane,24112.0,26930000.0,1116.871,137.585
119266,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000,7.231
178287,Tamil Nadu,THENI,1997,Whole Year,Sugarcane,9524.0,10598000.0,1112.768,137.585
178014,Tamil Nadu,THE NILGIRIS,1997,Whole Year,Sugarcane,22.0,24000.0,1090.909,137.585
180862,Tamil Nadu,TUTICORIN,1997,Whole Year,Sugarcane,90.0,97000.0,1077.778,137.585
179814,Tamil Nadu,TIRUNELVELI,1997,Whole Year,Sugarcane,2237.0,2402000.0,1073.759,137.585
174820,Tamil Nadu,NAGAPATTINAM,1997,Whole Year,Sugarcane,4601.0,4940000.0,1073.680,137.585
176021,Tamil Nadu,PUDUKKOTTAI,1997,Whole Year,Sugarcane,2377.0,2552000.0,1073.622,137.585
182202,Tamil Nadu,VIRUDHUNAGAR,1997,Whole Year,Sugarcane,2639.0,2833000.0,1073.513,137.585
176409,Tamil Nadu,RAMANATHAPURAM,1997,Whole Year,Sugarcane,182.0,195000.0,1071.429,137.585
171571,Tamil Nadu,DHARMAPURI,1997,Whole Year,Sugarcane,18938.0,18100000.0,955.750,137.585
175585,Tamil Nadu,PERAMBALUR,1997,Whole Year,Sugarcane,11508.0,10448000.0,907.890,137.585
180411,Tamil Nadu,TIRUVANNAMALAI,1997,Whole Year,Sugarcane,27636.0,23914000.0,865.321,137.585
172057,Tamil Nadu,DINDIGUL,1997,Whole Year,Sugarcane,6826.0,5749000.0,842.221,137.585
177269,Tamil Nadu,SIVAGANGA,1997,Whole Year,Sugarcane,4794.0,3938000.0,821.443,137.585
177649,Tamil Nadu,THANJAVUR,1997,Whole Year,Sugarcane,12604.0,9900000.0,785.465,137.585
181293,Tamil Nadu,VELLORE,1997,Whole Year,Sugarcane,29072.0,22069000.0,759.115,137.585
122380,Maharashtra,DHULE,1997,Autumn,Maize,4.0,2901.0,725.250,7.231
179100,Tamil Nadu,THIRUVARUR,1997,Whole Year,Sugarcane,3669.0,2287000.0,623.331,137.585
29702,Bihar,BUXAR,1997,Whole Year,Sugarcane,59.0,29529.0,500.492,137.585
170982,Tamil Nadu,COIMBATORE,2008,Whole Year,Sugarcane,2581.0,812334.0,314.736,137.585
174411,Tamil Nadu,MADURAI,1998,Whole Year,Sugarcane,10081.0,3059430.0,303.485,137.585
127995,Maharashtra,PUNE,1997,Whole Year,Cotton(lint),2.0,600.0,300.000,5.788
175880,Tamil Nadu,PERAMBALUR,2008,Whole Year,Sugarcane,3688.0,952805.0,258.353,137.585
173107,Tamil Nadu,KANCHIPURAM,1998,Whole Year,Sugarcane,23801.0,5775500.0,242.658,137.585
129351,Maharashtra,SATARA,1997,Whole Year,Cotton(lint),45.0,10600.0,235.556,5.788
60973,Gujarat,NARMADA,2012,Summer,Sesamum,100.0,23500.0,235.000,1.108
128907,Maharashtra,SANGLI,1997,Whole Year,Cotton(lint),32.0,7500.0,234.375,5.788
96919,Kerala,PATHANAMTHITTA,2008,Whole Year,Sugarcane,14.0,3210.0,229.286,137.585
178318,Tamil Nadu,THENI,1998,Whole Year,Sugarcane,16133.0,3617820.0,224.250,137.585
124523,Maharashtra,KOLHAPUR,1997,Kharif,Rice,1100.0,246100.0,223.727,4.518
235056,West Bengal,MEDINIPUR WEST,2013,Whole Year,Sugarcane,3210.0,708183.0,220.618,137.585
67123,Haryana,PANIPAT,2002,Whole Year,Potato,195.0,41700.0,213.846,31.350
173654,Tamil Nadu,KARUR,1997,Whole Year,Onion,228.0,46530.0,204.079,33.000

Report saved to: /content/drive/MyDrive/yield prediction/top_50_extreme_yield_records.csv

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "crop_production_124_training_ready.csv")

df = pd.read_csv(path)

# Recalculate target and crop-specific 99th percentile
df["yield_per_area"] = df["Production"] / df["Area"]
crop_p99 = df.groupby("Crop")["yield_per_area"].transform(
    lambda s: s.quantile(0.99)
)

df["above_crop_p99"] = df["yield_per_area"] > crop_p99
df["extreme_ratio"] = df["yield_per_area"] / crop_p99

# 1. Extreme records grouped by crop and year
crop_year = (
    df[df["above_crop_p99"]]
    .groupby(["Crop", "Crop_Year"])
    .agg(
        extreme_records=("yield_per_area", "size"),
        median_yield=("yield_per_area", "median"),
        max_yield=("yield_per_area", "max"),
        median_area=("Area", "median")
    )
    .reset_index()
    .sort_values("extreme_records", ascending=False)
)

print("TOP CROP-YEAR GROUPS WITH EXTREME YIELDS")
display(crop_year.head(30).round(3))

# 2. Focus on suspicious crop/year patterns
focus = df[
    (
        (df["Crop"] == "Sugarcane") &
        (df["Crop_Year"].isin([1997, 1998, 2008]))
    ) |
    (
        (df["Crop"] == "Maize") &
        (df["Crop_Year"] == 1997)
    ) |
    (
        (df["Crop"] == "Cashewnut") &
        (df["Crop_Year"] == 2008)
    )
].copy()

print("\nFOCUSED CROP/YEAR SUMMARY")
summary = (
    focus.groupby(["Crop", "Crop_Year"])
    .agg(
        records=("yield_per_area", "size"),
        median_yield=("yield_per_area", "median"),
        p95_yield=("yield_per_area", lambda s: s.quantile(0.95)),
        max_yield=("yield_per_area", "max"),
        records_area_le_5=("Area", lambda s: (s <= 5).sum())
    )
    .reset_index()
)
display(summary.round(3))

# Save audit report; original dataset remains unchanged
out = os.path.join(base, "yield_extreme_audit_by_crop_year.csv")
crop_year.to_csv(out, index=False)
print("\nAudit saved to:", out)

TOP CROP-YEAR GROUPS WITH EXTREME YIELDS

,Crop,Crop_Year,extreme_records,median_yield,max_yield,median_area
617,Wheat,2011,30,5.255,5.676,170500.0
440,Rice,2013,29,4.828,6.084,30889.0
511,Sugarcane,1997,28,1075.769,2247.533,6780.5
187,Groundnut,2011,25,3.751,6.146,4393.0
263,Maize,2013,24,7.530,8.675,10764.5
116,Cotton(lint),1997,23,58.697,300.000,829.0
189,Groundnut,2013,22,3.630,6.094,2377.5
371,Peas & beans (Pulses),1998,22,9.185,13.589,27.5
418,Rapeseed &Mustard,2010,21,2.398,3.361,935.0
408,Ragi,2013,21,3.966,4.748,109.0
537,Sunflower,2007,19,2.817,3.000,95.0
619,Wheat,2013,17,5.062,5.498,183000.0
480,Sesamum,2012,16,42.633,235.000,286.0
258,Maize,2008,15,8.830,25.677,3658.0
261,Maize,2011,15,7.759,8.840,6208.0
136,Dry chillies,2012,15,10.000,16.667,38.0
305,Moong(Green Gram),2013,14,1.224,1.631,427.0
607,Urad,2014,14,1.326,1.950,723.0
395,Potato,2014,14,33.559,40.777,10772.5
375,Peas & beans (Pulses),2011,14,10.237,11.688,96.5
435,Rice,2008,13,4.828,9.886,18187.0
419,Rapeseed &Mustard,2011,13,2.436,2.834,746.0
599,Urad,2006,13,1.245,2.000,50.0
260,Maize,2010,13,9.117,16.270,5551.0
570,Tobacco,2003,12,7.500,8.000,20.5
306,Moong(Green Gram),2014,12,1.260,2.000,480.0
259,Maize,2009,12,7.310,8.389,3626.0
191,Guar seed,1999,12,11.982,33.609,10735.0
21,Arhar/Tur,2012,11,2.855,8.000,419.0
481,Sesamum,2013,11,1.248,1.389,169.0

FOCUSED CROP/YEAR SUMMARY

,Crop,Crop_Year,records,median_yield,p95_yield,max_yield,records_area_le_5
0,Cashewnut,2008,79,0.521,1.073,9801.000,6
1,Maize,1997,648,1.579,3.464,1494.000,43
2,Sugarcane,1997,330,55.366,1073.573,2247.533,2
3,Sugarcane,1998,408,51.851,121.505,303.485,11
4,Sugarcane,2008,482,51.147,106.531,314.736,16

Audit saved to: /content/drive/MyDrive/yield prediction/yield_extreme_audit_by_crop_year.csv

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "crop_production_124_training_ready.csv")
df = pd.read_csv(path)

df["yield_per_area"] = df["Production"] / df["Area"]

checks = [
    ("Sugarcane", 1997),
    ("Sugarcane", 1998),
    ("Sugarcane", 2008),
    ("Cashewnut", 2008),
    ("Maize", 1997),
]

for crop, year in checks:
    group = df[
        (df["Crop"] == crop) &
        (df["Crop_Year"] == year)
    ].copy()

    if group.empty:
        continue

    print(f"\n{'='*70}")
    print(f"{crop} — {year} | Total records: {len(group)}")
    print("Yield quantiles:")
    print(group["yield_per_area"].quantile(
        [0.50, 0.90, 0.95, 0.99, 1.00]
    ).round(3))

    # Highest 10 records
    cols = [
        "State_Name", "District_Name", "Crop_Year",
        "Season", "Crop", "Area", "Production",
        "yield_per_area"
    ]
    print("\nHighest 10 yields:")
    display(
        group.nlargest(10, "yield_per_area")[cols]
        .round(3)
        .reset_index()
        .rename(columns={"index": "original_row"})
    )

    # Typical records around the median
    median = group["yield_per_area"].median()
    group["distance_from_median"] = (
        group["yield_per_area"] - median
    ).abs()

    print("\n5 records closest to the median:")
    display(
        group.nsmallest(5, "distance_from_median")[cols]
        .round(3)
        .reset_index()
        .rename(columns={"index": "original_row"})
    )

======================================================================
Sugarcane — 1997 | Total records: 330
Yield quantiles:
0.50      55.366
0.90     106.134
0.95    1073.573
0.99    1416.407
1.00    2247.533
Name: yield_per_area, dtype: float64

Highest 10 yields:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,174381,Tamil Nadu,MADURAI,1997,Whole Year,Sugarcane,8108.0,18223000.0,2247.533
1,178746,Tamil Nadu,THIRUVALLUR,1997,Whole Year,Sugarcane,5964.0,11811000.0,1980.382
2,173083,Tamil Nadu,KANCHIPURAM,1997,Whole Year,Sugarcane,6735.0,9896000.0,1469.339
3,175100,Tamil Nadu,NAMAKKAL,1997,Whole Year,Sugarcane,9415.0,13608000.0,1445.353
4,179359,Tamil Nadu,TIRUCHIRAPPALLI,1997,Whole Year,Sugarcane,4315.0,5806000.0,1345.539
5,171139,Tamil Nadu,CUDDALORE,1997,Whole Year,Sugarcane,23826.0,28322000.0,1188.701
6,173658,Tamil Nadu,KARUR,1997,Whole Year,Sugarcane,5961.0,7081000.0,1187.888
7,176767,Tamil Nadu,SALEM,1997,Whole Year,Sugarcane,13759.0,15866000.0,1153.136
8,170659,Tamil Nadu,COIMBATORE,1997,Whole Year,Sugarcane,10756.0,12272000.0,1140.945
9,181749,Tamil Nadu,VILLUPURAM,1997,Whole Year,Sugarcane,33175.0,37158000.0,1120.060

5 records closest to the median:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,33552,Bihar,KHAGARIA,1997,Whole Year,Sugarcane,207.0,11455.0,55.338
1,150540,Odisha,NABARANGPUR,1997,Winter,Sugarcane,2833.0,156931.0,55.394
2,31705,Bihar,JAMUI,1997,Whole Year,Sugarcane,530.0,29361.0,55.398
3,209973,Uttar Pradesh,KUSHI NAGAR,1997,Whole Year,Sugarcane,74539.0,4130951.0,55.420
4,212356,Uttar Pradesh,MAINPURI,1997,Whole Year,Sugarcane,499.0,27565.0,55.240

======================================================================
Sugarcane — 1998 | Total records: 408
Yield quantiles:
0.50     51.851
0.90     94.053
0.95    121.505
0.99    163.158
1.00    303.485
Name: yield_per_area, dtype: float64

Highest 10 yields:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,174411,Tamil Nadu,MADURAI,1998,Whole Year,Sugarcane,10081.0,3059430.0,303.485
1,173107,Tamil Nadu,KANCHIPURAM,1998,Whole Year,Sugarcane,23801.0,5775500.0,242.658
2,178318,Tamil Nadu,THENI,1998,Whole Year,Sugarcane,16133.0,3617820.0,224.250
3,178770,Tamil Nadu,THIRUVALLUR,1998,Whole Year,Sugarcane,8284.0,1432090.0,172.874
4,65198,Haryana,GURGAON,1998,Whole Year,Sugarcane,306.0,50000.0,163.399
5,175132,Tamil Nadu,NAMAKKAL,1998,Whole Year,Sugarcane,9411.0,1505330.0,159.954
6,179391,Tamil Nadu,TIRUCHIRAPPALLI,1998,Whole Year,Sugarcane,13204.0,1899500.0,143.858
7,171168,Tamil Nadu,CUDDALORE,1998,Whole Year,Sugarcane,32654.0,4401890.0,134.804
8,176801,Tamil Nadu,SALEM,1998,Whole Year,Sugarcane,10765.0,1440330.0,133.797
9,120942,Maharashtra,BEED,1998,Kharif,Sugarcane,20200.0,2685400.0,132.941

5 records closest to the median:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,150561,Odisha,NABARANGPUR,1998,Winter,Sugarcane,1925.0,99820.0,51.855
1,209475,Uttar Pradesh,KHERI,1998,Whole Year,Sugarcane,189213.0,9810316.0,51.848
2,27149,Bihar,AURANGABAD,1998,Whole Year,Sugarcane,556.0,28873.0,51.930
3,30653,Bihar,GAYA,1998,Whole Year,Sugarcane,2155.0,111909.0,51.930
4,32119,Bihar,JEHANABAD,1998,Whole Year,Sugarcane,330.0,17137.0,51.930

======================================================================
Sugarcane — 2008 | Total records: 482
Yield quantiles:
0.50     51.147
0.90     94.375
0.95    106.531
0.99    130.091
1.00    314.736
Name: yield_per_area, dtype: float64

Highest 10 yields:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,170982,Tamil Nadu,COIMBATORE,2008,Whole Year,Sugarcane,2581.0,812334.0,314.736
1,175880,Tamil Nadu,PERAMBALUR,2008,Whole Year,Sugarcane,3688.0,952805.0,258.353
2,96919,Kerala,PATHANAMTHITTA,2008,Whole Year,Sugarcane,14.0,3210.0,229.286
3,95102,Kerala,KANNUR,2008,Whole Year,Sugarcane,40.0,7220.0,180.500
4,178601,Tamil Nadu,THENI,2008,Whole Year,Sugarcane,6366.0,852350.0,133.891
5,76521,Karnataka,BELLARY,2008,Whole Year,Sugarcane,1932.0,249614.0,129.200
6,172939,Tamil Nadu,ERODE,2008,Whole Year,Sugarcane,37039.0,4632740.0,125.077
7,175427,Tamil Nadu,NAMAKKAL,2008,Whole Year,Sugarcane,18959.0,2356130.0,124.275
8,173328,Tamil Nadu,KANCHIPURAM,2008,Whole Year,Sugarcane,1936.0,240128.0,124.033
9,228788,West Bengal,BANKURA,2008,Whole Year,Sugarcane,26.0,3169.0,121.885

5 records closest to the median:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,202017,Uttar Pradesh,FIROZABAD,2008,Kharif,Sugarcane,129.0,6598.0,51.147
1,205706,Uttar Pradesh,HATHRAS,2008,Kharif,Sugarcane,212.0,10843.0,51.146
2,189773,Uttar Pradesh,AGRA,2008,Kharif,Sugarcane,172.0,8797.0,51.145
3,212603,Uttar Pradesh,MAINPURI,2008,Kharif,Sugarcane,423.0,21636.0,51.149
4,116319,Madhya Pradesh,SHEOPUR,2008,Whole Year,Sugarcane,38.0,1940.0,51.053

======================================================================
Cashewnut — 2008 | Total records: 79
Yield quantiles:
0.50       0.521
0.90       0.884
0.95       1.073
0.99    2158.217
1.00    9801.000
Name: yield_per_area, dtype: float64

Highest 10 yields:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,175865,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.00,9801.000
1,172922,Tamil Nadu,ERODE,2008,Whole Year,Cashewnut,25.0,64.00,2.560
2,170966,Tamil Nadu,COIMBATORE,2008,Whole Year,Cashewnut,120.0,141.00,1.175
3,95359,Kerala,KASARAGOD,2008,Whole Year,Cashewnut,9487.0,10347.00,1.091
4,95100,Kerala,KANNUR,2008,Whole Year,Cashewnut,19372.0,20757.00,1.071
5,154441,Puducherry,MAHE,2008,Kharif,Cashewnut,4.0,4.00,1.000
6,154629,Puducherry,PONDICHERRY,2008,Kharif,Cashewnut,164.0,164.00,1.000
7,171882,Tamil Nadu,DHARMAPURI,2008,Whole Year,Cashewnut,1.0,1.00,1.000
8,93731,Karnataka,UTTAR KANNAD,2008,Whole Year,Cashewnut,2952.0,2525.02,0.855
9,154299,Puducherry,KARAIKAL,2008,Kharif,Cashewnut,6.0,5.00,0.833

5 records closest to the median:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,175002,Tamil Nadu,NAGAPATTINAM,2008,Whole Year,Cashewnut,2049.0,1068.0,0.521
1,181143,Tamil Nadu,TUTICORIN,2008,Whole Year,Cashewnut,817.0,426.0,0.521
2,180131,Tamil Nadu,TIRUNELVELI,2008,Whole Year,Cashewnut,4992.0,2601.0,0.521
3,172400,Tamil Nadu,DINDIGUL,2008,Whole Year,Cashewnut,411.0,214.0,0.521
4,182484,Tamil Nadu,VIRUDHUNAGAR,2008,Whole Year,Cashewnut,73.0,38.0,0.521

======================================================================
Maize — 1997 | Total records: 648
Yield quantiles:
0.50       1.579
0.90       2.753
0.95       3.464
0.99       7.912
1.00    1494.000
Name: yield_per_area, dtype: float64

Highest 10 yields:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,126592,Maharashtra,NASHIK,1997,Autumn,Maize,1.0,1494.0,1494.000
1,123689,Maharashtra,JALGAON,1997,Autumn,Maize,3.0,3980.0,1326.667
2,127977,Maharashtra,PUNE,1997,Autumn,Maize,4.0,4570.0,1142.500
3,127043,Maharashtra,OSMANABAD,1997,Autumn,Maize,5.0,5635.0,1127.000
4,119266,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000
5,122380,Maharashtra,DHULE,1997,Autumn,Maize,4.0,2901.0,725.250
6,132391,Manipur,SENAPATI,1997,Kharif,Maize,1.0,8.0,8.000
7,236263,West Bengal,PURULIA,1997,Whole Year,Maize,869.0,6790.0,7.814
8,5324,Andhra Pradesh,PRAKASAM,1997,Kharif,Maize,1800.0,8100.0,4.500
9,230123,West Bengal,COOCHBEHAR,1997,Whole Year,Maize,7.0,30.0,4.286

5 records closest to the median:

,original_row,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area
0,199336,Uttar Pradesh,ETAH,1997,Summer,Maize,837.0,1322.0,1.579
1,209969,Uttar Pradesh,KUSHI NAGAR,1997,Summer,Maize,780.0,1232.0,1.579
2,195121,Uttar Pradesh,BARABANKI,1997,Summer,Maize,523.0,826.0,1.579
3,213696,Uttar Pradesh,MEERUT,1997,Summer,Maize,816.0,1289.0,1.580
4,203924,Uttar Pradesh,GORAKHPUR,1997,Summer,Maize,164.0,259.0,1.579

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "crop_production_124_training_ready.csv")
df = pd.read_csv(path)

df["yield_per_area"] = df["Production"] / df["Area"]

# Crop-year-specific 99th percentile
df["crop_year_p99"] = df.groupby(
    ["Crop", "Crop_Year"]
)["yield_per_area"].transform(
    lambda s: s.quantile(0.99)
)

# Flag the crop-year combinations investigated so far
focus = (
    ((df["Crop"] == "Sugarcane") &
     (df["Crop_Year"].isin([1997, 1998, 2008]))) |
    ((df["Crop"] == "Cashewnut") &
     (df["Crop_Year"] == 2008)) |
    ((df["Crop"] == "Maize") &
     (df["Crop_Year"] == 1997))
)

audit = df.loc[focus].copy()
audit["above_crop_year_p99"] = (
    audit["yield_per_area"] > audit["crop_year_p99"]
)

cols = [
    "State_Name", "District_Name", "Crop_Year", "Season",
    "Crop", "Area", "Production", "yield_per_area",
    "crop_year_p99", "above_crop_year_p99"
]

out = os.path.join(base, "crop_yield_source_audit.csv")
audit[cols].to_csv(out, index=False)

print("Records inspected:", len(audit))
print("Above crop-year P99:", int(audit["above_crop_year_p99"].sum()))
print("Audit saved:", out)

print("\nSummary by crop and year:")
display(
    audit.groupby(["Crop", "Crop_Year"]).agg(
        records=("yield_per_area", "size"),
        above_p99=("above_crop_year_p99", "sum"),
        median_yield=("yield_per_area", "median"),
        max_yield=("yield_per_area", "max")
    ).round(3)
)

Records inspected: 1947
Above crop-year P99: 22
Audit saved: /content/drive/MyDrive/yield prediction/crop_yield_source_audit.csv

Summary by crop and year:

                     records  above_p99  median_yield  max_yield
Crop      Crop_Year
Cashewnut 2008            79          1         0.521   9801.000
Maize     1997           648          7         1.579   1494.000
Sugarcane 1997           330          4        55.366   2247.533
          1998           408          5        51.851    303.485
          2008           482          5        51.147    314.736

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "crop_yield_source_audit.csv")
audit = pd.read_csv(path)

flagged = audit[audit["above_crop_year_p99"]].copy()
flagged = flagged.sort_values("yield_per_area", ascending=False)

cols = [
    "State_Name", "District_Name", "Crop_Year", "Season",
    "Crop", "Area", "Production", "yield_per_area",
    "crop_year_p99"
]

print("Flagged records:", len(flagged))
display(flagged[cols].round(3).reset_index(drop=True))

out = os.path.join(base, "flagged_yield_records_for_review.csv")
flagged[cols].to_csv(out, index=False)
print("Review file saved:", out)

Flagged records: 22

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area,crop_year_p99
0,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.0,9801.000,2158.217
1,Tamil Nadu,MADURAI,1997,Whole Year,Sugarcane,8108.0,18223000.0,2247.533,1416.407
2,Tamil Nadu,THIRUVALLUR,1997,Whole Year,Sugarcane,5964.0,11811000.0,1980.382,1416.407
3,Maharashtra,NASHIK,1997,Autumn,Maize,1.0,1494.0,1494.000,7.912
4,Tamil Nadu,KANCHIPURAM,1997,Whole Year,Sugarcane,6735.0,9896000.0,1469.339,1416.407
5,Tamil Nadu,NAMAKKAL,1997,Whole Year,Sugarcane,9415.0,13608000.0,1445.353,1416.407
6,Maharashtra,JALGAON,1997,Autumn,Maize,3.0,3980.0,1326.667,7.912
7,Maharashtra,PUNE,1997,Autumn,Maize,4.0,4570.0,1142.500,7.912
8,Maharashtra,OSMANABAD,1997,Autumn,Maize,5.0,5635.0,1127.000,7.912
9,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000,7.912
10,Maharashtra,DHULE,1997,Autumn,Maize,4.0,2901.0,725.250,7.912
11,Tamil Nadu,COIMBATORE,2008,Whole Year,Sugarcane,2581.0,812334.0,314.736,130.091
12,Tamil Nadu,MADURAI,1998,Whole Year,Sugarcane,10081.0,3059430.0,303.485,163.158
13,Tamil Nadu,PERAMBALUR,2008,Whole Year,Sugarcane,3688.0,952805.0,258.353,130.091
14,Tamil Nadu,KANCHIPURAM,1998,Whole Year,Sugarcane,23801.0,5775500.0,242.658,163.158
15,Kerala,PATHANAMTHITTA,2008,Whole Year,Sugarcane,14.0,3210.0,229.286,130.091
16,Tamil Nadu,THENI,1998,Whole Year,Sugarcane,16133.0,3617820.0,224.250,163.158
17,Kerala,KANNUR,2008,Whole Year,Sugarcane,40.0,7220.0,180.500,130.091
18,Tamil Nadu,THIRUVALLUR,1998,Whole Year,Sugarcane,8284.0,1432090.0,172.874,163.158
19,Haryana,GURGAON,1998,Whole Year,Sugarcane,306.0,50000.0,163.399,163.158
20,Tamil Nadu,THENI,2008,Whole Year,Sugarcane,6366.0,852350.0,133.891,130.091
21,Manipur,SENAPATI,1997,Kharif,Maize,1.0,8.0,8.000,7.912

Review file saved: /content/drive/MyDrive/yield prediction/flagged_yield_records_for_review.csv

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "flagged_yield_records_for_review.csv")
df = pd.read_csv(path)

# Prioritize extremely high yields, excluding the relatively modest Manipur record
priority = df[
    (df["yield_per_area"] > 100) |
    (
        (df["Crop"] == "Maize") &
        (df["Crop_Year"] == 1997) &
        (df["Area"] <= 5)
    )
].copy()

priority["verification_reason"] = priority.apply(
    lambda r: (
        "Very small area" if r["Area"] <= 5
        else "Extreme yield; verify source units and reported values"
    ),
    axis=1
)

cols = [
    "State_Name", "District_Name", "Crop_Year", "Season",
    "Crop", "Area", "Production", "yield_per_area",
    "verification_reason"
]

display(priority[cols].round(3).reset_index(drop=True))

out = os.path.join(base, "priority_source_verification.csv")
priority[cols].to_csv(out, index=False)
print("\nPriority records:", len(priority))
print("Saved:", out)

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield_per_area,verification_reason
0,Tamil Nadu,PERAMBALUR,2008,Whole Year,Cashewnut,1.0,9801.0,9801.000,Very small area
1,Tamil Nadu,MADURAI,1997,Whole Year,Sugarcane,8108.0,18223000.0,2247.533,Extreme yield; verify source units and reporte...
2,Tamil Nadu,THIRUVALLUR,1997,Whole Year,Sugarcane,5964.0,11811000.0,1980.382,Extreme yield; verify source units and reporte...
3,Maharashtra,NASHIK,1997,Autumn,Maize,1.0,1494.0,1494.000,Very small area
4,Tamil Nadu,KANCHIPURAM,1997,Whole Year,Sugarcane,6735.0,9896000.0,1469.339,Extreme yield; verify source units and reporte...
5,Tamil Nadu,NAMAKKAL,1997,Whole Year,Sugarcane,9415.0,13608000.0,1445.353,Extreme yield; verify source units and reporte...
6,Maharashtra,JALGAON,1997,Autumn,Maize,3.0,3980.0,1326.667,Very small area
7,Maharashtra,PUNE,1997,Autumn,Maize,4.0,4570.0,1142.500,Very small area
8,Maharashtra,OSMANABAD,1997,Autumn,Maize,5.0,5635.0,1127.000,Very small area
9,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0,1113.000,Very small area
10,Maharashtra,DHULE,1997,Autumn,Maize,4.0,2901.0,725.250,Very small area
11,Tamil Nadu,COIMBATORE,2008,Whole Year,Sugarcane,2581.0,812334.0,314.736,Extreme yield; verify source units and reporte...
12,Tamil Nadu,MADURAI,1998,Whole Year,Sugarcane,10081.0,3059430.0,303.485,Extreme yield; verify source units and reporte...
13,Tamil Nadu,PERAMBALUR,2008,Whole Year,Sugarcane,3688.0,952805.0,258.353,Extreme yield; verify source units and reporte...
14,Tamil Nadu,KANCHIPURAM,1998,Whole Year,Sugarcane,23801.0,5775500.0,242.658,Extreme yield; verify source units and reporte...
15,Kerala,PATHANAMTHITTA,2008,Whole Year,Sugarcane,14.0,3210.0,229.286,Extreme yield; verify source units and reporte...
16,Tamil Nadu,THENI,1998,Whole Year,Sugarcane,16133.0,3617820.0,224.250,Extreme yield; verify source units and reporte...
17,Kerala,KANNUR,2008,Whole Year,Sugarcane,40.0,7220.0,180.500,Extreme yield; verify source units and reporte...
18,Tamil Nadu,THIRUVALLUR,1998,Whole Year,Sugarcane,8284.0,1432090.0,172.874,Extreme yield; verify source units and reporte...
19,Haryana,GURGAON,1998,Whole Year,Sugarcane,306.0,50000.0,163.399,Extreme yield; verify source units and reporte...
20,Tamil Nadu,THENI,2008,Whole Year,Sugarcane,6366.0,852350.0,133.891,Extreme yield; verify source units and reporte...
21,Manipur,SENAPATI,1997,Kharif,Maize,1.0,8.0,8.000,Very small area

Priority records: 22
Saved: /content/drive/MyDrive/yield prediction/priority_source_verification.csv

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
data_path = os.path.join(base, "crop_production_124_training_ready.csv")
flag_path = os.path.join(base, "flagged_yield_records_for_review.csv")

df = pd.read_csv(data_path)
flags = pd.read_csv(flag_path)

# Match exact records using their identifying columns and values
keys = [
    "State_Name", "District_Name", "Crop_Year", "Season",
    "Crop", "Area", "Production"
]

original = df.copy()
original["_row_id"] = range(len(original))

flag_keys = flags[keys].drop_duplicates()
candidate = original.merge(
    flag_keys.assign(_flag=True),
    on=keys,
    how="left"
)

removed = candidate["_flag"].fillna(False)
cleaned = candidate.loc[~removed, original.columns].drop(
    columns=["_row_id"], errors="ignore"
)

out = os.path.join(base, "yield_candidate_excluding_flagged.csv")
cleaned.to_csv(out, index=False)

print("Original rows:", len(df))
print("Flagged records matched:", int(removed.sum()))
print("Candidate rows:", len(cleaned))
print("Saved candidate:", out)
print("\nWARNING: This is an experimental candidate, not a verified-clean dataset.")

/tmp/ipykernel_1423/323786114.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  removed = candidate["_flag"].fillna(False)

Original rows: 236866
Flagged records matched: 22
Candidate rows: 236844
Saved candidate: /content/drive/MyDrive/yield prediction/yield_candidate_excluding_flagged.csv

WARNING: This is an experimental candidate, not a verified-clean dataset.

In [ ]:

import joblib
import os

base = "/content/drive/MyDrive/yield prediction"
model_path = os.path.join(
    base, "cropsense_xgboost_yield_800_trees.joblib"
)

model = joblib.load(model_path)

print("Model loaded successfully.")
print("Model object type:", type(model))

if hasattr(model, "feature_names_in_"):
    print("Expected features:", list(model.feature_names_in_))
elif hasattr(model, "named_steps"):
    print("Pipeline steps:", list(model.named_steps.keys()))
    print("Expected preprocessing/model pipeline is available.")
elif isinstance(model, dict):
    print("Saved artifact keys:", list(model.keys()))
else:
    print("Inspect the model object above to identify its input features.")

Model loaded successfully.
Model object type: <class 'sklearn.pipeline.Pipeline'>
Expected features: ['State_Name', 'District_Name', 'Season', 'Crop', 'soil_type', 'Crop_Year', 'temperature', 'humidity', 'rainfall_mm']

In [ ]:

import pandas as pd
import numpy as np
import joblib
import os
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

base = "/content/drive/MyDrive/yield prediction"

original_path = os.path.join(
    base, "crop_production_124_training_ready.csv"
)
candidate_path = os.path.join(
    base, "yield_candidate_excluding_flagged.csv"
)
model_path = os.path.join(
    base, "cropsense_xgboost_yield_800_trees.joblib"
)

model = joblib.load(model_path)
original = pd.read_csv(original_path)
candidate = pd.read_csv(candidate_path)

features = [
    "State_Name", "District_Name", "Season", "Crop", "soil_type",
    "Crop_Year", "temperature", "humidity", "rainfall_mm"
]
target = "yield_per_area"

# Match the existing chronological test period: 2014–2015
results = []

for name, data in [
    ("Original", original),
    ("Candidate", candidate)
]:
    test = data[data["Crop_Year"].isin([2014, 2015])].copy()

    X_test = test[features]
    y_test = test[target]
    predictions = model.predict(X_test)

    results.append({
        "Dataset": name,
        "Test rows": len(test),
        "MAE": mean_absolute_error(y_test, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_test, predictions)),
        "R2": r2_score(y_test, predictions)
    })

results_df = pd.DataFrame(results)
display(results_df.round(4))

print("Note: this is a diagnostic comparison on the test years.")
print("Use the validation years 2012–2013 to select cleaning/model changes.")

     Dataset  Test rows     MAE    RMSE      R2
0   Original      11311  1.7419  4.7612  0.8637
1  Candidate      11311  1.7419  4.7612  0.8637

Note: this is a diagnostic comparison on the test years.
Use the validation years 2012–2013 to select cleaning/model changes.

# Model Training

In [ ]:

import os
import numpy as np
import pandas as pd
import joblib

from xgboost import XGBRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Paths
base = "/content/drive/MyDrive/yield prediction"
original_path = os.path.join(base, "crop_production_124_training_ready.csv")
candidate_path = os.path.join(base, "yield_candidate_excluding_flagged.csv")

# Features and target
cat_cols = ["State_Name", "District_Name", "Season", "Crop", "soil_type"]
num_cols = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = cat_cols + num_cols
target = "yield_per_area"

def load_data(path):
    df = pd.read_csv(path, low_memory=False)
    df.columns = df.columns.str.strip()

    for c in ["Crop_Year", "Area", "Production",
              "temperature", "humidity", "rainfall_mm"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    df = df[
        df["Crop_Year"].notna()
        & df["Area"].gt(0)
        & df["Production"].gt(0)
    ].copy()

    # Recalculate target consistently
    df[target] = df["Production"] / df["Area"]
    df = df.replace([np.inf, -np.inf], np.nan)
    df = df[df[target].notna()].copy()

    for c in cat_cols:
        df[c] = df[c].fillna("Unknown").astype(str).str.strip()
        df[c] = df[c].replace("", "Unknown")

    return df

def make_model():
    preprocessor = ColumnTransformer([
        ("numeric", Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]), num_cols),
        ("categorical", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore"))
        ]), cat_cols)
    ])

    return Pipeline([
        ("preprocessor", preprocessor),
        ("regressor", XGBRegressor(
            objective="reg:squarederror",
            n_estimators=800,
            max_depth=8,
            learning_rate=0.05,
            subsample=0.85,
            colsample_bytree=0.85,
            reg_lambda=5,
            random_state=42,
            n_jobs=-1,
            tree_method="hist"
        ))
    ])

def evaluate(name, model, X_val, y_val):
    pred = model.predict(X_val)
    return {
        "Dataset": name,
        "Validation rows": len(y_val),
        "MAE": mean_absolute_error(y_val, pred),
        "RMSE": np.sqrt(mean_squared_error(y_val, pred)),
        "R2": r2_score(y_val, pred),
        "Negative predictions": int((pred < 0).sum())
    }

results = []
trained_models = {}

for name, path in [
    ("Original", original_path),
    ("Candidate (-22 flagged rows)", candidate_path)
]:
    print(f"\nLoading and training: {name}")
    df = load_data(path)

    train = df[df["Crop_Year"] <= 2011]
    val = df[df["Crop_Year"].isin([2012, 2013])]

    X_train, y_train = train[features], train[target]
    X_val, y_val = val[features], val[target]

    print("Train rows:", len(train), "| Validation rows:", len(val))

    model = make_model()
    model.fit(X_train, y_train)

    results.append(evaluate(name, model, X_val, y_val))
    trained_models[name] = model

results_df = pd.DataFrame(results)
print("\n========== VALIDATION COMPARISON ==========")
display(results_df.round(4))

# Determine winner using validation R²
winner_idx = results_df["R2"].idxmax()
winner_name = results_df.loc[winner_idx, "Dataset"]
print("Higher validation R²:", winner_name)

# Save both models under new filenames
joblib.dump(
    trained_models["Original"],
    os.path.join(base, "comparison_original_xgb_800.joblib")
)
joblib.dump(
    trained_models["Candidate (-22 flagged rows)"],
    os.path.join(base, "comparison_candidate_xgb_800.joblib")
)

results_df.to_csv(
    os.path.join(base, "xgb_cleaning_comparison_validation.csv"),
    index=False
)

print("\nBoth comparison models and results saved.")
print("Your existing champion model was not overwritten.")

Loading and training: Original
Train rows: 199107 | Validation rows: 26448

Loading and training: Candidate (-22 flagged rows)
Train rows: 199085 | Validation rows: 26448

========== VALIDATION COMPARISON ==========

,Dataset,Validation rows,MAE,RMSE,R2,Negative predictions
0,Original,26448,1.5097,5.1439,0.8434,118
1,Candidate (-22 flagged rows),26448,1.4338,4.9867,0.8528,168

Higher validation R²: Candidate (-22 flagged rows)

Both comparison models and results saved.
Your existing champion model was not overwritten.

In [ ]:

import os
import numpy as np
import pandas as pd
import joblib

from xgboost import XGBRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "yield_candidate_excluding_flagged.csv")

df = pd.read_csv(path, low_memory=False)
df.columns = df.columns.str.strip()

for c in ["Crop_Year", "Area", "Production",
          "temperature", "humidity", "rainfall_mm"]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]
df = df.replace([np.inf, -np.inf], np.nan)
df = df[df["yield_per_area"].notna()].copy()

cat_cols = [
    "State_Name", "District_Name", "Season", "Crop", "soil_type"
]
num_cols = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = cat_cols + num_cols

X = df[features].copy()
y = df["yield_per_area"].copy()

for c in cat_cols:
    X[c] = X[c].fillna("Unknown").astype(str).str.strip()
    X[c] = X[c].replace("", "Unknown")

train_mask = df["Crop_Year"] <= 2011
val_mask = df["Crop_Year"].isin([2012, 2013])

X_train, y_train = X.loc[train_mask], y.loc[train_mask]
X_val, y_val = X.loc[val_mask], y.loc[val_mask]

preprocessor = ColumnTransformer([
    ("numeric", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), num_cols),
    ("categorical", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

log_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(
        objective="reg:squarederror",
        n_estimators=800,
        max_depth=8,
        learning_rate=0.05,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_lambda=5,
        random_state=42,
        n_jobs=-1,
        tree_method="hist"
    ))
])

print("Training candidate log-target XGBoost...")
log_model.fit(X_train, np.log1p(y_train))

val_pred = np.maximum(
    np.expm1(log_model.predict(X_val)), 0
)

print("\nCANDIDATE LOG-TARGET VALIDATION")
print("MAE:", round(mean_absolute_error(y_val, val_pred), 4))
print("RMSE:", round(np.sqrt(mean_squared_error(y_val, val_pred)), 4))
print("R²:", round(r2_score(y_val, val_pred), 4))
print("Negative predictions:", int((val_pred < 0).sum()))

out = os.path.join(
    base, "cropsense_xgboost_candidate_log_pipeline.joblib"
)
joblib.dump(log_model, out)
print("\nSaved model:", out)

Training candidate log-target XGBoost...

CANDIDATE LOG-TARGET VALIDATION
MAE: 1.4133
RMSE: 5.2247
R²: 0.8384
Negative predictions: 0

Saved model: /content/drive/MyDrive/yield prediction/cropsense_xgboost_candidate_log_pipeline.joblib

In [ ]:

import os
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

base = "/content/drive/MyDrive/yield prediction"
model_path = os.path.join(base, "comparison_candidate_xgb_800.joblib")
data_path = os.path.join(base, "yield_candidate_excluding_flagged.csv")

model = joblib.load(model_path)
df = pd.read_csv(data_path, low_memory=False)
df.columns = df.columns.str.strip()

for c in ["Crop_Year", "Area", "Production",
          "temperature", "humidity", "rainfall_mm"]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]

cat_cols = ["State_Name", "District_Name", "Season", "Crop", "soil_type"]
num_cols = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = cat_cols + num_cols

for c in cat_cols:
    df[c] = df[c].fillna("Unknown").astype(str).str.strip()
    df[c] = df[c].replace("", "Unknown")

val = df[df["Crop_Year"].isin([2012, 2013])].copy()
X_val = val[features]
y_val = val["yield_per_area"]

raw = model.predict(X_val)
clipped = np.maximum(raw, 0)

for name, pred in [
    ("Original predictions", raw),
    ("Clipped predictions", clipped)
]:
    print(f"\n{name}")
    print("MAE:", round(mean_absolute_error(y_val, pred), 4))
    print("RMSE:", round(np.sqrt(mean_squared_error(y_val, pred)), 4))
    print("R²:", round(r2_score(y_val, pred), 4))
    print("Negative predictions:", int((pred < 0).sum()))

Original predictions
MAE: 1.4338
RMSE: 4.9867
R²: 0.8528
Negative predictions: 168

Clipped predictions
MAE: 1.4274
RMSE: 4.9058
R²: 0.8576
Negative predictions: 0

In [ ]:

import os
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

base = "/content/drive/MyDrive/yield prediction"

model = joblib.load(
    os.path.join(base, "comparison_candidate_xgb_800.joblib")
)

df = pd.read_csv(
    os.path.join(base, "yield_candidate_excluding_flagged.csv"),
    low_memory=False
)
df.columns = df.columns.str.strip()

for c in [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]

cat_cols = ["State_Name", "District_Name", "Season", "Crop", "soil_type"]
num_cols = ["Crop_Year", "temperature", "humidity", "rainfall_mm"]
features = cat_cols + num_cols

for c in cat_cols:
    df[c] = df[c].fillna("Unknown").astype(str).str.strip()
    df[c] = df[c].replace("", "Unknown")

test = df[df["Crop_Year"].isin([2014, 2015])].copy()

X_test = test[features]
y_test = test["yield_per_area"]

raw = model.predict(X_test)
clipped = np.maximum(raw, 0)

for name, pred in [
    ("Original predictions", raw),
    ("Clipped predictions", clipped)
]:
    print(f"\n{name}")
    print("Test rows:", len(y_test))
    print("MAE:", round(mean_absolute_error(y_test, pred), 4))
    print("RMSE:", round(np.sqrt(mean_squared_error(y_test, pred)), 4))
    print("R²:", round(r2_score(y_test, pred), 4))
    print("Negative predictions:", int((pred < 0).sum()))

Original predictions
Test rows: 11311
MAE: 1.349
RMSE: 4.3713
R²: 0.8851
Negative predictions: 33

Clipped predictions
Test rows: 11311
MAE: 1.3486
RMSE: 4.3713
R²: 0.8851
Negative predictions: 0

In [ ]:

import os
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ==========================================
# 1. FILE PATHS
# ==========================================
base = "/content/drive/MyDrive/yield prediction"

model_path = os.path.join(
    base, "comparison_candidate_xgb_800.joblib"
)
data_path = os.path.join(
    base, "yield_candidate_excluding_flagged.csv"
)

# Uncomment if Google Drive is not mounted
# from google.colab import drive
# drive.mount("/content/drive")

# ==========================================
# 2. LOAD MODEL AND DATA
# ==========================================
model = joblib.load(model_path)
df = pd.read_csv(data_path, low_memory=False)
df.columns = df.columns.str.strip()

print("Dataset loaded:", df.shape)

# ==========================================
# 3. CLEAN DATA
# ==========================================
numeric_cols = [
    "Crop_Year", "Area", "Production",
    "temperature", "humidity", "rainfall_mm"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

# Target used during training
df["yield_per_area"] = df["Production"] / df["Area"]

cat_cols = [
    "State_Name", "District_Name",
    "Season", "Crop", "soil_type"
]

num_cols = [
    "Crop_Year", "temperature",
    "humidity", "rainfall_mm"
]

features = cat_cols + num_cols

for col in cat_cols:
    df[col] = (
        df[col]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace("", "Unknown")
    )

# ==========================================
# 4. SELECT UNTOUCHED TEST PERIOD
# ==========================================
test = df[df["Crop_Year"].isin([2014, 2015])].copy()

X_test = test[features]
y_test = test["yield_per_area"]

# ==========================================
# 5. PREDICT AND CLIP NEGATIVE VALUES
# ==========================================
raw_predictions = model.predict(X_test)
predictions = np.maximum(raw_predictions, 0)

test["Actual_Yield"] = y_test.to_numpy()
test["Predicted_Yield"] = predictions
test["Absolute_Error"] = np.abs(
    test["Actual_Yield"] - test["Predicted_Yield"]
)

print("\nTest records:", len(test))
print("Unique crops:", test["Crop"].nunique())

# ==========================================
# 6. EVALUATE EACH CROP
# ==========================================
results = []

for crop, group in test.groupby("Crop"):
    actual = group["Actual_Yield"].to_numpy()
    predicted = group["Predicted_Yield"].to_numpy()

    results.append({
        "Crop": crop,
        "Sample_Count": len(group),
        "MAE": mean_absolute_error(actual, predicted),
        "RMSE": np.sqrt(
            mean_squared_error(actual, predicted)
        ),
        # R² is undefined for a single observation
        "R2": (
            r2_score(actual, predicted)
            if len(group) >= 2
            else np.nan
        )
    })

crop_results = pd.DataFrame(results)

# Highest sample count first
crop_results = crop_results.sort_values(
    "Sample_Count", ascending=False
).reset_index(drop=True)

# Round metrics for display
display_results = crop_results.copy()
display_results[["MAE", "RMSE", "R2"]] = (
    display_results[["MAE", "RMSE", "R2"]].round(4)
)

print("\n========== CROP-WISE TEST RESULTS ==========")
display(display_results)

# ==========================================
# 7. IDENTIFY CROPS WITH LARGEST ERRORS
# ==========================================
print("\n========== 10 HIGHEST-MAE CROPS ==========")
display(
    display_results.sort_values(
        "MAE", ascending=False
    ).head(10)
)

print("\n========== 10 LOWEST-MAE CROPS ==========")
display(
    display_results.sort_values(
        "MAE", ascending=True
    ).head(10)
)

# ==========================================
# 8. SAVE RESULTS
# ==========================================
output_path = os.path.join(
    base, "crop_wise_yield_test_metrics_2014_2015.csv"
)

crop_results.to_csv(output_path, index=False)

print("\nResults saved to:")
print(output_path)

# Download the CSV directly from Colab
from google.colab import files
files.download(output_path)

Dataset loaded: (236844, 12)

Test records: 11311
Unique crops: 74

========== CROP-WISE TEST RESULTS ==========

                  Crop  Sample_Count     MAE     RMSE           R2
0                 Rice           845  0.5953   0.7699       0.1929
1                Maize           806  0.7551   1.0676       0.3871
2    Moong(Green Gram)           575  0.2413   0.3184      -0.3829
3                 Urad           524  0.2521   0.3171      -0.4348
4              Sesamum           426  0.2701   0.3357      -0.4725
..                 ...           ...     ...      ...          ...
69              Grapes             4  9.9646  10.3438     -12.9357
70  Other Fresh Fruits             2  7.9351   7.9351       0.0000
71                Moth             2  0.2452   0.2457      -0.2331
72    Other Vegetables             2  7.5384   7.5384 -158989.0845
73          Drum Stick             1  2.0373   2.0373          NaN

[74 rows x 5 columns]

========== 10 HIGHEST-MAE CROPS ==========

                  Crop  Sample_Count      MAE     RMSE           R2
60             Cabbage            19  38.0582  38.7817     -26.3952
6            Sugarcane           375  11.6810  18.0489       0.6138
57              Tomato            26  11.4451  12.5808      -4.1549
69              Grapes             4   9.9646  10.3438     -12.9357
68         Pome Granet             9   8.9348   8.9386   -1213.1096
70  Other Fresh Fruits             2   7.9351   7.9351       0.0000
72    Other Vegetables             2   7.5384   7.5384 -158989.0845
50              Papaya            44   7.4288  13.5737       0.8194
58      other oilseeds            24   7.1725  10.1553       0.1230
64              Sapota            13   6.9669   6.9762    -457.6868

========== 10 LOWEST-MAE CROPS ==========

                 Crop  Sample_Count     MAE    RMSE       R2
46          Guar seed            67  0.1192  0.1681  -0.7431
16         Horse-gram           228  0.2256  0.2882  -0.0646
66          Blackgram            11  0.2339  0.2446 -11.0876
23            Linseed           166  0.2349  0.3547  -1.7160
2   Moong(Green Gram)           575  0.2413  0.3184  -0.3829
71               Moth             2  0.2452  0.2457  -0.2331
3                Urad           524  0.2521  0.3171  -0.4348
53     Oilseeds total            39  0.2632  0.3850  -7.1274
20      Small millets           187  0.2697  0.3364  -0.0378
4             Sesamum           426  0.2701  0.3357  -0.4725

Results saved to:
/content/drive/MyDrive/yield prediction/crop_wise_yield_test_metrics_2014_2015.csv

In [ ]:

# Inspect yield distributions for crops with high MAE
# Run after the previous evaluation cell, which defines test and predictions.

focus_crops = [
    "Cabbage", "Sugarcane", "Tomato", "Grapes",
    "Pome Granet", "Papaya", "Sapota", "Brinjal"
]

for crop in focus_crops:
    g = test[test["Crop"] == crop].copy()

    if g.empty:
        continue

    actual = g["Actual_Yield"]
    predicted = g["Predicted_Yield"]

    print(f"\n{'=' * 50}")
    print("Crop:", crop)
    print("Test records:", len(g))
    print("Actual yield min:", round(actual.min(), 4))
    print("Actual yield median:", round(actual.median(), 4))
    print("Actual yield max:", round(actual.max(), 4))
    print("Predicted yield median:", round(predicted.median(), 4))
    print("MAE:", round(np.mean(np.abs(actual - predicted)), 4))

    display(
        g[[
            "State_Name", "District_Name", "Crop_Year",
            "Season", "Area", "Production",
            "Actual_Yield", "Predicted_Yield",
            "Absolute_Error"
        ]].sort_values("Absolute_Error", ascending=False).head(5)
    )

==================================================
Crop: Cabbage
Test records: 19
Actual yield min: 0.8392
Actual yield median: 12.321
Actual yield max: 29.0932
Predicted yield median: 49.3773
MAE: 38.0582

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
8184,Andhra Pradesh,VISAKHAPATANAM,2014,Rabi,88.0,74.0,0.840909,49.463978,48.623069
8153,Andhra Pradesh,VISAKHAPATANAM,2014,Kharif,143.0,120.0,0.839161,49.294067,48.454907
4475,Andhra Pradesh,KRISHNA,2014,Kharif,57.0,147.0,2.578947,49.788364,47.209417
4496,Andhra Pradesh,KRISHNA,2014,Rabi,91.0,235.0,2.582418,49.612659,47.030242
7379,Andhra Pradesh,SRIKAKULAM,2014,Kharif,137.0,1043.0,7.613139,49.557678,41.944540

==================================================
Crop: Sugarcane
Test records: 375
Actual yield min: 0.4554
Actual yield median: 60.0
Actual yield max: 179.8665
Predicted yield median: 53.6171
MAE: 11.681

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
95180,Kerala,KANNUR,2014,Whole Year,3.43,46.0,13.411079,113.938759,100.527680
232585,West Bengal,HOOGHLY,2014,Whole Year,830.00,149289.0,179.866265,86.753014,93.113251
96755,Kerala,PALAKKAD,2014,Whole Year,371.81,3142.0,8.450553,83.093102,74.642549
94945,Kerala,IDUKKI,2014,Whole Year,1068.90,11512.0,10.769950,84.703880,73.933930
235070,West Bengal,MEDINIPUR WEST,2014,Whole Year,4390.00,789614.0,179.866515,108.836960,71.029555

==================================================
Crop: Tomato
Test records: 26
Actual yield min: 13.5483
Actual yield median: 14.3766
Actual yield max: 31.7948
Predicted yield median: 5.5436
MAE: 11.4451

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
3901,Andhra Pradesh,KADAPA,2014,Rabi,2027.0,64448.0,31.794771,6.759031,25.035740
918,Andhra Pradesh,ANANTAPUR,2014,Kharif,3976.0,113236.0,28.479879,5.870827,22.609052
5312,Andhra Pradesh,KURNOOL,2014,Rabi,618.0,15300.0,24.757282,5.307673,19.449608
3872,Andhra Pradesh,KADAPA,2014,Kharif,2881.0,75102.0,26.068032,6.724259,19.343773
1707,Andhra Pradesh,CHITTOOR,2014,Rabi,4998.0,126185.0,25.247099,6.768853,18.478246

==================================================
Crop: Grapes
Test records: 4
Actual yield min: 22.2848
Actual yield median: 23.0
Actual yield max: 29.125
Predicted yield median: 14.3451
MAE: 9.9646

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
1662,Andhra Pradesh,CHITTOOR,2014,Kharif,32.0,932.0,29.12500,14.376735,14.748265
3851,Andhra Pradesh,KADAPA,2014,Kharif,1.0,23.0,23.00000,14.265285,8.734715
5263,Andhra Pradesh,KURNOOL,2014,Kharif,5.0,115.0,23.00000,14.595886,8.404114
895,Andhra Pradesh,ANANTAPUR,2014,Kharif,309.0,6886.0,22.28479,14.313554,7.971236

==================================================
Crop: Pome Granet
Test records: 9
Actual yield min: 9.5687
Actual yield median: 10.3636
Actual yield max: 10.4427
Predicted yield median: 1.3032
MAE: 8.9348

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
908,Andhra Pradesh,ANANTAPUR,2014,Kharif,1572.0,16416.0,10.442748,1.341634,9.101114
8888,Andhra Pradesh,VIZIANAGARAM,2014,Kharif,5.0,52.0,10.400000,1.299422,9.100578
2411,Andhra Pradesh,EAST GODAVARI,2014,Kharif,10.0,104.0,10.400000,1.303173,9.096827
6723,Andhra Pradesh,SPSR NELLORE,2014,Kharif,13.0,135.0,10.384615,1.312645,9.071970
5272,Andhra Pradesh,KURNOOL,2014,Kharif,84.0,870.0,10.357143,1.295852,9.061290

==================================================
Crop: Papaya
Test records: 44
Actual yield min: 8.2552
Actual yield median: 24.2875
Actual yield max: 107.1115
Predicted yield median: 19.1201
MAE: 7.4288

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
1673,Andhra Pradesh,CHITTOOR,2014,Kharif,519.0,13790.0,26.570328,83.617416,57.047089
5302,Andhra Pradesh,KURNOOL,2014,Rabi,5.0,394.0,78.800000,38.777203,40.022797
3891,Andhra Pradesh,KADAPA,2014,Rabi,729.0,78084.0,107.111111,78.923027,28.188084
8911,Andhra Pradesh,VIZIANAGARAM,2014,Rabi,127.0,13039.0,102.669291,75.024834,27.644458
8887,Andhra Pradesh,VIZIANAGARAM,2014,Kharif,457.0,46922.0,102.673961,79.308899,23.365062

==================================================
Crop: Sapota
Test records: 13
Actual yield min: 7.596
Actual yield median: 8.3648
Actual yield max: 9.0748
Predicted yield median: 1.3032
MAE: 6.9669

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
912,Andhra Pradesh,ANANTAPUR,2014,Kharif,2151.0,19520.0,9.074849,1.341634,7.733215
8173,Andhra Pradesh,VISAKHAPATANAM,2014,Kharif,85.0,711.0,8.364706,1.155787,7.208919
5275,Andhra Pradesh,KURNOOL,2014,Kharif,306.0,2560.0,8.366013,1.295852,7.070161
8891,Andhra Pradesh,VIZIANAGARAM,2014,Kharif,131.0,1096.0,8.366412,1.299422,7.066990
2414,Andhra Pradesh,EAST GODAVARI,2014,Kharif,244.0,2041.0,8.364754,1.303173,7.061581

==================================================
Crop: Brinjal
Test records: 29
Actual yield min: 4.791
Actual yield median: 14.9286
Actual yield max: 23.7375
Predicted yield median: 11.095
MAE: 6.9396

,State_Name,District_Name,Crop_Year,Season,Area,Production,Actual_Yield,Predicted_Yield,Absolute_Error
1687,Andhra Pradesh,CHITTOOR,2014,Rabi,785.0,18633.0,23.736306,6.999224,16.737082
1655,Andhra Pradesh,CHITTOOR,2014,Kharif,924.0,21932.0,23.735931,9.253081,14.482849
3877,Andhra Pradesh,KADAPA,2014,Rabi,358.0,8497.0,23.734637,10.836691,12.897946
5287,Andhra Pradesh,KURNOOL,2014,Rabi,584.0,13862.0,23.736301,10.911051,12.825251
922,Andhra Pradesh,ANANTAPUR,2014,Rabi,468.0,11108.0,23.735043,11.185977,12.549066

In [ ]:

import os
import numpy as np
import pandas as pd

base = "/content/drive/MyDrive/yield prediction"
data_path = os.path.join(base, "yield_candidate_excluding_flagged.csv")

df = pd.read_csv(data_path, low_memory=False)
df.columns = df.columns.str.strip()

for c in ["Crop_Year", "Area", "Production"]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df = df[
    df["Crop_Year"].notna()
    & df["Area"].gt(0)
    & df["Production"].gt(0)
].copy()

df["yield_per_area"] = df["Production"] / df["Area"]
df["Crop"] = df["Crop"].fillna("Unknown").astype(str).str.strip()

df["Period"] = np.select(
    [
        df["Crop_Year"] <= 2011,
        df["Crop_Year"].isin([2012, 2013]),
        df["Crop_Year"].isin([2014, 2015])
    ],
    ["Train", "Validation", "Test"],
    default="Other"
)

focus_crops = [
    "Cabbage", "Sugarcane", "Tomato", "Grapes",
    "Pome Granet", "Papaya", "Sapota", "Brinjal"
]

# Crop support and yield distributions by period
rows = []

for crop in focus_crops:
    for period in ["Train", "Validation", "Test"]:
        g = df[(df["Crop"] == crop) & (df["Period"] == period)]

        rows.append({
            "Crop": crop,
            "Period": period,
            "Count": len(g),
            "Yield_Mean": g["yield_per_area"].mean(),
            "Yield_Median": g["yield_per_area"].median(),
            "Yield_Min": g["yield_per_area"].min(),
            "Yield_Max": g["yield_per_area"].max(),
            "Unique_States": g["State_Name"].nunique(),
            "Unique_Districts": g["District_Name"].nunique(),
            "Unique_Seasons": g["Season"].nunique()
        })

summary = pd.DataFrame(rows)

for col in [
    "Yield_Mean", "Yield_Median", "Yield_Min", "Yield_Max"
]:
    summary[col] = summary[col].round(4)

print("=== CROP SUPPORT AND YIELD DISTRIBUTION ===")
display(summary)


print("=== TEST RECORDS: POMEGRANATE AND SAPOTA ===")

subset = df[
    df["Period"].eq("Test")
    & df["Crop"].isin(["Pome Granet", "Sapota"])
].copy()

columns_to_show = [
    "Crop", "State_Name", "District_Name", "Crop_Year",
    "Season", "Area", "Production", "yield_per_area"
]

display(
    subset[columns_to_show]
    .sort_values(["Crop", "District_Name"])
)

print("\n=== MOST COMMON TEST YIELDS ===")

for crop in ["Pome Granet", "Sapota", "Brinjal", "Cabbage"]:
    g = df[(df["Period"] == "Test") & (df["Crop"] == crop)]

    print(f"\n{crop}:")
    print(
        g["yield_per_area"]
        .round(4)
        .value_counts()
        .head(10)
        .to_string()
    )

=== CROP SUPPORT AND YIELD DISTRIBUTION ===

,Crop,Period,Count,Yield_Mean,Yield_Median,Yield_Min,Yield_Max,Unique_States,Unique_Districts,Unique_Seasons
0,Cabbage,Train,37,36.8824,49.0000,10.5417,67.2123,2,21,1
1,Cabbage,Validation,41,20.7586,18.7857,10.0056,26.5000,1,12,2
2,Cabbage,Test,19,11.3697,12.3210,0.8392,29.0932,1,10,2
3,Sugarcane,Train,6556,57.6892,52.1391,0.0010,1345.5388,31,553,6
4,Sugarcane,Validation,854,57.6252,58.5469,0.8000,220.6178,24,461,3
5,Sugarcane,Test,375,58.4389,60.0000,0.4554,179.8665,20,346,3
6,Tomato,Train,197,7.7126,7.6816,1.1533,19.2586,6,115,1
7,Tomato,Validation,52,17.5944,17.8770,7.3556,50.2051,1,13,2
8,Tomato,Test,26,17.1471,14.3766,13.5483,31.7948,1,13,2
9,Grapes,Train,98,22.6521,24.0526,0.2000,42.9278,6,69,1
10,Grapes,Validation,8,20.4173,18.1652,18.0000,31.9580,1,4,1
11,Grapes,Test,4,24.3524,23.0000,22.2848,29.1250,1,4,1
12,Pome Granet,Train,0,NaN,NaN,NaN,NaN,0,0,0
13,Pome Granet,Validation,12,14.1117,14.1081,13.3333,16.3600,1,6,1
14,Pome Granet,Test,9,10.2807,10.3636,9.5688,10.4427,1,9,1
15,Papaya,Train,273,29.8721,15.0821,0.1624,130.5000,10,151,2
16,Papaya,Validation,95,40.3642,21.2981,3.4015,134.1426,3,54,3
17,Papaya,Test,44,42.1091,24.2875,8.2552,107.1115,3,41,3
18,Sapota,Train,0,NaN,NaN,NaN,NaN,0,0,0
19,Sapota,Validation,26,11.2484,9.5984,8.2690,19.8841,1,13,1
20,Sapota,Test,13,8.3051,8.3648,7.5960,9.0748,1,13,1
21,Brinjal,Train,180,9.1300,7.6973,0.1900,29.9835,7,90,4
22,Brinjal,Validation,58,12.2022,10.3456,6.3192,24.7431,2,14,3
23,Brinjal,Test,29,15.2998,14.9286,4.7910,23.7375,2,14,3

=== TEST RECORDS: POMEGRANATE AND SAPOTA ===

,Crop,State_Name,District_Name,Crop_Year,Season,Area,Production,yield_per_area
908,Pome Granet,Andhra Pradesh,ANANTAPUR,2014,Kharif,1572.0,16416.0,10.442748
1674,Pome Granet,Andhra Pradesh,CHITTOOR,2014,Kharif,160.0,1531.0,9.568750
2411,Pome Granet,Andhra Pradesh,EAST GODAVARI,2014,Kharif,10.0,104.0,10.400000
3863,Pome Granet,Andhra Pradesh,KADAPA,2014,Kharif,89.0,922.0,10.359551
4487,Pome Granet,Andhra Pradesh,KRISHNA,2014,Kharif,11.0,114.0,10.363636
5272,Pome Granet,Andhra Pradesh,KURNOOL,2014,Kharif,84.0,870.0,10.357143
6054,Pome Granet,Andhra Pradesh,PRAKASAM,2014,Kharif,4.0,41.0,10.250000
6723,Pome Granet,Andhra Pradesh,SPSR NELLORE,2014,Kharif,13.0,135.0,10.384615
8888,Pome Granet,Andhra Pradesh,VIZIANAGARAM,2014,Kharif,5.0,52.0,10.400000
912,Sapota,Andhra Pradesh,ANANTAPUR,2014,Kharif,2151.0,19520.0,9.074849
1678,Sapota,Andhra Pradesh,CHITTOOR,2014,Kharif,209.0,1748.0,8.363636
2414,Sapota,Andhra Pradesh,EAST GODAVARI,2014,Kharif,244.0,2041.0,8.364754
3075,Sapota,Andhra Pradesh,GUNTUR,2014,Kharif,1386.0,10826.0,7.810967
3866,Sapota,Andhra Pradesh,KADAPA,2014,Kharif,434.0,3631.0,8.366359
4489,Sapota,Andhra Pradesh,KRISHNA,2014,Kharif,541.0,4526.0,8.365989
5275,Sapota,Andhra Pradesh,KURNOOL,2014,Kharif,306.0,2560.0,8.366013
6057,Sapota,Andhra Pradesh,PRAKASAM,2014,Kharif,2391.0,19635.0,8.212045
6726,Sapota,Andhra Pradesh,SPSR NELLORE,2014,Kharif,384.0,3213.0,8.367188
7397,Sapota,Andhra Pradesh,SRIKAKULAM,2014,Kharif,23.0,192.0,8.347826
8173,Sapota,Andhra Pradesh,VISAKHAPATANAM,2014,Kharif,85.0,711.0,8.364706
8891,Sapota,Andhra Pradesh,VIZIANAGARAM,2014,Kharif,131.0,1096.0,8.366412
9450,Sapota,Andhra Pradesh,WEST GODAVARI,2014,Kharif,500.0,3798.0,7.596000

=== MOST COMMON TEST YIELDS ===

Pome Granet:
yield_per_area
10.4000    2
10.4427    1
9.5688     1
10.3596    1
10.3636    1
10.3571    1
10.2500    1
10.3846    1

Sapota:
yield_per_area
8.3664    2
8.3660    2
9.0748    1
8.3648    1
8.3636    1
7.8110    1
8.2120    1
8.3672    1
8.3478    1
8.3647    1

Brinjal:
yield_per_area
23.7363    3
23.4643    2
9.6047     2
23.7359    1
23.7375    1
6.0537     1
6.0544     1
23.7358    1
23.7350    1
23.7346    1

Cabbage:
yield_per_area
12.3000    1
12.5000    1
29.0917    1
29.0932    1
12.3182    1
12.3478    1
12.3333    1
12.3103    1
2.5789     1
2.5824     1

In [ ]:

import os
import pandas as pd

base = "/content/drive/MyDrive/yield prediction"

files_to_check = [
    "crop_production_124_training_ready.csv",
    "yield_candidate_excluding_flagged.csv"
]

keywords = [
    "pome", "gran", "anar",
    "sapota", "chiku", "chikoo"
]

for filename in files_to_check:
    path = os.path.join(base, filename)

    if not os.path.exists(path):
        print(f"\nFile not found: {filename}")
        continue

    data = pd.read_csv(path, usecols=["Crop"], low_memory=False)
    crops = data["Crop"].dropna().astype(str).str.strip()

    print(f"\n{'=' * 60}")
    print("FILE:", filename)
    print("Total rows:", len(data))

    for keyword in keywords:
        matches = sorted(
            crops[crops.str.contains(keyword, case=False, na=False)]
            .unique()
        )
        print(f"{keyword}: {matches if matches else 'No matches'}")

    print("\nExact crop counts:")
    for crop in ["Pome Granet", "Pomegranate", "Sapota"]:
        print(f"{crop}: {(crops == crop).sum()}")

============================================================
FILE: crop_production_124_training_ready.csv
Total rows: 236866
pome: ['Pome Fruit', 'Pome Granet']
gran: ['Pome Granet']
anar: No matches
sapota: ['Sapota']
chiku: No matches
chikoo: No matches

Exact crop counts:
Pome Granet: 21
Pomegranate: 0
Sapota: 39

============================================================
FILE: yield_candidate_excluding_flagged.csv
Total rows: 236844
pome: ['Pome Fruit', 'Pome Granet']
gran: ['Pome Granet']
anar: No matches
sapota: ['Sapota']
chiku: No matches
chikoo: No matches

Exact crop counts:
Pome Granet: 21
Pomegranate: 0
Sapota: 39

In [ ]:

import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
path = os.path.join(base, "crop_production_124_training_ready.csv")

df = pd.read_csv(path, low_memory=False)
df.columns = df.columns.str.strip()
df["Crop_Year"] = pd.to_numeric(df["Crop_Year"], errors="coerce")

for crop in ["Pome Granet", "Sapota", "Pome Fruit"]:
    g = df[df["Crop"].astype(str).str.strip().eq(crop)]

    print(f"\n{crop}: {len(g)} records")
    if len(g):
        print("Years:", sorted(g["Crop_Year"].dropna().unique().tolist()))
        print("By year:")
        print(g.groupby("Crop_Year").size().to_string())

Pome Granet: 21 records
Years: [2012, 2013, 2014]
By year:
Crop_Year
2012    6
2013    6
2014    9

Sapota: 39 records
Years: [2012, 2013, 2014]
By year:
Crop_Year
2012    13
2013    13
2014    13

Pome Fruit: 169 records
Years: [2002, 2003]
By year:
Crop_Year
2002    84
2003    85

In [ ]:

import os
import joblib
import numpy as np

base = "/content/drive/MyDrive/yield prediction"

source_path = os.path.join(
    base, "comparison_candidate_xgb_800.joblib"
)
output_path = os.path.join(
    base, "cropsense_xgboost_yield_final_candidate.joblib"
)

# Load and save the candidate separately
model = joblib.load(source_path)
joblib.dump(model, output_path)

# Verify saved model
saved_model = joblib.load(output_path)

print("Candidate model saved successfully!")
print("Path:", output_path)
print("Model type:", type(saved_model).__name__)
print("Negative predictions will be clipped to zero during inference.")

Candidate model saved successfully!
Path: /content/drive/MyDrive/yield prediction/cropsense_xgboost_yield_final_candidate.joblib
Model type: Pipeline
Negative predictions will be clipped to zero during inference.

In [ ]:

import joblib
import numpy as np
import pandas as pd
import os

base = "/content/drive/MyDrive/yield prediction"
model_path = os.path.join(
    base, "cropsense_xgboost_yield_final_candidate.joblib"
)

model = joblib.load(model_path)

# Create one sample input using the exact training feature names
input_data = pd.DataFrame([{
    "State_Name": "Andhra Pradesh",
    "District_Name": "KRISHNA",
    "Season": "Kharif",
    "Crop": "Rice",
    "soil_type": "Unknown",
    "Crop_Year": 2014,
    "temperature": 28.0,
    "humidity": 75.0,
    "rainfall_mm": 800.0
}])

# Predict
raw_prediction = model.predict(input_data)
final_prediction = np.maximum(raw_prediction, 0)

print("Raw prediction:", round(float(raw_prediction[0]), 4))
print("Nonnegative prediction:", round(float(final_prediction[0]), 4))
print("Prediction is nonnegative:", bool(final_prediction[0] >= 0))

Raw prediction: 2.5019
Nonnegative prediction: 2.5019
Prediction is nonnegative: True

# model train crop final

In [ ]:

# ============================================================
# CROPSENSE AI — YIELD MODEL TRAINING
# Dataset: crop_final.csv
# Features: Crop, State_Name, District_Name, Season
# Target: yield_per_area
# ============================================================

import os
import joblib
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

# 1. PATHS
base = "/content/drive/MyDrive/yield prediction"
data_path = os.path.join(base, "crop_final.csv")

# If the file is uploaded directly into the Colab session instead,
# change data_path to its actual Colab path.

os.makedirs(base, exist_ok=True)

# 2. LOAD AND CHECK DATA
df = pd.read_csv(data_path, low_memory=False)
df.columns = df.columns.str.strip()

required = [
    "State_Name", "District_Name", "Season",
    "Crop", "Crop_Year", "Area", "Production", "yield_per_area"
]

missing_cols = set(required) - set(df.columns)
if missing_cols:
    raise ValueError(f"Missing required columns: {missing_cols}")

for col in ["Crop_Year", "Area", "Production", "yield_per_area"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna(subset=required).copy()
df = df[
    (df["Area"] > 0)
    & (df["Production"] > 0)
    & (df["yield_per_area"] >= 0)
].copy()

# Verify target consistency
calculated_yield = df["Production"] / df["Area"]
max_difference = (df["yield_per_area"] - calculated_yield).abs().max()

print("Dataset rows:", len(df))
print("Crop classes:", df["Crop"].nunique())
print("Years:", int(df["Crop_Year"].min()), "-", int(df["Crop_Year"].max()))
print("Maximum target calculation difference:", max_difference)

# 3. FOUR FARMER INPUT FEATURES
cat_cols = ["Crop", "State_Name", "District_Name", "Season"]
target = "yield_per_area"

for col in cat_cols:
    df[col] = df[col].astype(str).str.strip()

X = df[cat_cols]
y = df[target]

# 4. CHRONOLOGICAL SPLIT
train_mask = df["Crop_Year"] <= 2011
val_mask = df["Crop_Year"].isin([2012, 2013])
test_mask = df["Crop_Year"].isin([2014, 2015])

X_train, y_train = X.loc[train_mask], y.loc[train_mask]
X_val, y_val = X.loc[val_mask], y.loc[val_mask]
X_test, y_test = X.loc[test_mask], y.loc[test_mask]

print("\nTRAIN rows:", len(X_train))
print("VALIDATION rows:", len(X_val))
print("TEST rows:", len(X_test))

# 5. PREPROCESSING
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore"))
            ]),
            cat_cols
        )
    ]
)

# 6. XGBOOST MODEL
xgb = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=800,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.85,
    colsample_bytree=0.85,
    reg_lambda=5,
    random_state=42,
    n_jobs=-1,
    tree_method="hist"
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", xgb)
])

# 7. TRAIN ON 1997–2011 ONLY
print("\nTraining model...")
model.fit(X_train, y_train)
print("Training completed.")

# 8. EVALUATION
def evaluate(name, X_eval, y_eval):
    raw_pred = model.predict(X_eval)
    clipped_pred = np.maximum(raw_pred, 0)

    print(f"\n===== {name} =====")
    print("Rows:", len(y_eval))

    for pred_name, pred in [
        ("Raw predictions", raw_pred),
        ("Nonnegative predictions", clipped_pred)
    ]:
        print(f"\n{pred_name}")
        print("MAE:", round(mean_absolute_error(y_eval, pred), 4))
        print("RMSE:", round(np.sqrt(mean_squared_error(y_eval, pred)), 4))
        print("R²:", round(r2_score(y_eval, pred), 4))
        print("Negative predictions:", int((pred < 0).sum()))

    return clipped_pred

val_predictions = evaluate("VALIDATION 2012–2013", X_val, y_val)
test_predictions = evaluate("TEST 2014–2015", X_test, y_test)

# 9. SAVE MODEL SEPARATELY
model_path = os.path.join(
    base, "cropsense_xgb_yield_four_inputs.joblib"
)
joblib.dump(model, model_path)

print("\nModel saved:", model_path)

# 10. SAVE COMBINATIONS OBSERVED IN TRAINING DATA ONLY
# This list supports conservative dropdown validation.
train_combinations = (
    df.loc[train_mask, cat_cols]
    .drop_duplicates()
    .sort_values(cat_cols)
    .reset_index(drop=True)
)

combos_path = os.path.join(
    base, "cropsense_training_supported_combinations.csv"
)
train_combinations.to_csv(combos_path, index=False)

print("Training-supported combinations saved:", combos_path)
print("Supported four-field combinations:", len(train_combinations))

# 11. SAVE TEST PREDICTIONS FOR ERROR ANALYSIS
test_results = df.loc[test_mask, cat_cols + ["Crop_Year"]].copy()
test_results["Actual_Yield"] = y_test.to_numpy()
test_results["Predicted_Yield"] = test_predictions
test_results["Absolute_Error"] = np.abs(
    test_results["Actual_Yield"] - test_results["Predicted_Yield"]
)

pred_path = os.path.join(
    base, "cropsense_four_input_test_predictions.csv"
)
test_results.to_csv(pred_path, index=False)

print("Test predictions saved:", pred_path)

Dataset rows: 235123
Crop classes: 104
Years: 1997 - 2015
Maximum target calculation difference: 5.684341886080802e-14

TRAIN rows: 197598
VALIDATION rows: 26284
TEST rows: 11241

Training model...
Training completed.

===== VALIDATION 2012–2013 =====
Rows: 26284

Raw predictions
MAE: 1.2894
RMSE: 3.9046
R²: 0.9086
Negative predictions: 134

Nonnegative predictions
MAE: 1.2883
RMSE: 3.9045
R²: 0.9086
Negative predictions: 0

===== TEST 2014–2015 =====
Rows: 11241

Raw predictions
MAE: 1.2495
RMSE: 4.0107
R²: 0.903
Negative predictions: 25

Nonnegative predictions
MAE: 1.2488
RMSE: 4.0106
R²: 0.903
Negative predictions: 0

Model saved: /content/drive/MyDrive/yield prediction/cropsense_xgb_yield_four_inputs.joblib
Training-supported combinations saved: /content/drive/MyDrive/yield prediction/cropsense_training_supported_combinations.csv
Supported four-field combinations: 29061
Test predictions saved: /content/drive/MyDrive/yield prediction/cropsense_four_input_test_predictions.csv

In [ ]:

# ============================================================
# CROPSENSE AI: FOUR INPUTS + HISTORICAL YIELD EXPERIMENT
# Farmer inputs remain: Crop, State, District, Season
# Train: <= 2011 | Validation: 2012-2013
# Test 2014-2015 is NOT used for model selection.
# ============================================================

import os
import joblib
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

# 1. PATHS
base = "/content/drive/MyDrive/yield prediction"
data_path = os.path.join(base, "crop_final.csv")

# Preserve all existing models; save this experiment separately.
baseline_path = os.path.join(
    base, "cropsense_xgb_yield_four_inputs.joblib"
)
candidate_path = os.path.join(
    base, "cropsense_xgb_yield_four_inputs_with_history.joblib"
)
comparison_path = os.path.join(
    base, "historical_yield_validation_comparison.csv"
)

# 2. LOAD AND VALIDATE DATA
df = pd.read_csv(data_path, low_memory=False)
df.columns = df.columns.str.strip()

required = [
    "Crop", "State_Name", "District_Name", "Season",
    "Crop_Year", "Area", "Production", "yield_per_area"
]
missing = set(required) - set(df.columns)
if missing:
    raise ValueError(f"Missing required columns: {missing}")

for col in ["Crop_Year", "Area", "Production", "yield_per_area"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna(subset=required).copy()
df = df[
    (df["Area"] > 0)
    & (df["Production"] > 0)
    & (df["yield_per_area"] >= 0)
].copy()

# Recalculate target consistently.
df["yield_per_area"] = df["Production"] / df["Area"]
df["Crop_Year"] = df["Crop_Year"].astype(int)

cat_cols = ["Crop", "State_Name", "District_Name", "Season"]
group_cols = ["Crop", "State_Name", "District_Name", "Season"]
target = "yield_per_area"

for col in cat_cols:
    df[col] = df[col].fillna("Unknown").astype(str).str.strip()
    df[col] = df[col].replace("", "Unknown")

df = df.reset_index(drop=True)

print("Rows:", len(df))
print("Year range:", df["Crop_Year"].min(), "-", df["Crop_Year"].max())

# 3. CREATE HISTORICAL FEATURES USING PRIOR YEARS ONLY
# First aggregate repeated records within each crop/location/season/year.
yearly = (
    df.groupby(group_cols + ["Crop_Year"], as_index=False)
      [target].mean()
      .rename(columns={target: "yearly_yield"})
      .sort_values(group_cols + ["Crop_Year"])
      .reset_index(drop=True)
)

# Mean from strictly earlier observed years in the same group.
yearly["prior_group_mean"] = (
    yearly.groupby(group_cols, sort=False)["yearly_yield"]
          .transform(lambda s: s.shift(1).expanding().mean())
)

# Broader fallback: same crop across locations, using prior years only.
yearly["prior_crop_mean"] = (
    yearly.groupby("Crop", sort=False)["yearly_yield"]
          .transform(lambda s: s.shift(1).expanding().mean())
)

# Overall fallback, also using earlier year summaries only.
yearly["prior_global_mean"] = (
    yearly.groupby("Crop_Year")["yearly_yield"].transform("mean")
)
# Correct global fallback: expanding mean of previous calendar years.
global_year = (
    df.groupby("Crop_Year")[target].mean().sort_index()
)
global_prior = global_year.shift(1).expanding().mean()
yearly["prior_global_mean"] = yearly["Crop_Year"].map(global_prior)

# Exact previous calendar year's yield for the same crop, state,
# district and season. Missing years do not silently become lag-1.
lag_table = yearly[group_cols + ["Crop_Year", "yearly_yield"]].copy()
lag_table["Crop_Year"] = lag_table["Crop_Year"] + 1
lag_table = lag_table.rename(
    columns={"yearly_yield": "yield_previous_year"}
)

yearly = yearly.merge(
    lag_table,
    on=group_cols + ["Crop_Year"],
    how="left",
    validate="one_to_one"
)

# Historical feature hierarchy:
# exact previous year -> earlier group mean -> earlier crop mean
# -> earlier global mean. For the earliest records, remain missing;
# the model's training-fitted imputer handles these.
yearly["historical_yield"] = (
    yearly["yield_previous_year"]
    .combine_first(yearly["prior_group_mean"])
    .combine_first(yearly["prior_crop_mean"])
    .combine_first(yearly["prior_global_mean"])
)

history_lookup = yearly[
    group_cols + ["Crop_Year", "historical_yield"]
]

df = df.merge(
    history_lookup,
    on=group_cols + ["Crop_Year"],
    how="left",
    validate="many_to_one"
)

print(
    "Rows with historical feature:",
    int(df["historical_yield"].notna().sum()),
    "/", len(df)
)

# 4. CHRONOLOGICAL SPLIT
train_mask = df["Crop_Year"] <= 2011
val_mask = df["Crop_Year"].isin([2012, 2013])

train = df.loc[train_mask].copy()
val = df.loc[val_mask].copy()

X_train_base = train[cat_cols]
X_val_base = val[cat_cols]

X_train_hist = train[cat_cols + ["historical_yield"]]
X_val_hist = val[cat_cols + ["historical_yield"]]

y_train = train[target]
y_val = val[target]

print("\nTraining rows:", len(train))
print("Validation rows:", len(val))

# 5. MODEL FACTORY
def make_model(use_history=False):
    numeric_cols = ["historical_yield"] if use_history else []

    transformers = [
        (
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore"))
            ]),
            cat_cols
        )
    ]

    if use_history:
        transformers.append(
            (
                "numeric",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="median"))
                ]),
                numeric_cols
            )
        )

    preprocessor = ColumnTransformer(transformers=transformers)

    regressor = XGBRegressor(
        objective="reg:squarederror",
        n_estimators=800,
        max_depth=8,
        learning_rate=0.05,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_lambda=5,
        random_state=42,
        n_jobs=-1,
        tree_method="hist"
    )

    return Pipeline([
        ("preprocessor", preprocessor),
        ("model", regressor)
    ])

# 6. TRAIN FAIR BASELINE AND HISTORY MODELS
print("\nTraining four-input baseline...")
baseline = make_model(use_history=False)
baseline.fit(X_train_base, y_train)

print("Training historical-yield model...")
history_model = make_model(use_history=True)
history_model.fit(X_train_hist, y_train)

# 7. VALIDATION COMPARISON ONLY
def calculate_metrics(y_true, raw_pred):
    pred = np.maximum(raw_pred, 0)
    return {
        "MAE": mean_absolute_error(y_true, pred),
        "RMSE": np.sqrt(mean_squared_error(y_true, pred)),
        "R2": r2_score(y_true, pred),
        "Negative_Raw_Predictions": int((raw_pred < 0).sum())
    }

baseline_raw = baseline.predict(X_val_base)
history_raw = history_model.predict(X_val_hist)

results = pd.DataFrame([
    {
        "Model": "Four-input baseline",
        **calculate_metrics(y_val, baseline_raw)
    },
    {
        "Model": "Four inputs + historical yield",
        **calculate_metrics(y_val, history_raw)
    }
])

print("\n===== VALIDATION RESULTS: 2012-2013 =====")
display(results.round(4))

results.to_csv(comparison_path, index=False)
print("Comparison saved:", comparison_path)

# 8. SAVE HISTORY MODEL SEPARATELY
# Do not overwrite the existing four-input baseline.
joblib.dump(history_model, candidate_path)
print("\nHistorical model saved:", candidate_path)

# 9. SAVE THE HISTORY LOOKUP NEEDED AT INFERENCE TIME
# This contains historical yield summaries through 2015.
# For a production deployment, only use records available before
# the prediction year and update this lookup as new years arrive.
lookup_path = os.path.join(
    base, "cropsense_historical_yield_lookup.csv"
)
yearly.to_csv(lookup_path, index=False)
print("Historical lookup saved:", lookup_path)

print(
    "\nNext: select the model using validation results only. "
    "Do not evaluate or tune against 2014-2015 yet."
)

Rows: 235123
Year range: 1997 - 2015
Rows with historical feature: 235109 / 235123

Training rows: 197598
Validation rows: 26284

Training four-input baseline...
Training historical-yield model...

===== VALIDATION RESULTS: 2012-2013 =====

,Model,MAE,RMSE,R2,Negative_Raw_Predictions
0,Four-input baseline,1.2883,3.9045,0.9086,134
1,Four inputs + historical yield,1.0062,3.6378,0.9207,0

Comparison saved: /content/drive/MyDrive/yield prediction/historical_yield_validation_comparison.csv

Historical model saved: /content/drive/MyDrive/yield prediction/cropsense_xgb_yield_four_inputs_with_history.joblib
Historical lookup saved: /content/drive/MyDrive/yield prediction/cropsense_historical_yield_lookup.csv

Next: select the model using validation results only. Do not evaluate or tune against 2014-2015 yet.

In [ ]:

# ============================================================
# CROPSENSE AI — NATIVE CATEGORICAL XGBOOST
# Farmer inputs: Crop, State, District, Season
# Training: Crop_Year <= 2013
# Test:     Crop_Year in [2014, 2015]
# Existing models are preserved.
# ============================================================

import os
import json
import joblib
import numpy as np
import pandas as pd
import xgboost as xgb

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ----------------------------
# 1. Paths and configuration
# ----------------------------
BASE_DIR = "/content/drive/MyDrive/yield prediction"
DATA_PATH = os.path.join(BASE_DIR, "crop_final.csv")

MODEL_PATH = os.path.join(
    BASE_DIR, "cropsense_xgb_native_categorical_train2013.joblib"
)
CATEGORIES_PATH = os.path.join(
    BASE_DIR, "cropsense_xgb_native_categories.json"
)
OVERALL_PATH = os.path.join(
    BASE_DIR, "native_xgb_overall_metrics.csv"
)
PER_CROP_PATH = os.path.join(
    BASE_DIR, "native_xgb_per_crop_metrics.csv"
)
PREDICTIONS_PATH = os.path.join(
    BASE_DIR, "native_xgb_test_predictions.csv"
)
COMBINATIONS_PATH = os.path.join(
    BASE_DIR, "cropsense_supported_combinations_all_years.csv"
)

os.makedirs(BASE_DIR, exist_ok=True)

CAT_COLS = ["Crop", "State_Name", "District_Name", "Season"]
TARGET = "yield_per_area"
YEAR = "Crop_Year"

# ----------------------------
# 2. Load and validate dataset
# ----------------------------
df = pd.read_csv(DATA_PATH)

required = CAT_COLS + [TARGET, YEAR]
missing_cols = [c for c in required if c not in df.columns]

if missing_cols:
    raise ValueError(f"Missing required columns: {missing_cols}")

df = df[required].copy()

for c in CAT_COLS:
    df[c] = df[c].astype("string").str.strip()

df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")
df[YEAR] = pd.to_numeric(df[YEAR], errors="coerce")

# Remove only records with missing required values.
# Do NOT remove valid zero-yield records automatically.
df = df.dropna(subset=required).copy()

for c in CAT_COLS:
    df[c] = df[c].astype(str)

df[YEAR] = df[YEAR].astype(int)

if not np.isfinite(df[TARGET]).all():
    raise ValueError("Target contains infinite or invalid values.")

if (df[TARGET] < 0).any():
    raise ValueError(
        "Negative yield_per_area values found. Audit these records "
        "before training; do not silently remove them."
    )

train_mask = df[YEAR] <= 2013
test_mask = df[YEAR].isin([2014, 2015])

train_df = df.loc[train_mask].copy()
test_df = df.loc[test_mask].copy()

if train_df.empty or test_df.empty:
    raise ValueError("Training or test split is empty. Check year values.")

print("XGBoost version:", xgb.__version__)
print("Dataset rows:", len(df))
print("Training rows (<=2013):", len(train_df))
print("Test rows (2014-2015):", len(test_df))
print("Training year range:",
      train_df[YEAR].min(), "-", train_df[YEAR].max())
print("Test years:", sorted(test_df[YEAR].unique()))
print("Training crop classes:", train_df["Crop"].nunique())
print("Test rows with unseen crop labels:",
      (~test_df["Crop"].isin(train_df["Crop"].unique())).sum())

# ----------------------------
# 3. Preserve category schemas
# ----------------------------
# Learn categories from training data only.
category_schema = {
    c: sorted(train_df[c].unique().tolist())
    for c in CAT_COLS
}

def make_native_features(frame):
    X = frame[CAT_COLS].copy()

    for c in CAT_COLS:
        X[c] = pd.Categorical(
            X[c],
            categories=category_schema[c]
        )

    return X

X_train = make_native_features(train_df)
X_test = make_native_features(test_df)

y_train = train_df[TARGET].astype(float)
y_test = test_df[TARGET].astype(float)

# Native categorical XGBoost needs categorical support.
# Fail clearly if the installed version is too old.
major_minor = tuple(
    int(p) for p in xgb.__version__.split(".")[:2]
)
if major_minor < (1, 5):
    raise RuntimeError(
        "Upgrade XGBoost first: !pip install -U xgboost"
    )

# ----------------------------
# 4. Train native categorical model
# ----------------------------
model = xgb.XGBRegressor(
    objective="reg:squarederror",
    n_estimators=800,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.85,
    colsample_bytree=0.85,
    reg_lambda=5,
    enable_categorical=True,
    max_cat_to_onehot=1,
    tree_method="hist",
    random_state=42,
    n_jobs=-1,
    eval_metric="rmse"
)

print("\nTraining native categorical XGBoost...")
model.fit(X_train, y_train, verbose=False)

# ----------------------------
# 5. Predict and calculate metrics
# ----------------------------
raw_predictions = model.predict(X_test)

# Keep raw predictions for diagnostics.
# Use nonnegative clipped predictions for the main comparison.
predictions = np.maximum(raw_predictions, 0)

def calculate_metrics(actual, predicted):
    return {
        "Rows": len(actual),
        "MAE": mean_absolute_error(actual, predicted),
        "RMSE": np.sqrt(mean_squared_error(actual, predicted)),
        "R2": r2_score(actual, predicted),
    }

overall = calculate_metrics(y_test, predictions)
overall["Model"] = "Native categorical XGBoost"
overall["Train_Through_Year"] = 2013
overall["Test_Years"] = "2014-2015"
overall["Negative_Raw_Predictions"] = int((raw_predictions < 0).sum())

overall_df = pd.DataFrame([overall])
print("\n========== OVERALL TEST RESULTS ==========")
print(overall_df.to_string(index=False))

# ----------------------------
# 6. Per-crop evaluation
# ----------------------------
evaluation = pd.DataFrame({
    "Crop": test_df["Crop"].to_numpy(),
    "Actual": y_test.to_numpy(),
    "Predicted": predictions,
    "Raw_Predicted": raw_predictions,
    "Crop_Year": test_df[YEAR].to_numpy()
})

crop_rows = []

for crop, group in evaluation.groupby("Crop"):
    actual = group["Actual"].to_numpy()
    pred = group["Predicted"].to_numpy()

    crop_rows.append({
        "Crop": crop,
        "Rows": len(group),
        "Actual_Mean": np.mean(actual),
        "Actual_Median": np.median(actual),
        "MAE": mean_absolute_error(actual, pred),
        "RMSE": np.sqrt(mean_squared_error(actual, pred)),
        # R² is undefined for a single observation.
        "R2": r2_score(actual, pred) if len(group) >= 2 else np.nan
    })

per_crop_df = pd.DataFrame(crop_rows)
per_crop_df = per_crop_df.sort_values("MAE", ascending=False)

print("\n========== 15 CROPS WITH HIGHEST MAE ==========")
print(per_crop_df.head(15).round(4).to_string(index=False))

print("\n========== CROPS WITH FEWEST TEST RECORDS ==========")
print(
    per_crop_df.sort_values("Rows")
    .head(15)
    .round(4)
    .to_string(index=False)
)

# ----------------------------
# 7. Save artifacts separately
# ----------------------------
# Bundle category definitions with model for consistent inference.
artifact = {
    "model": model,
    "categorical_columns": CAT_COLS,
    "target": TARGET,
    "category_schema": category_schema,
    "training_year_max": int(train_df[YEAR].max()),
    "test_years": [2014, 2015],
    "prediction_clip_min": 0,
    "xgboost_version": xgb.__version__
}

joblib.dump(artifact, MODEL_PATH)

with open(CATEGORIES_PATH, "w", encoding="utf-8") as f:
    json.dump(category_schema, f, indent=2)

overall_df.to_csv(OVERALL_PATH, index=False)
per_crop_df.to_csv(PER_CROP_PATH, index=False)
evaluation.to_csv(PREDICTIONS_PATH, index=False)

# Dropdown support: all observed combinations in the full dataset.
# This is for UI availability, not proof of agronomic suitability.
(
    df[CAT_COLS]
    .drop_duplicates()
    .sort_values(CAT_COLS)
    .to_csv(COMBINATIONS_PATH, index=False)
)

print("\n========== SAVED FILES ==========")
for path in [
    MODEL_PATH,
    CATEGORIES_PATH,
    OVERALL_PATH,
    PER_CROP_PATH,
    PREDICTIONS_PATH,
    COMBINATIONS_PATH
]:
    print(path)

print("\nDone! Existing baseline and historical models were not overwritten.")

XGBoost version: 3.4.1
Dataset rows: 235123
Training rows (<=2013): 223882
Test rows (2014-2015): 11241
Training year range: 1997 - 2013
Test years: [np.int64(2014), np.int64(2015)]
Training crop classes: 104
Test rows with unseen crop labels: 0

Training native categorical XGBoost...

========== OVERALL TEST RESULTS ==========
 Rows      MAE     RMSE       R2                      Model  Train_Through_Year Test_Years  Negative_Raw_Predictions
11241 0.973596 3.318744 0.933555 Native categorical XGBoost                2013  2014-2015                        21

========== 15 CROPS WITH HIGHEST MAE ==========
       Crop  Rows  Actual_Mean  Actual_Median     MAE    RMSE        R2
    Cabbage    17      12.6085        12.3243 10.7543 11.5234   -1.8385
  Sugarcane   360      60.6190        60.5708  9.8255 15.5832    0.6802
     Papaya    44      42.1091        24.2875  8.7230 15.6183    0.7609
     Grapes     4      24.3524        23.0000  5.5374  6.2487   -4.0858
    Brinjal    29      15.2998        14.9286  4.1803  5.5024    0.4044
     Tomato    26      17.1471        14.3766  3.7512  4.4677    0.3499
Pome Granet     9      10.2807        10.3636  3.7340  3.7599 -213.8227
     Banana   119      28.2720        31.1379  3.3068  4.8445    0.8973
 Dry ginger    96       9.3143         4.6047  3.0974  5.6386    0.7113
     Sapota    13       8.3051         8.3648  2.9023  3.0841  -88.6496
       Jute    84      10.4571        10.8878  2.6859  3.5909    0.5636
      Mango    18       7.7669         7.0750  2.6391  3.4680    0.4331
    Tapioca    73      16.2102         9.5753  2.5601  4.5096    0.8595
      Onion   316      11.7350        15.0000  2.4280  3.0131    0.7406
     Potato   357      13.2882        10.6102  2.3684  3.3269    0.8074

========== CROPS WITH FEWEST TEST RECORDS ==========
                   Crop  Rows  Actual_Mean  Actual_Median     MAE    RMSE        R2
             Drum Stick     1       0.6761         0.6761  0.1744  0.1744       NaN
                   Moth     2       0.6537         0.6537  0.2292  0.2974   -0.8067
       Other Vegetables     2      11.4062        11.4062  0.0935  0.1131  -34.7990
     Other Fresh Fruits     2      10.6448        10.6448  0.1282  0.1583    0.0000
                 Grapes     4      24.3524        23.0000  5.5374  6.2487   -4.0858
            Pome Granet     9      10.2807        10.3636  3.7340  3.7599 -213.8227
                   Bean    10       1.3546         1.3690  0.0398  0.0475   -0.5322
              Blackgram    11       0.8206         0.8000  0.2004  0.2187   -8.6649
                  Lemon    13       7.6017         6.2000  1.4907  1.5918    0.7595
                 Sapota    13       8.3051         8.3648  2.9023  3.0841  -88.6496
               Cardamom    14       0.1064         0.0754  0.0557  0.0838    0.4163
         other oilseeds    14       0.8965         0.6667  0.4161  0.6213   -0.3492
                Cabbage    17      12.6085        12.3243 10.7543 11.5234   -1.8385
                  Mango    18       7.7669         7.0750  2.6391  3.4680    0.4331
Other Cereals & Millets    19       0.6250         0.5000  0.2017  0.2490   -0.3422

========== SAVED FILES ==========
/content/drive/MyDrive/yield prediction/cropsense_xgb_native_categorical_train2013.joblib
/content/drive/MyDrive/yield prediction/cropsense_xgb_native_categories.json
/content/drive/MyDrive/yield prediction/native_xgb_overall_metrics.csv
/content/drive/MyDrive/yield prediction/native_xgb_per_crop_metrics.csv
/content/drive/MyDrive/yield prediction/native_xgb_test_predictions.csv
/content/drive/MyDrive/yield prediction/cropsense_supported_combinations_all_years.csv

Done! Existing baseline and historical models were not overwritten.

In [ ]:

# ============================================================
# CROPSENSE AI - YIELD PREDICTION TRAINING PIPELINE
# Models: LightGBM + Native Categorical XGBoost
# Farmer inputs: Crop, State, District, Season
# Target: yield_per_area
# Evaluation: Train <= 2013, test 2014-2015
# Deployment model: retrained on all available years
# ============================================================

%pip -q install -U lightgbm xgboost joblib

import os
import json
import joblib
import warnings
import numpy as np
import pandas as pd
import lightgbm as lgb
import xgboost as xgb

from google.colab import drive
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

warnings.filterwarnings("ignore", category=UserWarning)

# ------------------------------------------------------------
# 1. DRIVE AND PATHS
# ------------------------------------------------------------
drive.mount("/content/drive")

BASE = "/content/drive/MyDrive/yield prediction"
DATA_PATH = os.path.join(BASE, "crop_final.csv")
OUT = os.path.join(BASE, "cropsense_corrected_v3")
os.makedirs(OUT, exist_ok=True)

CAT = ["Crop", "State_Name", "District_Name", "Season"]
TARGET = "yield_per_area"
YEAR = "Crop_Year"

# Set True only for a separately validated historical-feature experiment.
USE_LAGS = False

print("LightGBM:", lgb.__version__)
print("XGBoost:", xgb.__version__)

# ------------------------------------------------------------
# 2. LOAD AND VALIDATE DATA
# ------------------------------------------------------------
df = pd.read_csv(DATA_PATH, low_memory=False)
df.columns = df.columns.str.strip()

required = CAT + [YEAR, TARGET]
missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}")

for c in CAT:
    df[c] = df[c].astype("string").str.strip()

df[YEAR] = pd.to_numeric(df[YEAR], errors="coerce")
df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")

df = df.dropna(subset=required).copy()
df = df[df[CAT].apply(lambda col: col.str.len() > 0).all(axis=1)]
df = df[np.isfinite(df[TARGET]) & np.isfinite(df[YEAR])].copy()
df[YEAR] = df[YEAR].astype(int)

# Retain legitimate zero-yield observations.
if (df[TARGET] < 0).any():
    raise ValueError(
        "Negative yield_per_area values found. Inspect these rows "
        "before training; this script will not silently discard them."
    )

df = df.reset_index(drop=True)

train_mask = df[YEAR] <= 2013
test_mask = df[YEAR].isin([2014, 2015])

if not train_mask.any() or not test_mask.any():
    raise ValueError("Training or test set is empty. Check the year range.")

train_df = df.loc[train_mask].copy()
test_df = df.loc[test_mask].copy()

print("\n========== DATA SUMMARY ==========")
print("Rows:", len(df))
print("Years:", df[YEAR].min(), "-", df[YEAR].max())
print("Training rows:", len(train_df))
print("Test rows:", len(test_df))
print("Training years:", train_df[YEAR].min(), "-", train_df[YEAR].max())
print("Test years:", sorted(test_df[YEAR].unique().tolist()))
print("Unique crops:", df["Crop"].nunique())
print("Zero-yield records retained:", int((df[TARGET] == 0).sum()))

# ------------------------------------------------------------
# 3. CATEGORY SCHEMAS
# Evaluation schema is learned from training data only.
# Deployment schema is learned from all data when retraining.
# ------------------------------------------------------------
def build_schema(frame):
    return {c: sorted(frame[c].astype(str).unique().tolist()) for c in CAT}

eval_schema = build_schema(train_df)

def make_features(frame, schema, features=CAT):
    X = frame[features].copy()
    for c in CAT:
        if c in X.columns:
            X[c] = pd.Categorical(
                X[c].astype(str),
                categories=schema[c]
            )
    return X

X_train = make_features(train_df, eval_schema)
X_test = make_features(test_df, eval_schema)

y_train = train_df[TARGET].astype(float)
y_test = test_df[TARGET].astype(float)

# Report unseen category values, if any.
for c in CAT:
    unseen = (~test_df[c].isin(eval_schema[c])).sum()
    print(f"Unseen test values in {c}: {unseen}")

# ------------------------------------------------------------
# 4. MODEL CONFIGURATIONS
# ------------------------------------------------------------
lgb_params = dict(
    objective="regression",
    n_estimators=800,
    learning_rate=0.04,
    num_leaves=127,
    min_child_samples=10,
    reg_lambda=5.0,
    random_state=42,
    verbosity=-1,
    n_jobs=-1
)

xgb_params = dict(
    objective="reg:squarederror",
    n_estimators=800,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.85,
    colsample_bytree=0.85,
    reg_lambda=5,
    enable_categorical=True,
    max_cat_to_onehot=1,
    tree_method="hist",
    random_state=42,
    n_jobs=-1
)

# ------------------------------------------------------------
# 5. TRAIN AND EVALUATE ON IDENTICAL ROWS
# ------------------------------------------------------------
models = {}

print("\nTraining LightGBM...")
models["LightGBM"] = lgb.LGBMRegressor(**lgb_params)
models["LightGBM"].fit(X_train, y_train, categorical_feature=CAT)

print("Training native categorical XGBoost...")
models["Native categorical XGBoost"] = xgb.XGBRegressor(**xgb_params)
models["Native categorical XGBoost"].fit(X_train, y_train, verbose=False)

def score_model(actual, raw_pred):
    pred = np.maximum(np.asarray(raw_pred, dtype=float), 0)
    return {
        "Rows": len(actual),
        "MAE": mean_absolute_error(actual, pred),
        "RMSE": np.sqrt(mean_squared_error(actual, pred)),
        "R2": r2_score(actual, pred),
        "Negative_Raw_Predictions": int((np.asarray(raw_pred) < 0).sum())
    }, pred

overall_rows = []
per_crop_tables = []
prediction_table = test_df[CAT + [YEAR, TARGET]].copy()
prediction_table = prediction_table.rename(columns={TARGET: "Actual"})

for name, model in models.items():
    raw = model.predict(X_test)
    metrics, pred = score_model(y_test, raw)

    metrics["Model"] = name
    metrics["Train_Through_Year"] = int(train_df[YEAR].max())
    metrics["Test_Period"] = "2014-2015"
    overall_rows.append(metrics)

    prediction_table[name + "_Prediction"] = pred
    prediction_table[name + "_Raw_Prediction"] = raw

    crop_rows = []
    temp = pd.DataFrame({
        "Crop": test_df["Crop"].to_numpy(),
        "Actual": y_test.to_numpy(),
        "Predicted": pred
    })

    for crop, group in temp.groupby("Crop"):
        actual = group["Actual"].to_numpy()
        predicted = group["Predicted"].to_numpy()
        crop_rows.append({
            "Model": name,
            "Crop": crop,
            "Rows": len(group),
            "Actual_Mean": actual.mean(),
            "MAE": mean_absolute_error(actual, predicted),
            "RMSE": np.sqrt(mean_squared_error(actual, predicted)),
            "R2": r2_score(actual, predicted) if len(group) >= 2 else np.nan
        })

    per_crop_tables.append(pd.DataFrame(crop_rows))

overall_df = pd.DataFrame(overall_rows)
per_crop_df = pd.concat(per_crop_tables, ignore_index=True)

print("\n========== OVERALL TEST RESULTS ==========")
print(
    overall_df[["Model", "Rows", "MAE", "RMSE", "R2",
                "Negative_Raw_Predictions"]]
    .round(4).to_string(index=False)
)

for name in models:
    print(f"\n========== HIGHEST MAE CROPS: {name} ==========")
    print(
        per_crop_df[per_crop_df["Model"] == name]
        .sort_values("MAE", ascending=False)
        .head(15)
        .round(4).to_string(index=False)
    )

# ------------------------------------------------------------
# 6. SAVE EVALUATION RESULTS
# ------------------------------------------------------------
overall_df.to_csv(os.path.join(OUT, "overall_metrics.csv"), index=False)
per_crop_df.to_csv(os.path.join(OUT, "per_crop_metrics.csv"), index=False)
prediction_table.to_csv(
    os.path.join(OUT, "test_predictions.csv"), index=False
)

# ------------------------------------------------------------
# 7. CHOOSE THE MODEL USING THE PREDECLARED METRIC
# Lower validation MAE should determine selection in a tuning workflow.
# Here the reported test MAE is only a development comparison.
# Do not describe this test-based choice as unbiased final selection.
# ------------------------------------------------------------
# Choose the candidate with lower test MAE for this benchmark only.
# Change this explicitly if you have already selected a model using
# a separate chronological validation period.
selected_name = overall_df.sort_values("MAE").iloc[0]["Model"]
print("\nLowest-MAE test benchmark:", selected_name)

# ------------------------------------------------------------
# 8. RETRAIN SELECTED MODEL ON ALL AVAILABLE YEARS
# This is for deployment after the latest training year.
# Its score is NOT the 2014-2015 test score.
# ------------------------------------------------------------
deployment_schema = build_schema(df)
X_all = make_features(df, deployment_schema)
y_all = df[TARGET].astype(float)

if selected_name == "LightGBM":
    final_model = lgb.LGBMRegressor(**lgb_params)
    final_model.fit(X_all, y_all, categorical_feature=CAT)
else:
    final_model = xgb.XGBRegressor(**xgb_params)
    final_model.fit(X_all, y_all, verbose=False)

bundle = {
    "model": final_model,
    "model_name": selected_name,
    "categorical_columns": CAT,
    "target": TARGET,
    "category_schema": deployment_schema,
    "features": CAT,
    "training_year_min": int(df[YEAR].min()),
    "training_year_max": int(df[YEAR].max()),
    "prediction_clip_min": 0
}

MODEL_PATH = os.path.join(OUT, "cropsense_yield_deployment.joblib")
joblib.dump(bundle, MODEL_PATH)

# Dropdown combinations from all available years.
combos = df[CAT].drop_duplicates().sort_values(CAT).reset_index(drop=True)
COMBOS_PATH = os.path.join(OUT, "supported_combinations.csv")
combos.to_csv(COMBOS_PATH, index=False)

print("\n========== DEPLOYMENT ARTIFACTS ==========")
print("Selected model:", selected_name)
print("Deployment training rows:", len(df))
print("Deployment year range:", df[YEAR].min(), "-", df[YEAR].max())
print("Supported observed combinations:", len(combos))
print("Model bundle:", MODEL_PATH)
print("Supported combinations:", COMBOS_PATH)
print("Metrics folder:", OUT)

# ------------------------------------------------------------
# 9. FOUR-INPUT PREDICTION FUNCTION
# ------------------------------------------------------------
def predict_yield(crop, state, district, season, bundle=None):
    """
    Returns predicted yield_per_area and diagnostic notes.
    Inputs: crop, state, district, season.
    """
    b = bundle if bundle is not None else joblib.load(MODEL_PATH)

    values = {
        "Crop": str(crop).strip(),
        "State_Name": str(state).strip(),
        "District_Name": str(district).strip(),
        "Season": str(season).strip()
    }

    known = any(
        (combos[c] == values[c]).all()
        for c in []  # no-op; exact combination check below
    )

    known = (
        (combos["Crop"] == values["Crop"]) &
        (combos["State_Name"] == values["State_Name"]) &
        (combos["District_Name"] == values["District_Name"]) &
        (combos["Season"] == values["Season"])
    ).any()

    row = pd.DataFrame([values])
    X = make_features(row, b["category_schema"], b["features"])

    notes = []
    if not known:
        notes.append(
            "This exact combination was not observed in the dataset; "
            "treat the estimate cautiously."
        )

    if any(pd.isna(X[c].iloc[0]) for c in CAT):
        notes.append(
            "At least one input category was not learned by the model. "
            "The estimate may be unreliable."
        )

    prediction = max(float(b["model"].predict(X)[0]), 0.0)
    return round(prediction, 4), notes

# Example using an observed combination:
example = combos.iloc[0]
value, notes = predict_yield(
    example["Crop"],
    example["State_Name"],
    example["District_Name"],
    example["Season"]
)
print("\nExample input:", example.to_dict())
print("Predicted yield_per_area:", value)
print("Notes:", notes)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
LightGBM: 4.6.0
XGBoost: 3.4.1

========== DATA SUMMARY ==========
Rows: 235123
Years: 1997 - 2015
Training rows: 223882
Test rows: 11241
Training years: 1997 - 2013
Test years: [2014, 2015]
Unique crops: 104
Zero-yield records retained: 0
Unseen test values in Crop: 0
Unseen test values in State_Name: 0
Unseen test values in District_Name: 1
Unseen test values in Season: 0

Training LightGBM...
Training native categorical XGBoost...

========== OVERALL TEST RESULTS ==========
                     Model  Rows    MAE   RMSE     R2  Negative_Raw_Predictions
                  LightGBM 11241 0.9555 3.2949 0.9345                         2
Native categorical XGBoost 11241 0.9736 3.3187 0.9336                        21

========== HIGHEST MAE CROPS: LightGBM ==========
   Model        Crop  Rows  Actual_Mean     MAE    RMSE        R2
LightGBM     Cabbage    17      12.6085 10.5555 11.0112   -1.5918
LightGBM   Sugarcane   360      60.6190  9.6938 15.1908    0.6961
LightGBM      Papaya    44      42.1091  9.2490 16.8483    0.7218
LightGBM      Grapes     4      24.3524  4.9507  6.1837   -3.9805
LightGBM     Brinjal    29      15.2998  3.8810  5.1992    0.4682
LightGBM      Banana   119      28.2720  3.6079  5.4462    0.8702
LightGBM      Tomato    26      17.1471  3.5786  4.2320    0.4167
LightGBM Pome Granet     9      10.2807  3.5305  3.6102 -197.0526
LightGBM  Dry ginger    96       9.3143  3.3447  6.1167    0.6603
LightGBM      Sapota    13       8.3051  2.9307  3.0148  -84.6666
LightGBM       Mango    18       7.7669  2.7491  3.4850    0.4275
LightGBM        Jute    84      10.4571  2.7050  3.5834    0.5654
LightGBM     Tapioca    73      16.2102  2.4745  4.4898    0.8608
LightGBM       Onion   316      11.7350  2.3845  2.9411    0.7529
LightGBM      Potato   357      13.2882  2.2954  3.2775    0.8130

========== HIGHEST MAE CROPS: Native categorical XGBoost ==========
                     Model        Crop  Rows  Actual_Mean     MAE    RMSE        R2
Native categorical XGBoost     Cabbage    17      12.6085 10.7543 11.5234   -1.8385
Native categorical XGBoost   Sugarcane   360      60.6190  9.8255 15.5832    0.6802
Native categorical XGBoost      Papaya    44      42.1091  8.7230 15.6183    0.7609
Native categorical XGBoost      Grapes     4      24.3524  5.5374  6.2487   -4.0858
Native categorical XGBoost     Brinjal    29      15.2998  4.1803  5.5024    0.4044
Native categorical XGBoost      Tomato    26      17.1471  3.7512  4.4677    0.3499
Native categorical XGBoost Pome Granet     9      10.2807  3.7340  3.7599 -213.8227
Native categorical XGBoost      Banana   119      28.2720  3.3068  4.8445    0.8973
Native categorical XGBoost  Dry ginger    96       9.3143  3.0974  5.6386    0.7113
Native categorical XGBoost      Sapota    13       8.3051  2.9023  3.0841  -88.6496
Native categorical XGBoost        Jute    84      10.4571  2.6859  3.5909    0.5636
Native categorical XGBoost       Mango    18       7.7669  2.6391  3.4680    0.4331
Native categorical XGBoost     Tapioca    73      16.2102  2.5601  4.5096    0.8595
Native categorical XGBoost       Onion   316      11.7350  2.4280  3.0131    0.7406
Native categorical XGBoost      Potato   357      13.2882  2.3684  3.3269    0.8074

Lowest-MAE test benchmark: LightGBM

========== DEPLOYMENT ARTIFACTS ==========
Selected model: LightGBM
Deployment training rows: 235123
Deployment year range: 1997 - 2015
Supported observed combinations: 30723
Model bundle: /content/drive/MyDrive/yield prediction/cropsense_corrected_v3/cropsense_yield_deployment.joblib
Supported combinations: /content/drive/MyDrive/yield prediction/cropsense_corrected_v3/supported_combinations.csv
Metrics folder: /content/drive/MyDrive/yield prediction/cropsense_corrected_v3

Example input: {'Crop': 'Arcanut (Processed)', 'State_Name': 'Karnataka', 'District_Name': 'BAGALKOT', 'Season': 'Whole Year'}
Predicted yield_per_area: 1.0907
Notes: []

In [ ]:

%pip -q install -U lightgbm

import os
import numpy as np
import pandas as pd
import lightgbm as lgb

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import ParameterSampler

BASE = "/content/drive/MyDrive/yield prediction"
DATA_PATH = os.path.join(BASE, "crop_final.csv")
OUT = os.path.join(BASE, "cropsense_lightgbm_tuning")
os.makedirs(OUT, exist_ok=True)

CAT = ["Crop", "State_Name", "District_Name", "Season"]
TARGET = "yield_per_area"
YEAR = "Crop_Year"

# Load data
df = pd.read_csv(DATA_PATH, low_memory=False)
df.columns = df.columns.str.strip()

for c in CAT:
    df[c] = df[c].astype("string").str.strip()

df[YEAR] = pd.to_numeric(df[YEAR], errors="coerce")
df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")
df = df.dropna(subset=CAT + [YEAR, TARGET]).copy()
df = df[np.isfinite(df[TARGET]) & np.isfinite(df[YEAR])]
df = df[df[TARGET] >= 0].copy()

for c in CAT:
    df[c] = df[c].astype(str)

df[YEAR] = df[YEAR].astype(int)
df = df.reset_index(drop=True)

# Chronological train / validation / test
train = df[df[YEAR] <= 2011].copy()
valid = df[df[YEAR].isin([2012, 2013])].copy()
test = df[df[YEAR].isin([2014, 2015])].copy()

# Learn category definitions from training only.
categories = {
    c: sorted(train[c].unique().tolist())
    for c in CAT
}

def features(frame):
    X = frame[CAT].copy()
    for c in CAT:
        X[c] = pd.Categorical(X[c], categories=categories[c])
    return X

X_train = features(train)
X_valid = features(valid)

y_train = train[TARGET].astype(float)
y_valid = valid[TARGET].astype(float)

print("Train rows:", len(train))
print("Validation rows:", len(valid))
print("Test rows (reserved for final comparison):", len(test))

# Hyperparameter search space
param_space = {
    "learning_rate": [0.02, 0.03, 0.04, 0.05, 0.07],
    "n_estimators": [500, 800, 1200, 1600],
    "max_depth": [-1, 8, 12, 16],
    "num_leaves": [31, 63, 127],
    "min_child_samples": [10, 20, 40],
    "reg_lambda": [1.0, 5.0, 10.0],
    "colsample_bytree": [0.8, 0.9, 1.0],
    "subsample": [0.8, 0.9, 1.0]
}

# Randomly sample 30 configurations first.
# Increase to 50-80 if runtime permits.
candidates = list(ParameterSampler(
    param_space, n_iter=30, random_state=42
))

results = []

for i, params in enumerate(candidates, start=1):
    # num_leaves should not exceed the theoretical leaf limit
    # for a depth-limited tree.
    if params["max_depth"] > 0:
        params["num_leaves"] = min(
            params["num_leaves"],
            2 ** params["max_depth"]
        )

    model = lgb.LGBMRegressor(
        objective="regression",
        random_state=42,
        verbosity=-1,
        n_jobs=-1,
        **params
    )

    model.fit(X_train, y_train, categorical_feature=CAT)

    raw_pred = model.predict(X_valid)
    pred = np.maximum(raw_pred, 0)

    row = {
        **params,
        "Validation_MAE": mean_absolute_error(y_valid, pred),
        "Validation_RMSE": np.sqrt(
            mean_squared_error(y_valid, pred)
        ),
        "Validation_R2": r2_score(y_valid, pred),
        "Negative_Raw_Predictions": int((raw_pred < 0).sum())
    }
    results.append(row)

    print(
        f"[{i:02d}/{len(candidates)}] "
        f"MAE={row['Validation_MAE']:.4f} | "
        f"RMSE={row['Validation_RMSE']:.4f} | "
        f"R2={row['Validation_R2']:.4f}"
    )

results_df = pd.DataFrame(results).sort_values(
    "Validation_MAE", ascending=True
).reset_index(drop=True)

results_path = os.path.join(OUT, "tuning_results.csv")
results_df.to_csv(results_path, index=False)

print("\n========== TOP 10 CONFIGURATIONS ==========")
print(results_df.head(10).round(4).to_string(index=False))
print("\nSaved:", results_path)

Train rows: 197598
Validation rows: 26284
Test rows (reserved for final comparison): 11241
[01/30] MAE=1.1814 | RMSE=3.7991 | R2=0.9135
[02/30] MAE=1.1694 | RMSE=3.7910 | R2=0.9139
[03/30] MAE=1.1548 | RMSE=3.7548 | R2=0.9155
[04/30] MAE=1.1444 | RMSE=3.7672 | R2=0.9149
[05/30] MAE=1.1495 | RMSE=3.7868 | R2=0.9141
[06/30] MAE=1.1972 | RMSE=3.7891 | R2=0.9140
[07/30] MAE=1.1907 | RMSE=3.8130 | R2=0.9129
[08/30] MAE=1.1686 | RMSE=3.7909 | R2=0.9139
[09/30] MAE=1.1766 | RMSE=3.8000 | R2=0.9135
[10/30] MAE=1.1493 | RMSE=3.7999 | R2=0.9135
[11/30] MAE=1.1789 | RMSE=3.8189 | R2=0.9126
[12/30] MAE=1.2160 | RMSE=3.8282 | R2=0.9122
[13/30] MAE=1.1835 | RMSE=3.7945 | R2=0.9137
[14/30] MAE=1.2564 | RMSE=3.9074 | R2=0.9085
[15/30] MAE=1.2044 | RMSE=3.7982 | R2=0.9135
[16/30] MAE=1.1625 | RMSE=3.7870 | R2=0.9140
[17/30] MAE=1.1725 | RMSE=3.7739 | R2=0.9146
[18/30] MAE=1.1581 | RMSE=3.7870 | R2=0.9140
[19/30] MAE=1.1488 | RMSE=3.8164 | R2=0.9127
[20/30] MAE=1.1664 | RMSE=3.8059 | R2=0.9132
[21/30] MAE=1.1652 | RMSE=3.8094 | R2=0.9130
[22/30] MAE=1.1524 | RMSE=3.8125 | R2=0.9129
[23/30] MAE=1.1458 | RMSE=3.8053 | R2=0.9132
[24/30] MAE=1.1628 | RMSE=3.7796 | R2=0.9144
[25/30] MAE=1.2100 | RMSE=3.8054 | R2=0.9132
[26/30] MAE=1.1734 | RMSE=3.7850 | R2=0.9141
[27/30] MAE=1.1806 | RMSE=3.7711 | R2=0.9148
[28/30] MAE=1.1835 | RMSE=3.7945 | R2=0.9137
[29/30] MAE=1.1715 | RMSE=3.7882 | R2=0.9140
[30/30] MAE=1.1463 | RMSE=3.8090 | R2=0.9130

========== TOP 10 CONFIGURATIONS ==========
 subsample  reg_lambda  num_leaves  n_estimators  min_child_samples  max_depth  learning_rate  colsample_bytree  Validation_MAE  Validation_RMSE  Validation_R2  Negative_Raw_Predictions
       0.8         5.0          31          1600                 40         -1           0.07               0.9          1.1444           3.7672         0.9149                         3
       1.0        10.0          63          1200                 40         -1           0.07               1.0          1.1458           3.8053         0.9132                         4
       1.0         1.0          63          1600                 10         16           0.05               1.0          1.1463           3.8090         0.9130                        11
       0.8         1.0         127          1200                 10         12           0.05               1.0          1.1488           3.8164         0.9127                         4
       1.0         5.0         127           500                 10         16           0.05               0.9          1.1493           3.7999         0.9135                         7
       0.9        10.0         127           800                 40         12           0.05               0.9          1.1495           3.7868         0.9141                         8
       0.8        10.0          63           800                 20         12           0.07               1.0          1.1524           3.8125         0.9129                         5
       1.0        10.0          63          1600                 20         -1           0.07               0.8          1.1548           3.7548         0.9155                       111
       0.8         5.0         127           800                 40         16           0.07               0.8          1.1581           3.7870         0.9140                       130
       0.9         1.0         127           500                 20         -1           0.07               0.8          1.1625           3.7870         0.9140                       149

Saved: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/tuning_results.csv

In [ ]:

import os
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

BASE = "/content/drive/MyDrive/yield prediction"
DATA_PATH = os.path.join(BASE, "crop_final.csv")

CAT = ["Crop", "State_Name", "District_Name", "Season"]
TARGET = "yield_per_area"
YEAR = "Crop_Year"

df = pd.read_csv(DATA_PATH, low_memory=False)
df.columns = df.columns.str.strip()

for c in CAT:
    df[c] = df[c].astype("string").str.strip()

df[YEAR] = pd.to_numeric(df[YEAR], errors="coerce")
df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")
df = df.dropna(subset=CAT + [YEAR, TARGET]).copy()
df = df[np.isfinite(df[TARGET]) & np.isfinite(df[YEAR])]
df = df[df[TARGET] >= 0].copy()

for c in CAT:
    df[c] = df[c].astype(str)

df[YEAR] = df[YEAR].astype(int)

train = df[df[YEAR] <= 2013].copy()
test = df[df[YEAR].isin([2014, 2015])].copy()

categories = {
    c: sorted(train[c].unique().tolist()) for c in CAT
}

def make_X(frame):
    X = frame[CAT].copy()
    for c in CAT:
        X[c] = pd.Categorical(X[c], categories=categories[c])
    return X

X_train = make_X(train)
X_test = make_X(test)
y_train = train[TARGET].astype(float)
y_test = test[TARGET].astype(float)

configs = {
    "Existing LightGBM": {
        "n_estimators": 800,
        "learning_rate": 0.04,
        "num_leaves": 127,
        "min_child_samples": 10,
        "reg_lambda": 5.0,
    },
    "Tuned LightGBM": {
        "n_estimators": 1600,
        "learning_rate": 0.07,
        "num_leaves": 31,
        "min_child_samples": 40,
        "reg_lambda": 5.0,
        "subsample": 0.8,
        "colsample_bytree": 0.9,
        "max_depth": -1,
    }
}

results = []

for name, params in configs.items():
    model = lgb.LGBMRegressor(
        objective="regression",
        random_state=42,
        verbosity=-1,
        n_jobs=-1,
        **params
    )
    model.fit(X_train, y_train, categorical_feature=CAT)

    raw = model.predict(X_test)
    pred = np.maximum(raw, 0)

    results.append({
        "Model": name,
        "Rows": len(test),
        "MAE": mean_absolute_error(y_test, pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, pred)),
        "R2": r2_score(y_test, pred),
        "Negative_Raw_Predictions": int((raw < 0).sum())
    })

results_df = pd.DataFrame(results)
print(results_df.round(4).to_string(index=False))

out = os.path.join(
    BASE, "cropsense_lightgbm_tuning", "same_test_comparison.csv"
)
results_df.to_csv(out, index=False)
print("\nSaved:", out)

            Model  Rows    MAE   RMSE     R2  Negative_Raw_Predictions
Existing LightGBM 11241 0.9555 3.2949 0.9345                         2
   Tuned LightGBM 11241 0.9640 3.2855 0.9349                         3

Saved: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/same_test_comparison.csv

In [ ]:

# ============================================================
# CROPSENSE AI — FOCUSED LIGHTGBM TUNING
# Train:      <= 2011
# Validation: 2012-2013
# Test:       2014-2015 (NOT USED FOR SELECTION)
# Existing models remain unchanged.
# ============================================================

%pip -q install -U lightgbm

import os
import numpy as np
import pandas as pd
import lightgbm as lgb

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import ParameterSampler

BASE = "/content/drive/MyDrive/yield prediction"
DATA_PATH = os.path.join(BASE, "crop_final.csv")
OUT = os.path.join(BASE, "cropsense_lightgbm_tuning")
os.makedirs(OUT, exist_ok=True)

CAT = ["Crop", "State_Name", "District_Name", "Season"]
TARGET = "yield_per_area"
YEAR = "Crop_Year"

# ------------------------------------------------------------
# 1. Load and validate data
# ------------------------------------------------------------
df = pd.read_csv(DATA_PATH, low_memory=False)
df.columns = df.columns.str.strip()

for c in CAT:
    df[c] = df[c].astype("string").str.strip()

df[YEAR] = pd.to_numeric(df[YEAR], errors="coerce")
df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")

df = df.dropna(subset=CAT + [YEAR, TARGET]).copy()
df = df[np.isfinite(df[YEAR]) & np.isfinite(df[TARGET])].copy()
df = df[df[TARGET] >= 0].copy()

for c in CAT:
    df[c] = df[c].astype(str)

df[YEAR] = df[YEAR].astype(int)
df = df.reset_index(drop=True)

train = df[df[YEAR] <= 2011].copy()
valid = df[df[YEAR].isin([2012, 2013])].copy()
test = df[df[YEAR].isin([2014, 2015])].copy()

if train.empty or valid.empty or test.empty:
    raise ValueError("One of the chronological splits is empty.")

# Categories learned only from training data.
categories = {
    c: sorted(train[c].unique().tolist()) for c in CAT
}

def make_X(frame):
    X = frame[CAT].copy()
    for c in CAT:
        X[c] = pd.Categorical(
            X[c].astype(str), categories=categories[c]
        )
    return X

X_train = make_X(train)
X_valid = make_X(valid)
y_train = train[TARGET].astype(float)
y_valid = valid[TARGET].astype(float)

print("LightGBM version:", lgb.__version__)
print("Training rows:", len(train))
print("Validation rows:", len(valid))
print("Reserved test rows:", len(test))

# ------------------------------------------------------------
# 2. Focused parameter search
# ------------------------------------------------------------
# Includes the existing configuration as a baseline.
# 40 trials offer a broader search without being exhaustive.
parameter_space = {
    "learning_rate": [0.02, 0.03, 0.04, 0.05],
    "n_estimators": [600, 800, 1000, 1200],
    "num_leaves": [63, 127, 191],
    "min_child_samples": [10, 20, 30],
    "reg_lambda": [3.0, 5.0, 8.0, 10.0],
    "max_depth": [-1, 12, 16],
    "colsample_bytree": [0.8, 0.9, 1.0],
    "subsample": [0.8, 0.9, 1.0],
    "subsample_freq": [0, 1]
}

sampled = list(ParameterSampler(
    parameter_space, n_iter=40, random_state=2026
))

baseline = {
    "learning_rate": 0.04,
    "n_estimators": 800,
    "num_leaves": 127,
    "min_child_samples": 10,
    "reg_lambda": 5.0,
    "max_depth": -1,
    "colsample_bytree": 1.0,
    "subsample": 1.0,
    "subsample_freq": 0
}

# Guarantee the current configuration is included.
candidates = [baseline] + sampled
results = []

# ------------------------------------------------------------
# 3. Fit candidates and evaluate validation only
# ------------------------------------------------------------
for i, params in enumerate(candidates, start=1):
    model = lgb.LGBMRegressor(
        objective="regression",
        random_state=42,
        verbosity=-1,
        n_jobs=-1,
        **params
    )

    model.fit(X_train, y_train, categorical_feature=CAT)

    raw = model.predict(X_valid)
    pred = np.maximum(raw, 0)

    results.append({
        **params,
        "Validation_MAE": mean_absolute_error(y_valid, pred),
        "Validation_RMSE": np.sqrt(
            mean_squared_error(y_valid, pred)
        ),
        "Validation_R2": r2_score(y_valid, pred),
        "Negative_Raw_Predictions": int((raw < 0).sum())
    })

    print(
        f"[{i:02d}/{len(candidates)}] "
        f"MAE={results[-1]['Validation_MAE']:.4f} | "
        f"RMSE={results[-1]['Validation_RMSE']:.4f} | "
        f"R2={results[-1]['Validation_R2']:.4f}"
    )

results_df = pd.DataFrame(results).sort_values(
    "Validation_MAE", ascending=True
).reset_index(drop=True)

results_path = os.path.join(OUT, "focused_tuning_results.csv")
results_df.to_csv(results_path, index=False)

print("\n========== TOP 10 VALIDATION CONFIGURATIONS ==========")
print(results_df.head(10).round(4).to_string(index=False))

print("\n========== BASELINE VALIDATION RESULT ==========")
baseline_rows = results_df[
    (results_df["learning_rate"] == baseline["learning_rate"]) &
    (results_df["n_estimators"] == baseline["n_estimators"]) &
    (results_df["num_leaves"] == baseline["num_leaves"]) &
    (results_df["min_child_samples"] == baseline["min_child_samples"]) &
    (results_df["reg_lambda"] == baseline["reg_lambda"]) &
    (results_df["max_depth"] == baseline["max_depth"]) &
    (results_df["colsample_bytree"] == baseline["colsample_bytree"]) &
    (results_df["subsample"] == baseline["subsample"]) &
    (results_df["subsample_freq"] == baseline["subsample_freq"])
]
print(baseline_rows.round(4).to_string(index=False))

print("\nSaved tuning results:", results_path)
print("No existing model was overwritten.")

LightGBM version: 4.6.0
Training rows: 197598
Validation rows: 26284
Reserved test rows: 11241
[01/41] MAE=1.1492 | RMSE=3.8111 | R2=0.9129
[02/41] MAE=1.2487 | RMSE=3.9192 | R2=0.9079
[03/41] MAE=1.1678 | RMSE=3.7943 | R2=0.9137
[04/41] MAE=1.1452 | RMSE=3.7801 | R2=0.9144
[05/41] MAE=1.1561 | RMSE=3.8021 | R2=0.9134
[06/41] MAE=1.1690 | RMSE=3.8264 | R2=0.9122
[07/41] MAE=1.1684 | RMSE=3.8230 | R2=0.9124
[08/41] MAE=1.1476 | RMSE=3.8174 | R2=0.9127
[09/41] MAE=1.1480 | RMSE=3.7832 | R2=0.9142
[10/41] MAE=1.1583 | RMSE=3.8435 | R2=0.9115
[11/41] MAE=1.1673 | RMSE=3.8269 | R2=0.9122
[12/41] MAE=1.1810 | RMSE=3.8400 | R2=0.9116
[13/41] MAE=1.1627 | RMSE=3.8075 | R2=0.9131
[14/41] MAE=1.2063 | RMSE=3.8683 | R2=0.9103
[15/41] MAE=1.1658 | RMSE=3.7954 | R2=0.9137
[16/41] MAE=1.1549 | RMSE=3.8087 | R2=0.9131
[17/41] MAE=1.1532 | RMSE=3.8615 | R2=0.9106
[18/41] MAE=1.1477 | RMSE=3.8039 | R2=0.9133
[19/41] MAE=1.1936 | RMSE=3.8772 | R2=0.9099
[20/41] MAE=1.2071 | RMSE=3.8483 | R2=0.9112
[21/41] MAE=1.1528 | RMSE=3.7891 | R2=0.9140
[22/41] MAE=1.2494 | RMSE=3.9234 | R2=0.9077
[23/41] MAE=1.1778 | RMSE=3.8314 | R2=0.9120
[24/41] MAE=1.1950 | RMSE=3.8452 | R2=0.9114
[25/41] MAE=1.1730 | RMSE=3.8289 | R2=0.9121
[26/41] MAE=1.1568 | RMSE=3.8022 | R2=0.9134
[27/41] MAE=1.1703 | RMSE=3.8135 | R2=0.9128
[28/41] MAE=1.1654 | RMSE=3.8218 | R2=0.9125
[29/41] MAE=1.1891 | RMSE=3.9020 | R2=0.9087
[30/41] MAE=1.1572 | RMSE=3.8036 | R2=0.9133
[31/41] MAE=1.1542 | RMSE=3.7796 | R2=0.9144
[32/41] MAE=1.1661 | RMSE=3.7817 | R2=0.9143
[33/41] MAE=1.1527 | RMSE=3.7810 | R2=0.9143
[34/41] MAE=1.1599 | RMSE=3.8489 | R2=0.9112
[35/41] MAE=1.1477 | RMSE=3.8027 | R2=0.9133
[36/41] MAE=1.2075 | RMSE=3.9115 | R2=0.9083
[37/41] MAE=1.1667 | RMSE=3.7980 | R2=0.9135
[38/41] MAE=1.1733 | RMSE=3.8568 | R2=0.9109
[39/41] MAE=1.1461 | RMSE=3.8165 | R2=0.9127
[40/41] MAE=1.1944 | RMSE=3.8541 | R2=0.9110
[41/41] MAE=1.1509 | RMSE=3.8312 | R2=0.9120

========== TOP 10 VALIDATION CONFIGURATIONS ==========
 learning_rate  n_estimators  num_leaves  min_child_samples  reg_lambda  max_depth  colsample_bytree  subsample  subsample_freq  Validation_MAE  Validation_RMSE  Validation_R2  Negative_Raw_Predictions
          0.05          1200         127                 10         5.0         12               1.0        0.9               0          1.1452           3.7801         0.9144                         4
          0.05          1200         127                 30         3.0         -1               1.0        1.0               0          1.1461           3.8165         0.9127                         6
          0.03          1200         191                 10         8.0         16               0.9        0.8               0          1.1476           3.8174         0.9127                         7
          0.03           800         191                 10         5.0         16               0.9        0.9               0          1.1477           3.8039         0.9133                         5
          0.05          1200         191                 20         8.0         12               0.9        0.8               0          1.1477           3.8027         0.9133                         1
          0.04          1200          63                 10         3.0         -1               0.9        1.0               0          1.1480           3.7832         0.9142                         7
          0.04           800         127                 10         5.0         -1               1.0        1.0               0          1.1492           3.8111         0.9129                         8
          0.04           600         191                 20         8.0         16               1.0        0.9               1          1.1509           3.8312         0.9120                         7
          0.04          1000          63                 20         5.0         -1               1.0        1.0               0          1.1527           3.7810         0.9143                         6
          0.05           600         127                 10         5.0         12               0.9        0.9               0          1.1528           3.7891         0.9140                         7

========== BASELINE VALIDATION RESULT ==========
 learning_rate  n_estimators  num_leaves  min_child_samples  reg_lambda  max_depth  colsample_bytree  subsample  subsample_freq  Validation_MAE  Validation_RMSE  Validation_R2  Negative_Raw_Predictions
          0.04           800         127                 10         5.0         -1               1.0        1.0               0          1.1492           3.8111         0.9129                         8

Saved tuning results: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/focused_tuning_results.csv
No existing model was overwritten.

In [ ]:

# ============================================================
# CROPSENSE AI — FINAL LIGHTGBM CONFIGURATION COMPARISON
# Train: <= 2013 | Test: 2014-2015
# Existing model: preserved
# ============================================================

import os
import numpy as np
import pandas as pd
import lightgbm as lgb

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

BASE = "/content/drive/MyDrive/yield prediction"
DATA_PATH = os.path.join(BASE, "crop_final.csv")
OUT = os.path.join(BASE, "cropsense_lightgbm_tuning")
os.makedirs(OUT, exist_ok=True)

CAT = ["Crop", "State_Name", "District_Name", "Season"]
TARGET = "yield_per_area"
YEAR = "Crop_Year"

# Load and clean
df = pd.read_csv(DATA_PATH, low_memory=False)
df.columns = df.columns.str.strip()

for c in CAT:
    df[c] = df[c].astype("string").str.strip()

df[YEAR] = pd.to_numeric(df[YEAR], errors="coerce")
df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")
df = df.dropna(subset=CAT + [YEAR, TARGET]).copy()
df = df[np.isfinite(df[YEAR]) & np.isfinite(df[TARGET])]
df = df[df[TARGET] >= 0].copy()

for c in CAT:
    df[c] = df[c].astype(str)

df[YEAR] = df[YEAR].astype(int)

train = df[df[YEAR] <= 2013].copy()
test = df[df[YEAR].isin([2014, 2015])].copy()

categories = {c: sorted(train[c].unique()) for c in CAT}

def make_X(frame):
    X = frame[CAT].copy()
    for c in CAT:
        X[c] = pd.Categorical(X[c], categories=categories[c])
    return X

X_train = make_X(train)
X_test = make_X(test)
y_train = train[TARGET].astype(float)
y_test = test[TARGET].astype(float)

# Existing configuration and best tuned configuration
configs = {
    "Existing LightGBM": {
        "n_estimators": 800,
        "learning_rate": 0.04,
        "num_leaves": 127,
        "min_child_samples": 10,
        "reg_lambda": 5.0,
        "max_depth": -1,
        "colsample_bytree": 1.0,
        "subsample": 1.0,
        "subsample_freq": 0
    },
    "Tuned LightGBM": {
        "n_estimators": 1200,
        "learning_rate": 0.05,
        "num_leaves": 127,
        "min_child_samples": 10,
        "reg_lambda": 5.0,
        "max_depth": 12,
        "colsample_bytree": 1.0,
        "subsample": 0.9,
        "subsample_freq": 0
    }
}

rows = []
predictions = pd.DataFrame({
    "Crop": test["Crop"].to_numpy(),
    "Crop_Year": test[YEAR].to_numpy(),
    "Actual": y_test.to_numpy()
})

for name, params in configs.items():
    model = lgb.LGBMRegressor(
        objective="regression",
        random_state=42,
        verbosity=-1,
        n_jobs=-1,
        **params
    )
    model.fit(X_train, y_train, categorical_feature=CAT)

    raw = model.predict(X_test)
    pred = np.maximum(raw, 0)

    rows.append({
        "Model": name,
        "Rows": len(test),
        "MAE": mean_absolute_error(y_test, pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, pred)),
        "R2": r2_score(y_test, pred),
        "Negative_Raw_Predictions": int((raw < 0).sum())
    })

    predictions[name + "_Prediction"] = pred
    predictions[name + "_Absolute_Error"] = np.abs(y_test.to_numpy() - pred)

results = pd.DataFrame(rows).sort_values("MAE")
print("\n========== SAME-TEST COMPARISON ==========")
print(results.round(4).to_string(index=False))

results.to_csv(
    os.path.join(OUT, "focused_tuned_test_comparison.csv"),
    index=False
)
predictions.to_csv(
    os.path.join(OUT, "focused_tuned_test_predictions.csv"),
    index=False
)

# Crop-level comparison
crop_results = []
for model_name in configs:
    pred_col = model_name + "_Prediction"
    for crop, group in predictions.groupby("Crop"):
        crop_results.append({
            "Model": model_name,
            "Crop": crop,
            "Rows": len(group),
            "MAE": np.mean(group["Actual"] - group[pred_col]) if False
                   else np.mean(np.abs(group["Actual"] - group[pred_col])),
            "RMSE": np.sqrt(np.mean((group["Actual"] - group[pred_col]) ** 2))
        })

crop_results = pd.DataFrame(crop_results)
crop_results.to_csv(
    os.path.join(OUT, "focused_tuned_per_crop_comparison.csv"),
    index=False
)

print("\n========== SAVED ==========")
print("Comparison:", os.path.join(OUT, "focused_tuned_test_comparison.csv"))
print("Predictions:", os.path.join(OUT, "focused_tuned_test_predictions.csv"))
print("Per-crop comparison:", os.path.join(OUT, "focused_tuned_per_crop_comparison.csv"))
print("\nNo existing model was overwritten.")

========== SAME-TEST COMPARISON ==========
            Model  Rows    MAE   RMSE     R2  Negative_Raw_Predictions
   Tuned LightGBM 11241 0.9501 3.2753 0.9353                         2
Existing LightGBM 11241 0.9555 3.2949 0.9345                         2

========== SAVED ==========
Comparison: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/focused_tuned_test_comparison.csv
Predictions: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/focused_tuned_test_predictions.csv
Per-crop comparison: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/focused_tuned_per_crop_comparison.csv

No existing model was overwritten.

In [ ]:
params = {
    "objective": "regression",
    "n_estimators": 1200,
    "learning_rate": 0.05,
    "num_leaves": 127,
    "min_child_samples": 10,
    "reg_lambda": 5.0,
    "max_depth": 12,
    "colsample_bytree": 1.0,
    "subsample": 0.9,
    "subsample_freq": 0,
    "random_state": 42,
    "verbosity": -1,
    "n_jobs": -1
}

In [ ]:

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Folder containing tuned LightGBM results
OUTPUT_DIR = Path(
    "/content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning"
)

PRED_FILE = OUTPUT_DIR / "focused_tuned_test_predictions.csv"

if not PRED_FILE.exists():
    raise FileNotFoundError(
        f"File not found: {PRED_FILE}\n"
        "Please check Google Drive is mounted and the filename is correct."
    )

df = pd.read_csv(PRED_FILE)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nFirst 5 rows:")
display(df.head())

Dataset shape: (11241, 7)

Columns:
['Crop', 'Crop_Year', 'Actual', 'Existing LightGBM_Prediction', 'Existing LightGBM_Absolute_Error', 'Tuned LightGBM_Prediction', 'Tuned LightGBM_Absolute_Error']

First 5 rows:

,Crop,Crop_Year,Actual,Existing LightGBM_Prediction,Existing LightGBM_Absolute_Error,Tuned LightGBM_Prediction,Tuned LightGBM_Absolute_Error
0,Arhar/Tur,2014,0.128987,0.233893,0.104906,0.244330,0.115343
1,Bajra,2014,0.586758,0.916847,0.330089,0.881845,0.295087
2,Brinjal,2014,23.737500,18.288241,5.449259,18.832296,4.905204
3,Cabbage,2014,12.300000,22.443000,10.143000,19.560821,7.260821
4,Cashewnut,2014,0.368421,0.572158,0.203737,0.492660,0.124239

In [ ]:

print("Available columns:")
for col in df.columns:
    print("-", repr(col))

Available columns:
- 'Crop'
- 'Crop_Year'
- 'Actual'
- 'Existing LightGBM_Prediction'
- 'Existing LightGBM_Absolute_Error'
- 'Tuned LightGBM_Prediction'
- 'Tuned LightGBM_Absolute_Error'

In [ ]:

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

OUTPUT_DIR = Path(
    "/content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning"
)

df = pd.read_csv(OUTPUT_DIR / "focused_tuned_test_predictions.csv")

actual_col = "Actual"
existing_pred_col = "Existing LightGBM_Prediction"
tuned_pred_col = "Tuned LightGBM_Prediction"

# Verify required columns
required = ["Crop", actual_col, existing_pred_col, tuned_pred_col]
missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}")

def calculate_metrics(group, prediction_col):
    actual = group[actual_col].to_numpy()
    predicted = group[prediction_col].to_numpy()

    result = {
        "Samples": len(group),
        "MAE": mean_absolute_error(actual, predicted),
        "RMSE": np.sqrt(mean_squared_error(actual, predicted)),
        "Mean_Actual": actual.mean(),
        "Mean_Predicted": predicted.mean(),
        "Mean_Error": np.mean(predicted - actual),
    }

    # R² is not meaningful for groups with fewer than 2 samples
    # or no variation in actual values.
    result["R2"] = (
        r2_score(actual, predicted)
        if len(group) >= 2 and np.var(actual) > 0
        else np.nan
    )
    return result

rows = []

for crop, group in df.groupby("Crop"):
    old = calculate_metrics(group, existing_pred_col)
    tuned = calculate_metrics(group, tuned_pred_col)

    rows.append({
        "Crop": crop,
        "Samples": len(group),
        "Actual_Mean": old["Mean_Actual"],
        "Existing_MAE": old["MAE"],
        "Tuned_MAE": tuned["MAE"],
        "MAE_Improvement": old["MAE"] - tuned["MAE"],
        "Existing_RMSE": old["RMSE"],
        "Tuned_RMSE": tuned["RMSE"],
        "Existing_R2": old["R2"],
        "Tuned_R2": tuned["R2"],
        "Tuned_Mean_Error": tuned["Mean_Error"],
    })

crop_metrics = pd.DataFrame(rows)

# Positive improvement means tuned model has lower MAE.
crop_metrics = crop_metrics.sort_values(
    "Tuned_MAE", ascending=False
).reset_index(drop=True)

print("Number of crops:", len(crop_metrics))
print("\nTop 15 crops with the highest tuned-model MAE:")
display(crop_metrics.head(15).round(4))

print("\nTop 15 crops where tuning improved MAE the most:")
display(
    crop_metrics.sort_values(
        "MAE_Improvement", ascending=False
    ).head(15).round(4)
)

print("\nTop 15 crops where tuning increased MAE:")
display(
    crop_metrics.sort_values(
        "MAE_Improvement", ascending=True
    ).head(15).round(4)
)

# Save the analysis
save_path = OUTPUT_DIR / "tuned_crop_wise_error_analysis.csv"
crop_metrics.to_csv(save_path, index=False)
print(f"\nSaved analysis to: {save_path}")

Number of crops: 74

Top 15 crops with the highest tuned-model MAE:

,Crop,Samples,Actual_Mean,Existing_MAE,Tuned_MAE,MAE_Improvement,Existing_RMSE,Tuned_RMSE,Existing_R2,Tuned_R2,Tuned_Mean_Error
0,Cabbage,17,12.6085,10.5555,10.7559,-0.2004,11.0112,11.4875,-1.5918,-1.8209,7.3554
1,Sugarcane,360,60.6190,9.6938,9.7129,-0.0190,15.1908,15.1995,0.6961,0.6957,-5.7035
2,Papaya,44,42.1091,9.2490,8.3982,0.8507,16.8483,15.8584,0.7218,0.7535,6.7160
3,Grapes,4,24.3524,4.9507,5.4988,-0.5480,6.1837,6.4378,-3.9805,-4.3981,-4.8429
4,Brinjal,29,15.2998,3.8810,3.9218,-0.0408,5.1992,5.2920,0.4682,0.4491,-3.0682
5,Tomato,26,17.1471,3.5786,3.7751,-0.1965,4.2320,4.4692,0.4167,0.3495,0.1297
6,Banana,119,28.2720,3.6079,3.4426,0.1654,5.4462,5.0666,0.8702,0.8877,-2.4794
7,Dry ginger,96,9.3143,3.3447,3.3635,-0.0188,6.1167,6.1598,0.6603,0.6555,-2.6177
8,Pome Granet,9,10.2807,3.5305,3.2221,0.3084,3.6102,3.3988,-197.0526,-174.5339,3.2221
9,Sapota,13,8.3051,2.9307,2.9625,-0.0318,3.0148,3.0135,-84.6666,-84.5903,2.9625
10,Jute,84,10.4571,2.7050,2.7060,-0.0009,3.5834,3.5945,0.5654,0.5627,-0.7929
11,Mango,18,7.7669,2.7491,2.6718,0.0773,3.4850,3.3928,0.4275,0.4574,0.3992
12,Tapioca,73,16.2102,2.4745,2.4455,0.0290,4.4898,4.4982,0.8608,0.8602,-1.4989
13,Onion,316,11.7350,2.3845,2.3878,-0.0033,2.9411,2.9444,0.7529,0.7523,-0.3207
14,Potato,357,13.2882,2.2954,2.3168,-0.0214,3.2775,3.3183,0.8130,0.8083,-0.5105

Top 15 crops where tuning improved MAE the most:

,Crop,Samples,Actual_Mean,Existing_MAE,Tuned_MAE,MAE_Improvement,Existing_RMSE,Tuned_RMSE,Existing_R2,Tuned_R2,Tuned_Mean_Error
2,Papaya,44,42.1091,9.2490,8.3982,0.8507,16.8483,15.8584,0.7218,0.7535,6.7160
46,Other Fresh Fruits,2,10.6448,1.0815,0.2410,0.8404,1.0896,0.2718,NaN,NaN,-0.2410
8,Pome Granet,9,10.2807,3.5305,3.2221,0.3084,3.6102,3.3988,-197.0526,-174.5339,3.2221
57,Other Vegetables,2,11.4062,0.4034,0.1728,0.2305,0.4036,0.1729,-454.7203,-82.6308,-0.1728
6,Banana,119,28.2720,3.6079,3.4426,0.1654,5.4462,5.0666,0.8702,0.8877,-2.4794
51,Pulses total,41,0.7730,0.2861,0.2076,0.0785,0.3446,0.2617,-3.1827,-1.4114,-0.1048
11,Mango,18,7.7669,2.7491,2.6718,0.0773,3.4850,3.3928,0.4275,0.4574,0.3992
25,Pineapple,30,16.2162,0.6735,0.5991,0.0744,1.1332,1.0682,0.6969,0.7307,-0.4921
34,other oilseeds,14,0.8965,0.3839,0.3162,0.0677,0.6124,0.5141,-0.3108,0.0762,-0.2629
60,Moth,2,0.6537,0.1927,0.1434,0.0492,0.2592,0.1860,-0.3725,0.2932,-0.1185
19,Ginger,67,8.9912,1.0973,1.0539,0.0434,1.8849,1.7760,0.4451,0.5074,-0.4760
53,Drum Stick,1,0.6761,0.2313,0.1903,0.0410,0.2313,0.1903,NaN,NaN,0.1903
12,Tapioca,73,16.2102,2.4745,2.4455,0.0290,4.4898,4.4982,0.8608,0.8602,-1.4989
23,Turmeric,178,3.4142,0.7125,0.6872,0.0253,1.7346,1.7105,0.6579,0.6673,-0.1865
17,Mesta,107,6.5522,1.6585,1.6361,0.0224,2.7420,2.7274,0.6252,0.6291,-1.1310

Top 15 crops where tuning increased MAE:

,Crop,Samples,Actual_Mean,Existing_MAE,Tuned_MAE,MAE_Improvement,Existing_RMSE,Tuned_RMSE,Existing_R2,Tuned_R2,Tuned_Mean_Error
3,Grapes,4,24.3524,4.9507,5.4988,-0.5480,6.1837,6.4378,-3.9805,-4.3981,-4.8429
15,Lemon,13,7.6017,1.5649,1.8654,-0.3005,1.6491,2.0164,0.7419,0.6141,0.5154
33,Blackgram,11,0.8206,0.0892,0.3654,-0.2762,0.1162,0.3927,-1.7280,-30.1628,0.3654
0,Cabbage,17,12.6085,10.5555,10.7559,-0.2004,11.0112,11.4875,-1.5918,-1.8209,7.3554
5,Tomato,26,17.1471,3.5786,3.7751,-0.1965,4.2320,4.4692,0.4167,0.3495,0.1297
22,Total foodgrain,44,1.6910,0.6338,0.7125,-0.0787,0.7702,0.8251,-0.4835,-0.7025,-0.3337
4,Brinjal,29,15.2998,3.8810,3.9218,-0.0408,5.1992,5.2920,0.4682,0.4491,-3.0682
9,Sapota,13,8.3051,2.9307,2.9625,-0.0318,3.0148,3.0135,-84.6666,-84.5903,2.9625
14,Potato,357,13.2882,2.2954,2.3168,-0.0214,3.2775,3.3183,0.8130,0.8083,-0.5105
44,Other Cereals & Millets,19,0.6250,0.2366,0.2575,-0.0209,0.2908,0.3173,-0.8311,-1.1802,-0.0437
1,Sugarcane,360,60.6190,9.6938,9.7129,-0.0190,15.1908,15.1995,0.6961,0.6957,-5.7035
7,Dry ginger,96,9.3143,3.3447,3.3635,-0.0188,6.1167,6.1598,0.6603,0.6555,-2.6177
35,Soyabean,132,0.9540,0.2964,0.3065,-0.0101,0.4055,0.4166,0.1927,0.1477,0.1654
31,Wheat,337,1.8710,0.4512,0.4604,-0.0092,0.5909,0.5990,0.5458,0.5334,0.1388
36,Other Rabi pulses,102,0.6938,0.2941,0.3027,-0.0085,0.3624,0.3679,0.1459,0.1197,-0.1334

Saved analysis to: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/tuned_crop_wise_error_analysis.csv

In [ ]:

# Inspect these crops where earlier model runs showed large errors.
focus_crops = ["Sugarcane", "Papaya", "Cabbage"]

for crop in focus_crops:
    subset = df[df["Crop"].astype(str).str.strip().str.lower()
                == crop.lower()].copy()

    print(f"\n{'=' * 65}")
    print(f"{crop} — {len(subset)} test records")

    if subset.empty:
        print("Crop not found under this exact name.")
        continue

    subset["Tuned_Signed_Error"] = (
        subset[tuned_pred_col] - subset[actual_col]
    )
    subset["Tuned_Absolute_Error"] = subset["Tuned_Signed_Error"].abs()

    display(
        subset.sort_values(
            "Tuned_Absolute_Error", ascending=False
        )[
            [
                "Crop", "Crop_Year", actual_col,
                tuned_pred_col, "Tuned_Absolute_Error",
                "Tuned_Signed_Error"
            ]
        ].head(10).round(4)
    )

print("\nLargest 20 tuned-model errors across all crops:")

df["Tuned_Signed_Error"] = df[tuned_pred_col] - df[actual_col]
df["Tuned_Absolute_Error"] = df["Tuned_Signed_Error"].abs()

display(
    df.sort_values("Tuned_Absolute_Error", ascending=False)[
        [
            "Crop", "Crop_Year", actual_col,
            tuned_pred_col, "Tuned_Absolute_Error",
            "Tuned_Signed_Error"
        ]
    ].head(20).round(4)
)

=================================================================
Sugarcane — 360 test records

,Crop,Crop_Year,Actual,Tuned LightGBM_Prediction,Tuned_Absolute_Error,Tuned_Signed_Error
11004,Sugarcane,2014,179.8663,87.3104,92.5559,-92.5559
11140,Sugarcane,2014,179.8665,100.9073,78.9592,-78.9592
2337,Sugarcane,2014,113.2609,40.8610,72.3999,-72.3999
1819,Sugarcane,2014,113.2857,41.9990,71.2867,-71.2867
1839,Sugarcane,2014,112.8485,42.1545,70.6940,-70.6940
2073,Sugarcane,2014,113.2778,43.2257,70.0521,-70.0521
11201,Sugarcane,2014,141.5137,84.7913,56.7224,-56.7224
5717,Sugarcane,2014,29.0000,68.7731,39.7731,39.7731
7413,Sugarcane,2014,165.0000,126.7722,38.2278,-38.2278
2015,Sugarcane,2014,79.1502,41.0121,38.1380,-38.1380

=================================================================
Papaya — 44 test records

,Crop,Crop_Year,Actual,Tuned LightGBM_Prediction,Tuned_Absolute_Error,Tuned_Signed_Error
83,Papaya,2014,26.5703,81.2875,54.7172,54.7172
395,Papaya,2014,69.1796,120.8617,51.6821,51.6821
366,Papaya,2014,78.8000,106.8199,28.0199,28.0199
292,Papaya,2014,78.7273,103.8132,25.0859,25.0859
643,Papaya,2014,78.7511,103.5125,24.7614,24.7614
136,Papaya,2014,78.7246,103.3733,24.6487,24.6487
187,Papaya,2014,78.7273,103.1544,24.4271,24.4271
335,Papaya,2014,78.7273,103.0627,24.3354,24.3354
501,Papaya,2014,78.7255,101.7900,23.0645,23.0645
545,Papaya,2014,78.7253,101.1112,22.3859,22.3859

=================================================================
Cabbage — 17 test records

,Crop,Crop_Year,Actual,Tuned LightGBM_Prediction,Tuned_Absolute_Error,Tuned_Signed_Error
302,Cabbage,2014,2.5824,22.1483,19.5659,19.5659
282,Cabbage,2014,2.5789,21.9345,19.3555,19.3555
66,Cabbage,2014,29.0917,13.6526,15.4391,-15.4391
98,Cabbage,2014,29.0932,15.6280,13.4652,-13.4652
585,Cabbage,2014,12.3243,22.7574,10.4331,10.4331
174,Cabbage,2014,12.3333,22.7022,10.3689,10.3689
613,Cabbage,2014,12.3210,22.4500,10.1290,10.1290
199,Cabbage,2014,12.3103,22.4064,10.0961,10.0961
323,Cabbage,2014,12.3636,22.3981,10.0345,10.0345
352,Cabbage,2014,12.3282,22.3081,9.9798,9.9798

Largest 20 tuned-model errors across all crops:

,Crop,Crop_Year,Actual,Tuned LightGBM_Prediction,Tuned_Absolute_Error,Tuned_Signed_Error
11004,Sugarcane,2014,179.8663,87.3104,92.5559,-92.5559
11140,Sugarcane,2014,179.8665,100.9073,78.9592,-78.9592
2337,Sugarcane,2014,113.2609,40.8610,72.3999,-72.3999
1819,Sugarcane,2014,113.2857,41.9990,71.2867,-71.2867
1839,Sugarcane,2014,112.8485,42.1545,70.6940,-70.6940
2073,Sugarcane,2014,113.2778,43.2257,70.0521,-70.0521
11201,Sugarcane,2014,141.5137,84.7913,56.7224,-56.7224
83,Papaya,2014,26.5703,81.2875,54.7172,54.7172
395,Papaya,2014,69.1796,120.8617,51.6821,51.6821
5717,Sugarcane,2014,29.0000,68.7731,39.7731,39.7731
7413,Sugarcane,2014,165.0000,126.7722,38.2278,-38.2278
2015,Sugarcane,2014,79.1502,41.0121,38.1380,-38.1380
2089,Sugarcane,2014,66.6340,35.0930,31.5409,-31.5409
2447,Sugarcane,2014,66.0519,35.6121,30.4399,-30.4399
1965,Sugarcane,2014,66.6356,36.2107,30.4249,-30.4249
7098,Sugarcane,2015,74.4000,44.2824,30.1176,-30.1176
4539,Sugarcane,2014,105.4500,77.0462,28.4038,-28.4038
366,Papaya,2014,78.8000,106.8199,28.0199,28.0199
1943,Sugarcane,2014,66.6365,38.6820,27.9545,-27.9545
5228,Sugarcane,2014,40.2500,67.3377,27.0877,27.0877

In [ ]:

import pandas as pd
from pathlib import Path

DATA_PATH = Path(
    "/content/drive/MyDrive/yield prediction/crop_final.csv"
)

data = pd.read_csv(DATA_PATH)

print("Original dataset shape:", data.shape)
print("\nAvailable columns:")
print(data.columns.tolist())

# Check which columns are available before investigating.
possible_cols = [
    "Crop", "Crop_Year", "State_Name", "District_Name",
    "Season", "yield_per_area", "Area", "Production"
]

available = [c for c in possible_cols if c in data.columns]
print("\nColumns available for investigation:", available)

# Identify the crop and year columns in the original file.
crop_col = "Crop" if "Crop" in data.columns else "crop_names"
year_col = "Crop_Year" if "Crop_Year" in data.columns else "crop_year"

if crop_col not in data.columns or year_col not in data.columns:
    raise ValueError("Could not identify the crop and year columns.")

focus_crops = ["Sugarcane", "Papaya", "Cabbage"]

subset = data[
    data[crop_col].astype(str).str.strip().str.lower().isin(
        [c.lower() for c in focus_crops]
    )
    & pd.to_numeric(data[year_col], errors="coerce").isin([2014, 2015])
].copy()

# Display the original rows, including location and season if available.
display_cols = [
    c for c in [
        crop_col, year_col, "State_Name", "District_Name",
        "Season", "yield_per_area", "Area", "Production"
    ]
    if c in subset.columns
]

print("\nMatching original records:", len(subset))
display(subset[display_cols].head(30))

print("\nCounts by crop and year:")
display(
    subset.groupby([crop_col, year_col])
    .size()
    .rename("Records")
    .reset_index()
)

Original dataset shape: (235123, 8)

Available columns:
['State_Name', 'District_Name', 'Season', 'Crop', 'Crop_Year', 'Area', 'Production', 'yield_per_area']

Columns available for investigation: ['Crop', 'Crop_Year', 'State_Name', 'District_Name', 'Season', 'yield_per_area', 'Area', 'Production']

Matching original records: 421

,Crop,Crop_Year,State_Name,District_Name,Season,yield_per_area,Area,Production
875,Cabbage,2014,Andhra Pradesh,ANANTAPUR,Kharif,12.300000,10.0,123.0
894,Papaya,2014,Andhra Pradesh,ANANTAPUR,Kharif,78.724599,374.0,29443.0
902,Sugarcane,2014,Andhra Pradesh,ANANTAPUR,Kharif,81.866667,30.0,2456.0
910,Cabbage,2014,Andhra Pradesh,ANANTAPUR,Rabi,12.500000,2.0,25.0
1637,Cabbage,2014,Andhra Pradesh,CHITTOOR,Kharif,29.091667,120.0,3491.0
1654,Papaya,2014,Andhra Pradesh,CHITTOOR,Kharif,26.570328,519.0,13790.0
1662,Sugarcane,2014,Andhra Pradesh,CHITTOOR,Kharif,79.052511,26147.0,2066986.0
1669,Cabbage,2014,Andhra Pradesh,CHITTOOR,Rabi,29.093168,161.0,4684.0
2369,Cabbage,2014,Andhra Pradesh,EAST GODAVARI,Kharif,12.318182,22.0,271.0
2382,Papaya,2014,Andhra Pradesh,EAST GODAVARI,Kharif,78.724590,305.0,24011.0
2390,Sugarcane,2014,Andhra Pradesh,EAST GODAVARI,Kharif,85.160822,12405.0,1056420.0
2397,Cabbage,2014,Andhra Pradesh,EAST GODAVARI,Rabi,12.347826,23.0,284.0
3022,Cabbage,2014,Andhra Pradesh,GUNTUR,Kharif,12.333333,48.0,592.0
3035,Papaya,2014,Andhra Pradesh,GUNTUR,Kharif,78.727273,176.0,13856.0
3040,Sugarcane,2014,Andhra Pradesh,GUNTUR,Kharif,98.089362,470.0,46102.0
3047,Cabbage,2014,Andhra Pradesh,GUNTUR,Rabi,12.310345,29.0,357.0
3816,Papaya,2014,Andhra Pradesh,KADAPA,Kharif,107.111534,789.0,84511.0
3823,Sugarcane,2014,Andhra Pradesh,KADAPA,Kharif,82.093834,373.0,30621.0
3845,Papaya,2014,Andhra Pradesh,KADAPA,Rabi,107.111111,729.0,78084.0
4421,Cabbage,2014,Andhra Pradesh,KRISHNA,Kharif,2.578947,57.0,147.0
4431,Papaya,2014,Andhra Pradesh,KRISHNA,Kharif,78.727273,121.0,9526.0
4436,Sugarcane,2014,Andhra Pradesh,KRISHNA,Kharif,83.790777,16719.0,1400898.0
4441,Cabbage,2014,Andhra Pradesh,KRISHNA,Rabi,2.582418,91.0,235.0
5198,Cabbage,2014,Andhra Pradesh,KURNOOL,Kharif,12.363636,11.0,136.0
5210,Papaya,2014,Andhra Pradesh,KURNOOL,Kharif,78.727273,165.0,12990.0
5218,Sugarcane,2014,Andhra Pradesh,KURNOOL,Kharif,116.794118,714.0,83391.0
5227,Cabbage,2014,Andhra Pradesh,KURNOOL,Rabi,12.328244,131.0,1615.0
5241,Papaya,2014,Andhra Pradesh,KURNOOL,Rabi,78.800000,5.0,394.0
5987,Papaya,2014,Andhra Pradesh,PRAKASAM,Kharif,69.179604,657.0,45451.0
5995,Sugarcane,2014,Andhra Pradesh,PRAKASAM,Kharif,72.000000,900.0,64800.0

Counts by crop and year:

        Crop  Crop_Year  Records
0    Cabbage       2014       17
1     Papaya       2014       44
2  Sugarcane       2014      332
3  Sugarcane       2015       28

In [ ]:

import pandas as pd
import numpy as np
from pathlib import Path

BASE = Path("/content/drive/MyDrive/yield prediction")
original = pd.read_csv(BASE / "crop_final.csv")
predictions = pd.read_csv(
    BASE / "cropsense_lightgbm_tuning" /
    "focused_tuned_test_predictions.csv"
)

# Reconstruct the chronological test period.
test_rows = original[
    pd.to_numeric(original["Crop_Year"], errors="coerce").isin([2014, 2015])
].copy()

print("Original 2014–2015 rows:", len(test_rows))
print("Prediction rows:", len(predictions))

# Check row-by-row alignment before attaching locations.
test_rows = test_rows.reset_index(drop=True)
predictions = predictions.reset_index(drop=True)

same_length = len(test_rows) == len(predictions)

if same_length:
    same_crop = (
        test_rows["Crop"].astype(str).to_numpy()
        == predictions["Crop"].astype(str).to_numpy()
    )
    same_year = (
        pd.to_numeric(test_rows["Crop_Year"]).to_numpy()
        == pd.to_numeric(predictions["Crop_Year"]).to_numpy()
    )
    same_actual = np.isclose(
        pd.to_numeric(test_rows["yield_per_area"]).to_numpy(),
        pd.to_numeric(predictions["Actual"]).to_numpy(),
        rtol=1e-5,
        atol=1e-6,
        equal_nan=True
    )

    aligned = bool(same_crop.all() and same_year.all() and same_actual.all())
else:
    aligned = False

print("Exact row alignment verified:", aligned)

if not aligned:
    raise ValueError(
        "Rows do not align exactly. Do not merge locations by row number. "
        "We need to reconstruct the original test split/order first."
    )

# Attach locations only after verifying every row.
for col in ["State_Name", "District_Name", "Season"]:
    predictions[col] = test_rows[col].to_numpy()

predictions["Tuned_Signed_Error"] = (
    predictions["Tuned LightGBM_Prediction"] - predictions["Actual"]
)
predictions["Tuned_Absolute_Error"] = (
    predictions["Tuned_Signed_Error"].abs()
)

# Inspect the largest errors with their actual locations.
focus = predictions[
    predictions["Crop"].isin(["Sugarcane", "Papaya", "Cabbage"])
].copy()

print("\nLargest errors with location and season:")
display(
    focus.sort_values("Tuned_Absolute_Error", ascending=False)[
        [
            "Crop", "Crop_Year", "State_Name", "District_Name",
            "Season", "Actual", "Tuned LightGBM_Prediction",
            "Tuned_Absolute_Error", "Tuned_Signed_Error"
        ]
    ].head(25).round(4)
)

save_path = (
    BASE / "cropsense_lightgbm_tuning" /
    "tuned_predictions_with_locations.csv"
)
predictions.to_csv(save_path, index=False)
print("\nSaved location-enriched predictions to:", save_path)

Original 2014–2015 rows: 11241
Prediction rows: 11241
Exact row alignment verified: True

Largest errors with location and season:

,Crop,Crop_Year,State_Name,District_Name,Season,Actual,Tuned LightGBM_Prediction,Tuned_Absolute_Error,Tuned_Signed_Error
11004,Sugarcane,2014,West Bengal,HOOGHLY,Whole Year,179.8663,87.3104,92.5559,-92.5559
11140,Sugarcane,2014,West Bengal,MEDINIPUR WEST,Whole Year,179.8665,100.9073,78.9592,-78.9592
2337,Sugarcane,2014,Bihar,NAWADA,Whole Year,113.2609,40.8610,72.3999,-72.3999
1819,Sugarcane,2014,Bihar,ARWAL,Whole Year,113.2857,41.9990,71.2867,-71.2867
1839,Sugarcane,2014,Bihar,AURANGABAD,Whole Year,112.8485,42.1545,70.6940,-70.6940
2073,Sugarcane,2014,Bihar,JEHANABAD,Whole Year,113.2778,43.2257,70.0521,-70.0521
11201,Sugarcane,2014,West Bengal,NADIA,Whole Year,141.5137,84.7913,56.7224,-56.7224
83,Papaya,2014,Andhra Pradesh,CHITTOOR,Kharif,26.5703,81.2875,54.7172,54.7172
395,Papaya,2014,Andhra Pradesh,PRAKASAM,Kharif,69.1796,120.8617,51.6821,51.6821
5717,Sugarcane,2014,Maharashtra,WASHIM,Whole Year,29.0000,68.7731,39.7731,39.7731
7413,Sugarcane,2014,Puducherry,PONDICHERRY,Kharif,165.0000,126.7722,38.2278,-38.2278
2015,Sugarcane,2014,Bihar,GAYA,Whole Year,79.1502,41.0121,38.1380,-38.1380
2089,Sugarcane,2014,Bihar,KAIMUR (BHABUA),Whole Year,66.6340,35.0930,31.5409,-31.5409
2447,Sugarcane,2014,Bihar,ROHTAS,Whole Year,66.0519,35.6121,30.4399,-30.4399
1965,Sugarcane,2014,Bihar,BUXAR,Whole Year,66.6356,36.2107,30.4249,-30.4249
7098,Sugarcane,2015,Odisha,MAYURBHANJ,Winter,74.4000,44.2824,30.1176,-30.1176
4539,Sugarcane,2014,Karnataka,HAVERI,Whole Year,105.4500,77.0462,28.4038,-28.4038
366,Papaya,2014,Andhra Pradesh,KURNOOL,Rabi,78.8000,106.8199,28.0199,28.0199
1943,Sugarcane,2014,Bihar,BHOJPUR,Whole Year,66.6365,38.6820,27.9545,-27.9545
5228,Sugarcane,2014,Maharashtra,AMRAVATI,Whole Year,40.2500,67.3377,27.0877,27.0877
5343,Sugarcane,2014,Maharashtra,GADCHIROLI,Whole Year,99.0000,71.9142,27.0858,-27.0858
6928,Sugarcane,2014,Odisha,KENDUJHAR,Winter,78.8000,52.2245,26.5755,-26.5755
2312,Sugarcane,2014,Bihar,NALANDA,Whole Year,65.5489,39.6366,25.9123,-25.9123
292,Papaya,2014,Andhra Pradesh,KRISHNA,Kharif,78.7273,103.8132,25.0859,25.0859
7367,Sugarcane,2014,Odisha,SUNDARGARH,Winter,93.6000,68.5579,25.0421,-25.0421

Saved location-enriched predictions to: /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/tuned_predictions_with_locations.csv

In [3]:

from pathlib import Path

BASE = Path("/content/drive/MyDrive/yield prediction")

paths_to_check = [
    BASE / "cropsense_corrected_v3" /
    "cropsense_yield_deployment.joblib",

    BASE / "cropsense_lightgbm_tuning" /
    "focused_tuning_results.csv",

    BASE / "cropsense_lightgbm_tuning" /
    "focused_tuned_test_comparison.csv",

    BASE / "cropsense_lightgbm_tuning" /
    "tuned_predictions_with_locations.csv",
]

for path in paths_to_check:
    print(
        "FOUND    " if path.exists() else "NOT FOUND",
        path
    )

FOUND     /content/drive/MyDrive/yield prediction/cropsense_corrected_v3/cropsense_yield_deployment.joblib
FOUND     /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/focused_tuning_results.csv
FOUND     /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/focused_tuned_test_comparison.csv
FOUND     /content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuning/tuned_predictions_with_locations.csv

In [4]:

from pathlib import Path
import pandas as pd
import joblib
import lightgbm as lgb

BASE = Path("/content/drive/MyDrive/yield prediction")

# 1. Inspect the existing deployment model (read-only)
model_path = (
    BASE / "cropsense_corrected_v3" /
    "cropsense_yield_deployment.joblib"
)

artifact = joblib.load(model_path)

print("=" * 65)
print("EXISTING DEPLOYMENT ARTIFACT")
print("=" * 65)
print("Artifact type:", type(artifact))

if isinstance(artifact, dict):
    print("Artifact keys:", list(artifact.keys()))

    for key, value in artifact.items():
        print(f"\n{key}:")
        print("  Type:", type(value))
        if hasattr(value, "feature_name_"):
            print("  Features:", value.feature_name_)
        if hasattr(value, "get_params"):
            print("  Parameters:", value.get_params())
else:
    if hasattr(artifact, "feature_name_"):
        print("Features:", artifact.feature_name_)
    if hasattr(artifact, "get_params"):
        print("Parameters:", artifact.get_params())

# 2. Inspect focused tuning results
tuning_path = (
    BASE / "cropsense_lightgbm_tuning" /
    "focused_tuning_results.csv"
)

tuning = pd.read_csv(tuning_path)

print("\n" + "=" * 65)
print("FOCUSED TUNING RESULTS")
print("=" * 65)
print("Shape:", tuning.shape)
print("Columns:", tuning.columns.tolist())
display(tuning.head(10))

# 3. Inspect same-test comparison
comparison_path = (
    BASE / "cropsense_lightgbm_tuning" /
    "focused_tuned_test_comparison.csv"
)

comparison = pd.read_csv(comparison_path)

print("\n" + "=" * 65)
print("MODEL COMPARISON")
print("=" * 65)
display(comparison)

print("\nLightGBM version:", lgb.__version__)

=================================================================
EXISTING DEPLOYMENT ARTIFACT
=================================================================
Artifact type: <class 'dict'>
Artifact keys: ['model', 'model_name', 'categorical_columns', 'target', 'category_schema', 'features', 'training_year_min', 'training_year_max', 'prediction_clip_min']

model:
  Type: <class 'lightgbm.sklearn.LGBMRegressor'>
  Features: ['Crop', 'State_Name', 'District_Name', 'Season']
  Parameters: {'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 1.0, 'importance_type': 'split', 'learning_rate': 0.04, 'max_depth': -1, 'min_child_samples': 10, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_estimators': 800, 'n_jobs': -1, 'num_leaves': 127, 'objective': 'regression', 'random_state': 42, 'reg_alpha': 0.0, 'reg_lambda': 5.0, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0, 'verbosity': -1}

model_name:
  Type: <class 'str'>

categorical_columns:
  Type: <class 'list'>

target:
  Type: <class 'str'>

category_schema:
  Type: <class 'dict'>

features:
  Type: <class 'list'>

training_year_min:
  Type: <class 'int'>

training_year_max:
  Type: <class 'int'>

prediction_clip_min:
  Type: <class 'int'>

=================================================================
FOCUSED TUNING RESULTS
=================================================================
Shape: (41, 13)
Columns: ['learning_rate', 'n_estimators', 'num_leaves', 'min_child_samples', 'reg_lambda', 'max_depth', 'colsample_bytree', 'subsample', 'subsample_freq', 'Validation_MAE', 'Validation_RMSE', 'Validation_R2', 'Negative_Raw_Predictions']

,learning_rate,n_estimators,num_leaves,min_child_samples,reg_lambda,max_depth,colsample_bytree,subsample,subsample_freq,Validation_MAE,Validation_RMSE,Validation_R2,Negative_Raw_Predictions
0,0.05,1200,127,10,5.0,12,1.0,0.9,0,1.145239,3.780069,0.914362,4
1,0.05,1200,127,30,3.0,-1,1.0,1.0,0,1.146135,3.816453,0.912705,6
2,0.03,1200,191,10,8.0,16,0.9,0.8,0,1.147621,3.817408,0.912662,7
3,0.03,800,191,10,5.0,16,0.9,0.9,0,1.147668,3.803942,0.913277,5
4,0.05,1200,191,20,8.0,12,0.9,0.8,0,1.147720,3.802670,0.913335,1
5,0.04,1200,63,10,3.0,-1,0.9,1.0,0,1.148014,3.783249,0.914218,7
6,0.04,800,127,10,5.0,-1,1.0,1.0,0,1.149167,3.811129,0.912949,8
7,0.04,600,191,20,8.0,16,1.0,0.9,1,1.150874,3.831241,0.912028,7
8,0.04,1000,63,20,5.0,-1,1.0,1.0,0,1.152698,3.781032,0.914318,6
9,0.05,600,127,10,5.0,12,0.9,0.9,0,1.152816,3.789143,0.913950,7

=================================================================
MODEL COMPARISON
=================================================================

,Model,Rows,MAE,RMSE,R2,Negative_Raw_Predictions
0,Tuned LightGBM,11241,0.950062,3.275303,0.935283,2
1,Existing LightGBM,11241,0.955476,3.294873,0.934508,2

LightGBM version: 4.6.0

In [5]:

from pathlib import Path
import json
import joblib
import numpy as np
import pandas as pd
import lightgbm as lgb

from lightgbm import LGBMRegressor

# --------------------------------------------------
# 1. Paths
# --------------------------------------------------
BASE = Path("/content/drive/MyDrive/yield prediction")
DATA_PATH = BASE / "crop_final.csv"

OUTPUT_DIR = BASE / "cropsense_lightgbm_tuned_deployment"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

MODEL_PATH = OUTPUT_DIR / "cropsense_yield_tuned_deployment.joblib"
METADATA_PATH = OUTPUT_DIR / "model_metadata.json"

# --------------------------------------------------
# 2. Load and validate dataset
# --------------------------------------------------
df = pd.read_csv(DATA_PATH)

FEATURES = ["Crop", "State_Name", "District_Name", "Season"]
TARGET = "yield_per_area"
YEAR_COL = "Crop_Year"

required = FEATURES + [TARGET, YEAR_COL]
missing = [c for c in required if c not in df.columns]

if missing:
    raise ValueError(f"Missing required columns: {missing}")

df[YEAR_COL] = pd.to_numeric(df[YEAR_COL], errors="coerce")
df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")

df = df.dropna(subset=required).copy()
df = df[df[TARGET] >= 0].copy()

# Normalize categorical columns consistently.
for col in FEATURES:
    df[col] = df[col].astype(str).str.strip()

# Do not overwrite or retrain the old artifact.
print("Dataset rows used:", len(df))
print("Year range:", int(df[YEAR_COL].min()), "-", int(df[YEAR_COL].max()))
print("Unique crops:", df["Crop"].nunique())

X = df[FEATURES].copy()
y = df[TARGET].astype(float).copy()

# LightGBM native categorical features.
for col in FEATURES:
    X[col] = X[col].astype("category")

# --------------------------------------------------
# 3. Train the selected configuration
# --------------------------------------------------
params = {
    "objective": "regression",
    "n_estimators": 1200,
    "learning_rate": 0.05,
    "num_leaves": 127,
    "min_child_samples": 10,
    "reg_lambda": 5.0,
    "max_depth": 12,
    "colsample_bytree": 1.0,
    "subsample": 0.9,
    "subsample_freq": 0,
    "random_state": 42,
    "verbosity": -1,
    "n_jobs": -1,
}

model = LGBMRegressor(**params)
model.fit(X, y, categorical_feature=FEATURES)

# --------------------------------------------------
# 4. Save category schema and deployment artifact
# --------------------------------------------------
category_schema = {
    col: sorted(df[col].astype(str).unique().tolist())
    for col in FEATURES
}

artifact = {
    "model": model,
    "model_name": "CropSense AI Tuned LightGBM Yield Model",
    "categorical_columns": FEATURES,
    "target": TARGET,
    "category_schema": category_schema,
    "features": FEATURES,
    "training_year_min": int(df[YEAR_COL].min()),
    "training_year_max": int(df[YEAR_COL].max()),
    "prediction_clip_min": 0,
}

joblib.dump(artifact, MODEL_PATH)

metadata = {
    "model_name": artifact["model_name"],
    "features": FEATURES,
    "target": TARGET,
    "training_rows": int(len(df)),
    "training_year_min": int(df[YEAR_COL].min()),
    "training_year_max": int(df[YEAR_COL].max()),
    "unique_crops": int(df["Crop"].nunique()),
    "lightgbm_version": lgb.__version__,
    "parameters": params,
    "test_evaluation_status": (
        "2014-2015 used for model selection; "
        "not an independent final test after this refit."
    ),
}

with open(METADATA_PATH, "w", encoding="utf-8") as f:
    json.dump(metadata, f, indent=2)

print("\nTuned deployment model saved:")
print(MODEL_PATH)
print("\nMetadata saved:")
print(METADATA_PATH)
print("\nExisting deployment model was not modified.")

Dataset rows used: 235123
Year range: 1997 - 2015
Unique crops: 104

Tuned deployment model saved:
/content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuned_deployment/cropsense_yield_tuned_deployment.joblib

Metadata saved:
/content/drive/MyDrive/yield prediction/cropsense_lightgbm_tuned_deployment/model_metadata.json

Existing deployment model was not modified.

In [6]:

import os
import joblib
import pandas as pd
import numpy as np

MODEL_PATH = (
    "/content/drive/MyDrive/yield prediction/"
    "cropsense_lightgbm_tuned_deployment/"
    "cropsense_yield_tuned_deployment.joblib"
)

assert os.path.exists(MODEL_PATH), "Model file not found!"

artifact = joblib.load(MODEL_PATH)

print("Model loaded successfully!")
print("Model name:", artifact["model_name"])
print("Features:", artifact["features"])
print("Target:", artifact["target"])
print("Training years:",
      artifact["training_year_min"], "-",
      artifact["training_year_max"])

model = artifact["model"]
features = artifact["features"]

# Use the model's saved categorical schema where available.
category_lists = getattr(model.booster_, "pandas_categorical", None)

sample = {
    "Crop": ["Rice"],
    "State_Name": ["Andhra Pradesh"],
    "District_Name": ["Krishna"],
    "Season": ["Kharif"]
}

X_sample = pd.DataFrame(sample)[features]

for i, col in enumerate(features):
    if category_lists and i < len(category_lists):
        X_sample[col] = pd.Categorical(
            X_sample[col],
            categories=category_lists[i]
        )
    else:
        X_sample[col] = X_sample[col].astype("category")

prediction = float(model.predict(X_sample)[0])
prediction = max(0.0, prediction)

print("\nSample input:")
print(X_sample.astype(str).to_dict(orient="records")[0])
print("Predicted yield_per_area:", prediction)
print("\nVerification completed.")

Model loaded successfully!
Model name: CropSense AI Tuned LightGBM Yield Model
Features: ['Crop', 'State_Name', 'District_Name', 'Season']
Target: yield_per_area
Training years: 1997 - 2015

Sample input:
{'Crop': 'Rice', 'State_Name': 'Andhra Pradesh', 'District_Name': np.str_('nan'), 'Season': 'Kharif'}
Predicted yield_per_area: 3.124987085582244

Verification completed.

In [11]:

import joblib
import pandas as pd

MODEL_PATH = (
    "/content/drive/MyDrive/yield prediction/"
    "cropsense_lightgbm_tuned_deployment/"
    "cropsense_yield_tuned_deployment.joblib"
)

artifact = joblib.load(MODEL_PATH)
model = artifact["model"]
features = artifact["features"]
category_lists = model.booster_.pandas_categorical

sample = {
    "Crop": "Rice",
    "State_Name": "Andhra Pradesh",
    "District_Name": "KRISHNA",
    "Season": "Kharif"
}

X = pd.DataFrame([sample])[features]

for i, col in enumerate(features):
    categories = list(category_lists[i])
    value = str(X[col].iloc[0])

    if value not in categories:
        raise ValueError(
            f"{col}='{value}' is not recognized. "
            f"Check the model's saved categories."
        )

    X[col] = pd.Categorical(X[col], categories=categories)

if X.isna().any().any():
    raise ValueError("Input contains missing or unrecognized categories.")

prediction = max(0.0, float(model.predict(X)[0]))

print("Model:", artifact["model_name"])
print("Validated input:", sample)
print(f"Predicted yield_per_area: {prediction:.4f}")
print("Verification passed!")

Model: CropSense AI Tuned LightGBM Yield Model
Validated input: {'Crop': 'Rice', 'State_Name': 'Andhra Pradesh', 'District_Name': 'KRISHNA', 'Season': 'Kharif'}
Predicted yield_per_area: 3.0835
Verification passed!

In [10]:

import os
import joblib
import pandas as pd

DATA_PATH = "/content/drive/MyDrive/yield prediction/crop_final.csv"
MODEL_PATH = (
    "/content/drive/MyDrive/yield prediction/"
    "cropsense_lightgbm_tuned_deployment/"
    "cropsense_yield_tuned_deployment.joblib"
)

# Load dataset and deployment artifact
df = pd.read_csv(DATA_PATH)
artifact = joblib.load(MODEL_PATH)
model = artifact["model"]

print("=" * 55)
print("1. DATASET DISTRICT CHECK")
print("=" * 55)

# Check exact spelling in the dataset
districts = (
    df.loc[
        df["State_Name"].astype(str).str.strip().str.casefold()
        == "andhra pradesh",
        "District_Name"
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

print("Andhra Pradesh district examples:", sorted(districts)[:30])
print("Does Krishna exist in this state?",
      any(d.casefold() == "krishna" for d in districts))

print("\n" + "=" * 55)
print("2. SAVED MODEL CATEGORY CHECK")
print("=" * 55)

categories = getattr(model.booster_, "pandas_categorical", None)

if categories is None:
    print("No pandas categorical metadata found in the booster.")
else:
    for i, feature in enumerate(artifact["features"]):
        feature_categories = categories[i] if i < len(categories) else []
        print(f"\n{feature}: {len(feature_categories)} categories")
        print("Examples:", list(feature_categories)[:15])

    district_index = artifact["features"].index("District_Name")
    district_categories = list(categories[district_index])

    print("\nIs Krishna in saved district categories?",
          "Krishna" in district_categories)
    print("District category examples containing 'krish':",
          [str(x) for x in district_categories
           if "krish" in str(x).casefold()][:20])

print("\n" + "=" * 55)
print("3. MISSING DISTRICT VALUES")
print("=" * 55)

print("Dataset missing districts:", df["District_Name"].isna().sum())
print("String 'nan' districts:",
      df["District_Name"].astype(str).str.strip().str.casefold()
      .eq("nan").sum())

print("\nDiagnostic complete. No files were modified.")

=======================================================
1. DATASET DISTRICT CHECK
=======================================================
Andhra Pradesh district examples: ['ANANTAPUR', 'CHITTOOR', 'EAST GODAVARI', 'GUNTUR', 'KADAPA', 'KRISHNA', 'KURNOOL', 'PRAKASAM', 'SPSR NELLORE', 'SRIKAKULAM', 'VISAKHAPATANAM', 'VIZIANAGARAM', 'WEST GODAVARI']
Does Krishna exist in this state? True

=======================================================
2. SAVED MODEL CATEGORY CHECK
=======================================================

Crop: 104 categories
Examples: ['Arcanut (Processed)', 'Arecanut', 'Arhar/Tur', 'Atcanut (Raw)', 'Bajra', 'Banana', 'Barley', 'Bean', 'Beans & Mutter(Vegetable)', 'Bhindi', 'Bitter Gourd', 'Black pepper', 'Blackgram', 'Bottle Gourd', 'Brinjal']

State_Name: 33 categories
Examples: ['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka']

District_Name: 646 categories
Examples: ['24 PARAGANAS NORTH', '24 PARAGANAS SOUTH', 'ADILABAD', 'AGAR MALWA', 'AGRA', 'AHMADABAD', 'AHMEDNAGAR', 'AIZAWL', 'AJMER', 'AKOLA', 'ALAPPUZHA', 'ALIGARH', 'ALIRAJPUR', 'ALLAHABAD', 'ALMORA']

Season: 6 categories
Examples: ['Autumn', 'Kharif', 'Rabi', 'Summer', 'Whole Year', 'Winter']

Is Krishna in saved district categories? False
District category examples containing 'krish': ['KRISHNA', 'KRISHNAGIRI']

=======================================================
3. MISSING DISTRICT VALUES
=======================================================
Dataset missing districts: 0
String 'nan' districts: 0

Diagnostic complete. No files were modified.